### ISSUE TITLE
Error "fsc.exe" exited with code -532462766

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#6182] opened 2019-02-04 05:17 UTC
Today, during a simple "no change, just recompile" action of my solution using MSBuild, `fsc,exe` suddenly showed me the following error:

> "fsc.exe" exited with code -532462766

### Repro steps

Unfortunately, this is the first time I encounter this (at least with this code, something similar used to happen, but with a different output: https://github.com/Microsoft/visualfsharp/issues/779, and was solved). 

After compiling again the error went away.

### Expected behavior

No error, or a descriptive error instead of only the code. Is there any way we can deduct the underlying error? Perhaps a glitch of the OS, a problem with a hard drive? 

I.e., with some Windows errors, you can take the hex value, subtract something and you get the actual Win32 error code, do we have something similar here?

### Actual behavior

Occasionally this error seems to pop up.

### Known workarounds

The error disappears after doing it again.

### Related information 

Only happened once so far on a 15.9.6 installation in Visual Studio, using MSBuild to build the solution. This is a legacy style F# solution.

Putting this out there because there were no results, except that apparently a test exists that understand or expects this error too: https://github.com/Microsoft/visualfsharp/blob/5450aff16583e4f86603c7dd1eb2cb50cfebb611/vsintegration/tests/UnitTests/LegacyLanguageService/Tests.LanguageService.Script.fs#L1491

**Comment by TIHan** [comment] 2019-02-04 18:02
Yea, this sounds like a problem. We will need a repro though.

So it only happens on first build?

**Comment by TIHan** [comment] 2019-02-04 19:37
Gotcha. I don't know about the error code; we will have to do a little bit of research and digging to see what that is.

Here are some stuff I found:

- https://stackoverflow.com/questions/43328087/compiler-error-message-the-compiler-failed-with-error-code-532462766
- https://stackoverflow.com/questions/34034352/visual-studio-build-error-csc-exe-exited-with-code-532462766
- https://social.msdn.microsoft.com/Forums/azure/en-US/5c6d0500-15fb-4ba5-a29e-1820d2596210/error-532462766-after-submit-a-job?forum=MediaServices

**Comment by abelbraaksma** [comment] 2019-02-11 12:15
@tihan, I think we have our repro, see #6226

**Comment by forki** [comment] 2019-02-11 12:16
So I'm your repro? 😂

**Comment by abelbraaksma** [comment] 2019-02-11 12:19
@forki looks like it ;p

**Comment by abelbraaksma** [comment] 2019-02-11 12:20
Or at the very least you showed a path that could cause this error number to be reported, we might now be able to track the code segment that raises this. Before that we had nothing to go on.

**Comment by forki** [comment] 2019-02-11 12:24
Yeah it's 100 percent reproducible in my work machine. So if someone wants
me to try something...

Am Mo., 11. Feb. 2019, 13:20 hat Abel Braaksma <notifications@github.com>
geschrieben:

**Comment by abelbraaksma** [comment] 2019-10-27 18:42
@cartermp, @TIHan, this still happens, or at least it started happening again. This time I had a look in the Windows Event Log and found some useful information:

First log item, source '.NET Runtime'

```
Application: fsc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at <StartupCode$FSharp-Compiler-Private>.$FSharp.Compiler.Driver..cctor()

Exception Info: System.TypeInitializationException
   at FSharp.Compiler.Driver.main0[a](a ctok, String[] argv, Resolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, ErrorLoggerProvider errorLoggerProvider, DisposablesTracker disposables)
   at FSharp.Compiler.Driver.typecheckAndCompile(CompilationThreadToken ctok, String[] argv, Resolver legacyReferenceResolver, Boolean bannerAlreadyPrinted, ReduceMemoryFlag reduceMemoryUsage, CopyFSharpCoreFlag defaultCopyFSharpCore, Exiter exiter, ErrorLoggerProvider loggerProvider, FSharpOption`1 tcImportsCapture, FSharpOption`1 dynamicAssemblyCreator)
   at FSharp.Compiler.CommandLineMain.Driver.main(String[] argv)
   at FSharp.Compiler.CommandLineMain.main(String[] argv)
   at FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ReraiseIfWatsonable(System.Exception)
   at FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger, System.Exception, range)
   at FSharp.Compiler.CommandLineMain.main(System.String[])
```

Second one, source 'Application Error':

```
Faulting application name: fsc.exe, version: 10.600.19.45501, time stamp: 0x8748a12a
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24475, time stamp: 0x5cdd8011
Exception code: 0xe0434352
Fault offset: 0x0000c5af
Faulting process id: 0x503c
Faulting application start time: 0x01d58cf52d87edaa
Faulting application path: c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\commonextensions\microsoft\fsharp\fsc.exe
Faulting module path: C:\windows\syswow64\KERNELBASE.dll
Report Id: 6c4ab736-f8e8-11e9-a58f-005056c00008
```

Third one from 'Windows Error Reporting':

```
Fault bucket 113879185, type 313225739
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: fsc.exe
P2: 10.600.19.45501
P3: 8748a12a
P4: FSharp.Compiler.Private
P5: 10.600.19.45501
P6: e50203b7
P7: 2f0c
P8: 0
P9: System.NullReferenceException
P10: 

Attached files:
C:\Users\Abel\AppData\Local\Temp\WER74A5.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users\Abel\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_fsc.exe_e755376e66f54b5459d2480d4bee5058b6a9fb_39327966

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6c4ab736-f8e8-11e9-a58f-005056c00008
Report Status: 0
```

I think the NRE inside the startup code is a strong hint here.

**Comment by MNemteanu** [comment] 2019-11-26 22:20
I was getting same error when trying to change the .NET Target Framework to 4.7 on an older website (using Visual Studio 2019). The error was fixed when I removed the /roslyn folder (was re-created) and removed and re-installed 2 NuGet packages:
![image](https://user-images.githubusercontent.com/53495377/69677423-2ca2e800-1060-11ea-840e-10ac557a513f.png)

**Comment by dsyme** [comment] 2020-08-26 17:42
@abelbraaksma I think we should close this in the absence of a repro - the repro in #6226 seems to be too specific to .NET Framework things to follow up on this

**Comment by dsyme** [comment] 2020-08-26 17:42
@abelbraaksma I think we should close this in the absence of a repro - the repro in #6226 seems to be too specific to .NET Framework things to follow up on this

**Closed by dsyme** 2020-08-26 17:42 UTC
Labels: Area-Compiler, bug, needs repro

**Comment by abelbraaksma** [comment] 2020-08-27 17:43
@dsyme, agreed. I haven't seen this happening on my ci system for a while anyway. Considering the linked reports from @TIHan, this may have been a CLR issue and not an fsc issue.

**Comment by CosminSontu** [comment] 2023-02-15 08:53
This happens for me on .NET SDK 7.0.102.
Solution has one console F# project created with dotnet cli commands.
The project failed with the aforementioned error.
Then, I tried loading the solution folder in Visual Studio (2022) and it built successfully.
Then the CLI build also started working.

So it seems that the Visual Studio build system managed to do something that dotnet cli couldn't (although I vaguely remember VS relies on the CLI behind the scenes and should be consistent - at least in C# case it is)

**Comment by abelbraaksma** [comment] 2023-02-27 12:21
@CosminSontu did you just use `dotnet new` and then build it? It is reproducible or did the issue disappear after the first time you opened it in VS?

**Comment by CosminSontu** [comment] 2023-02-28 09:13
The problem went away after building the solution with VS.
