### ISSUE TITLE
FSharp.Compiler.Service v38.0 fails with the official sample in net472

### ISSUE THREAD

**Issue by nightroman** [dotnet/fsharp#10467] opened 2020-11-15 15:17 UTC
The sample code is from http://fsharp.github.io/FSharp.Compiler.Service/interactive.html

It works in net50 and fails in net472.

**Steps:**

- use the attached project

- change to the project directory and run

```
dotnet run
```

**Actual result**

It fails with this not clear error:

```
Unhandled Exception: System.Exception: Error creating evaluation session: StopProcessingExn None
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2829
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible, FSharpOption`1 legacyReferenceResolver) in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 3155
   at Program.main(String[] argv) in C:\Users\rjq\Desktop\FCS_net472\Program.fs:line 20
```

**Expected result**

It works and prints "43".

**Related question/issue**

Is FCS v38.0 supposed to work in net472? I thought so but maybe I missed something fundamental.

If it is supposed to work, I have another issue from the actual app with a clear error on creating a session:

```
error FS0078: Unable to find the file 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Workflow.Compiler.exe.dll' in any of C:\Windows\Microsoft.NET\Framework64\v4.0.30319 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF C:\Bin\Far\x64 C:\Bin\Far\x64\
```

**Known workarounds**

For the sample, like I said, using net50 works around the issue.

But for the actual app, none. It cannot yet use net50 for many reasons.

I hope the underlying problem is the same, so if it is solved for the sample, the app might work as well.

****
[FCS_net472.zip](https://github.com/dotnet/fsharp/files/5542610/FCS_net472.zip)

**Comment by KevinRansom** [comment] 2020-11-16 09:02
@nightroman Thanks for this, we will take a look.

**Comment by goswinr** [comment] 2020-11-17 10:31
Thanks @KevinRansom I also encountered a  `StopProcessingExn`  on net472: https://github.com/fsharp/FSharp.Compiler.Service/issues/935. maybe this is related.

**Comment by nightroman** [comment] 2020-12-16 15:12
Is there some progress? I cannot wait to try and enjoy FSharp.Core 5.0.0 in our application...

**Comment by KevinRansom** [comment] 2020-12-16 20:42
@nightroman sorry I got randomised away from this.  I still need to take a look.

**Comment by goswinr** [comment] 2020-12-17 11:59
I get the same  `StopProcessingExn None` but also this on the FSI error Textwriter: 

```
error FS0078: Unable to find the file 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Microsoft.Workflow.Compiler.exe.dll' in any of
 C:\Windows\Microsoft.NET\Framework64\v4.0.30319
 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF
 D:\Git\Seff\binStandalone\Release\x64\net472
 D:\Git\Seff\binStandalone\Release\x64\net472\
```

**Comment by goswinr** [comment] 2020-12-17 12:03
for the `GetProjectOptionsFromScript`  I had to add `<PackageReference Include="Microsoft.Build.Utilities.Core" Version="16.8.0" />`  but the `FSharpChecker.ParseAndCheckFileInProject(filepath, 0, sourceText , options)`  also fails with:  `FSharpCheckFileAnswer.Aborted`

**Comment by nightroman** [comment] 2021-01-16 16:41
Happy New Year! Is there any progress or plans?

**Comment by nightroman** [comment] 2021-02-05 16:26
At least... is this issue, and hopefully related, going to be fixed? Or is it not fixable and net472 is not supported anymore?

**Comment by goswinr** [comment] 2021-02-05 16:37
Please maintain support for .NETStandard 2.0 of FSharp.Compiler.Service. 🙏
As it says on Nuget.org.
![image](https://user-images.githubusercontent.com/884885/107061626-b3ad2d80-67d8-11eb-8896-634bbe1bf9e1.png)

**Comment by KevinRansom** [comment] 2021-02-05 18:02
@goswinr , that is a mistake, we will fix it.

**Comment by cartermp** [comment] 2021-02-05 20:01
FCS isn't (and won't be) .NET 5 only.

**Comment by nightroman** [comment] 2021-02-05 20:16
>FCS isn't (and won't be) .NET 5 only.

I am still not sure how to treat the answers.

Is FCS supposed to work in net472 environment? It is not working, hence he issue.

**Comment by KevinRansom** [comment] 2021-02-05 20:17
It's pretty straightforward.   It's a bug.

**Comment by KevinRansom** [comment] 2021-02-05 21:46
The bug has been fixed in main for quite a while.
Preparing to release a new nuget package with the fix : 38.0.3https://github.com/dotnet/fsharp/pull/11030

**Comment by nightroman** [comment] 2021-02-06 05:14
@KevinRansom It's an awesome news, thank you. Does FCS have some nightly / prerelease packages? I would like to try and give some feedback. Like I mentioned, I had other issues not so easy to report. I wonder if they were related and got fixed or not.

**Comment by KevinRansom** [comment] 2021-02-06 05:28
@nightroman :

This is a preview package ... it's the same bits we will be publishing.

[FSharp.Compiler.Service.39.0.0-preview.21105.3.zip](https://github.com/dotnet/fsharp/files/5936317/FSharp.Compiler.Service.39.0.0-preview.21105.3.zip)

**Comment by baronfel** [comment] 2021-02-06 05:32
oh hey, the FSharp.Core dependency range is fixed in that one compared to a few days back! I can try previews now! Thanks team.

**Comment by nightroman** [comment] 2021-02-06 06:19
I am going through breaking changes and packaging issues.
I noticed that FCS depends on System.Buffers 4.0.2 but this package version is not even on NuGet.

**Comment by nightroman** [comment] 2021-02-06 06:33
So far cannot start due to:

>error FS0193: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

The assembly exists but has a different/newer version than expected.

**Comment by KevinRansom** [comment] 2021-02-06 06:39
The package dependency is correctly specified as:
        <dependency id="System.Buffers" version="4.5.1" exclude="Build,Analyzers" />
However, it seems as if the assembly version in the compile is incorrect.

The package has an assembly versioned 4.0.3.0 and the build seemed to use 4.0.2.0, I have no idea why right now.

**Comment by nightroman** [comment] 2021-02-06 06:41
Solved with app.config with assembly redirect. The actual System.Buffers assembly version is 4.0.3.0.
Should not perhaps FCS depend on this version instead of 4.0.2.0?

Interestingly, the NuGet package version is 4.5.1 and file version is 4.6.28619.1 ...

All in all, I am able to load FCS and this is a good start! I am testing further.

**Comment by KevinRansom** [comment] 2021-02-06 06:43
Yeah this is certainly a bug.  Everything about the build looks right, so there may be something environmental on the CI, anyway I will need to fix the bug.

**Comment by nightroman** [comment] 2021-02-06 06:58
Another dependency issues, now at runtime on testing

>error FS0193: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Also worked around using redirects. The actual version is 5.0.0.0

**Comment by KevinRansom** [comment] 2021-02-06 07:02
That is likely a missing dependency in the nuspec:   System.Runtime.CompilerServices.Unsafe  Although I have to say there were a number of files in the net472 directory of fcs I was surprised to see.

**Comment by nightroman** [comment] 2021-02-06 07:09
All my FCS interactive tests passed. This is awesome, I look forward to the new package FCS 39.

In the meantime I have and investigate `System.InvalidOperationException: Unexpected checker abort.` in our app editor services.

**Comment by KevinRansom** [comment] 2021-02-06 07:30
It's a bloody bug in the System.Buffers nuget package:
````
// Assembly System.Buffers, Version 4.0.2.0
Location: | C:\Users\codec\.nuget\packages\system.buffers\4.5.1\ref\netstandard2.0\System.Buffers.dll

// Assembly System.Buffers, Version 4.0.3.0
Location: C:\Users\codec\.nuget\packages\system.buffers\4.5.1\lib\netstandard2.0\System.Buffers.dll 
````

**Comment by nightroman** [comment] 2021-02-06 07:33
>In the meantime I have and investigate System.InvalidOperationException: Unexpected checker abort. in our app editor services.

Solved. It was my bad, missed `Microsoft.Build.Utilities.Core.dll`. But the error "Unexpected checker abort." could be better :-)

**Comment by nightroman** [comment] 2021-02-06 07:39
@KevinRansom Thank you for the fix and the provided preview package for testing. With mentioned caveats, FCS 39 seems to be working in our net472 environment! I look forward to the NuGet update, to make the awesome F# 5 available for our users.

**Comment by nightroman** [comment] 2021-02-06 07:47
Please feel free to close. Or I will close when FCS 39 is out, after final testing.

**Comment by KevinRansom** [comment] 2021-02-06 08:00
Raised bug against system.buffers: https://github.com/dotnet/runtime/issues/47949

**Comment by nightroman** [comment] 2021-02-06 08:02
May I highjack this thread for F# 5 FCS question? I've tried this NuGet package sample https://devblogs.microsoft.com/dotnet/announcing-f-5/#package-references-in-f-scripts

It works with `dotnet fsi` as expected but it fails in FCS

```
2.nuget.fsx(1,1): error FS3400: Package manager key 'nuget' was not registered in [C:\Bin\Far\x64\FarNet\Modules\FSharpFar; C:\Bin\Far\x64\], []. Currently registered: 
2.nuget.fsx(1,1): warning FS0213: '' is not a valid assembly name FSharp.Compiler.Interactive.Shell+FsiCompilationException: Operation could not be completed due to earlier error
```

Am I missing an assembly?

**Comment by KevinRansom** [comment] 2021-02-06 09:00
I made a few tweaks to your program.fs from the above solution and it works for me both net472 and net5.0:

Ensure that in your executable code directory the one containing FSharp.Compiler.Service there is also ````FSharp.DependencyManager.Nuget.dll````  The dll is part of the FSharp.Compiler.Service package.

![image](https://user-images.githubusercontent.com/5175830/107113749-c98d1380-6815-11eb-8a60-9b1cd69f6251.png)

**Comment by KevinRansom** [comment] 2021-02-06 09:10
Don't use:  https://www.nuget.org/packages/FSharp.DependencyManager.Nuget it's out of date, FSharp.Compiler.Service carries the nuget packagemanager dll.

**Comment by nightroman** [comment] 2021-02-06 09:16
Right, I missed `FSharp.DependencyManager.Nuget.dll` in your package zip.
I have now copied it from there.
But I still have the same problem...

**Comment by KevinRansom** [comment] 2021-02-06 09:18
Can you make a repro, or is it in your full project?

**Comment by nightroman** [comment] 2021-02-06 09:23
Strictly speaking I am calling `fsiSession.EvalScriptNonThrowing`, not `EvalInteractionNonThrowing`. Does it make a difference? I do not see other differences yet.

> Can you make a repro, or is it in your full project?

It is in my full project. But I will try make a repro case, indeed. (If the issue is not specific to the full app)

**Comment by nightroman** [comment] 2021-02-06 09:43
@KevinRansom Wow, it works when I run in the debugger and fails if I run without.
Amy clues what's going on?

**Comment by KevinRansom** [comment] 2021-02-06 09:47
It's kind of hugely late here, I'm bailing for the night.

**Comment by nightroman** [comment] 2021-02-06 09:47
To be precise, it works if start my app from Visual Studio, i.e. both F5 and CtrlF5 work fine.
But if I run the app on its own then the script fails.

**Comment by nightroman** [comment] 2021-02-06 09:48
>It's kind of hugely late here, I'm bailing for the night.

Sure, no problem, thank you for your help.

**Comment by nightroman** [comment] 2021-02-06 10:34
Here is what I found. nuget in scripts works if I set this environment variable (like when I start from VS):

    VSAPPIDDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\

So it looks like I have the workaround. But is it how it should be in "production"?

**Comment by KevinRansom** [comment] 2021-02-06 17:44
@nightroman on the desktop #r "nuget: uses msbuild.exe, and it has no way to find it, so it uses a set of heuristics.  Given that msbuild is deployed along with Visual studio, the places we look are there.

So VSAPPIDIR is a signal, VSINSTALLDIR is a single, and relative to FSharp.Compiler.Service.dll is a signal.
        let roots = [|
            Path.GetFullPath(Path.Combine(fsharpCompilerPath, "../../../../.."))
            vsRootFromVSAPPIDDIR
            Environment.GetEnvironmentVariable("VSINSTALLDIR")
            |]

When running on the coreclr it depends on the dotnet sdk and has similar heuristics.

**Comment by KevinRansom** [comment] 2021-02-06 18:02
@nightroman , I have actually been wondering whether I can just steal the package resolution code from paket that would still leave the individual dll resolution code, however, that is a much simpler problem than resolving the package graph.  The beauty of that as an approach, is it would eliminate the dependence on any external programs.
The problem is, as always, priorities and FUD ... we have something that works and is usable, and we don't know what nuget magic sauce users depend on.

**Comment by baronfel** [comment] 2021-02-06 18:13
yep, this is one of the reasons why @smoothdeveloper and I wonder about publishing these handlers as out-of-band components somehow. If we had that then we could more rapidly update the resolution logic and perhaps even try things like using the paket resolver in the nuget handler without tightly coupling the dependency manager to the SDK release schedule.

**Comment by KevinRansom** [comment] 2021-02-06 18:51
@baronfel #r "nuget:   is very close to the platform, and is pretty much a core part of the scripting language now.  It's the only use we really see on the notebooks, we rarely see developers references raw dll's any longer.  Also, once it's stable it shouldn't rev that frequently, indeed the only important change in the last while was the 
 possible deadlock fix:  
 https://github.com/dotnet/fsharp/commit/3b1b3001338cc2a96314c184eaedc047f0442eba#diff-321f4606dcf602dca5ba56bab895f1df3725686754fdb60bcd2c27c681d11d38

And the follow up commit.  The rest have been tweaks.

The bulk of the PackageManagment changes have been in the assembly and native dll resolution code.  Now that code has been revised a lot mainly I suppose due to trying to figure out how to be netstandard 2.0 only whilst using non netstandard2.0 apis (Ooops!!!) and will likely rev bigly again, because I think we are going to have to bite the bullet and have a package manager assembyloadcontext rather than relying on the default assemblyloadcontext.

But in truth, my biggest want is to eliminate our dependence on msbuild or dotnet build, doing that I am going to need to do the same sort of stuff as nuget.exe and paket, so making a library that we can ship and use is probably ideal.  Given that Steffen did the first #r nuget implementation it seems only fair that we should steal paket.core too :-)    However, I am not that keen to learn another 30000 line codebase.

**Comment by baronfel** [comment] 2021-02-06 18:53
> I am not that keen to learn another 30000 line codebase

Thank you for brightening my day with your phrasing!

**Comment by nightroman** [comment] 2021-02-06 18:57
Thank you all for the answers.
I have two more questions, probably the last, about FCS session configuration with F# 5.

(1) I see that `-r:nuget: PackafeID` does not work (equivalent of `#r` in scripts). Is this expected? If yes, will this way be supported in the future? I can see some advantages. Or is it possible that I am using the wrong syntax?

(2) `-r:-r:System.Management.Automation` (GAC assembly) worked in v37. Now it does not. It might be expected but I better ask. Is this OK or regression?

**Comment by KevinRansom** [comment] 2021-02-06 19:15
@nightroman

1.  No the truth of the matter is that the command line syntax for fsc are merely there these days to give msbuild a way to transfer information to the compiler.   Too much of package management and assembly resolution is built into msbuild that doing part of it in the compiler, would likely cause incompatabilities with builds constructed using msbuild.  We would nearly certainly end up with different versions of assemblies shared between packages and referenced projects and the like.

2.  Nothing we have done deliberately should have impacted GAC resolution.

**Comment by nightroman** [comment] 2021-02-06 19:21
@KevinRansom
1. I understand, thank you.
2. Should I submit a separate issue? (But I remember that .NET SDK projects do not support GAC references, so I though the issue might be related/expected)

**Comment by KevinRansom** [comment] 2021-02-06 19:25
@nightroman -- it shouldn't be related to netsdk non-support for the gac.  However, even if it's broken we probably wouldn't fix it, because it's not cross platform, and would likely only work on the desktop version of the compiler which we hope to deprecate one day.  So, it's a serendipitous break, encouraging developers not to rely on ambient state like the gac.

**Comment by nightroman** [comment] 2021-02-06 20:00
All right, once again thank you the fix of the main issue and for this long and useful discussion. Closing.

**Comment by KevinRansom** [comment] 2021-02-06 20:14
@nightroman , I will close it once we publish the actual package. 

Also the fsharp.core package referenced is not correct.  should be 5.0.0

[This System.Buffers: ](https://github.com/dotnet/fsharp/issues/10467#issuecomment-774408739) I will try to fix, before we ship.

[This System.Runtime.CompilerServices.Unsafe: ](https://github.com/dotnet/fsharp/issues/10467#issuecomment-774414165) I need to look at a bit more, but I suspect the issue is in your project, I believe the build is supposed to auto generate a binding redirect for you when you have conflicting references.  I suspect you are referencing something that pulls in : System.Runtime.CompilerServices.Unsafe, 5.0.0'' and the auto generate binding redirects is not working.

I added this to my project file to simulate this
````
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="5.0.0" />
````
And the build generated this config file:

**Comment by nightroman** [comment] 2021-02-07 06:40
> I believe the build is supposed to auto generate a binding redirect for you when you have conflicting references.

Probably if we build an executable. But our scenario is different. We are building a library ([FarNet.FSharpFar](https://github.com/nightroman/FarNet/tree/master/FSharpFar)). It used as a plugin in an existing application (Far Manager), native executable which is not ours.

Fortunately, in this scenario app.config tweaks work. But they are done manually and we ship this app.config together with `FarNet`, another plugin library which actually loads FSharpFar.

Note that this approach with redirects is not always available if you build and ship a library. Sometime you do not even know what app is going to use it.

**Comment by KevinRansom** [comment] 2021-02-07 08:25
@nightroman , i just checked the history of FSharp.Compiler.Ser vice, and it has depended on System.Buffers: 4.5.1 since version 34.0.1  https://www.nuget.org/packages/FSharp.Compiler.Service/34.0.1.

I don't think we can make the change after all this time.  We will have to wait for the bcl team to fix and deploy a corrected package.

**Comment by goswinr** [comment] 2021-02-07 08:50
> i just checked the history of FSharp.Compiler.Ser vice, and it has depended on System.Buffers: 4.5.1 since version 34.0.1

I am also hosting FCS in net472 and since 34.0.1 it doesn’t work anymore 
https://github.com/fsharp/FSharp.Compiler.Service/issues/935

**Comment by KevinRansom** [comment] 2021-02-07 09:11
yes ... and that is undesirable ...

**Comment by KevinRansom** [comment] 2021-02-07 09:13
The trouble is the graph to modify is pretty big, and we can't force upgrades, because we can't rely on binding redirects, and there are other packages apparently with similar issues.

**Comment by KevinRansom** [comment] 2021-02-07 09:14
I will give it another go to try and figure out a graph that will work I suppose.

**Comment by nightroman** [comment] 2021-02-07 09:57
@goswinr FWIW this is what I have in my host app.config and this works around issues on loading FCS 39

```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9999.9999.9999.9999" newVersion="5.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9999.9999.9999.9999" newVersion="4.0.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9999.9999.9999.9999" newVersion="5.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by nightroman** [comment] 2021-02-08 02:00
Sorry for yet another issue in this long thread. But it is rather serious and FCS 39 is not yet released, so I am not sure where to post it instead.

It looks like I lost the ability to debug scripts invoked by FCS 39 in Visual Studio 2019 (16.8.4), breakpoints are never hit.
On switching back to (my) previous FCS 37 all is fine, breakpoints are hit and script debugging is cool and useful.

For script debugging I either start the host app from VS by F5 and then invoke scripts there with breakpoints set in VS, or alternatively I attach VS debugger to already running host processes. Both ways work in FCS 37, none in FCS 39 :(

**Comment by KevinRansom** [comment] 2021-02-08 02:06
@nightroman , script debugging is not available on the coreclr, and the APIs are not available on a netstandard2.0 build of the compiler.  37.0.0 shipped a desktop build of the compiler, FCS no longer offers a desktop build, and so that feature is no longer available, along with a few other desktop only features.  We may eventually add back script debugging, but currently it is not possible.

Sorry,

Kevin

**Comment by nightroman** [comment] 2021-02-08 02:19
Oh, the brave new world...

**Comment by nightroman** [comment] 2021-02-08 20:24
> script debugging is not available on the coreclr

I started to think of a workaround. Optionally (i.e. with some "enable script debugging"), if evaluation is about to be performed with an attached debugger (I believe there is such API) then a new temporary session is used instead which compiles an assembly from sources and references it instead of adding sources.

I wonder if it is doable in principle, any thoughts? I know it is not the same runtime and some code may not work due to new sessions and compiled assemblies. That is why the workaround is optional. In many cases it might be useful (debugging is useful).

**Comment by KevinRansom** [comment] 2021-02-09 00:04
@nightroman , yes we can probably do something like what you suggest, however, that is a vast change from how the FSI repl currently generates and executes code.  I'm pretty sure we can do it in such a way that everything feels the same as it does today.  CSI in fact operates that way.

**Comment by KevinRansom** [comment] 2021-02-11 03:51
We posted new FSharp.Core and FSharp.CompilerService packages.

**Closed by KevinRansom** 2021-02-11 03:51 UTC
Labels: Area-FCS

**Comment by baronfel** [comment] 2021-02-11 03:54
great! I noticed that the release notes link is malformed in nuget: https://www.nuget.org/packages/FSharp.Compiler.Service/

**Comment by KevinRansom** [comment] 2021-02-11 05:05
@baronfel , I'm really gonna have to do better at those release notes.

**Comment by baronfel** [comment] 2021-02-11 05:08
It's ok, it's not like nuget is especially easy for _anyone_

**Comment by KevinRansom** [comment] 2021-02-11 05:14
Oh bloody heck it's the link generation:
**https://github.com/dotnet/fsharp**https://github.com/dotnet/fsharp/blob/main/release-notes.md#FSharp-Compiler-Service-3900

does the prefix twice.

**Comment by nightroman** [comment] 2021-02-11 07:57
>We posted new FSharp.Core and FSharp.CompilerService packages.

@KevinRansom Thank you for the long awaited update and fixes! Fantastic news.

What would you recommend for script debugging? Should we try to implement the workaround or there is a chance that FCS may do this in the future, relatively soon (months, not years)?

**Comment by KevinRansom** [comment] 2021-02-11 08:10
I don't really have a recommendation ... I don't really believe that a debugger is the best interface for a notebook or even a repl, a better way to display state is more interesting as well as a way to capture state history and stepping backwards and forwards through that.  THe problem with having the debugging feature, is that conditions the way we thing about things to match the vs debugger.  The good thing about not doing a debugger, is we can make it work cross platform.

**Comment by nightroman** [comment] 2021-02-11 08:15
> I don't really believe that a debugger is the best interface for a notebook or even a repl...

Well, our scenario is totally different from notebook or repl. FSharpFar provides normal programming using F# scripts without building assemblies and restarting anything. REPL is available as well but it is not that needed or used, in fact.

**Comment by KevinRansom** [comment] 2021-02-11 08:19
So sort of edit and continue on steroids, thats pretty nice.

**Comment by nightroman** [comment] 2021-02-11 08:20
Yes, exactly, I could not put it better.

**Comment by KevinRansom** [comment] 2021-02-11 08:27
We'll have something like it eventually, but it is not on the near horizon, I'm not sure that you can work around it, since the debugger needs source ranges and debugger symbols, which aren't really exposed in FSI.  So to do it I suspect requires some core compiler work.

**Comment by nightroman** [comment] 2021-02-11 08:29
I was thinking of a different workaround, presumably doable:

> Optionally (i.e. with some "enable script debugging"), if evaluation is about to be performed with an attached debugger (I believe there is such API) then a new temporary session is used instead which compiles an assembly from sources and references it instead of adding sources. So in theory script debugging is turned into usual debugging.

**Comment by KevinRansom** [comment] 2021-02-11 08:35
@nightroman , you lose access to the values which have been already computed, as well as previously compiled functions.

**Comment by nightroman** [comment] 2021-02-11 08:41
Yes, I am aware that the session / runtime is slightly different. That is why the "script debugging" mode will be offered as optional.
But like I said it is not that important in our scenarios, if there is a bug to debug, it's OK to do this in a fresh session.

**Comment by KevinRansom** [comment] 2021-02-11 08:43
cool, then compiling and debugging the script should be fine.

**Comment by goswinr** [comment] 2021-02-11 12:56
Many Thanks for this release!
In the past I used `FSharp.Compiler.Layout.showL` to get the signature as string of  a `Layout` .
the new `FSharp.Compiler.TextLayout.Layout` doesn't have a `showL` function anymore.
Is this internal now? https://github.com/dotnet/fsharp/blob/main/release-notes.md#changes-in-fsharpcompilertextlayout
Is there a new  way to get a signature string from an `FSharpToolTipElement` ?
