### ISSUE TITLE
Provide actual name ranges for FSharpSymbolUse

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#3920] opened 2017-11-10 12:26 UTC
Consider a use of FromString below:
```fsharp
let lexbuf = Lexing.LexBuffer<_>.FromString(str)
//           |----------------------------|
// current range is bigger than actual name usage
```
We could keep start pos of symbol use as well.

**Comment by dsyme** [comment] 2017-11-10 14:05
@auduchinok I suppose providing just the range ``FromString`` would be simpler and provide for overall accuracy.  I don't really know why we provided the long names historically.  Do you have any use for them?

My guess is that a fair bit of client FCS code is sensitive to this however.

**Comment by auduchinok** [comment] 2017-11-10 14:11
@dsyme No, there's no uses of it in our code.
Talking about client code I've seen, there're usually methods that trim these ranges and look error-prone (e.g. looking for dot separator that may be a part of operator).

**Comment by dsyme** [comment] 2017-11-10 14:18
> Talking about client code I've seen, there're usually methods that trim these ranges and look error-prone (e.g. looking for dot separator that may be a part of operator).

Yeah, I've seen that code too.  

I suppose we can do a major version upgrade and put out some info to major consumers that the ranges have changed

**Comment by vasily-kirichenko** [comment] 2017-11-10 15:38
I confirm that we don’t rely on long range and trimm them. If we need full long ident, we use QuickParse. I think we should add LongIdent into FSharpSymbolUse (however, we cannot remove QP entirely because we need to parse partially typed symbols in complition).

**Comment by dsyme** [comment] 2017-11-10 16:12
@vasily-kirichenko Thanks for checking!

**Comment by vasily-kirichenko** [comment] 2017-11-10 19:48
Implemented in https://github.com/Microsoft/visualfsharp/pull/3922. I think there will be a storm of failing tests :)

**Comment by vasily-kirichenko** [comment] 2017-11-14 20:19
@auduchinok 

![image](https://user-images.githubusercontent.com/873919/32802767-4867c572-c992-11e7-947b-e88308d9f984.png)

![image](https://user-images.githubusercontent.com/873919/32802743-2b5b8fae-c992-11e7-9e46-10d92edb59c8.png)

**Comment by auduchinok** [comment] 2017-11-14 20:25
@vasily-kirichenko This is great!
Looking at how `LexBuffer` is highlighted it looks like `<_>` is still in its range.

**Comment by vasily-kirichenko** [comment] 2017-11-14 20:53
Yes.

**Comment by dsyme** [comment] 2022-04-05 04:25
There is a duplicate of this error where "<_>" is still included.  I will close this.

**Closed by dsyme** 2022-04-05 04:25 UTC
Labels: Area-LangService, Feature Improvement
