### ISSUE TITLE
The last Visual Studio 16.3.2 hangs by switching solution configuration

### ISSUE THREAD

**Issue by AndreiDegtiarev** [dotnet/fsharp#7691] opened 2019-10-03 16:33 UTC
Solution contains c# and f# projects, netcore and netframework configurations. The switch from Debug to Release configuration cause endless operation with message box title “Microsoft Visual F# Tools” and with content “Updating solution configuration…”
* Operating System
Windows 10

* Editing Tools: Visual Studio 16.3.2

**Comment by cartermp** [comment] 2019-10-03 18:00
Relevant routine is here: https://github.com/dotnet/fsharp/blob/f50d9c4f2131eac75738fd4c381a1f658cf12db6/vsintegration/src/FSharp.ProjectSystem.FSharp/Project.fs#L1702-L1724

We haven't touched the legacy F# project system in a very long time, so this isn't a new change on our end.

@panopticoncentral @tmeschter were there any changes in the VS base project system that could affect this?

**Comment by tmeschter** [comment] 2019-10-03 18:17
Unfortunately I don't know how the legacy F# project system relate to the C#/VB systems and their underlying pieces.

Is this a regression from 16.2?

**Comment by cartermp** [comment] 2019-10-03 18:21
@AndreiDegtiarev would be good to know if this is indeed a regression from 16.0.

@tmeschter the legacy F# project system uses MPF underneath, but beyond that I don't know how it truly works with VS. There was an issue in the past where a VSLangProj change broke parallel builds - (possibly resurfaced in F# atop CPS in #7683) - but how that bubbles up to the F# legacy system is a bit of a mystery to me. @KevinRansom may know more.

**Comment by AndreiDegtiarev** [comment] 2019-10-03 18:53
Beginning from 16.3.2 (very last update) I’m not able any more to switch solution configuration from Debug to Release on two different machines. Cleaning, reboot don’t help. It is interesting that I have different debug and release configurations, the switch between debug configurations (netcore to framework) works without problems. In the previous Visual Studio updates there were already indications that something is going wrong but the reload of solution in previous versions did help

**Comment by panopticoncentral** [comment] 2019-10-04 17:31
There's nothing that I know of that's happened in the servicing updates, but there are other possibilities. @AndreiDegtiarev do you have a repro scenario we could try out? Barring that, could you take a full process dump (using something like https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) and attach it to a "Report a problem" in VS and then let us know?

**Comment by AndreiDegtiarev** [comment] 2019-10-05 05:49
@panopticoncentral Unfortunately, I don’t have a repo which I can share. We could make Skype conference where I can demonstrate my problem

**Comment by jmecosta** [comment] 2019-10-05 11:05
i also have the same problem

**Comment by AndreiDegtiarev** [comment] 2019-10-05 13:04
Thank you jmecosta, now I feel much better about myself because I’m not alone in this world with my problem :-)

**Comment by panopticoncentral** [comment] 2019-10-07 19:25
@AndreiDegtiarev @jmecosta Can you [report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) and then note it here? That will capture data we can use to start figuring out what's wrong.

**Comment by AndreiDegtiarev** [comment] 2019-10-08 12:14
Problem was reported. https://developercommunity.visualstudio.com/content/problem/766725/the-last-visual-studio-1632-hangs-by-switching-sol.html

**Comment by jmecosta** [comment] 2019-10-09 10:24
@panopticoncentral  been there, done that
![image](https://user-images.githubusercontent.com/1041352/66473498-0b7a3e00-ea98-11e9-8e0a-eb7e655bcba9.png)

its still in "triage" whatever that means... meanwhile we get the pain

**Comment by panopticoncentral** [comment] 2019-10-09 19:22
@AndreiDegtiarev You can ignore the "Need more info" status of your problem, it looks like there were some crossed wired, I'm looking at the dump to see if I can figure out what's going wrong.

@jmecosta The "triage" status means that it's waiting for the team to look at it to determine its priority and who should look at it. I'll email the team and see if they can get it triaged soon.

**Comment by jmecosta** [comment] 2019-10-12 19:32
darn, i cant release my application because i cant change the configuration to release

**Comment by jmecosta** [comment] 2019-10-12 19:52
as a workaround, open the sln file. Deleted all AnyCpu, x86, Debug stuff. so now have a solution file for debug and a solution for release! hopefully you guys can fix this

**Comment by abelbraaksma** [comment] 2019-10-13 12:39
> Is this a regression from 16.2?

@AndreiDegtiarev, @tmeschter, I also have a very large configuration with 8 solution configurations, mixed F#, C# and C++, but in 16.3.1 I don't encounter this situation. I have not updated to 16.3.2 yet because of this report, but I did notice something else: NCrunch (an addin) hangs sometimes on switching configurations. Just to say: did you try it with a `/SafeMode` switch to be sure there's not extension in the way?

@jmecosta, as an alternative for the workaround you mention, you could try these to ease the pain a bit:

* Run `devenv your.sln /Build Debug` or devenv your.sln /Build "Debug|x86"`, see [`/Build`](https://docs.microsoft.com/en-us/visualstudio/ide/reference/build-devenv-exe?view=vs-2019) switch for more info. This will at least allow you to release
* Alternatively, use MSBuild for building the solution
* Something that may or may not help with the issue, is upgrading all files, incl sln files, to the new Visual Studio version (though it's a long shot). You can do this automatically with [`devenv /Upgrade`](https://docs.microsoft.com/en-us/visualstudio/ide/reference/upgrade-devenv-exe?view=vs-2019)
* You can install multiple instances of Visual Studio, so you could install a new instance with a lower version. For the same reason I still have 15.9.x versions around if I get stuck, and both a 16.2.0 and a 16.3.1

Perhaps some things to try with your current situation:

* Try, before you switch solutions, to close all editors
* Try, before you switch solutions, to unload the prj files, this may lead to a specific project file that causes this behavior
* Perhaps there's a difference between switching from the toolbar (no popup) or switching from the configuration popup? Or doesn't the method matter and all ways lead to lockups?

> Editing Tools: Visual Studio 16.3.2

There's a 16.3.4 out, you might also try upgrading.

**Comment by jmecosta** [comment] 2019-10-13 19:19
16.3.4 has the same problem.. im pretty sure this started in 16.3.2

not sure if this helps
![image](https://user-images.githubusercontent.com/1041352/66720576-2be32900-ee07-11e9-9206-283c5c6c3180.png)

the devenv.exe /Build works ok, thanks for the hint

**Comment by AndreiDegtiarev** [comment] 2019-10-13 20:21
I can confirm that the problem has started with 16.3.2 and 16.3.4 has the problem as well.

**Comment by dsyme** [comment] 2019-10-15 03:10
I get this problem switching configurations in `VisualFSharp.sln`

**Comment by dsyme** [comment] 2019-10-15 03:19
@panopticoncentral This is a severe problem I think. Makes VS unusable.  I assume it only hits solutions containing legacy projects but still, that's a huge proportion of projects

**Comment by panopticoncentral** [comment] 2019-10-15 07:08
@dsyme `VisualFSharp.sln` doesn't have any legacy projects as far as I saw, does it? Can you make a report and then send me a link? For both @dsyme and @AndreiDegtiarev, do you see any activity in MSBuild worker processes?

**Comment by abelbraaksma** [comment] 2019-10-15 07:41
> I'm using 16.3.0 Preview 4.0

Interesting, as I'm using 16.3.1 (professional rtm, not preview) and don't have this problem on mixed legacy projects, which would put this bug earlier. @dsyme, how are you or others usually switching? Through config manager, or direct access drop down on toolbar (no popup)?

**Comment by AndreiDegtiarev** [comment] 2019-10-15 21:31
@panopticoncentral I don't see any activities in MSBuild process, I closed all open documents, I killed all child VS processes, but nothing helped

**Comment by panopticoncentral** [comment] 2019-10-15 21:31
This appears to be the issue addressed [here](https://developercommunity.visualstudio.com/content/problem/748449/vs2019-1630-hang-when-closing-or-change-solution-c.html). It is currently scheduled to be fixed in the next minor release (16.4) but we're looking at servicing it in the current minor release (16.3.x). You can follow it's progress there.

**Comment by cartermp** [comment] 2019-10-15 21:34
@dsyme I'm not sure how to reproduce this with VisualFSharp.sln. I switched configurations from Debug to Release and VS doesn't have with the 16.3.5 update and latest master.

**Comment by cartermp** [comment] 2019-10-15 21:35
As per @panopticoncentral's comment I'll close this.

**Closed by cartermp** 2019-10-15 21:35 UTC
Labels: Area-External, Area-IDE Legacy Project System

**Comment by AndreiDegtiarev** [comment] 2019-10-15 21:59
Unfortunately, version 16.3.5 didn’t solve my problem. I've waited for about 15 minutes but the result is the same: VS hangs

**Comment by cartermp** [comment] 2019-10-15 22:17
@AndreiDegtiarev As per the linked issue, the fix is scheduled for 16.4 and _may_ be serviced into the 16.3.x release.

**Comment by panopticoncentral** [comment] 2019-10-15 22:17
For some reason the item I linked to says it is fixed in the current release, which is wrong. It's not going to be fixed until 16.4 at the moment. You can verify this in the current VS preview.

**Comment by abelbraaksma** [comment] 2019-10-15 22:18
@AndreiDegtiarev in not sure it's already in the current download, see @panopticoncentral comment of 44 min ago, at which moment it wasn't, which is hardly enough time to get it out. But I can be wrong ;)

**Comment by AndreiDegtiarev** [comment] 2019-10-16 07:02
@panopticoncentral Thank you for the solution of this problem! One question more. VS 16.4 will be released together with .net core 3.1 and .net core 3.1 is planned for December 2019. So, the solution of actual problem will be not released earlier as in about two months, is this correct?

**Comment by abelbraaksma** [comment] 2019-10-16 07:30
@panopticoncentral, here's a quote from an earlier post, looks like they'll try to release it sooner:

> but we're looking at servicing it in the current minor release

**Comment by abelbraaksma** [comment] 2019-10-23 12:38
Hmm, yesterday 16.3.6 came out and I hoped the fix would be part of this. While they updated the issue to the correct status (it is now _Solved - pending release_), it doesn't seem to have made it in this release...

See https://developercommunity.visualstudio.com/content/problem/748449/vs2019-1630-hang-when-closing-or-change-solution-c.html

**Comment by jmecosta** [comment] 2019-10-23 15:11
at least its consistent with release notes of 16.3.6, not release yet :(

**Comment by AndreiDegtiarev** [comment] 2019-10-23 16:48
The last statement from @panopticoncentral  was 

> It's not going to be fixed until 16.4 at the moment. 

So it seems that before December we will not get solution, I hope that I'm wrong

**Comment by AndreiDegtiarev** [comment] 2019-10-25 19:38
Workaround suggested here: https://developercommunity.visualstudio.com/comments/794272/view.html by Nicholas Poh has solved my problem and the fix will be released in the next VS update v16.3.7

**Comment by jmecosta** [comment] 2019-10-27 09:39
![image](https://user-images.githubusercontent.com/1041352/67632616-6096bc00-f8ae-11e9-9962-938c142db66f.png)
doesnt lock

**Comment by jmecosta** [comment] 2019-11-03 16:49
Fixed in latest 16.3 for me
