### ISSUE TITLE
Compiler chooses arbitrary, incorrect instantiation of generic interface when correct one is inferable

### ISSUE THREAD

**Issue by DalekBaldwin** [dotnet/fsharp#10432] opened 2020-11-11 22:15 UTC
This concerns the new F# 5 feature, https://github.com/fsharp/fslang-design/blob/master/preview/FS-1031-Allow%20implementing%20the%20same%20interface%20at%20different%20generic%20instantiations%20in%20the%20same%20type.md

```fsharp
type IA<'T> =
    abstract DoStuff : 'T -> string

type MyThing () =
    interface IA<string> with
        member __.DoStuff x = x
    interface IA<int> with
        member __.DoStuff x = x.ToString()
```

For generic interfaces to be broadly useful in F# in a clean, fluid style without explicit casting, the compiler should be able to infer the correct implementation when applying bounded polymorphic functions.

```fsharp
// instead of this
(mything :> IA<int>).DoStuff 5
(mything :> IA<string>).DoStuff "blah"

// define this
let dostuff (i:#IA<'T>) (x:'T) =
    i.DoStuff x

dostuff mything 5
5 |> dostuff mything
dostuff mything "blah"
"blah" |> dostuff mything

// or, same thing with arguments reversed
let dostuffrev (x:'T) (i:#IA<'T>) =
    i.DoStuff x

dostuffrev 5 mything
mything |> dostuffrev 5
dostuffrev "blah" mything
mything |> dostuffrev "blah"
```

**Expected behavior**

```fsharp
dostuff mything 5 // "5"
5 |> dostuff mything // "5"
dostuff mything "blah" // "blah"
"blah" |> dostuff mything // "blah"

dostuffrev 5 mything // "5"
mything |> dostuffrev 5 // "5"
dostuffrev "blah" mything // "blah"
mything |> dostuffrev "blah" // "blah"
```
**Actual behavior**

`dostuff` has a case that fails when `dostuffrev` succeeds, and vice versa. In each case the compiler prematurely decides that `IA<int>` is the only possible implementation, and reports a type mismatch in the other argument:

```fsharp
dostuff mything "blah"
//error FS0001: This expression was expected to have type
//    'int'    
//but here has type
//    'string'    

mything |> dostuffrev "blah"
//error FS0001: This expression was expected to have type
//    'int'    
//but here has type
//    'string'    
```

That is, `dostuff` works for both types only in the pipelined style, and `dostuffrev` works for both types only in the direct application style.

**Known workarounds**

Defining a single-argument uncurried function can work:

```fsharp
let dostufftup (x:'T, i:#IA<'T>) =
    i.DoStuff x

dostufftup (5, mything) // "5"
(5, mything) |> dostufftup // "5"
dostufftup ("blah", mything) // "blah"
("blah", mything) |> dostufftup // "blah"
```

But not always:

```fsharp
let dostufftuprev (i:#IA<'T>, x:'T) =
    i.DoStuff x

dostufftuprev (mything, 5) // "5"
(mything, 5) |> dostufftuprev // "5"

dostufftuprev (mything, "blah")
//error FS0001: This expression was expected to have type
//    'int'    
//but here has type
//    'string'    

(mything, "blah") |> dostufftuprev
//error FS0001: Type mismatch. Expecting a
//    'MyThing * string -> 'a'    
//but given a
//    'MyThing * int -> string'    
//The type 'string' does not match the type 'int'
```

**Related information**

* Operating system: Windows 10
* .NET Runtime kind: .Net 5 (Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0)

**Comment by cartermp** [comment] 2020-11-12 18:52
cc @KevinRansom who worked on the feature, looks like there's a gap related to inference around flexible types

**Comment by dsyme** [comment] 2020-12-03 21:19
There is also a relevant F# type inference limitation that may be coming into play - I haven't looked closely at the repo above but it is definitely relevant to #10516 

The important thing to know is this:

> **When F# sees `'a :> IA<ty1>` and `'a :> IA<ty2>` constraints for a type inference variable `'a` then it unifies `ty1` and `ty2`.**

This is by design, and one of the reasons why multiple instantiations of generic interfaces was not supported in F#. 

The reason this is done is that it is very, very common to have `'a :> seq<ty1>` and `'a :> seq<ty2>` for partially inferred types `ty1` and `ty2`.  This happens everywhere in F# code and in this situation it's crucial to flow type equalities between `ty1` and `ty2`.  

That is, the F# type inference system simply assumes that generic code is not constrained over multiple different interface instantiations.

Type definitions that implement multiple instantiations can be *used* but you can't write F# generic code over this code or structure.

It would be a separate RFC to enable this in some limited cases (e.g. when full type annotations are given), though I'd also recommend just not trying to do this

This may or may not be the cause of the above.  On a quick glance it is the cause of #10516

**Comment by DalekBaldwin** [comment] 2020-12-03 21:36
Interesting. In my code, the test lines are evaluated entirely separately, with only one concrete type (either `string` or `int`) to unify against the `'T` in `IA<'T>`, so I believe the underlying cause is different from #10516 .

**Comment by DalekBaldwin** [comment] 2020-12-03 21:49
That is, `dostuff mything "blah"` will fail to typecheck even if that's the only use of `dostuff` that appears anywhere.

**Comment by dsyme** [comment] 2020-12-04 11:10
@DalekBaldwin It's the same issue as the one I mentioned, or at least closely related.

When you do `dostuff mything` or `mything |> dostuffrev` the constraint of `IA<?T> = IA<int>` is encountered before the constraint `IA<?T> = IA<string>` and `int` is chosen to solve the inference type `?T`.

When you do `5 |> dostuff mything` or `"blah" |> dostuff mything` the solution `?T = int` or `?T = string` is pre-chosen and it is obvious (I believe via the feasibly-equivalent relationship in the compiler and language spec) that the compiler can apply the appropriate `C :> IA<int>` or `C :> IA<string>`

Given the constraint `C :> IA<?T>` the compiler will not continue with `?T` unresolved.

So this is just how it works. If you're going to use this feature you'll need type annotations and/or flowed type information.

**Comment by dsyme** [comment] 2020-12-04 11:10
I'll close this as by design.  Please add a language suggestion to fslang-suggestions if you wish.

**Closed by dsyme** 2020-12-04 11:10 UTC
Labels: Area-Compiler, bug
