### ISSUE TITLE
FSI internal error FS0193: Could not load file or assembly 'System.Diagnostics.StackTrace', and bunch of "binding session" messages

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#13126] opened 2022-05-11 11:37 UTC
I unexpectedly got the error in the title, multiple times:

> error FS0193: internal error: Could not load file or assembly 'System.Diagnostics.StackTrace, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)

**Repro steps**

I used FSI in VS 2022, and copied this snippet _without first opening the namespaces_:

```f#
> let f = List.map (fun (k, v) -> Generic.KeyValuePair(k, v));;

  let f = List.map (fun (k, v) -> Generic.KeyValuePair(k, v));;
  --------------------------------^^^^^^^

stdin(7,33): error FS0039: The value, namespace, type or module 'Generic' is not defined.
..... (see below)
```

**Expected behavior**

It should just give the "missing namespace" error.

**Actual behavior**

It gave instead this odd bunch:

```text
error FS0193: internal error: Could not load file or assembly 'System.Diagnostics.StackTrace, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)



error FS0193: internal error: Could not load file or assembly 'System.Diagnostics.StackTrace, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)



error FS0193: internal error: Could not load file or assembly 'System.Diagnostics.StackTrace, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)

Binding session to 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.3\ref\net6.0\System.Diagnostics.StackTrace.dll'...
Binding session to 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.3\ref\net6.0\System.Diagnostics.StackTrace.dll'...
Binding session to 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.3\ref\net6.0\System.Diagnostics.StackTrace.dll'...
Binding session to 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.3\ref\net6.0\System.Diagnostics.StackTrace.dll'...
Binding session to 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.3\ref\net6.0\System.Diagnostics.StackTrace.dll'...
Binding session to 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.3\ref\net6.0\System.Diagnostics.StackTrace.dll'...
Binding session to 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.3\ref\net6.0\System.Diagnostics.StackTrace.dll'...
```

**Known workarounds**

* Ignore the odd behavior and continue ;).
* Reset FSI also seemed to make the error go away. Which begs the q. whether it'll pop up again or not.

**Related information**

* Operating system: Widows 10 & 11
* .NET 6, F# 6, preview _not_ selected
* VS 2022

F# interactive settings were such:

![image](https://user-images.githubusercontent.com/16015770/167840853-694efed2-bef6-4c0c-b567-03e6d605377c.png)

Oddly, running the same snippet with `dotnet fsi` _does not exhibit the same behavior_:

```text
D:\Projects\Tests>dotnet fsi

Microsoft (R) F# Interactive version 12.0.1.0 for F# 6.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let f = List.map (fun (k, v) -> Generic.KeyValuePair(k, v));;

  let f = List.map (fun (k, v) -> Generic.KeyValuePair(k, v));;
  --------------------------------^^^^^^^

stdin(1,33): error FS0039: The value, namespace, type or module 'Generic' is not defined.
```

**Comment by dsyme** [comment] 2022-05-23 15:56
@vzarytovskii I don't repro this, do you?

@abelbraaksma   Maybe it depends on global.json in script directory?

**Comment by vzarytovskii** [comment] 2022-05-23 16:14
Hm, just checked - couldn't reproduce it.

**Comment by dsyme** [comment] 2022-08-16 10:20
Closing as both @vzarytovskii and I tried to repro and couldn't.

Thanks!

**Closed by dsyme** 2022-08-16 10:20 UTC
Labels: Bug, Regression, Area-FSI, Impact-Medium

**Comment by abelbraaksma** [comment] 2022-08-16 11:58
Yeah, I can't repro it either anymore.

**Comment by deyanp** [comment] 2022-10-11 11:49
@dsyme , can this be reopened?

I am getting the following error (after reinstalling dotnet sdk on Ubuntu 22.04):

```
otnet fsi

Microsoft (R) F# Interactive version 12.0.4.0 for F# 6.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let x = {| a = "aaa" |};;


error FS0193: internal error: Unable to load one or more of the requested types.
Method 'CompareTo' in type '<>f__AnonymousType3185369283`1' from assembly 'FSI-ASSEMBLY2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```
