### ISSUE TITLE
FSharp.Core reference not found in .NET 5 RC1, RC2

### ISSUE THREAD

**Issue by reinux** [dotnet/fsharp#10255] opened 2020-10-14 19:58 UTC
FSharp.Core 5.0.0 seems not to be getting installed, either by the VS Community preview installer or by the .NET SDK installer.

I thought it might be just me, but it seems some other people are having the issue as well.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Install VSCommunity or .NET SDK, RC1 or RC2
2. Start a new project (any F# project) or .fsx
3. Build or execute some code

**Actual behavior**

> Error FS3217 error NU1102: Unable to find package FSharp.Core with version (>= 5.0.0) F# Miscellaneous Files
> Error FS3217 error NU1102: - Found 35 version(s) in nuget.org [ Nearest version: 5.0.0-beta.20417.1 ] F# Miscellaneous Files
> Error FS3217 error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages F# Miscellaneous Files

**Known workarounds**

Apparently, [some people are just using FSharp.Core 4.7](https://www.reddit.com/r/fsharp/comments/javuyg/anyone_else_having_trouble_getting_net_5_rc1_or/) from nuget for now. This doesn't work with F# Interactive.

**Related information**

I haven't tried uninstalling RC2 yet, but uninstalling RC1 hadn't worked, instead instantly telling me it was done rather than actually uninstalling. Details at https://github.com/dotnet/core/issues/5200 . To summarize:

Editing C:\program files\dotnet\sdk\5.0.100-rc.1.20452.10\fsharp\Microsoft.FSharp.NetSdk.props so that the value of the FSCorePackageVersion tag reads 5.0.0-beta.* as opposed to 5.0.0 (to match FSharpCorePreviewPackageVersion) enabled the template and dotnet restore to work, but dotnet build produces this error:

```
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Microsoft.Common.CurrentVersion.targets(1178,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\rei\source\repos\test\test.fsproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Microsoft.Common.CurrentVersion.targets(1178,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\rei\source\repos\test\test.fsproj]
    0 Warning(s)
    1 Error(s)
```

* Operating system
Windows 10 Pro 19041.572
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
.NET 5 RC1, RC2
* Editing Tools (e.g. Visual Studio Version, Visual Studio)
Visual Studio Community, VSCode

**Comment by brettfo** [comment] 2020-10-15 17:47
Thanks for reporting the issue.  Can you post the contents of your `.fsproj` and `.fs` files?  I just installed RC2 and invoked this:

``` bash
dotnet new console --language F#
```

And that generated two files, `Project.fsproj`:

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

And `Program.fs`:

``` fsharp
// Learn more about F# at http://docs.microsoft.com/dotnet/fsharp

open System

// Define a function to construct a message to print
let from whom =
    sprintf "from %s" whom

[<EntryPoint>]
let main argv =
    let message = from "F#" // Call the function
    printfn "Hello world %s" message
    0 // return an integer exit code
```

I was then able to restore/build/run:

``` bash
$ dotnet restore
...
$ dotnet build
...
$ dotnet run
Hello world from F#
```

Examining the final output binary with `ildasm` I can see that it's got a reference to `FSharp.Core, version=5.0.0.0` and the correct file was also copied to the `bin/Debug` directory.

I was also able to repeat this experiment after deleting the `~/.nuget/FSharp.Core` directory, ensuring that I didn't get lucky with a locally cached copy.  Running the restore step downloaded package version `5.0.0-beta.20514.8`.

**Comment by reinux** [comment] 2020-10-15 18:17
`dotnet new console --language F#` manages to make a project, but fails trying to restore it:

```
PS C:\Users\rei\source\repos\Test4> dotnet new console -lang F#
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Users\rei\source\repos\Test4\Test4.fsproj...
  Determining projects to restore...
C:\Users\rei\source\repos\Test4\Test4.fsproj : error NU1102: Unable to find package FSharp.Core with version (>= 5.0.0)
C:\Users\rei\source\repos\Test4\Test4.fsproj : error NU1102:   - Found 35 version(s) in nuget.org [ Nearest version: 5.0.0-beta.20417.1 ]
C:\Users\rei\source\repos\Test4\Test4.fsproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  Failed to restore C:\Users\rei\source\repos\Test4\Test4.fsproj (in 118 ms).
Restore failed.
Post action failed.
```

Just to be sure, `dotnet --version` prints `5.0.100-rc.2.20479.15`.

Program.fs:

```
// Learn more about F# at http://docs.microsoft.com/dotnet/fsharp

open System

// Define a function to construct a message to print
let from whom =
    sprintf "from %s" whom

[<EntryPoint>]
let main argv =
    let message = from "F#" // Call the function
    printfn "Hello world %s" message
    0 // return an integer exit code
```

Test4.fsproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

Also, here's the content of my .nuget folder. I was kind of expecting FSharp.Core.dll to be missing or something, but it looks the same for 4.7.2:

```
    Directory: C:\Users\rei\.nuget\packages\fsharp.core\5.0.0-beta.20417.1\lib\netstandard2.0


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2020-09-24  11:12 PM                cs
d-----        2020-09-24  11:12 PM                de
d-----        2020-09-24  11:12 PM                es
d-----        2020-09-24  11:12 PM                fr
d-----        2020-09-24  11:12 PM                it
d-----        2020-09-24  11:12 PM                ja
d-----        2020-09-24  11:12 PM                ko
d-----        2020-09-24  11:12 PM                pl
d-----        2020-09-24  11:12 PM                pt-BR
d-----        2020-09-24  11:12 PM                ru
d-----        2020-09-24  11:12 PM                tr
d-----        2020-09-24  11:12 PM                zh-Hans
d-----        2020-09-24  11:12 PM                zh-Hant
-a----        2020-08-17   6:32 PM        2885504 FSharp.Core.dll
-a----        2020-08-17   6:32 PM         862221 FSharp.Core.xml
```

**Comment by brettfo** [comment] 2020-10-15 18:48
From the directory that you're running these commands, can you look all the way up to the root to see if there's a file named `global.json` or `NuGet.config`?  Those files can affect what SDK gets used to build (`global.json`) and what NuGet sources to use `NuGet.config`).  There may be one of those that's interrupting something.

E.g., if your test project is at `C:\Code\Samples\Tests\Test.fsproj`, look for any of the following files:

- `C:\Code\Samples\Tests\global.json`
- `C:\Code\Samples\Tests\NuGet.config`
- `C:\Code\Samples\global.json`
- `C:\Code\Samples\NuGet.config`
- `C:\Code\global.json`
- `C:\Code\NuGet.config`
- `C:\global.json`
- `C:\NuGet.config`

If you do find any of those files, can you post the contents?

Finally, if none of those files are present (or if the contents are benign), you can add this like to your `.fsproj` to let NuGet know about the preview package feed so restore will work.  You'll need to add it between the `<PropertyGroup>` and `</PropertyGroup>` tags:

``` xml
<RestoreSources>$(RestoreSources);https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json</RestoreSources>
```

**Comment by cartermp** [comment] 2020-10-15 18:54
FWIW I do not reproduce this issue either on my mac, and that one has no additional messing about with feeds going on.

**Comment by reinux** [comment] 2020-10-15 18:56
Can't find either global.json or NuGet.config.

Adding `RestoreSources` doesn't seem to have helped, although now it's detecting more versions.

I threw in a `<LangVersion>preview</LangVersion>` just to try it out, but that didn't help either.

PS C:\Users\rei\source\repos\test4> cat .\Test4.fsproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RestoreSources>$(RestoreSources);https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json</RestoreSources>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
PS C:\Users\rei\source\repos\test4> dotnet restore
  Determining projects to restore...
C:\Users\rei\source\repos\test4\Test4.fsproj : error NU1102: Unable to find package FSharp.Core with version (>= 5.0.0)
C:\Users\rei\source\repos\test4\Test4.fsproj : error NU1102:   - Found 296 version(s) in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json [ Nearest version: 5.0.0-beta.20514.8 ]
  Failed to restore C:\Users\rei\source\repos\test4\Test4.fsproj (in 98 ms).

**Comment by cartermp** [comment] 2020-10-15 19:03
@reinux Can you upload the full project after a build (bin and obj) here? I can't reproduce this on any of my machines.

**Comment by reinux** [comment] 2020-10-15 19:08
[Test4.zip](https://github.com/dotnet/fsharp/files/5387223/Test4.zip)

FYI this has the `LangVersion` tag set.

This is a bit far-fetched, but do you think it might be using a different string comparison on my machine, so it's not seeing 5.0.0.* as being `>=` 5.0.0?

I have a bunch of Japanese stuff going on on my machine, and while I haven't changed the UI language or the default region or anything, I've seen a lot of programs try to choose a language by various other obscure means.

**Comment by cartermp** [comment] 2020-10-15 23:24
I just downloaded the repro you uploaded and it ran without issue on my machine, against FSharp.Core `5.0.0-beta.20515.4` as-written in the `project.assets.json` file.

The locale thing might be a lead, but I doubt it's the case.

As it stands I have no idea why this might be happening on your machine. Do you notice any issues building any C# projects if you have them?

**Comment by reinux** [comment] 2020-10-15 23:31
Huh... I could have sworn it was working before with RC1, but C# is failing now as well. `dotnet restore` works fine, but `dotnet build` on a new project from the C# console template fails.

```
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Microsoft.Common.CurrentVersion.targets(1180,5): error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\rei\source\repos\test6\test6.csproj]
```

I did try downloading and installing the MSI for the SDK, but as before, it finishes instantaneously and doesn't seem to have made any difference. This particular symptom is actually why I posted an issue under dotnet/core.

**Comment by cartermp** [comment] 2020-10-16 17:30
Yeah, that would point to something wrong with your environment. Have you tried uninstalling and re-installing the RCs?

**Comment by reinux** [comment] 2020-10-16 19:54
I have, yes.

That was a tad strange too, because when I install or uninstall the SDK (for either RC1 or RC2) without uninstalling VS first, it would finish instantaneously without actually doing anything other than just toggling the install/uninstall button the next time I run it.

I guess the UI just hasn't been made to warn you that VS depends on it.

**Comment by reinux** [comment] 2020-10-17 02:09
Just tried uninstalling all versions of .NET Core and Visual Studio and reinstalled VS 2019 Preview on its own. No dice.

**Comment by KevinRansom** [comment] 2020-10-19 18:29
Hey Reinux,

It's not at all clear to me why this is not working.  I think we need to approach this slowly.

1. Can you create, build and debug a C# project, with your current set up?

**Comment by reinux** [comment] 2020-10-19 20:05
Unfortunately, after a ton of tinkering, I've become unable to reproduce the problem either, and I'm not 100% sure why.

The last things I did were to uninstall all versions of the SDK and VS, manually remove `\Program Files\dotnet\sdk` (because the uninstaller doesn't actually do anything), and then reinstall just VS 2019 Preview.

I *think* it might have something to do with the fact that I had .NET Core 3 SDK installed via Scoop. Maybe .NET 5 barfs when the registry tells it that there should be a previous version of the SDK, but can't find it because the path is hard-coded?

**Comment by cartermp** [comment] 2021-02-06 22:28
Closing this out due to no reproduction, and it seems like it may have been an environmental thing

**Closed by cartermp** 2021-02-06 22:28 UTC
Labels: Area-MSBuild, Area-SDK and Samples, needs repro
