### ISSUE TITLE
same code compiles in VS but not in FSI

### ISSUE THREAD

**Issue by mattg23** [dotnet/fsharp#9945] opened 2020-08-15 12:47 UTC
Hi,
I have a project where i'm using F# as an embedded scripting language for user scripts.
I am having trouble compiling lambda expressions in FSI. 
The same expression compiles fine using VS in a normal .fs file. 
I boiled the example down to the most simple.

**Repro steps**
[Repo with my test program](https://github.com/mattg23/ReproFsi)

```
open System.Text
open System.IO
open FSharp.Compiler.Interactive.Shell

let smallLambda = fun x -> let p = x
                           p

let smallLambda2 =
    fun x ->
        let p = x
        p

let codeSmallLambda = """
let smallLambda = fun x -> let p = x
                           p

"""

// this works in F# Interactive window
let codeSmallLambda2 = """
let smallLambda2 =
    fun x ->
        let p = x
        p
"""

[<EntryPoint>]
let main argv =

    printfn "smallLambda: %A , smallLambda2: %A" smallLambda smallLambda2

    let sbOut = StringBuilder()
    let sbErr = StringBuilder()

    let fsi =
        let inStream = new StringReader "" 
        let outStream = new StringWriter(sbOut)
        let errStream = new StringWriter(sbErr)
        let fsiConfig = FsiEvaluationSession.GetDefaultConfiguration()       
        let argv = [| "fsi.exe"; "--noninteractive"; "--quiet";"--nologo";"--langversion:latest" |]
        let session = FsiEvaluationSession.Create(fsiConfig, argv, inStream, outStream, errStream)
        session.EvalInteractionNonThrowing "open System;;" |> ignore
        session.EvalInteractionNonThrowing "#indent \"off\";;" |> ignore
        session

    printfn "TEST: %s" codeSmallLambda

    let evalresult, errors = fsi.EvalExpressionNonThrowing codeSmallLambda 

    match evalresult with
    | Choice1Of2(Some fsiValue) -> printfn "compile successful: %A" fsiValue
    | Choice2Of2(e) -> printfn "%A" e

    errors |> Array.map (printfn "%A") |> ignore

    printfn "TEST: %s" codeSmallLambda2

    let evalresult, errors = fsi.EvalExpressionNonThrowing codeSmallLambda2 

    match evalresult with
    | Choice1Of2(Some fsiValue) -> printfn "compile successful: %A" fsiValue
    | Choice2Of2(e) -> printfn "%A" e

    errors |> Array.map (printfn "%A") |> ignore

    0 // return an integer exit code
```

**Expected behavior**

code should compile fine using `fsi.EvalExpressionNonThrowing`.

**Actual behavior**

**The output of the above program is:**
```
smallLambda: <fun:main@29-2> , smallLambda2: <fun:main@29-3>
TEST:
let smallLambda = fun x -> let p = x
                           p


FSharp.Compiler.Interactive.Shell+FsiCompilationException: Operation could not be completed due to earlier error
input.fsx (5,1)-(5,1) parse error Unexpected end of input in expression. Expected 'in' or other token.
input.fsx (5,1)-(5,1) interactive error parse error
TEST:
let smallLambda =
    fun x ->
        let p = x
        p

FSharp.Compiler.Interactive.Shell+FsiCompilationException: Operation could not be completed due to earlier error
input.fsx (6,1)-(6,1) parse error Unexpected end of input in expression. Expected 'in' or other token.
input.fsx (6,1)-(6,1) interactive error parse error
```

Output of "F# Interactive" window in VS:
```
> let smallLambda = fun x -> let p = x
                             p
;;

                               p
  -----------------------------^

stdin(4,30): error FS0010: Unexpected identifier in binding. Expected incomplete structured construct at or before this point or other token.

> let smallLambda =
    fun x ->
        let p = x
        p
;;
val smallLambda : x:'a -> 'a
```

**Known workarounds**

None

**Related information**

Provide any related information (optional):

* Operating system: Win 10
* .NET Runtime kind: tested on (no difference in behavior found):
    * net5.0
    * netcoreapp3.1
    * net461
    * net471 

* Editing Tools: VS Enterprise 2019, v16.7.0

**Comment by dsyme** [comment] 2020-08-24 15:03
I think this is by design when using `EvalExpressionNonThrowing` - have you tried using `EvalInteractionNonThrowing`?

**Comment by dsyme** [comment] 2020-08-24 15:14
Actually it's also the use of `#indent "off"`.  Whya re you using that?

Anyway this is by design

**Comment by cartermp** [comment] 2020-08-24 15:40
What is by design, the indent off or the other FSI API?

When i remove indent off and use the other API there is no FSI value. When i use `EvalExpressionNonThrowing` then it's a different error. There does not appear to be a way to mimic how FSI itself actually evaluates these with these APIs.

What API should be used? Re-opening until there's closure on this.

**Comment by mattg23** [comment] 2020-08-24 16:05
I second the question by @cartermp.
I have updated my repo to include tests with indent on/off and `EvalExpressionNonThrowing` and `EvalInteractiveNonThrowing`.
If you like I can post the output here, so that you don't have to download the repo. 
But none of the tests reproduce a usable FsiValue.

The reason I have indent "off" is, that the code I compile to a `FsiValue` is actually provided by the user and I have no control over the editor they are using (tabs vs spaces). But if indent "on" would be a requirement to make this work, that should not be a problem for me to enforce.

I guess the other way would be to use the actual compiler to create an in memory assembly containing the user code and call that?

**Comment by dsyme** [comment] 2020-08-26 12:26
> I have updated my repo to include tests with indent on/off and EvalExpressionNonThrowing and EvalInteractionNonThrowing.

Yes, my undertstanding is that you should use `EvalInteractionNonThrowing` to evaluate the declarations.

To access non-function values you then use either the `ValueBound` event or `GetBoundValues` or a call to `EvalExpressionNonThrowing` with the text of the variable name.

To access function values is a bit trickier.  In general you use `EvalExpressionNonThrowing` but if they are generic functions you will need to type constrain the generic function to a specific ground type not involving generic parameters.

See https://github.com/mattg23/ReproFsi/pull/1

> The reason I have indent "off" is, that the code I compile to a FsiValue is actually provided by the user and I have no control over the editor they are using (tabs vs spaces). But if indent "on" would be a requirement to make this work, that should not be a problem for me to enforce.

If you turn indentation awareness off then the examples declarations you're evaluating are no longer valid F# code.

If they are coding F#, they will need to be using an editor using spaces, or do a tabs-to-spaces transform as you acquire the text

**Comment by dsyme** [comment] 2020-08-26 12:30
I will close this again as the behaviour is as expected even if the calls are a bit convoluted.

**Closed by dsyme** 2020-08-26 12:30 UTC
Labels: Area-FSI, bug
