### ISSUE TITLE
Type inference breaks over multiple instantiations of generic interface

### ISSUE THREAD

**Issue by Horusiath** [dotnet/fsharp#10516] opened 2020-11-20 18:25 UTC
This issue is related to the newest feature of F# 5.0, which now enables for a class to implement the same generic interface with multiple parameters. In normal circumstances F# type inference works for cases like eg:

```fsharp
// this works correctly
type A() =
    member this.Foo() = printfn "foo"

[<Interface>]
type IA = abstract Value: A

type B() =
    member this.Bar() = printfn "bar"

[<Interface>]
type IB = abstract Value: B
    
let foo (env: #IA) = env.Value.Foo()
let bar (env: #IB) = env.Value.Bar()
    
// env type is inferred to be 'a  :> IA and 'a :> IB
let run env =
    foo env
    bar env
```

Now, interfaces `IA` and `IB` have very similar structure and could be unified under a single generic interface `I<'T>`, however trying to convert that code yields following error:

```fsharp
[<Interface>]
type I<'T> = abstract Value: 'T

type A() =
    member this.Foo() = printfn "foo"

type B() =
    member this.Bar() = printfn "bar"
    
let foo (env: #I<A>) = env.Value.Foo()
let bar (env: #I<B>) = env.Value.Bar()
    
let run env =
    foo env
    bar env // error: The type 'B' does not match the type 'A'
```

Specifying generic constraints manually also fails:

```fsharp
let run (env: 'e when 'e :> I<A> and 'e :> I<B>) = // error: Type constraint mismatch. The type ''e' is not compatible with 'I<B>'
    foo env
    bar env // same error: The type 'B' does not match the type 'A'
```

Provide any related information (optional):

* Operating system: Windows 10, but I expect it to behave the same way everywhere
* .NET Runtime kind: .NET 5.0, F# 5.0
* Editing Tools: anything where FCS runs on

**Comment by cartermp** [comment] 2020-11-20 18:27
Closing as duplicate of https://github.com/dotnet/fsharp/issues/10432

**Closed by cartermp** 2020-11-20 18:27 UTC

**Comment by dsyme** [comment] 2020-12-03 21:19
See comment here: https://github.com/dotnet/fsharp/issues/10432
