### ISSUE TITLE
Improve error message for let! in invalid location (e.g. r.h.s. of ``let``) 

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#3252] opened 2017-06-24 09:00 UTC
This code doesn't compile:

    let f() = async { return 1 }
    let a = async {
        let x = 
            match 1 with
            | 1 -> 
                let! x = f()
                x
            | _ ->  1
        return x
    }

![image](https://user-images.githubusercontent.com/57396/27507255-a256090a-58cb-11e7-8814-68a2e3331f65.png)

The message is misleading since I'm inside an async workflow. So we should either change the message or ideally find a way to allow it.

Note: If I remove the let binding of x then it works:

    let f() = async { return 1 }
    let a = async {
        match 1 with
        | 1 -> 
            let! x = f()
            return x
        | _ -> return 1
    }

the following code also works but is a bit meh:

    let f() = async { return 1 }
    let a = async {
        let! x =
            match 1 with
            | 1 -> f()
            | _ -> async { return 1 }

        return x
    }

**Comment by realvictorprm** [comment] 2017-06-24 09:04
I think this is a bug, however I'm still looking into language specs.

**Comment by matthid** [comment] 2017-06-24 09:04
I thought about making a language suggestion about this, because this is in fact frustrating from time to time.
But it looks quite hard to do, because even if we implicitly add the `async` scope to the match your code wouldn't compile, because at the very least you need to use `let! x =` instead of `let x =`
and within the match you probably would need to use `return` in both match cases which is both a bit unexpected.

I guess we need to go with improving the error-message for now :/

**Comment by realvictorprm** [comment] 2017-06-24 09:06
I agree on @matthid's idea. I'm not yet that into the compiler so any ideas where we can add this check?

**Comment by matthid** [comment] 2017-06-24 09:07
@realvictorprm I'm pretty sure it's according to the spec, it was like this forever. You explicitly need to mark computation expressions, they don't get inherited by regular bindings...

```fsharp
let f() = async { return 1 }
let a = async {
    let! x = async {
        match 1 with
        | 1 -> 
            let! x = f()
            return x
        | _ ->  return 1 }
    return x
}
```

is the only way.

**Comment by realvictorprm** [comment] 2017-06-24 09:12
Ah no you are right @matthid. I'm sorry so tiny little details here. Should we really consider to get this working?

**Comment by matthid** [comment] 2017-06-24 09:18
To be honest I tried to write a spec/suggestion to do it implicitly (ie make @forki's code "just work" / leave out the inner async block) but I couldn't find a syntax I was happy with. I guess that's the reason we don't have it. Also there are so much emerging problems (for example that you still need to use `return` and how would the compiler do this in a backwards compat way?). That I just got over this "limitation" / ugliness.

**Comment by realvictorprm** [comment] 2017-06-24 09:21
@matthid We would need to keep information about whether the current code is in an async block. 

On the other hand, honestly isn't the example code an example for bad async code?

**Comment by realvictorprm** [comment] 2017-06-24 09:37
@forki Would it help to change it to "This construct may only be used within computation expressions. _Global computation expressions don't apply to inner bindings._"

**Comment by forki** [comment] 2017-06-24 09:42
If we can't make it compile then the error message should point me in the right direction to resolve it. This is not very easy here, but I just wanted to raise it since the workarounds end in really annoying code.

**Comment by realvictorprm** [comment] 2017-06-24 09:44
@forki so far I saw (through debugging) we need to add further properties or checks which point out whether the current function lies inside of an async block. 

If we want this to work we need to think about which further changes need to be applied and then extend the specification + compiler

**Comment by dsyme** [comment] 2017-06-26 12:49
> If we can't make it compile then the error message should point me in the right direction to resolve it. This is not very easy here, but I just wanted to raise it since the workarounds end in really annoying code.

@forki Yes, @matthid is correct that [this](https://github.com/Microsoft/visualfsharp/issues/3252#issuecomment-310826738) is the way to code this.

Could you adjust this to be an error message feature request? 

thanks
don

**Comment by cartermp** [comment] 2017-06-26 16:00
This would be fantastic as an error message improvement.

**Comment by kerams** [comment] 2023-06-28 06:12
Duplicate of https://github.com/dotnet/fsharp/issues/2739

**Closed** 2024-01-04 22:54 UTC
Labels: Feature Improvement, Theme-Simple-F#, Area-Diagnostics
