### ISSUE TITLE
Hmm?

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#8649] opened 2020-03-02 18:19 UTC
![image](https://user-images.githubusercontent.com/19922066/75704990-5de12300-5cf5-11ea-9031-9d3c82fd1fd3.png)

**Comment by cartermp** [comment] 2020-03-02 19:11
Do you have any additional information to share aside from a screenshot?

**Comment by voronoipotato** [comment] 2020-03-02 20:08
Interestingly it looks like a couple visual issues may be happening here. I noticed the filename is missing, and the highlighting is _strange_.  @Happypig375 as a wild shot in the dark, did you use unicode characters in the filename?

**Comment by Happypig375** [comment] 2020-03-03 06:14
After reopening the file, the strange behavior is gone. Not sure if anything can be done about this.

**Comment by Happypig375** [comment] 2020-03-03 06:15
@voronoipotato Nope

**Comment by abelbraaksma** [comment] 2020-03-03 10:06
Such coloring issues happen from time to time. It used to happen quite often in VS with search, but that big has been fixed a while ago.

I had something similar two days ago. Where multiple selections seemed to co-exist. And later, typing wasn't possible (but clicking, it pasting with mouse was, but short-cuts, not even Ctrl-S worked). 

The problem with such issues is always the same: very hard to repro. I think that it can be caused by not enough memory. A typical F# session for me ends quickly with VS using 2.8GB and issues like these tend to happen when the internal limits of the x86 process of devenv.exe are reached. 

It happens less often nowadays, much has improved in VS 2019 (though mem usage is still an issue). With it, those weird 'text select' issues happen less frequently too.

**Comment by cartermp** [comment] 2020-03-03 18:26
Without any info it's hard to say what this is, but here's a rough timeline + dump of info that is related:

* The F# compiler maintains a `range` structure that is filled when tokens are parsed, and this structure corresponds to how "big" that token is
* This `range` structure is fed through all tooling at nearly all levels, notably classification (which is what gives colors in an editor)
* Historically, the size of `range` was kept small because there was a fear that making it larger would dramatically impact performance, since `range` is so ubiquitous
* This small size wasn't a problem until the F# userbase got larger and larger, which also meant a greater variety of source code - longer identifiers, string literals, files, etc.
* This led to issues like you see above, where classification was just "off"
* We carefully increased the size of `range` in the middle of the VS 2017 timeframe (#4476), without impacting overall performance much, to the point where it would take comically massive file sizes and identifier sizes to result in a misclassification

Given that in the above image, the name of the file is missing from the tab, I don't think this is an issue with the F# tooling. My guess is that something in the core VS editor was corrupted as some kind of fluke, resulting in a missing name in the tab and classification that's going bonkers.

**Comment by cartermp** [comment] 2020-08-31 22:29
Closing as no repro

**Closed by cartermp** 2020-08-31 22:29 UTC
Labels: needs repro
