### ISSUE TITLE
Code lens broken in dev17 

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#12151] opened 2021-09-15 13:11 UTC
Sometimes, (type) code lens are either offset or duplicated in the dev17 (31714.462.main), for example:
<hr/>

![image](https://user-images.githubusercontent.com/1260985/133439372-f30c7d59-7cfe-44ee-94bb-27af065e01ef.png)
<hr/>

![image](https://user-images.githubusercontent.com/1260985/133453042-71336aa4-5589-40f4-83e7-961959ca42ab.png)

I didn't find a stable repro yet, it sometimes just breaks (I guess, related when the file is re-typechecked).

It does not apply to the whole file, some lens can be broken, some can look just fine:
<hr/>

![image](https://user-images.githubusercontent.com/1260985/133439928-19842317-71e8-4fc7-9589-c17f4c623c0e.png)
<hr/>

**Comment by cartermp** [comment] 2021-09-15 16:11
See here for more info https://github.com/dotnet/fsharp/issues/6964#issuecomment-711419671

**Comment by cartermp** [comment] 2021-09-15 16:12
I did a spike / have a branch that simplifies the code a lot and isolates the issue. It's a quirk with the rendering/presentation layer. I couldn't figure out how to improve that stuff though.

**Comment by dsyme** [comment] 2021-09-16 13:22
@vzarytovskii I'll close as duplicate of #6964

**Closed by dsyme** 2021-09-16 13:22 UTC
