### ISSUE TITLE
TailCall incorrectly flags some tail recursive functions

### ISSUE THREAD

**Issue by travis-leith** [dotnet/fsharp#16477] opened 2024-01-01 17:37 UTC
Please provide a succinct description of the issue.

**Repro steps**

create a project with the following code
```f#
[<TailCall>]
let rec f () =
    printfn ""
    if true then
        f()
    else
        ()
```

then call `dotnet build`

**Expected behavior**

No compiler warnings are expected since `f` is tail recursive.

**Actual behavior**

A compiler warning is generated claiming "The member or function 'f' has the 'TailCallAttribute' attribute, but is not being used in a tail recursive way."

**Known workarounds**

Negatng the `if` condition removes the warning

```f#
[<TailCall>]
let rec f () =
    printfn ""
    if not true then
        ()
    else
        f()
```

**Related information**

* Windows 10
* .NET 8

**Comment by dawedawe** [comment] 2024-01-01 19:50
Thanks @travis-leith for raising this issue.
I can't reproduce this in a Release build, only in Debug.
I'll take a look.

**Comment by dawedawe** [comment] 2024-01-02 09:48
Using a locally build compiler, I can't reproduce this anymore with a Debug build.
So it seems to be already fixed.

**Comment by psfinaki** [comment] 2024-01-03 13:25
@travis-leith can you share the VS or FSC version you are using?

**Comment by vzarytovskii** [comment] 2024-01-03 16:09
I doubt it was released to either VS or FCS package yet.

**Comment by psfinaki** [comment] 2024-01-03 16:23
This reproduces in VS GA (17.8.3) but does not in Preview (17.9.0 Preview 2.0) so very likely to have been fixed in the meantime.

**Comment by 0101** [comment] 2024-01-08 18:05
Seems it's been fixed. If not we can reopen this.

**Closed by 0101** 2024-01-08 18:05 UTC
Labels: Bug, Needs-Triage
