### ISSUE TITLE
The enum<> constraint allows constraining by impossible enums, like enum<string>, enum<File>

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9778] opened 2020-07-24 22:28 UTC
The little-used `enum` constraint requires a specific type, which logically should be any of the integers. However, you can use any type, which leads to impossible code:

![image](https://user-images.githubusercontent.com/16015770/88440484-576f5700-ce0e-11ea-9941-f2d1229e8747.png)

**Repro steps**

Simple repro with `string`, but you can use any type, really:

```f#
type Foo<'T when 'T: enum<string>>(x: 'T) =   // expected: error here
    member _.Z = x

module Bar =
    let z = Foo(System.MidpointRounding.ToEven)  // 2x FS0001
```

**Expected behavior**

Error on constraint.

**Actual behavior**

Error on using the type, twice:

> Program.fs(43,21): error FS0001: The type 'string' does not match the type 'int32'
> Program.fs(43,17): error FS0001: The type 'string' does not match the type 'int32'

**Known workarounds**

Don't do this ;).

Related: #9777 (I propose to fix as suggested there, or flat out forbid a non-CLi-enum-underlying type here)

**Comment by dsyme** [comment] 2020-08-24 17:42
Yes, don't do this :-)

This is actually by design in a strange way.  When you write `'T: enum<int>` it's saying "T is an enum with underlying type `int`".  

So when you write `T: enum<string>` you're saying "T is an enum with underlying type `string`".   That is impossible to satisfy for any T, but it's perfectly possible to write cosntraints that can't be satisfied.

Note this constraint really only exists to support EnumOfValue and EnumToValue to get from integers to enums and back again.  I've never seen it used anywhere else.

**Comment by abelbraaksma** [comment] 2020-08-24 17:44
> I've never seen it used anywhere else.

Me neither, though recently C# introduced this constrained as well, which, given some of the feedback, may lead to it being applied more. It's actually why I tried this in the first place ;).

**Comment by dsyme** [comment] 2020-08-24 17:49
Right, if I've read correctly their constraint is just `System.Enum` (which can already be used as a trait in F#) and doesn't provide the relationship with the underlying type.

https://devblogs.microsoft.com/premier-developer/dissecting-new-generics-constraints-in-c-7-3/

Anyway I'll close this as by-design, though it certainly is a curiosity :-) 

(Note that if we did fix this, then generic code like `EnumOfValue<A,B>` would actually need _another_ constraint on B to say "and B is a valid enum underlying type")

**Closed by dsyme** 2020-08-24 17:49 UTC
Labels: Area-Compiler, bug

**Comment by abelbraaksma** [comment] 2020-08-24 18:14
> Note that if we did fix this, then generic code like EnumOfValue<A,B> when A: enum<B> would actually need another constraint on B to say "oh and B is a valid enum underlying type"

Good point. Though, we could of course infer that `'T` inside `enum<'T>` is itself already `where 'T: unmanaged`.

I'll settle with this being a curiosity. I've actually been thinking about a more general rule for unresolvable constraints: raise a warning when we can statically assess that's the case. This is not the only _curiosity_ out there ;).
