### ISSUE TITLE
Single-case union type with indexed property fails to pretty-print in FSI

### ISSUE THREAD

**Issue by nicklecompte** [dotnet/fsharp#5713] opened 2018-09-30 22:30 UTC
#### Repro steps

1. Open FSI and a blank .fsx in e.g. VS Code, and send the following to FSI:

```
type Vector1< 'T> =
| Vector1 of 'T array
with
    member v.Values = match v with Vector1 v' -> v'

    member v.Item with get(i:int) = v.Values.[i]

type Vector2< 'T> = {
    vector2Item : 'T array
}
with
    member v.Item with get(i:int) = v.vector2Item.[i]

type Vector3< 'T> =
| Vector3 of 'T array
```

2. Send these to FSI one at a time:
```
Vector1([|1;2;3|])

{vector2Item=[|1;2;3|]}

Vector3([|1;2;3|])

```
#### Expected behavior

FSI prints
```

> 
val it : Vector1<int> = Vector1 [|1; 2; 3|]
> 
val it : Vector2<int> = {vector2Item = [|1; 2; 3|];}
>
val it: Vector3<int> = Vector3 [|1; 2; 3|]
```

#### Actual behavior

Vector1 fails to pretty-print:

```
Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.FSharp.Reflection.Impl.getUnionCaseRecordReader@294.Invoke(Object obj)
   at Microsoft.FSharp.Reflection.FSharpValue.GetUnionFields(Object value, Type unionType, FSharpOption`1 bindingFlags)
   at Internal.Utilities.StructuredFormat.ReflectUtils.Value.GetValueInfoOfObject$cont@434(BindingFlags bindingFlags, Object obj, Type reprty, Unit unitVar)
   at Internal.Utilities.StructuredFormat.Display.polyL[a](BindingFlags bindingFlags, FSharpFunc`2 objL, ShowMode showMode, Int32 i, Precedence prec, a x, Type typ)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiValuePrinter.PrintValue(FsiValuePrinterMode printMode, FormatOptions opts, Object x, Type ty)
val it : Vector1<int> = 

> 
val it : Vector2<int> = {vector2Item = [|1; 2; 3|];}

> 
val it : Vector3<int> = Vector3 [|1; 2; 3|]

````

#### Known workarounds

None yet, if I want to use x.[index] notation. This works, but is inconvenient:

````
type Vector4< 'T> =
| Vector4 of 'T array
with
    member v.GetByIndex (ind: int) = match v with | Vector4 v' -> v'.[ind]

Vector4 [|1;2;3|];;
val it : Vector4<int> = Vector4 [|1; 2; 3|]
````

#### Related information 

Originally I found this bug using a statically-resolved generic type with static member constraints and with a setter as well as a getter. But using vanilla unconstrained generics & getter-only properties still has this issue.

* Windows 10
* F# Interactive version 10.2.3 for F# 4.5
* FSharp.Core-4.4.3.0
* .NET Framework 4.7
* VS2017, also seen in VSCode with Ionide
* Presumably minor severity since the resulting types work fine, including the .[x] notation

**Comment by cartermp** [comment] 2018-10-02 17:12
Just as a note for posterity, it does work for non-single-case unions.

**Comment by dsyme** [comment] 2022-04-01 04:22
Duplicate of https://github.com/dotnet/fsharp/issues/9399

**Closed by dsyme** 2022-04-01 04:22 UTC
Labels: Bug, Area-Compiler, Impact-Medium
