### ISSUE TITLE
dotnet fsi throwing PNSE if run from NanoServer

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#10097] opened 2020-09-10 08:36 UTC
**Repro steps**

After switching to windows containers in docker for windows:

```
>  docker run -it mcr.microsoft.com/dotnet/sdk:5.0.100-preview.8-nanoserver-1909 pwsh

... docker output ...

PS C:\> dotnet fsi
Unhandled exception. System.PlatformNotSupportedException: The system does not support the STA thread apartment.
PS C:\>
```

**Comment by cartermp** [comment] 2020-09-14 18:32
Closing as a duplicate of https://github.com/dotnet/fsharp/issues/10097

**Comment by cartermp** [comment] 2020-09-14 18:33
oops - https://github.com/dotnet/fsharp/issues/7813

**Comment by KevinRansom** [comment] 2020-09-14 20:27
dotnet fsi is a new scenario for runing fsi.  And so I am going to not set the STAThreadAttribute on the coreclr version of the compiler.  If developers have scripts that run on Windows and require STAThread, then they will be able to use the desktop version of fsi.exe

**Closed** 2020-09-15 04:51 UTC
Labels: Area-FSI, Resolution-Duplicate, Severity-Medium, bug
