### ISSUE TITLE
FSC : error FS0078: Unable to find the file 'netstandard.dll'

### ISSUE THREAD

**Issue by kant2002** [dotnet/fsharp#10009] opened 2020-08-26 04:00 UTC
When attempt to build Infer.Net on .NET 5.0 RC1 master (5.0.100-rc.1.20425.5) build produce strange error
```
FSC : error FS0078: Unable to find the file 'netstandard.dll' in any of
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades
 c:\GitHub\dotnet\infer\test\TestFSharp
 C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\FSharp\
```

At the same time compiler pass netstandard.dll as reference. 

The project uses net461 as target framework and reference `<PackageReference Include="FSharp.Core" Version="4.7.2" />` which get's overriden to version `5.0.0-beta.20425.4`

**Repro steps**

1. git clone https://github.com/kant2002/infer
2. cd infer
3. git checkout kant/net50
4. dotnet build -c DebugFull

**Expected behavior**

Build should be ok.

**Actual behavior**

compilation fails. 

**Related information**

```
>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20425.5
 Commit:    85c205f9d8
```

In case this would be useful: command line how fsc was invoked
```
C:\Program Files\dotnet\dotnet.exe "C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\FSharp\fsc.exe" -o:obj\DebugFull\net461\TestFSharp.exe
-g
--debug:portable
--noframework
--define:TRACE
--define:NET45
--define:NETFULL
--define:DEBUG
--define:DEBUGFULL
--define:NETFRAMEWORK
--define:NET461
--keyfile:c:\GitHub\dotnet\infer\build\\..\Infer.snk
--optimize+
--platform:anycpu
-r:c:\nuget\packages\fsharp.core\5.0.0-beta.20425.4\lib\netstandard2.0\FSharp.Core.dll
-r:c:\nuget\nuget\packages\microsoft.codeanalysis.csharp\2.10.0\lib\netstandard1.3\Microsoft.CodeAnalysis.CSharp.dll
-r:c:\nuget\nuget\packages\microsoft.codeanalysis.common\2.10.0\lib\netstandard1.3\Microsoft.CodeAnalysis.dll
-r:c:\GitHub\dotnet\infer\src\Compiler\bin\Debug\netstandard2.0\Microsoft.ML.Probabilistic.Compiler.dll
-r:c:\GitHub\dotnet\infer\src\Runtime\bin\Debug\netstandard2.0\Microsoft.ML.Probabilistic.dll
-r:c:\GitHub\dotnet\infer\src\FSharpWrapper\bin\Debug\netstandard2.0\Microsoft.ML.Probabilistic.FSharp.dll
-r:c:\nuget\nuget\packages\microsoft.codecoverage\16.6.1\lib\net45\Microsoft.VisualStudio.CodeCoverage.Shim.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\Microsoft.Win32.Primitives.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netfx.force.conflicts.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.AppContext.dll
-r:c:\nuget\nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Collections.Concurrent.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Collections.dll
-r:c:\nuget\nuget\packages\system.collections.immutable\1.5.0\lib\netstandard2.0\System.Collections.Immutable.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Collections.NonGeneric.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Collections.Specialized.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.ComponentModel.Composition.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.ComponentModel.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.ComponentModel.EventBasedAsync.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.ComponentModel.Primitives.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.ComponentModel.TypeConverter.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Console.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Data.Common.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.Contracts.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.Debug.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.FileVersionInfo.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.Process.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.StackTrace.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.TextWriterTraceListener.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.Tools.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.TraceSource.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Diagnostics.Tracing.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Drawing.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Drawing.Primitives.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Dynamic.Runtime.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Globalization.Calendars.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Globalization.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Globalization.Extensions.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.Compression.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.IO.Compression.FileSystem.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.Compression.ZipFile.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.FileSystem.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.FileSystem.DriveInfo.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.FileSystem.Primitives.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.FileSystem.Watcher.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.IsolatedStorage.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.MemoryMappedFiles.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.Pipes.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.IO.UnmanagedMemoryStream.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Linq.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Linq.Expressions.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Linq.Parallel.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Linq.Queryable.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Http.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.NameResolution.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.NetworkInformation.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Ping.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Primitives.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Requests.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Security.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.Sockets.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.WebHeaderCollection.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.WebSockets.Client.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Net.WebSockets.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Numerics.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.ObjectModel.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Reflection.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Reflection.Extensions.dll
-r:c:\nuget\nuget\packages\system.reflection.metadata\1.6.0\lib\netstandard2.0\System.Reflection.Metadata.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Reflection.Primitives.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Resources.Reader.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Resources.ResourceManager.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Resources.Writer.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.CompilerServices.VisualC.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.Extensions.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.Handles.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.InteropServices.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.InteropServices.RuntimeInformation.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.Numerics.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Runtime.Serialization.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.Serialization.Formatters.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.Serialization.Json.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.Serialization.Primitives.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.Serialization.Xml.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Security.Claims.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Security.Cryptography.Algorithms.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Security.Cryptography.Csp.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Security.Cryptography.Encoding.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Security.Cryptography.Primitives.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Security.Cryptography.X509Certificates.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Security.Principal.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Security.SecureString.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Text.Encoding.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Text.Encoding.Extensions.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Text.RegularExpressions.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Threading.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Threading.Overlapped.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Threading.Tasks.dll
-r:c:\nuget\nuget\packages\system.threading.tasks.extensions\4.3.0\lib\portable-net45+win8+wp8+wpa81\System.Threading.Tasks.Extensions.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Threading.Tasks.Parallel.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Threading.Thread.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Threading.ThreadPool.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Threading.Timer.dll
-r:c:\nuget\nuget\packages\system.valuetuple\4.5.0\ref\net461\System.ValueTuple.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.Linq.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.ReaderWriter.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.XDocument.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.XmlDocument.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.XmlSerializer.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.XPath.dll
-r:C:\Program Files\dotnet\sdk\5.0.100-rc.1.20425.5\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Xml.XPath.XDocument.dll
-r:c:\nuget\nuget\packages\xunit.abstractions\2.0.3\lib\net35\xunit.abstractions.dll
-r:c:\nuget\nuget\packages\xunit.assert\2.4.1\lib\netstandard1.1\xunit.assert.dll
-r:c:\nuget\nuget\packages\xunit.extensibility.core\2.4.1\lib\net452\xunit.core.dll
-r:c:\nuget\nuget\packages\xunit.extensibility.execution\2.4.1\lib\net452\xunit.execution.desktop.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.ComponentModel.Annotations.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.Reflection.Emit.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.Reflection.Emit.ILGeneration.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.Reflection.Emit.Lightweight.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.Runtime.InteropServices.WindowsRuntime.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.ServiceModel.Duplex.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.ServiceModel.Http.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.ServiceModel.NetTcp.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.ServiceModel.Primitives.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\System.ServiceModel.Security.dll
--target:exe
--warn:4
--warnaserror
--warnaserror:76
--fullpaths
--flaterrors
--subsystemversion:6.00
--highentropyva+
--targetprofile:mscorlib
--nocopyfsharpcore
--deterministic+
--simpleresolution
obj\DebugFull\net461\.NETFramework,Version=v4.6.1.AssemblyAttributes.fs
obj\DebugFull\net461\TestFSharp.AssemblyInfo.fs
..\..\src\Shared\SharedAssemblyFileVersion.fs
DifficultyAbility.fs
AssemblyInfo.fs
BayesPointMachine.fs
ClinicalTrial.fs
GaussianwithRanges.fs
MixtureofGaussians.fs
TruncatedGaussian.fs
TwoCoins.fs
TestTutorials.fs
```

**Comment by dsyme** [comment] 2020-08-26 10:48
Yes looks like whatever is causing the `netstandard2.0` to be selected is wrong - the net45 version of FSharp.Core should be selected - or else your project requires minimally .NET 4.7.2.

> `-r:c:\nuget\packages\fsharp.core\5.0.0-beta.20425.4\lib\netstandard2.0\FSharp.Core.dll`

BTW any reason not to just switch over to NET Standard and .NET Core completely?  Or at least .NET 4.7.2?

**Comment by kant2002** [comment] 2020-08-26 12:15
I would try to ask main Infer.NET maintainer about net472, I'm only testing on .NET 5.0 previews so I more on the bleeding edge. This one thing looks like tooling issue so I report it. And I have another one separate issue on .NET 5.0 build, which I will post soon.

**Comment by kant2002** [comment] 2020-08-26 13:21
I was able reproduce as simple as 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>fsc_10009</RootNamespace>
        <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

So basically
- `dotnet new console -lang "F#"`
- Set `<TargetFramework>net461</TargetFramework>`

**Comment by cartermp** [comment] 2020-08-26 17:29
Closing this out as by design. NuGet resolution allows NS 2.0 and net461 to "work", but in practice it pretty much never does. You must use `net472` or higher for .NET Framework projects.

The reason why this shows up with .NET 5 SDK is that FSharp.Core is now .NET Standard 2.0 only, rather than also containing a net45 binary.

**Closed by cartermp** 2020-08-26 17:29 UTC
Labels: Resolution-By Design
