### ISSUE TITLE
Can't Use Library From F# (FS1109 System.Drawing)

### ISSUE THREAD

**Issue by EricM81** [dotnet/fsharp#17295] opened 2024-06-08 21:40 UTC
RhinoCommon is transitioning from the .Net Framework to .Net Core.  .Net Core is required for cross platform support.  This works fine in C#, but won't work from F#.

Repro steps (https://github.com/EricM81/RhinoCommonFsBug):

1) Create a .Net Core 7 library in F#.  

2) Add nuget package package: ```<PackageReference Include="RhinoCommon" Version="8.7.24138.15431" />```

3) Inherit the PlugIn class:

```f#
open Rhino.PlugIns
type MyPlugin() as this = 
    inherit PlugIn()
```
3) Compiler complains with "FS1109"

4) Do the same steps in c#.  Compiles with no issues.

* Windows 10
* .NET Core
* Visual Studio; VSCode; Rider

**Comment by kerams** [comment] 2024-06-09 08:48
> RhinoCommon is transitioning from the .Net Framework to .Net Core

You say that, but it still only supports `net48`.

> This works fine in C#

It compiles, but I'm willing to bet that you'll get a run-time exception if you try to do anything. `System.Drawing.Bitmap` appears to live in a different assembly on new versions of .NET.

Compilation error is the more reasonable outcome here in my opinion. If anything, C# is being too liberal in what it compiles. I know that oftentimes an old Framework library will just work, but the following warning is displayed for a reason

```
CsPlugin.csproj : warning NU1701: Package 'RhinoCommon 8.7.24138.15431' was restored using '.NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0'. This package may not be fully compatible with your project.
```

I wouldn't be surprised if the F#'s [team's] policy was to simply consider this an unsupported scenario.

**Comment by EricM81** [comment] 2024-06-10 16:14
> It compiles, but I'm willing to bet that you'll get a run-time exception if you try to do anything. `System.Drawing.Bitmap` appears to live in a different assembly on new versions of .NET.

I get that it looks weird, I don't know how or why they are doing this, but people are using this package to create cross-platform Win/Mac plugins on .Net Core with C#.

https://developer.rhino3d.com/guides/rhinocommon/moving-to-dotnet-7/

**Comment by KevinRansom** [comment] 2024-06-10 17:11
Closing this as "by design".

**Closed by KevinRansom** 2024-06-10 17:11 UTC
Labels: Bug, Resolution-By Design, Needs-Triage
