### ISSUE TITLE
Provide alternative QueueUserWorkItem for Async module

### ISSUE THREAD

**Issue by somdoron** [dotnet/fsharp#7890] opened 2019-11-21 08:04 UTC
**Is your feature request related to a problem? Please describe.**
I'm using the Async module with epoll/select at the base of the executing thread.
So for async operations, like file descriptor the async will look like this:
```
let readAsync = 
  async {
    match FD.tryRead fd with 
    | Some r -> return r
    | None ->
        do! Poll.Current.Once PollEvent.In fd
        return FD.read fd
  }
```

`Poll.Current` is a thread-local variable set by the Poll class when running an async computation.
Poll class also inherit from SynchronizationContext and set SynchronizationContext.Current to make sure continuations are happening on the Poll thread.

the Poll.Run function:
```
member this.Run<'T> (computation:async<'T) =         
        Poll.Current = this

        let prevCtx = SynchronizationContext.Current
        SynchronizationContext.SetSynchronizationContext this
        
        let mutable result = Ok <| Unchecked.defaultof<'T>                                                                                  
        Async.StartWithContinuations (computation,
                                      (fun res -> result <| Ok res),
                                      (fun exc -> result <| Error exc),
                                      (fun exc -> result <| Error exc))
        this.Wait ()

        SynchronizationContext.SetSynchronizationContext prevCtx

        match result with 
        | Ok result -> result
        | Error exc -> raise exc
```

The problem is that Parallel, Choice, and Sequential are not using the SynchronizationContext for posting the new computations, but the ThreadPool, which doesn't have a poll at the base. Calls to FD.readAsync will fail because Poll is not set on the Current thread.

Overriding or providing an alternate implementation won't work with third-party libraries.
For example, Suave is using Async.Parallel, so every async request computation will start on a thread-pool thread without a Poll.

**Describe the solution you'd like**
To provide the ThreadPool.QueueUserWorkItem function, the same way I can provide the SynchronizationContext.
So `Async.setCurrentQueueUserWorkItem` will set the function for the current thread.

**Describe alternatives you've considered**
Call `Async.SwitchToContext` at the beginning of an async computation.

**Additional context**
This will make it easier to work with none-dotnet libraries, like zeromq, which requires its own event loop. Also libevent and libuv.

**Comment by FraserWaters-GR** [comment] 2019-11-22 13:19
Shouldn't QueueAsync (https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Core/async.fs#L822) use `PostOrQueueWithTrampoline SynchronizationContext.Current` rather than just `QueueWorkItemWithTrampoline`

**Comment by cartermp** [comment] 2019-11-23 17:46
@dsyme thoughts?

**Comment by somdoron** [comment] 2019-11-24 09:31
@FraserWaters-GR I'm not sure, I think SynchronizationContext lacks the semantic between continuing on the SynchronizationContext and start on a new thread, if available.

**Comment by Frassle** [comment] 2019-11-24 19:47
The whole point of SynchronizationContext is to queue work to happen in that SynchronizationContext. It's up to the SynchronizationContext whether that means a new thread or not. 
This would just change that instead of always calling `ThreadPool.QueueUserWorkItem` it would call `SynchronizationContext.Post` if the current thread had a SynchronizationContext.

**Comment by Frassle** [comment] 2019-11-25 08:06
Thinking about this more this is kinda the same problem that ConfigureAwait on Task solves. Tasks by default flow SynchronisationContext, and you have to ConfigureAwait(false) to switch to the thread pool. While Asyncs always continue on the thread pool and you have to SwitchToContext just before the synchronus code that needs the context.

Changing this would probably break things (because code that currently runs in the thread pool could now get scheduled on the ui thread) but the current model does make SwitchToContext really hard to use because there's no way to "stay" in that context. Also while we have SwitchToThreadPool which is similar to ConfigureAwait(false) it incurs one extra work task queued as its an async itself not a modifier for another async.

**Comment by somdoron** [comment] 2019-11-25 08:58
Actually, in most of the cases Async actually continues on synchronization context, like Task.
I think only Parallel and Choice introduce the thread pool.

I do think it makes sense for Parallel to start on a new thread, as the name implied, however, I want to be able to control the thread. 

It is also a waste of time to switch to the thread pool and then switching back to a synchronization context.

**Comment by dsyme** [comment] 2019-11-25 11:43
There is a strong argument that `Parallel`, `Choice`, `Start` and `Sequential` should all have had `InThreadPool` as a naming suffix to make it abundantly clear what's going on.

`Async.ParallelInThreadPool`
`Async.StartInThreadPool`

etc.  

My gut feeling has always been that it is multiplying the permutations a bit too much to allow another start-this-computation hook beyond `SynchronizationContext`. But it's definitely worth discussing as there are certainly use-cases for it.

My impression is you are suggesting the hook be a thread local like `SynchronizationContext`?

**Comment by somdoron** [comment] 2019-11-25 12:03
> My impression is you are suggesting the hook be a thread local like SynchronizationContext?

Yes. `Async.setCurrentQueueUserWorkItem` will set a thread-local variable.

Using SynchronizationContext (instead of thread pool) for this can also do the trick, my only comment is that SynchronizationContext lacks the semantic of a new thread (continuation and new thread are the same).

I think the available solutions are:
1. New hook, `Async.setCurrentQueueUserWorkItem` to override the thread pool (my favorite).
2. Current versions of `Parallel`, `Choice` and `Sequential` should use SynchronizationContext, maybe adding `InThreadPool` versions.
3. Adding an optional parameter `useThreadPool` to `Parallel`, `Choice` and `Sequential` ( SynchronizationContext will be the default).

**Comment by FraserWaters-GR** [comment] 2019-11-26 09:19
Why not use SyncContext in some way, that is the .net framework way of specifying this. Could just add an optional arg to Parallel et al of `SynchronisationContext option`, which uses Current or ThreadPool if None. Choice there based on if wanting to maintain current behavior by default and `Parallel(work, null)` looking really odd for F# code.

**Comment by somdoron** [comment] 2019-11-26 09:28
As long as `SynchronisationContext.Current` is the default behavior (if not null) that will work as well.
I would use the `useThreadPool` parameter over `SynchronisationContext option`. Because, if we change the default behavior to `SynchronisationContext.Current` there would not be a way to force to the thread pool. So the idea of `useThreadPool` parameter is to force to use the thread pool.

We can also make it a choice of Current (default), ThreadPool or SyncContext of SyncContext.

**Comment by FraserWaters-GR** [comment] 2019-11-26 10:46
You force the thread pool by passing null for the SynchronisationContext. Threads in the thread pool will have SynchronisationContext.Current as null.

**Comment by somdoron** [comment] 2019-11-26 10:53
But what if the thread has a synchronization context and still want to use
the thread pool?

**Comment by FraserWaters-GR** [comment] 2019-11-26 13:33
Then you pass null (or `new SynchronizationContext()`), it's convention that a null SynchronizationContext means the default thread pool SynchronizationContext. That's why I said it may be nicer to keep the current behavior that None is the thread pool, so that you don't have to call it as `Parallel(work, null)` to get on the thread pool. If it is implemented like this and you want to stay on the current sync context it would be `Parallel(work, SynchronizationContext.Current)`.

I think you could easily argue for either option. None meaning thread pool maintains back compat, and means no need to pass null explicitly (which is really odd in F# code). While None meaning current is probably what people expect and it's shorter to opt in the common alternative ("null" is shorter than "SynchronizationContext.Current").

**Comment by somdoron** [comment] 2019-11-26 14:52
I think the default behavior must be synchronization context and not thread
pool, if not you will have no way to affect third party libraries. For
example suave use parallel, if I want to set a synchronization context I
have no option if thread pool is the default. Further, c# task use
synchronization context by default and also all of the async continuations,
exceot the new parallel, sequenctial and choice.

Actually adding a new parameter and keep the thread pool as default doesn't
solve the problem at all, as it equal to custom implementation. I dont have
an option to force third-party code to use my synchronization context or
custom thread pool.

**Comment by FraserWaters-GR** [comment] 2019-11-26 15:03
Ah yeh that's a good point. So the choices are:

- Add a new parameter where None == SyncContext.Current and to get to thread pool you pass `null` or `new SynchronizationContext()`
- Variant of that where the optional parameter is a DU of `ThreadPool | SynchronizationContext of SynchronizationContext` so you'd call it like `Parallel(work, ThreadPool)` or `Parallel(work, SynchronizationContext syncCtx)` and where None would be SynchronizationContext.Current.
- Use a new AsyncLocal (not thread local because that won't follow the async execution context) like SynchronizationContext.Current which Parallel, Choice etc look at to decide if they use a SyncContext or ThreadPool (I don't much like this, its another global state to understand async execution and it's so so close to what SynchronizationContext.Current is)

**Comment by somdoron** [comment] 2019-11-28 07:29
We can also go with @dsyme suggestion, add another variation of `Parallel`, `Choice` and `Sequential` with  `InThreadPool` and change the existing to use SynchronizationContext. Anyway, as long as the default is SynchronizationContext or a new thread pool hook it will solve my problem.

**Comment by somdoron** [comment] 2019-11-29 13:59
After reviewing parallel function I think defaulting to the synchronization context will break the maxDegreeOfParallelism parameter if the synchronization content is a single thread the maxDegreeOfParallelism will have no effect.

So I think the ability to have a custom thread pool function is the best option for the parallel and choice functions.

**Comment by Frassle** [comment] 2019-11-29 17:54
maxDegreeOfParallelism is a maximum, not an exact amount. If you use a sync context that supports less parallelism that's not a bug.

**Comment by somdoron** [comment] 2019-11-30 10:43
Make sense. I created #7915, let me know what you think.

**Comment by Frassle** [comment] 2020-05-28 08:46
I was thinking about this last night and thought of a new variant that is backwards compat, `Parallel(work : Async<'T> seq, useCurrentSynchronizationContext : bool option)`.

The second parameter would default to false (i.e. use the null SynchronizationContext, which is the thread pool) but if needed you could pass the second parameter as true to submit to the current ExecutionContext's SynchronizationContext. If you want to submit to a different SynchronizationContext you can just `do! Async.SwitchToSynchronizationContext x` before the Parallel call.

I don't think this is as tidy as my DU variant above (`Parallel(work, ThreadPool)` or `Parallel(work, SynchronizationContext syncCtx)`) but it's another option to consider.

Could also extend the DU variant to be:
```
| TheadPool
| SynchronizationContext of SynchronizationContext 
| CurrentSynchronizationContext 
```

Makes it easier to call as `Parallel(work, CurrentSynchronizationContext)` rather than `Parallel(work, SynchronizationContext SynchronizationContext.Current)`

**Comment by somdoron** [comment] 2020-06-28 07:01
I understand that breaking existing behavior is a big thing, but I think the existing behavior breaks the API of Async (and C# Task).
Async in all most all API methods relay on SynchronizationContext. The behavior should be, that unless you specify otherwise all async continuations must happen on the SynchronizationContext.

For [FsNetMQ](https://github.com/NetMQ/FsNetMQ/blob/master/src/FsNetMQ/Async.fs) I had to add explicit methods (e.g ParallelInContext) to solve the issue, otherwise, it would break the library (which relay on event-loop SynchronizationContext). If the library would gain more usage I would imagine a lot of issues regarding losing the SynchronizationContext.

Anyway, I think it worth fixing the existing behavior. I'm less concerned about the exact API but on changing the current (default) behavior.

cc @cartermp @Frassle

**Comment by Frassle** [comment] 2020-06-28 12:06
> Async in all most all API methods relay on SynchronizationContext

I think whats extra confusing about F# Async is that continuations and child computations do respect the SynchronizationContext but forking with Parallel/Choice doesn't and always goes to thread pool. C# Tasks are more consistent in that everything will use the current SynchronizationContext, having said that they have had a big thing about `ConfigureAwait(false)` being need on so many Task calls because it did want the thread pool not the sync context.

I think the upside is forgetting a `ConfigureAwait(false)` is its often just a performance issue, not a correctness issue. As opposed to what it sounds like @somdoron is hitting where leaving the sync context causes correctness bugs.

> Anyway, I think it worth fixing the existing behavior

I'm really torn on this because implicitly using the SyncContext is what I would of expected and would match Task, and its really easy to get on the thread pool if needed (just a `do! Async.SwitchToThreadPool()`) but yeh this will probably cause a lot of pain for current code as people work out what's changed (no one reads all the release notes!). You also don't need a new overloads for Parallel etc you can just make use of `Async.SwitchToThreadPool` and `Async.SwitchToContext` before the call to Parallel/Choice.

If you had to keep back compatibility could maybe mark the current ones obsolete to get people consciously choose if they want the thread pool or sync context. Probably don't want the new methods to have an optional second parameter in that case so probably want something like my DU idea:
```
[<RequireQualifiedAccess>]
AsyncContext = | Current | ThreadPool | SynchronizationContext of SynchronizationContext

Parallel(computations : Async<'T> array, context : AsyncContext) : Async<'T array>

// Called like
Async.Parallel(work, AsyncContext.Current)
````

**Comment by baronfel** [comment] 2020-08-10 14:31
Does the syncronization context have an impact on how AsyncLocal values are propagated? I ask because I believe I have run into this over the past week while integrating Serilog into an application.

Serilog uses an AsyncLocal to store a set of 'tags' that will be added to a log message when a log message is written.  My use case in particular is to propagate a set of identifying tokens to all messages logged in a given http request for tracing purposes.  My http handlers (in giraffe) interop back and forth between the task CE (Taskbuilder.fs) and asyncs, and what I'ce found is that some transitions between async and task do not seem to propagate this AsyncLocal context in the way I expect (ie at all), resulting in logs written from those flows not having the tags I specified.

Changing those code paths in particular to use `task` end-to-end usually results in the tags becoming available once more, which seems to correlate with my suspicion.

**Comment by NinoFloris** [comment] 2020-08-10 16:31
The execution context is responsible for flowing the async locals, and it is normally flowed itself by `Task.Run`, `Awaiter.OnCompleted`, `Task.ContinueWith`, `ThreadPool.QueueUserWorkItem` and others. 

Looking at Async it does not seem to use any Unsafe variants of those apis, which *would* require manual managament.
However it does use `TaskCompletionSource` to implement `StartAsTask` and it requires manual management as well. 
This is likely where the bug is, it would go something like this:

- Created Async and StartAsTask
- Await StartAsTask result, when completed it calls tcs.SetResult/Ex/Cancel. usually this would then continue inline on the same thread (`TaskCreationOptions.RunContinuationsAsynchronously` would prevent that). 

However there are a few possibilities here:

- The TPL sometimes chooses to go async anyway [to prevent unbounded stack growth](https://github.com/dotnet/runtime/blob/b5705587347d29d79cec830dc22b389e1ad9a9e0/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L3211), this would then switch threads during the SetResult without capturing the context. 
- If the Task is completed before any continuations are attached (for instance it's stored on a field before it gets awaited) it cannot run any continuations inline and cannot pass on the context either.

There are also a few bugs in TaskBuilder.fs around execution context capture and restore where it too uses TaskCompletionSource. And there's a related issue where it fails to restore the execution context to what it was before the TaskBuilder ran your initial sync code; it executes the 'firstStep' outside the AsyncMethodBuilder execution scope which causes it to leak asynclocals into the parent scope. Like a broken record I say, Ply fixed these cases.

For Async, changing this to instead depend on `AsyncTaskMethodBuilder` would do the trick, otherwise an easier change (though less efficient) would be to do an `ExecutionContext.Capture()` in StartAsTask and an `ExecutionContext.Run(ctx, callback)` in the continuations it passes to QueueAsync.

**Comment by Swoorup** [comment] 2020-11-16 12:34
I have a code that uses custom scheduler, it appears F# async doesn't respect it. What should happen in this case?

The FSharp.Control.Tasks.V2.ContextSensitive from TaskBuilder does however respect it. It seems odd not to have it as default?

let sthAsync () =
  async {
    printfn "From async Scheduler Id: %A" TaskScheduler.Current.Id // prints 1
  } |> Async.StartAsTask

let Scheduler = ConcurrentExclusiveSchedulerPair(TaskScheduler.Default, 1, 1)
printfn "ScheduleId: %A" Scheduler.ExclusiveScheduler.Id // prints 2

Task.Factory.StartNew(sthAsync, CancellationToken.None, TaskCreationOptions.None, Scheduler.ExclusiveScheduler) |> ignore

This limits ability to control concurrency from the top level.

**Comment by dsyme** [comment] 2022-04-21 01:43
I'll close this, we're not planning to add this to F# async beyond SyncContext (and there are various options for F# tasks).

**Closed by dsyme** 2022-04-21 01:43 UTC
Labels: Feature Request
