### ISSUE TITLE
Conflict between nested modules/types

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#8432] opened 2020-01-31 11:35 UTC
(Related: https://github.com/cmeeren/Feliz.MaterialUI/issues/40)

F# fails to access nested modules/types in a consistent manner, based on the level of nesting. Errors happen even for relatively shallow nesting.

```f#
module test =

  type a =
    static member b x = x

  module a =

    type b =
      static member c x = x



// Doesn't compile
let x = test.a.b.c
//               ^ The field, constructor or member 'c' is not defined

// Compiles
open test
let x = a.b.c
```

**Comment by cartermp** [comment] 2020-02-05 15:37
This is related to the weird resolution that F# does around modules and types, seen mostly when using static classes or static members. Unfortunately I'm not sure there's much to be done without incurring a breaking change. It affected a lot of how `open` with static classes work and was a primary reason for pulling the feature into preview. cc @TIHan

**Comment by cartermp** [comment] 2020-07-12 17:38
Closing this as by design. This is just how name resolution works in the face of ambiguities like this. Once the module-bound types and modules are brought into scope it picks one, but with fully qualified access it's ambiguous.

**Closed by cartermp** 2020-07-12 17:38 UTC
Labels: Resolution-By Design

**Comment by NinoFloris** [comment] 2020-07-12 18:18
I have to say 'fully qualified access is ambiguous' reads like an oxymoron

**Comment by NinoFloris** [comment] 2020-07-12 20:51
More constructively, what about bringing the underlying module type name into scope, hidden by default?

That way you could write: `test.aModule.b.c`

**Comment by abelbraaksma** [comment] 2020-07-12 21:04
> I have to say 'fully qualified access is ambiguous' reads like an oxymoron

I'd agree, but then, given this example, we apparently don't have a way for fully qualified access in the face of name collisions of types and modules. 

It would indeed be nice if we'd have a way to write a certain FQN for every type, module, member combination. While we can direct/help/guide type inference in most cases, this is currently not possible with modules.
