### ISSUE TITLE
Missing text-cursor-focus when going to definition in VS2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#10222] opened 2020-10-05 19:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1148347/missing-text-cursor-focus-when-going-to-definition.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
If you go to the definition of a type within an F# file, where the type is defined in another file (doesn't matter if F# or C#), the file is opened as expected and the correct line is shown. But the text-cursor is not showing up. This only happens if tabs are place left or right. No problem if tabs are placed on top.

It seems to be a longstanding issue, since there are a lot of similar bugs reported on developercommunity, but were closed because of "Not enough information".

This issue only happens with F# anymore. It was an issue with C# as well, but was fixed recently. [Andrew Hall 落 [MSFT] asked me kindly] (https://developercommunity.visualstudio.com/comments/1145679/view.html) to open an issue on the F# side.

I filed [the bug on F# repo](https://github.com/dotnet/fsharp/issues/9923), and according to cartermp it's an issue with the (VS-)editor and can't be fixed on their side. But he had a new insight: "The cursor gets stuck in the dropdown lists.". And it seems to be fixed in VS16.8, though would be really nice to get a fix ealier than next year :)

# Repro steps

1. Create a new F# ConsoleApp (doesn't matter if dotnetcore or other framework)
2. Click right on the tab of opened file Program.fs and select "Set Tab Layout -> Place Tabs on the Left"
3. Create a file File1.fs.
4. Create a type MyType() = class end in File1.fs
5. Use MyType in Program.fs (e.g. let x = typeof<File1.MyType>)
6. Right click on File1.MyType and select "Go To Definition"
7. Notice that you can't type or move the text-cursor (though selection still works)
8. A solution with described reproduction steps: ConsoleApp.zip

# Expected behavior

On 7. the text-cursor should be blinking and you should be able to type.

# Actual behavior

On 7. the text-cursor doesn't blink and you can't type.

# Known workarounds

Click into the window with the mouse cursor and the text-cursor re-appears.

# Related information
About Microsoft Visual Studio -> Copy Info (in short: pretty vanilla setup)
```
Microsoft Visual Studio Community 2019
Version 16.7.1
VisualStudio.16.Release/16.7.1+30406.217
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

C# Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   4.7.1.0
Visual Studio Tools for Unity
```

---
#### Feedback Bot on 8/13/2020, 07:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Georgios Tsiros on 9/11/2020, 04:43 AM: 

(private comment, text removed)
#### Georgios Tsiros on 9/15/2020, 06:38 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by JanWosnitza** [comment] 2020-11-24 08:58
Is this a dead-lock now? 😕

**Comment by cartermp** [comment] 2020-11-24 17:52
I don't know why this got all moved around. This isn't an F# tools issue.

Does it still repro for you in VS 16.8.x? I've never seen it reproduce with the released bits.

**Comment by JanWosnitza** [comment] 2020-11-25 09:36
Just updated to 16.8.2. Seems to be fixed now. Awesome 😄 So feel free to close it, @cartermp ! 🎉
(I created the original ticket got fixed first time but still occured for F#. So yeah, I guess ... yay ^^)

**Comment by cartermp** [comment] 2020-11-25 18:03
Good to know, thanks!

**Closed by cartermp** 2020-11-25 18:03 UTC
