### ISSUE TITLE
Error hint in IDE

### ISSUE THREAD

**Issue by GratianPlume** [dotnet/fsharp#14444] opened 2022-12-07 04:21 UTC
the following code:

```
   type AH() =
      member val X = 0 with get,set

   type GM() =
      member val ah = AH() with get,set
      static member F() = GM()

   let foo(ah: AH) =
      let x = GM()
      x.ah.X <- ah.X // look here
      x
```
Hint occurred
![image](https://user-images.githubusercontent.com/5526875/206086360-7cd9342e-754a-42a8-bf1b-39646013eb05.png)

it try fix it to:
![image](https://user-images.githubusercontent.com/5526875/206086791-baaa5584-b8d8-4bb4-9608-11df625657f2.png)

but, when I change `ah` to `Ah`, it becomes normal：
```
   type AH() =
      member val X = 0 with get,set

   type GM() =
      member val Ah = AH() with get,set // change
      static member F() = GM()

   let foo(ah: AH) =
      let x = GM()
      x.Ah.X <- ah.X // change
      x
```
![image](https://user-images.githubusercontent.com/5526875/206087218-67a4a53e-9f4b-454f-b3ec-309dca82a43d.png)

The above happened in `Microsoft Visual Studio Enterprise 2022 17.4.2`

**Comment by psfinaki** [comment] 2023-06-15 13:08
Hey @GratianPlume - looks like I cannot reproduce this in the latest VS, the code fix suggestion doesn't pop up:

![image](https://github.com/dotnet/fsharp/assets/5451366/5981e28e-0872-4dc3-8d59-2ea784482d6b)

I will close this - feel free to reopen if you come across this again.

**Closed by psfinaki** 2023-06-15 13:08 UTC
Labels: Bug, Impact-Medium, Area-LangService-CodeFixes
