### ISSUE TITLE
Type annotation code lens only annotates top-level let statements

### ISSUE THREAD

**Issue by bascarsija** [dotnet/fsharp#5697] opened 2018-09-24 21:21 UTC
The F# type annotation code lens only seems to show type annotations for top-level let statements within modules.  This is great, but the number of non-top-level (i.e. "nested") let statements far outweighs that of top-level ones in the code base in which I work, so the utility of this feature is very limited.

#### Repro steps

1. Open any F# file with a module having at least one let statement which itself has at least one let statement within it.  For example:

```
module Test

   let zeroFun = fun _ -> 0
    let zeroVal =
        let oneVal = 1
        zeroFun oneVal
```
#### Expected behavior

`zeroFun`, `zeroVal` _and_ `oneVal` have type annotations appear

#### Actual behavior

Only `zeroFun` and `zeroVal` have type annotations appear

#### Known workarounds

N/A

#### Related information 

* Windows 10
* Visual Studio Professional 15.8.5
* .NET Framework 4.7.03056

**Comment by cartermp** [comment] 2018-09-24 22:50
Also worth noting that inner values and functions are not annotated in Ionide (regardless of if it's codelens or linelens):
<img width="277" alt="screen shot 2018-09-24 at 15 45 16" src="https://user-images.githubusercontent.com/6309070/45983315-f6f41080-c010-11e8-9655-acd784ab1bac.png">
<img width="373" alt="screen shot 2018-09-24 at 15 48 05" src="https://user-images.githubusercontent.com/6309070/45983405-40dcf680-c011-11e8-81f6-086e4e19e267.png">

I don't think I'd like to have inner values annotated. It would get quite noisy to have annotations in the editor that aren't real (i.e., not actually a part of source). Perhaps as an option that's off by default. @Krzysztof-Cieslak did you ever play with additional annotations in Ionide? If so, any experiences to share?

**Comment by Krzysztof-Cieslak** [comment] 2018-09-25 03:58
I believe current state of annotations is fine, in my opinion adding more would make things too noisy - most top level functions contains many inner bindings and annotating them all would create lot of noise. Also it is consistent with other features such as code outline, breadcrumbs. And in the end - the more annotations the more we stress compiler, adding more code lenses may have performance implications

**Comment by bascarsija** [comment] 2018-09-25 20:46
FWIW, I am strongly in favor of the proposed solution to have an optional configuration.  The "noise" that others have discussed above is precisely the signal that is missing for me.

**Comment by cartermp** [comment] 2018-10-07 22:59
@bascarsija I don't personally want this, but I'd be open to a PR that implements it and places it behind an off-by-default option.

**Comment by realvictorprm** [comment] 2018-10-09 13:11
I kind of had the same thoughts and conclusions as @Krzysztof-Cieslak about this additional feature. However on the other hand I still see use cases for enabling more code lens in specific areas @bascarsija!

Instead of enabling code lens for every single let statement of a file I would rather propose to add the possibility to select certain lines of code and let them have code lens per key combination. Let's call this imaginary feature In-Depth-Code-Lens.

Those In-Depth-Code-Lens could be used for the complete file too however it's more a tool to let the user decide which lines of code really may have type annotations. So the benefit of such an approach is clearly the better performance and the reduction of unwanted noise for the user if used wisely bit by bit.
The main users could be Beginners inspecting random F# code trying to understand what types certain variables have but also F# Experts inspecting complex library code (for example the F# compiler!).

What do you think about this feature idea @bascarsija @cartermp?

**Comment by cartermp** [comment] 2018-10-09 15:10
On-demand annotations controlled by a keybinding would definitely be interesting.

**Comment by realvictorprm** [comment] 2018-10-10 08:21
Yesterday I had a deep look into this and I can confirm that it's possible to make such code lens with some restrictions because of technical problems right now (see below).


Unfortunately inner variables don't have a unique name making it difficult for me to create unique id's for the caching to allow code lens with still editable files.

**Comment by bascarsija** [comment] 2018-10-11 07:04
@realvictorprm, if I understand what you are proposing correctly with the hypothetical In-Depth-Code-Lens feature, it sounds like it could be leveraged for my "annotate everything" use case by a quick CTRL-A to select _everything_, followed by the feature-toggling keystroke.

**Comment by realvictorprm** [comment] 2018-10-11 08:55
@bascarsija exactly 👍 
However if this really get's in I'm quite sure that performance wise it won't be a good idea to use this in a big file 🤔

**Comment by cartermp** [comment] 2020-10-18 20:03
I will close this out because it's not the appropriate feature for codelens.

Instead, I'm going to prototype out support for Inline Hints, which is made available via this API: https://github.com/dotnet/roslyn/blob/master/src/Tools/ExternalAccess/FSharp/InlineHints/IFSharpInlineHintsService.cs

The idea being that you can toggle via **ctrl+alt** to see inferred types for bindings within the viewport. It is currently in preview for C# and I hope to also have preliminary support for F# in the 16.9 release.

**Closed by cartermp** 2020-10-18 20:03 UTC
Labels: Area-IDE Language Service, Feature Request
