### ISSUE TITLE
A strange behaviour about generics and multiple concrete generic interfaces

### ISSUE THREAD

**Issue by En3Tho** [dotnet/fsharp#11659] opened 2021-06-09 19:54 UTC
First of all I'm sorry if this has already been reported.

While playing with Env-style dependencies and trying different approaches I've stumbled upon a strange behaviour of FSharp compiler. Look at code below:

``` fsharp

module Gists.FSharp.Environment

type IEnv<'a> =
    abstract member Value: 'a

module GenericDeps =

    type Environment(dep, dep2) =
        interface IEnv<string> with member this.Value = dep
        interface IEnv<int> with member this.Value = dep2

    let consumeStringEnv (env: #IEnv<string>) value = env.Value |> ignore
    let consumeIntEnv (env: #IEnv<int>) value = env.Value |> ignore

    let consumeBothEnvs env =
        consumeStringEnv env ()
        consumeIntEnv env () // Error 1: The type 'int' does not match the type 'string'. Why is that?

    Environment("", 0) |> consumeBothEnvs

module NonGenericDeps =

    type IStringEnv = abstract member Value: string

    type IIntEnv = abstract member Value: int

    type Environment(dep, dep2) =
        interface IStringEnv with member this.Value = dep
        interface IIntEnv with member this.Value = dep2

    let consumeStringEnv (env: #IStringEnv) value = env.Value |> ignore
    let consumeIntEnv (env: #IIntEnv) value = env.Value |> ignore

    let consumeBothEnvs env = // works ok, inferred as both IStringEnv and IIntEnv
        consumeStringEnv env ()
        consumeIntEnv env ()

    Environment("", 0) |> consumeBothEnvs


module DoesntWork =
    type Why<'a when 'a :> IEnv<string> and 'a :> IEnv<int>>(value: 'a) = // Error2: Type constraint mismatch. The type ''a' is not compatible with type 'IEnv<int>'
        member _.Value = value

```

Comments are error messages by compiler.
Error 1: For some reason it cannot combine those two interfaces even thought they are concrete and are not ambiguous in any way and declared as flexible.
Error 2: Similar behaviour, for some reason compiler becomes rock solid about not letting a generic implement two concrete interfaces

Is this by design?

It works in C# by the way and I believe this is expected to work.

``` csharp

public interface IEnv<T>
{
    T Value { get; }
}

record Environment(string strEnv, int intEnv) : IEnv<string>, IEnv<int>
{
    string IEnv<string>.Value => strEnv;
    int IEnv<int>.Value => intEnv;
}

public void ConsumeStringEnv<T>(T env) where T: IEnv<string>
{    
    var _ = env.Value;
}

public void ConsumeIntEnv<T>(T env) where T: IEnv<int>
{
    var _ = env.Value;
}

public void ConsumeBothEnvs<T>(T env) where T: IEnv<string>, IEnv<int> // No errors
{    
    ConsumeStringEnv<T>(env);
    ConsumeIntEnv<T>(env);
}

ConsumeBothEnvs(new Environment("", 0));

record Works<T>(T Value) where T: IEnv<string>, IEnv<int> {}  // No errors

```

**Comment by En3Tho** [comment] 2021-06-14 21:49
@cartermp Hey, Phillip! Can you please clarify if it is a limitation or by design?

**Comment by En3Tho** [comment] 2021-06-17 07:35
@dsyme Can you please clarify if this needs fixing or by design? F# added multiple generic interface implementation in types but not in generics it seems? I see this as something that needs improvement but maybe I'm wrong?
Also, tagging @Happypig375 for being super active everywhere :D

**Comment by Happypig375** [comment] 2021-06-17 08:38
Minimal repro:
```fs
type I1 = abstract A : unit
type I2<'T> = abstract B : unit
let s1 (_: I1) = ()
let s2 (_: I2<int>) = ()
let s3 x = s1 x; s2 x
let s4 (_: I2<int>) = ()
let s5 (_: I2<string>) = ()
let s6 x = s4 x; s5 x // error FS0001: The type 'string' does not match the type 'int'
```
The compiler should consider different specializations of the same generic interface as different interfaces.

**Comment by Happypig375** [comment] 2021-06-17 08:44
```fs
type I1 = abstract A : unit
type I2<'T> = abstract B : unit
let s1 (_: I1) = ()
let s2 (_: I2<int>) = ()
let s3 x = s1 x; s2 x
let s4 (_: I2<int>) = ()
let s5 (_: I2<string>) = ()
let s6<'T when 'T :> I2<int> and 'T :> I2<string>>(x: 'T) = s4 x; s5 x
// error FS0193: Type constraint mismatch. The type ''T' is not compatible with type 'I2<string>'
```

**Comment by Happypig375** [comment] 2021-06-17 08:47
This is a duplicate of #10432.

**Comment by dsyme** [comment] 2021-06-17 11:08
Yes, this is by design, as discussed in #10432.  The language suggestion is the place to follow up on this

**Closed by dsyme** 2021-06-17 11:08 UTC
