### ISSUE TITLE
Unclear Error FS0001

### ISSUE THREAD

**Issue by psiLearn** [dotnet/fsharp#10184] opened 2020-09-25 09:18 UTC
The following error message (dotnetcore 5.0.100-rc.1.20452.10):

createBitmap.fsx(124,54): error FS0001: Dieser Ausdruck sollte den folgenden Typ aufweisen:
    "System.Drawing.Color (System.Drawing.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)"
Er ist jedoch vom folgenden Typ:
    "System.Drawing.Color (System.Drawing.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)"

seams to me of no value because both types are exactly the same.

The code that creates the error. 

```
(*
 * Bitmap Primitives Helpers
 * Partly inspired by http://fssnip.net/si.
*)

#I @"C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10"
//#I @"C:\Program Files\dotnet\sdk\3.1.400"
#r "System.Runtime.dll"
#r "System.Drawing.Common.dll"

open System.Drawing
open System

// deserialize a bitmap file
let fromFile (name : string) = new Bitmap(name)

// serialize a bitmap as png
let toFile (name : string) (bmp: Bitmap) =
    bmp.Save(name, Imaging.ImageFormat.Png) |> ignore
    bmp

// load a bitmap in array of tuples (x,y,Color)
let toRgbArray (bmp : Bitmap) =
    [| for y in 0..bmp.Height-1 do
       for x in 0..bmp.Width-1 -> x,y,bmp.GetPixel(x,y) |]   

// builds a bitmap instance from an array of tuples
let toBitmap (a:(int*int*Color)[]) =
//let toBitmap a =
    let height = (a |> Array.Parallel.map (fun (x,_,_) -> x) |> Array.max) + 1
    let width = (a |> Array.Parallel.map (fun (_,y,_) -> y) |> Array.max) + 1
    let bmp = new Bitmap(height,width)
    //a |> Array.Parallel.iter (fun (x,y,c) -> bmp.SetPixel(x,y,Color.FromArgb(int c.R,int c.G,int c.B) ))
    a |> Array.iter (fun (x,y,c) -> bmp.SetPixel(x,y,Color.FromArgb(int c.R,int c.G,int c.B) ))
    bmp

// converts an image to gray scale
let toGrayScale a =
    a |> Array.Parallel.map (
        fun (x,y,c : System.Drawing.Color) -> 
            let gscale = int((float c.R * 0.3) + (float c.G * 0.59) + (float c.B * 0.11))
            in  x,y,Color.FromArgb(int c.A, gscale, gscale, gscale))

// randomize or R or G or B each 1 to 3 pixels
let randomColorize a =
    let rnd = System.Random()
    let next = fun() -> rnd.Next(255)
    let rgb = function
        | 0 -> fun(c : System.Drawing.Color) -> Color.FromArgb(int c.A, next(), (int c.G), (int c.B))
        | 1 -> fun(c) -> Color.FromArgb(int c.A, (int c.R), next(), (int c.B))
        | _ -> fun(c) -> Color.FromArgb(int c.A, (int c.R), (int c.G), next())
    a |> Array.Parallel.mapi (
        fun i (x,y,c : System.Drawing.Color) -> 
            if i % rnd.Next(1,3) = 0 then x,y, rgb(rnd.Next(2))(c)
            else x,y,c)
(*
 * Usage example:
*)
let convertImage =
    use newBitmap =
        fromFile @"C:/Temp/with-color.jpg"
        |> toRgbArray
        |> toGrayScale // or custom in memory manipulation function
        |> toBitmap
    use savedBitmap =
        toFile @"C:/Temp/gray-scale.png" newBitmap
    ()
```

**Comment by abelbraaksma** [comment] 2020-09-25 17:06
When I try your code by pasting it in FSI (after removing the final ` ``` `), I get:

> error FS0193: Could not load file or assembly 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

When I paste your code in latest VS 2019 16.8 Preview 3.1 it gives me a type error:

![image](https://user-images.githubusercontent.com/16015770/94295807-1ad0f080-ff62-11ea-8b3d-a3eb5f4ed324.png)

How did you compile your code, or run your code, to get the error you showed?

**Comment by abelbraaksma** [comment] 2020-09-25 17:23
Ah, just noticed that the above error in my poor attempt to repro is caused by trying to load a .NET Core reference inside a .NET Framework FSI instance.

Loading your code in a session started with `dotnet fsi` shows the following English-language error which appears to mimic the one you have above in German:

> tryme.fsx(34,53): error FS0001: This expression was expected to have type
>  &nbsp;  'System.Drawing.Color (System.Drawing.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)'
> but here has type
> &nbsp;     'System.Drawing.Color (System.Drawing.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)'

**Comment by abelbraaksma** [comment] 2020-09-25 17:44
In case you want to investigate what the weird difference of the types is, you can do this:

```
   |> Array.iter (fun (x,y,c) -> 
        let color = Unchecked.defaultof<_>
        let ty = color.GetType()
        bmp.SetPixel(x, y, color)
   )
```

I noticed that `c` also has the wrong type according the FSI, but using `Unchecked.defaultof<_>` it doesn't balk at this line anymore (though there's another error at the bottom of your script). This may allow you to further investigate it, my guess is that somehow two `Color` definitions from different assemblies but the same namespace are in scope.

**Comment by cartermp** [comment] 2021-02-06 21:07
I'll close this as there are other tracking issues covering error message improvements

**Closed by cartermp** 2021-02-06 21:07 UTC

**Comment by abelbraaksma** [comment] 2021-02-26 20:04
@cartermp, I doubt this is about improving the error message. The problem here is that the error is raised even though the types are equal (as can be seen in my repro and in the OP).

I think it's caused by some weird type resolving going on in fsi, where it somehow get two exactly the same types in scope but from different assemblies (they may have the same name and signature, but different locations?).

Since the OP didn't check back I guess he found a workaround.
