### ISSUE TITLE
.NET9.0 mono VMR source-build fails to build "fsharp" on Fedora on s390x

### ISSUE THREAD

**Issue by Vishwanatha-HD** [dotnet/fsharp#17342] opened 2024-06-24 14:39 UTC
While trying for .NET9.0 mono VMR source-build, I see a failure while building "fsharp" on Fedora on s390x arch.

**Repro steps**

The cross-build SDK:
dotnet-sdk-9.0.100-preview.7.24321.1

The command that is getting run:
The command "/home/tester/dotnet/src/fsharp/build.sh --pack --publish --ci --configuration Release -bl /p:DotNetBuildRepo=true /p:DotNetBuildOrchestrator=true /p:RestoreConfigFile=/home/tester/dotnet/artifacts/obj/fsharp/NuGet.config /p:SourceBuildUseMonoRuntime=true /p:SourceBuiltAssetsDir=/home/tester/dotnet/artifacts/assets/Release/ /p:SourceBuiltAssetManifestsDir=/home/tester/dotnet/artifacts/obj/AssetManifests/fsharp/ /p:SourceBuiltSymbolsDir=/home/tester/dotnet/artifacts/obj/Symbols/fsharp/ /p:ArcadeBuildFromSource=true /p:DotNetBuildSourceOnly=true /p:PreviouslySourceBuiltNupkgCacheDir="/home/tester/dotnet/packages/" /p:ReferencePackageNupkgCacheDir="/home/tester/dotnet/prereqs/packages/reference/" /p:TreatWarningsAsErrors=false /p:GenerateResourceUsePreserializedResources=true --sourcebuild --tfm net9.0 /p:SourceBuildBootstrapTfm=net9.0 /p:SourceBuiltShippingPackagesDir=/home/tester/dotnet/artifacts/packages/Release/Shipping/fsharp/ /p:SourceBuiltNonShippingPackagesDir=/home/tester/dotnet/artifacts/packages/Release/NonShipping/fsharp/

**Expected behavior**

Expected behavior is that the "fsharp" should build successfully while building source build (VMR way), with the cross-build SDK on s390x.

**Actual Behavior**

Running into the error below....
  /home/tester/dotnet/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: Detected package downgrade: System.Reflection.Metadata from 9.0.0-preview.6.24319.11 to 8.0.0. Reference the package directly from the project to select a different version. [/home/tester/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
  /home/tester/dotnet/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: fsc -> Microsoft.Build.Tasks.Core 17.11.0-preview-24318-05 -> System.Reflection.Metadata (>= 9.0.0-preview.6.24319.11) [/home/tester/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
  /home/tester/dotnet/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: fsc -> System.Reflection.Metadata (>= 8.0.0) [/home/tester/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
  /home/tester/dotnet/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: Detected package downgrade: System.Reflection.Metadata from 9.0.0-preview.6.24319.11 to 8.0.0. Reference the package directly from the project to select a different version. [/home/tester/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
  /home/tester/dotnet/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: fsc -> Microsoft.Build.Tasks.Core 17.11.0-preview-24318-05 -> System.Reflection.Metadata (>= 9.0.0-preview.6.24319.11) [/home/tester/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
  /home/tester/dotnet/src/fsharp/src/fsc/fscProject/fsc.fsproj : error NU1605: fsc -> System.Reflection.Metadata (>= 8.0.0) [/home/tester/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
  /home/tester/dotnet/src/fsharp/eng/SourceBuild.props(42,5): error MSB3073: The command "./build.sh --bootstrap --skipBuild -bl --tfm net9.0 /p:SourceBuildUseMonoRuntime=true" exited with code -1. [/home/tester/dotnet/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
      0 Warning(s)
      7 Error(s)

**Known workarounds**

NA

**Related information**

* mono

[NET9 VMR source build failure on fedora on s390x.txt](https://github.com/user-attachments/files/15957304/NET9.VMR.source.build.failure.on.fedora.on.s390x.txt)

**Comment by vzarytovskii** [comment] 2024-06-24 14:47
I don't know how VMR works, someone from the team should look probably. I don't know how it's different from sourcebuild/our build. Maybe @ViktorHofer or someone from @dotnet/source-build-internal know how to fix it?

**Comment by MichaelSimons** [comment] 2024-06-24 14:50
This looks like a duplicate of https://github.com/dotnet/source-build/issues/4477

**Comment by Vishwanatha-HD** [comment] 2024-06-24 14:53
More info on the commit IDs that are used while building the same.
++ STAGE1_REF=main
++ STAGE1_REPO=https://github.com/dotnet/dotnet
++ STAGE1_COMMIT=7cffb1fb9996f93d0627d40900fae6fc454a6ac0

**Comment by vzarytovskii** [comment] 2024-06-24 14:59
> This looks like a duplicate of [dotnet/source-build#4477](https://github.com/dotnet/source-build/issues/4477)

Ok, thanks. Will close this one in favour of the earlier one. If there's anything actionable for us, feel free to move the original here.

Duplicate of https://github.com/dotnet/source-build/issues/4477

**Closed by vzarytovskii** 2024-06-24 14:59 UTC
Labels: Bug, Needs-Triage
