### ISSUE TITLE
F# implemented abstract static member causes Bad image format invoked through reflection

### ISSUE THREAD

**Issue by wallymathieu** [dotnet/fsharp#14391] opened 2022-11-25 06:17 UTC
**Repro steps**

In order to reproduce the issue I create an implementation of IParsable from F#, then invoke it through reflection

```f#
open System
open System.ComponentModel

// from https://madskristensen.net/post/A-shorter-and-URL-friendly-GUID
let toStr (x : Guid) = 
    let enc = Convert.ToBase64String(x.ToByteArray())
    let enc = enc.Replace("/", "_").Replace("+", "-")
    enc.Substring(0, 22)

let fromStr (encoded : string) = 
    let encoded = encoded.Replace("_", "/").Replace("-", "+")
    let buffer = Convert.FromBase64String(encoded + "==")
    if buffer.Length = 16 then Some(Guid buffer)
    else None

let tryParseId (prefix : string) (str : string) = 
    if str.StartsWith(prefix) then fromStr (str.Substring prefix.Length)
    else None

let parseId prefix str = 
    let maybeParsed = tryParseId prefix str
    match maybeParsed with
    | Some g -> g
    | None -> raise (FormatException str)

type CustomerId = 
    { Value : Guid }
    static member Default : CustomerId = { Value=Guid.Empty }
    static member Parse(str : string) : CustomerId = { Value = parseId "c-" str }
    override this.ToString() = sprintf "c-%s" (toStr this.Value)
    interface IParsable<CustomerId> with
        static member Parse(s:string, f:IFormatProvider) = CustomerId.Parse(s)
        static member TryParse(s:string, f:IFormatProvider, result:byref<CustomerId>) =
            try
                result <- CustomerId.Parse(s)
                true
            with _ ->
                result <- Unchecked.defaultof<_>
                false
typeof<CustomerId>.GetInterface("IParsable`1").GetMethod("Parse").Invoke(null, [| "c-ReJ_cYj8l0WmonC0k0hQvw"; null |]);;
(**
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.BadImageFormatException: Bad IL format.
   at InvokeStub_IParsable`1.Parse(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at <StartupCode$FSI_0030>.$FSI_0030.main@() in /Users/mathieu/src/cs/Saithe/stdin:line 158
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
*)
```

**Expected behavior**

If you implement the same logic but with an instance interface then you get the expected behaviour:

```f#
type IParsableInst<'T> = interface
    abstract member Parse : string -> 'T
    abstract member TryParse : string*byref<'T> -> bool
end

type CustomerId2 = 
    { Value2 : Guid }
    static member Default : CustomerId2 = { Value2=Guid.Empty }
    static member Parse(str : string) : CustomerId2 = { Value2 = parseId "c-" str }
    override this.ToString() = sprintf "c-%s" (toStr this.Value2)
    interface IParsableInst<CustomerId2> with
        member this.Parse(s:string) = CustomerId2.Parse(s)
        member this.TryParse(s:string, result:byref<CustomerId2>) =
            try
                result <- CustomerId2.Parse(s)
                true
            with _ ->
                result <- Unchecked.defaultof<_>
                false

typeof<CustomerId2>.GetInterface("IParsableInst`1").GetMethod("Parse").Invoke(CustomerId2.Default, [| "c-ReJ_cYj8l0WmonC0k0hQvw" |]);;
// val it: obj = { Value2 = 717fe245-fc88-4597-a6a2-70b4934850bf }
```

**Actual behavior**

Throws `System.BadImageFormatException`

**Known workarounds**

It's a new feature in .net.

**Related information**

* Operating system (Windows Appveyor Visual Studio 2022 image, Mac OS X, GitHub Ubuntu latest (at the time of writing 2022-11) )
* .NET Runtime kind (.NET 7.0.100)

**Comment by vzarytovskii** [comment] 2022-11-25 11:07
I presume it's because of the name of the interface, gotta look at it more closely.

**Comment by vzarytovskii** [comment] 2022-11-25 11:28
@wallymathieu actually, on a second thought, it seems that you are taking a method from the actual interface, not the implementation.

**Comment by wallymathieu** [comment] 2022-11-25 11:36
Why then does the second example work?

**Comment by vzarytovskii** [comment] 2022-11-25 11:44
> Why then does the second example work?

I don't yet know, looking at the codegen

**Comment by vzarytovskii** [comment] 2022-11-25 11:50
Okay, I believe that it's because we generate a virtual instance method, and a regular one for static implementation:
```fsharp;
        virtual CustomerId2 IParsableInst<CustomerId2>.Parse(string s)
        {
            return new CustomerId2(parseId("c-", s));
        }
```
For the static one
```fsharp
static CustomerId IParsable<CustomerId>.Parse(string s, IFormatProvider f)
	{
		return Parse(s);
	}
```

We probably could emit it as virtual, @dsyme thoughts?

**Comment by vzarytovskii** [comment] 2022-11-25 11:55
@wallymathieu 
You can kinda workaround it by getting the method on type by its full name, but it defeats the purpose of this method being "universal".
If I may ask you, why are you using reflection as oppose of the direct call on the type parameter?

**Comment by wallymathieu** [comment] 2022-11-25 11:57
I would hope that I don't need to use reflection. The thing I'm trying is this: https://github.com/NewtonsoftJsonExt/Saithe/pull/13/files

**Comment by wallymathieu** [comment] 2022-11-25 11:59
But as this is a new feature I'm kind of unsure how I would go about doing that 😃

**Comment by vzarytovskii** [comment] 2022-11-25 12:34
@wallymathieu I see, you can call it directly - `'T.Parse(...)`, like this:
```
open System

let toStr (x : Guid) = 
    let enc = Convert.ToBase64String(x.ToByteArray())
    let enc = enc.Replace("/", "_").Replace("+", "-")
    enc.Substring(0, 22)

let fromStr (encoded : string) = 
    let encoded = encoded.Replace("_", "/").Replace("-", "+")
    let buffer = Convert.FromBase64String(encoded + "==")
    if buffer.Length = 16 then Some(Guid buffer)
    else None

let tryParseId (prefix : string) (str : string) = 
    if str.StartsWith(prefix) then fromStr (str.Substring prefix.Length)
    else None

let parseId prefix str = 
    let maybeParsed = tryParseId prefix str
    match maybeParsed with
    | Some g -> g
    | None -> raise (FormatException str)

[<NoComparison; NoEquality>]
type CustomerId = 
    { Value : Guid }
    static member Default : CustomerId = { Value=Guid.Empty }
    static member Parse(str : string) : CustomerId = { Value = parseId "c-" str }
    override this.ToString() = sprintf "c-%s" (toStr this.Value)
    interface IParsable<CustomerId> with
        static member Parse(s:string, f:IFormatProvider) = CustomerId.Parse(s)
        static member TryParse(s:string, f:IFormatProvider, result:byref<CustomerId>) =
            try
                result <- CustomerId.Parse(s)
                true
            with _ ->
                result <- Unchecked.defaultof<_>
                false

let parse<'T when IParsable<'T>> (s: string) = 'T.Parse(s, Unchecked.defaultof<IFormatProvider>)

let parsed = parse<CustomerId> "c-ReJ_cYj8l0WmonC0k0hQvw"

printfn $"%A{parsed}"
// { Value = 717fe245-fc88-4597-a6a2-70b4934850bf }
```
This will, unlike SRTP, generate a runtime constrained call to `'T`:
```csharp
.method public static 
	!!T parse<(class [System.Runtime]System.IParsable`1<!!T>) T> (
		string s
	) cil managed 
{
	// Method begins at RVA 0x2138
	// Header size: 1
	// Code size: 14 (0xe)
	.maxstack 8

	// return T.Parse(s, null);
	IL_0000: ldarg.0
	IL_0001: ldnull
	IL_0002: constrained. !!T
	IL_0008: call !0 class [System.Runtime]System.IParsable`1<!!T>::Parse(string, class [System.Runtime]System.IFormatProvider)
	IL_000d: ret
} // end of method Program::parse

```

**Comment by vzarytovskii** [comment] 2022-11-25 12:35
But regarding the reflection issue - I will check what C# is emitting (whether it's emitting virutal method), and do the same,

**Comment by wallymathieu** [comment] 2022-11-25 13:58
Unless they have the same issue?

**Comment by vzarytovskii** [comment] 2022-11-28 16:12
For my future self, for the following code
```csharp
public interface IGetNext<T> where T : IGetNext<T>
{
    static abstract void A();
}

public struct RepeatSequence : IGetNext<RepeatSequence>
{
    public static void A() { return; }
}
```
 here's what C# generates:
```csharp
.class interface public auto ansi abstract IGetNext`1<(class IGetNext`1<!T>) T>
{
    .param constraint T, class IGetNext`1<!T>
        .custom instance void System.Runtime.CompilerServices.NullableAttribute::.ctor(uint8) = (
            01 00 01 00 00
        )
    // Methods
    .method public hidebysig abstract virtual static 
        void A () cil managed 
    {
    } // end of method IGetNext`1::A

} // end of class IGetNext`1

.class public sequential ansi sealed beforefieldinit RepeatSequence
    extends [System.Runtime]System.ValueType
    implements class IGetNext`1<valuetype RepeatSequence>
{
    .pack 0
    .size 1

    // Methods
    .method public hidebysig static 
        void A () cil managed 
    {
        .override method void class IGetNext`1<valuetype RepeatSequence>::A()
        // Method begins at RVA 0x207f
        // Code size 1 (0x1)
        .maxstack 8

        IL_0000: ret
    } // end of method RepeatSequence::A

} // end of class RepeatSequence
```
([Sharplab](https://sharplab.io/#v2:C4LglgNgPgAgzAAjAO2AUwE4DMCGBjNBASQHE1gA5NAD2AB4AVAPgQHcALTQhhEYsyjXrMAsACgA3uIQyEMAIwA2BDgBGAZ2AZ8wOQBYEAQQAUASgDc4gL7jx8BJowBXPLoBKaAA5ocwAMpoAI5OaMgEvPzkVLR0Ht6+AcGhBEziUmKycogKyjAGJqYIEnIA7OYINmJWQA==))

And here's what F# generates for the following code:
```fsharp
[<Interface>]
type IGetNext<'T when IGetNext<'T>> =
    static abstract member A : unit -> unit

type RepeatSequence =
    static member A() = ()
    interface IGetNext<RepeatSequence> with
        static member A() = RepeatSequence.A()
```

IL:
```csharp
	.class interface nested public auto ansi abstract serializable IGetNext`1<(class Program/IGetNext`1<!T>) T>
	{
		.custom instance void [FSharp.Core]Microsoft.FSharp.Core.InterfaceAttribute::.ctor() = (
			01 00 00 00
		)
		.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
			01 00 03 00 00 00 00 00
		)
		// Methods
		.method public hidebysig abstract virtual static 
			void A () cil managed 
		{
		} // end of method IGetNext`1::A

	} // end of class IGetNext`1

	.class nested public auto ansi serializable RepeatSequence
		extends [System.Runtime]System.Object
		implements class Program/IGetNext`1<class Program/RepeatSequence>
	{
		.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
			01 00 03 00 00 00 00 00
		)
		// Methods
		.method public static 
			void A () cil managed 
		{
			// Method begins at RVA 0x2050
			// Header size: 1
			// Code size: 1 (0x1)
			.maxstack 8

			IL_0000: ret
		} // end of method RepeatSequence::A

		.method public hidebysig static 
			void 'Program.IGetNext<Program.RepeatSequence>.A' () cil managed 
		{
			.override method void class Program/IGetNext`1<class Program/RepeatSequence>::A()
			// Method begins at RVA 0x2054
			// Header size: 1
			// Code size: 7 (0x7)
			.maxstack 8

			IL_0000: call void Program/RepeatSequence::A()
			IL_0005: nop
			IL_0006: ret
		} // end of method RepeatSequence::'Program.IGetNext<Program.RepeatSequence>.A'

	} // end of class RepeatSequence
```

We only generate explicit implementation by ourselves.

**Comment by vzarytovskii** [comment] 2022-11-28 16:14
> Unless they have the same issue?

Okay, the following F# code results in the bad IL too:
```csharp
using System.Reflection;
namespace Foo
{
    class C
    {
        public interface IGetNext<T> where T : IGetNext<T>
        {
            static abstract void A();
        }

        public struct RepeatSequence : IGetNext<RepeatSequence>
        {
            public static void A() { return; }
        }

        public static int Main(string[] _)
        {
            typeof(RepeatSequence).GetInterface("IGetNext`1").GetMethod("A").Invoke(null, null);
            return 0;
        }
    }
}
```
![image](https://user-images.githubusercontent.com/1260985/204326875-1b0762ed-df9c-4e78-9bd0-1004d970877c.png)


I'm going to close it as by design, language suggestion should be created instead if we want to change codegen.

**Closed by vzarytovskii** 2022-11-28 16:14 UTC
Labels: Bug, Needs-Triage

**Comment by wallymathieu** [comment] 2022-11-28 18:53
Then, this sounds more like a bug in .net rather than just F# or C#, since this means that both are supposed to write that IL, but that the reflection code cannot deal with the new format?

**Comment by vzarytovskii** [comment] 2022-11-28 20:48
> Then, this sounds more like a bug in .net rather than just F# or C#, since this means that both are supposed to write that IL, but that the reflection code cannot deal with the new format?

Good question.

I'm sure that reflection, in this case, generates exactly what it told to.

Another question is codegen - it probably could be different for both F# and C# - we could've generated virtual members instead, and it might've worked (still need to think of it more).

We, however, will likely not change codegen unless Roslyn will.

**Comment by wallymathieu** [comment] 2022-11-28 20:56
So where should I report this then?

**Comment by vzarytovskii** [comment] 2022-11-29 11:23
> So where should I report this then?

I would start with runtime repo, they'll probably route you in the right direction (I won't be surprised that it's by design, though).

Here's full C# example with instance and static method: https://sharplab.io/#v2:C4LgTgrgdgPlCGBbApgZwA7wMbIAQDEB7QgWACgBvc3G3AAQCZcBha2qs2r+gZlwEsowZGABm2PAEkihADwAVAHy4A7gAsReebhC5pxBYrbdcHEyboBGAGy54AI1TAw2YAKG4AggAoAlAG5jcxoHJxcsN0E3ACE/QM5zAF9yIK46PjCICIJiHT0ZWRkjBJMzYNp0+ht3Nx9fU3oAdlwGf1xkkvLKqNxY+oom3B42juCO1Iq+K1segFl4QW8rAAYAbQBdXAB9XwmaMvLcADd4MFxRXIBeXChkFRzCOL3uE7OAD1xr4ABPdGRCUTeGS+AB0AHFkMBJEIROIcN4AET6QgAA0sCNBEOAs0hakIABNEdEMSDoUdCABrZDeC6EAA0NwgABsmQFnmlLCCrABObxvNmdYKvXDfT64H5/AFA4iYyHQ4RiCSI5FoklYnHAPGEhGeElkynUqDMpkMo0sgWHGhWLmWXnfC2WgD0ACpcPI1GBCCpUOyKpyAErIURM5ARfiEKAg+SnADmcqg5Kw8GA4agAFE3jh0CmI7oM1mc1BcGp4KhcPZkMgi5rPSoi/ZRZq8MBY5DcAC7EXBInk6mQb7aABaYfKa3ReD4ySIeBxohgafAfPIbOp3Tj/F6AAy50I8+T/cFh2TDxBzFJMjRILqA64x+t/ugKZQGq1AAl4FB8SHSQmDS+Cd4ADy9gAFahm4LZgHGwAMgAaoQ/D4s6rqxhAKBCKgDIAMr8DGCDABAYB4KguEMtExAhh+AioMwEaZBEu67Ie5R3gGQYhmGEYgv+k6/lSYA/uSVJAaB4HtqBDLygACs4KFQZhvSCPiggxvgTIzmW3YGp4wDOExlpcMOg64Gmn7tqI7i3GcyCZsuha4E42AUuK4R4EZN60KxIKBsG4F9jx+r8YJBoiWB2SEBJehCDJYByTGCnREpKlqRp7hCcgOl6R5IRuPe7F+VxD5CPwz64gS0IXMFwnAWFbgRSBZFJVAqnqfFaXabpYCNZ+IjlkpIgMjV4EbLgmAuCgCoKcwzIEURFWELgWAzYRyD6QZOUnme8yLFhzgqSNOzZXYuUBo+JXIDx76ft+gUXWVhJDdkkHQXBCFIXFaFVsACk4XhyYrQ5pG9BRyBUfwNF0c4WTAIxR1eT5HGFtx923QJt2hWJ9WSdFsl2PJ3XKc1KVtVpVKZWAa2Ws6jo3nQzTLPEYxBB0iRAA===

**Comment by wallymathieu** [comment] 2022-12-07 06:05
Thanks! I'll report it to the runtime repo!
