### ISSUE TITLE
Cloning and building the repo with the current documentation results in an error in the console

### ISSUE THREAD

**Issue by 7sharp9** [dotnet/fsharp#10914] opened 2021-01-21 13:40 UTC
**Repro steps**

Provide the steps required to reproduce the problem:

1. Clone repo
2. ./build.sh

**Expected behavior**

No errors

**Actual behavior**

>/Users/davethomas/GitHub/fsharp/src/fsharp/absil/illib.fs(575,14): error FS0041: A unique overload for method 'Contains' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - String.Contains(value: char) : bool - String.Contains(value: string) : bool [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]

* Operating system - Mac
* .NET Runtime kind .NET Core

**Comment by vzarytovskii** [comment] 2021-01-21 13:45
That is interesting, it builds just fine in CI, what macOS version are you building on?

**Comment by 7sharp9** [comment] 2021-01-21 14:01
macOS 11.1

Heres the full build output if its useful:

```
❯ ./build.sh
FSharp.sln:
  Determining projects to restore...
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj (in 351 ms).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
FSharpEmbedResXSource: Skipping generation: '/Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Core/Proto/netstandard2.0/FSCore.fs' since it is up-to-date.
  FSharp.Core -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Core/Proto/netstandard2.0/FSharp.Core.dll
  fslex -> /Users/davethomas/GitHub/fsharp/artifacts/bin/fslex/Proto/netcoreapp3.1/fslex.dll
  fsyacc -> /Users/davethomas/GitHub/fsharp/artifacts/bin/fsyacc/Proto/netcoreapp3.1/fsyacc.dll
  AssemblyCheck -> /Users/davethomas/GitHub/fsharp/artifacts/bin/AssemblyCheck/Proto/netcoreapp3.1/AssemblyCheck.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.43
  Determining projects to restore...
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Build/FSharp.Build.fsproj (in 372 ms).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.DependencyManager.Nuget/FSharp.DependencyManager.Nuget.fsproj (in 126 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/fsc/fsc.fsproj (in 149 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj (in 152 ms).
  2 of 5 projects are up-to-date for restore.
  Determining projects to restore...
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Interactive.Settings/FSharp.Compiler.Interactive.Settings.fsproj (in 205 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/fsi/fsi.fsproj (in 205 ms).
  3 of 5 projects are up-to-date for restore.
  FSharp.Core -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Core/Proto/netstandard2.0/FSharp.Core.dll
  FSharp.Build -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Build/Proto/netstandard2.0/FSharp.Build.dll
  FSharp.DependencyManager.Nuget -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.DependencyManager.Nuget/Proto/netstandard2.0/FSharp.DependencyManager.Nuget.dll
  FSharp.Compiler.Service -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.Service/Proto/netstandard2.0/FSharp.Compiler.Service.dll
  fsc -> /Users/davethomas/GitHub/fsharp/artifacts/bin/fsc/Proto/netcoreapp3.1/fsc.dll
  FSharp.Compiler.Interactive.Settings -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.Interactive.Settings/Proto/netstandard2.0/FSharp.Compiler.Interactive.Settings.dll
  fsi -> /Users/davethomas/GitHub/fsharp/artifacts/bin/fsi/Proto/netcoreapp3.1/fsi.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:10.93
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj (in 362 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.DependencyManager.Nuget/FSharp.DependencyManager.Nuget.fsproj (in 362 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Build/FSharp.Build.fsproj (in 362 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Interactive.Settings/FSharp.Compiler.Interactive.Settings.fsproj (in 362 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/fsc/fsc.fsproj (in 362 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/fsi/fsi.fsproj (in 377 ms).
  Restored /Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj (in 405 ms).
  15 of 22 projects are up-to-date for restore.
FSharpEmbedResourceText: Skipping generation of /Users/davethomas/GitHub/fsharp/artifacts/obj/Microsoft.DotNet.DependencyManager/Debug/netstandard2.0/DependencyManager.fs and /Users/davethomas/GitHub/fsharp/artifacts/obj/Microsoft.DotNet.DependencyManager/Debug/netstandard2.0/DependencyManager.resx from DependencyManager.txt since up-to-date
FSharpEmbedResourceText: Skipping generation of /Users/davethomas/GitHub/fsharp/artifacts/obj/Microsoft.DotNet.DependencyManager/Debug/netstandard2.0/UtilsStrings.fs and /Users/davethomas/GitHub/fsharp/artifacts/obj/Microsoft.DotNet.DependencyManager/Debug/netstandard2.0/UtilsStrings.resx from ../utils/UtilsStrings.txt since up-to-date
FSharpEmbedResourceText: Skipping generation of /Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/FSComp.fs and /Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/FSComp.resx from ../FSComp.txt since up-to-date
FSharpEmbedResourceText: Skipping generation of /Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/DependencyManager.fs and /Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/DependencyManager.resx from ../Microsoft.DotNet.DependencyManager/DependencyManager.txt since up-to-date
FSharpEmbedResourceText: Skipping generation of /Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/FSIstrings.fs and /Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/FSIstrings.resx from ../fsi/FSIstrings.txt since up-to-date
FSharpEmbedResourceText: Skipping generation of /Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/UtilsStrings.fs and /Users/davethomas/GitHub/fsharp/artifacts/obj/FSharp.Compiler.Service/Debug/netstandard2.0/UtilsStrings.resx from ../utils/UtilsStrings.txt since up-to-date
  PEVerify -> /Users/davethomas/GitHub/fsharp/artifacts/bin/PEVerify/Debug/netcoreapp3.1/PEVerify.dll
  FSharp.Core -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Core/Debug/netstandard2.0/FSharp.Core.dll
  FSharp.Compiler.Server.Shared -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.Server.Shared/Debug/net472/FSharp.Compiler.Server.Shared.dll
  Microsoft.DotNet.DependencyManager -> /Users/davethomas/GitHub/fsharp/artifacts/bin/Microsoft.DotNet.DependencyManager/Debug/netstandard2.0/Microsoft.DotNet.DependencyManager.dll
  FSharp.Core.UnitTests -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Core.UnitTests/Debug/netcoreapp3.1/FSharp.Core.UnitTests.dll
  FSharp.Compiler.Interactive.Settings -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.Interactive.Settings/Debug/netstandard2.0/FSharp.Compiler.Interactive.Settings.dll
  FSharp.DependencyManager.Nuget -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.DependencyManager.Nuget/Debug/netstandard2.0/FSharp.DependencyManager.Nuget.dll
/usr/local/share/dotnet/sdk/5.0.102/Microsoft.Common.CurrentVersion.targets(2123,5): error MSB3277: Found conflicts between different versions of "System.IO.Compression" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/usr/local/share/dotnet/sdk/5.0.102/Microsoft.Common.CurrentVersion.targets(2123,5): error MSB3277: Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
  FSharp.Compiler.Service -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.Service/Debug/netstandard2.0/FSharp.Compiler.Service.dll
  FSharp.Compiler.Private.Scripting -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.Private.Scripting/Debug/netstandard2.0/FSharp.Compiler.Private.Scripting.dll
  FSharp.Compiler.Service.Tests -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.Service.Tests/Debug/netcoreapp3.1/FSharp.Compiler.Service.Tests.dll
  fsi -> /Users/davethomas/GitHub/fsharp/artifacts/bin/fsi/Debug/netcoreapp3.1/fsi.dll
  FSharp.Compiler.Private.Scripting.UnitTests -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.Private.Scripting.UnitTests/Debug/netcoreapp3.1/FSharp.Compiler.Private.Scripting.UnitTests.dll
  FSharp.Build -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Build/Debug/netstandard2.0/FSharp.Build.dll
  fsc -> /Users/davethomas/GitHub/fsharp/artifacts/bin/fsc/Debug/netcoreapp3.1/fsc.dll
  FSharp.Build.UnitTests -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Build.UnitTests/Debug/netcoreapp3.1/FSharp.Build.UnitTests.dll
/Users/davethomas/GitHub/fsharp/src/fsharp/absil/illib.fs(575,14): error FS0041: A unique overload for method 'Contains' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - String.Contains(value: char) : bool - String.Contains(value: string) : bool [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
  Microsoft.FSharp.Compiler -> /Users/davethomas/GitHub/fsharp/artifacts/bin/Microsoft.FSharp.Compiler/Debug/netcoreapp3.1/Microsoft.FSharp.Compiler.dll
  FSharp.Test.Utilities -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Test.Utilities/Debug/netcoreapp3.1/FSharp.Test.Utilities.dll
  CSharp_Analysis -> /Users/davethomas/GitHub/fsharp/artifacts/bin/CSharp_Analysis/Debug/netstandard2.0/CSharp_Analysis.dll
/Users/davethomas/GitHub/fsharp/src/fsharp/absil/ilwritepdb.fs(568,14): error FS0041: A unique overload for method 'GetFileName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetFileName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetFileName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/absil/ilwrite.fs(3503,23): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: System.ReadOnlySpan<char>) : System.ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
  FSharp.Compiler.ComponentTests -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.ComponentTests/Debug/netcoreapp3.1/FSharp.Compiler.ComponentTests.dll
  FSharpSuite.Tests -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharpSuite.Tests/Debug/netcoreapp3.1/FSharpSuite.Tests.dll
  FSharp.Compiler.UnitTests -> /Users/davethomas/GitHub/fsharp/artifacts/bin/FSharp.Compiler.UnitTests/Debug/netcoreapp3.1/FSharp.Compiler.UnitTests.dll
/Users/davethomas/GitHub/fsharp/src/fsharp/FxResolver.fs(258,23): error FS0041: A unique overload for method 'TryParse' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Version.TryParse(input: ReadOnlySpan<char>, result: byref<Version>) : bool - Version.TryParse(input: string, result: byref<Version>) : bool [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/FxResolver.fs(707,24): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/FxResolver.fs(708,13): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/ParseAndCheckInputs.fs(224,16): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/CompilerOptions.fs(509,21): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/ServiceUntypedParse.fs(38,19): error FS0041: A unique overload for method 'GetExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/ServiceUntypedParse.fs(43,19): error FS0041: A unique overload for method 'GetExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/ServiceUntypedParse.fs(48,19): error FS0041: A unique overload for method 'GetExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/FSharpCheckerResults.fs(1637,78): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/service.fs(193,59): error FS0041: A unique overload for method 'GetFileNameWithoutExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetFileNameWithoutExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetFileNameWithoutExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/fsi/fsi.fs(643,53): error FS0041: A unique overload for method 'GetFileNameWithoutExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetFileNameWithoutExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetFileNameWithoutExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]

Build FAILED.

/usr/local/share/dotnet/sdk/5.0.102/Microsoft.Common.CurrentVersion.targets(2123,5): error MSB3277: Found conflicts between different versions of "System.IO.Compression" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/usr/local/share/dotnet/sdk/5.0.102/Microsoft.Common.CurrentVersion.targets(2123,5): error MSB3277: Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/absil/illib.fs(575,14): error FS0041: A unique overload for method 'Contains' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - String.Contains(value: char) : bool - String.Contains(value: string) : bool [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/absil/ilwritepdb.fs(568,14): error FS0041: A unique overload for method 'GetFileName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetFileName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetFileName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/absil/ilwrite.fs(3503,23): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: System.ReadOnlySpan<char>) : System.ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/FxResolver.fs(258,23): error FS0041: A unique overload for method 'TryParse' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Version.TryParse(input: ReadOnlySpan<char>, result: byref<Version>) : bool - Version.TryParse(input: string, result: byref<Version>) : bool [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/FxResolver.fs(707,24): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/FxResolver.fs(708,13): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/ParseAndCheckInputs.fs(224,16): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/CompilerOptions.fs(509,21): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/ServiceUntypedParse.fs(38,19): error FS0041: A unique overload for method 'GetExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/ServiceUntypedParse.fs(43,19): error FS0041: A unique overload for method 'GetExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/ServiceUntypedParse.fs(48,19): error FS0041: A unique overload for method 'GetExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/FSharpCheckerResults.fs(1637,78): error FS0041: A unique overload for method 'GetDirectoryName' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetDirectoryName(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetDirectoryName(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/service/service.fs(193,59): error FS0041: A unique overload for method 'GetFileNameWithoutExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetFileNameWithoutExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetFileNameWithoutExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
/Users/davethomas/GitHub/fsharp/src/fsharp/fsi/fsi.fs(643,53): error FS0041: A unique overload for method 'GetFileNameWithoutExtension' could not be determined based on type information prior to this program point. A type annotation may be needed.Known type of argument: 'aCandidates: - Path.GetFileNameWithoutExtension(path: ReadOnlySpan<char>) : ReadOnlySpan<char> - Path.GetFileNameWithoutExtension(path: string) : string [/Users/davethomas/GitHub/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj]
    0 Warning(s)
    16 Error(s)

Time Elapsed 00:00:36.62
Build failed with exit code 1. Check errors above.
Error building solution (exit code '1').
fsharp on 🌱 main •NET v5.0.100 took 51s
❯
```

**Comment by cartermp** [comment] 2021-01-21 22:27
What .NET SDK version are you building against? And custom setup that you may have?

I can't reproduce this on my mac:

* macOS 11.1
* SDK is 5.0.100
* iterm2 and zsh just running `sh build.sh`

One thing I did notice is that it looks like the build actually happens twice.

**Comment by cartermp** [comment] 2021-02-06 21:57
Closing due to no repro. I confirmed again that this works on my mac.

**Closed by cartermp** 2021-02-06 21:57 UTC
Labels: Need More Info
