### ISSUE TITLE
internal error: Undefined or unsolved type variable:  ^TaskLike in backgroundTask CE

### ISSUE THREAD

**Issue by TheAngryByrd** [dotnet/fsharp#12931] opened 2022-04-02 17:14 UTC
👋  Hey there. 

I'm currently working on a [`cancellableTaskResult` in FsToolkit.ErrorHandling](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/172). I've been following the pattern of set down in FSharp.Core by having a `cancellableTaskResult` and a `backgroundCancellableTaskResult` to deal with the [SynchronizationContext behaviors](https://github.com/fsharp/fslang-design/pull/571/files).  One of the differences I've been going down the path of is using `Source` members on the computation expressions to avoid needing [a massive number of overloads](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/83) with regards to `Bind/ReturnFrom/MergeSources` etc. The common pattern for `Source` is `SomeOtherType` -> `TheTypeIKnowHowToBind`.  So for example, if you added `Source` members to AsyncBuilder, it would looking something like:

```fsharp 
 member __.Source(task: Task<'T>) : Async<'T> =
     Async.AwaitTask(task)
```

However, things get a bit weird when trying to implement against the [SRTP `^TaskLike`](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/tasks.fs#L282).  Typically these extensions have been put on the `Base` builder but because of the `SynchronizationContext`, I've put this extension on the `CancellableTaskResultBuilder`.  The way I've implemented is to use 

```fsharp
        type CancellableTaskResultBuilder with
            
            [<NoEagerConstraintApplication>]
            member inline this.Source< ^TaskLike, ^Awaiter, 'T, 'Error when ^TaskLike: (member GetAwaiter : unit -> ^Awaiter) and ^Awaiter :> ICriticalNotifyCompletion and ^Awaiter: (member get_IsCompleted :unit -> bool) and ^Awaiter: (member GetResult : unit -> 'T)>
                (t: ^TaskLike)
                : CancellableTaskResult<'T, 'Error> = // `CancellableTaskResult` is a `CancellationToken -> Task<Result<'T,'Error>>`
                fun _ ->
                    task {
                        let! result = t
                        return Ok result
                    }
```

Which works fine.  However when adding a similar implementation to the `BackgroundCancellableTaskResultBuilder` 

```fsharp
type BackgroundCancellableTaskResultBuilder with
            [<NoEagerConstraintApplication>]
            member inline this.Source< ^TaskLike, ^Awaiter, 'T, 'Error when ^TaskLike: (member GetAwaiter : unit -> ^Awaiter) and ^Awaiter :> ICriticalNotifyCompletion and ^Awaiter: (member get_IsCompleted :
                unit -> bool) and ^Awaiter: (member GetResult : unit -> 'T)>
                (t: ^TaskLike)
                : CancellableTaskResult<'T, 'Error> =
                fun _ ->
                    backgroundTask {
                        let! result = t
                        return Ok result
                    }
```

I get multiple errors such as:

```bash
src/FsToolkit.ErrorHandling.IcedTasks/CancellableTaskResultCE.fs(380,21): error FS0073: internal error: Undefined or unsolved type variable:  ^TaskLike [src/FsToolkit.ErrorHandling.IcedTasks/FsToolkit.ErrorHandling.IcedTasks.fsproj]
src/FsToolkit.ErrorHandling.IcedTasks/CancellableTaskResultCE.fs(380,21): error FS0073: internal error: Undefined or unsolved type variable:  ^Awaiter [src/FsToolkit.ErrorHandling.IcedTasks/FsToolkit.ErrorHandling.IcedTasks.fsproj]
src/FsToolkit.ErrorHandling.IcedTasks/unknown(1,1): error FS0073: internal error: Undefined or unsolved type variable:  ^TaskLike [src/FsToolkit.ErrorHandling.IcedTasks/FsToolkit.ErrorHandling.IcedTasks.fsproj]
src/FsToolkit.ErrorHandling.IcedTasks/unknown(1,1): error FS0073: internal error: Undefined or unsolved type variable:  ^Awaiter [src/FsToolkit.ErrorHandling.IcedTasks/FsToolkit.ErrorHandling.IcedTasks.fsproj]
```

I've read over these issues https://github.com/dotnet/fsharp/issues/9633 and https://github.com/dotnet/fsharp/issues/12184 and many of the issues linked but I'm unsure where to go other than filing a bug at this point.

**Repro steps**

https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/172 Should have the the weird compile errors

**Expected behavior**

Not getting this compile error.

**Actual behavior**

Getting this compile error.

**Known workarounds**

Just use `task` instead of `backgroundTask` for `Source` overloads using SRTP to bind for `^TaskLike`

**Related information**

Provide any related information (optional):

```bash
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.2.207 [/usr/local/share/dotnet/sdk]
  3.1.201 [/usr/local/share/dotnet/sdk]
  3.1.406 [/usr/local/share/dotnet/sdk]
  3.1.407 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]
  5.0.208 [/usr/local/share/dotnet/sdk]
  5.0.300 [/usr/local/share/dotnet/sdk]
  5.0.402 [/usr/local/share/dotnet/sdk]
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
  ```

**Comment by dsyme** [comment] 2022-04-04 13:19
This is a duplicate of https://github.com/dotnet/fsharp/issues/12761

**Closed** 2022-04-04 13:22 UTC
Labels: Bug
