### ISSUE TITLE
Authoring a Custom MSBuild Task using dotnet 6 or above and FSharp.Core 6.0.0.0 does not work

### ISSUE THREAD

**Issue by DamianReeves** [dotnet/fsharp#16016] opened 2023-09-21 19:00 UTC
Please provide a succinct description of the issue.

When using F# to author a custom MSBuild task things don't seem to work as expected. There seems to be an issue resolving the correct version of `FSharp.Core`.

**Repro steps**

Provide the steps required to reproduce the problem:

1. clone this repo: https://github.com/finos-labs/morphir-fsharp which has a small repo of the issue experienced first here: https://github.com/finos/morphir-dotnet/tree/main/samples/msbuild/Morphir.MSBuild.ConsoleSample
2. At the root of the repo, run the following command: 

```
dotnet msbuild samples/msbuild/Morphir.MSBuild.ConsoleSample/Morphir.MSBuild.ConsoleSample.fsproj -t:GenerateMorphirJson -v:d  
```

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**
My custom F# authored MSBuild task written in .NET 6 or above actually works.

**Actual behavior**

Provide a description of the actual behaviour observed. 
![image](https://github.com/dotnet/fsharp/assets/957246/57bdc2fb-b66a-4917-9771-d6445b3d671f)

**Known workarounds**

Provide a description of any known workarounds.

**Related information**

Provide any related information (optional):

* Operating system : MacOS Ventura (Intel Mac)
* .NET Runtime kind (.NET Core, .NET Framework, Mono) : .NET 6
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio Code and Rider

**Comment by KevinRansom** [comment] 2023-10-09 19:58
@DamianReeves ,

Hi,
The issue can arise when : Morphir.MSBuild.dll and the dotnet sdk FSharp.Build.dll or perhaps other build task dll's are built with a different version of FSharp.Core.  The first build task loaded will cause it's required version of fsharp.core.dll to be loaded.  Subsequent build tasks that require fsharp.core may fail to load correctly.

However,  It looks like your repo no longer has this issue:

if it does re-occur the best thing to do is to ensure that you build Morphir.MSBuild.dll with FSharp.Core, 6.0.0.0 and ensure that any other fsharp build tasks you use are also compiled with FSharp.Core, 6.0.0.0. 
Any of the 6.* nuget packages, but ideally 6.0.7    :   https://www.nuget.org/packages/FSharp.Core/6.0.7


````
C:\temp\morphir-fsharp>dotnet msbuild Morphir.FSharp.sln
MSBuild version 17.3.2+561848881 for .NET
  Morphir.MSBuild.ConsoleSample -> C:\temp\morphir-fsharp\samples\msbuild\Morphir.MSBuild.ConsoleSample\bin\Debug\net472\Morphir.MSBuild.ConsoleSample.exe
  Morphir.MSBuild.ConsoleSample -> C:\temp\morphir-fsharp\samples\msbuild\Morphir.MSBuild.ConsoleSample\bin\Debug\net6.0\Morphir.MSBuild.ConsoleSample.dll
  Morphir.FSharp -> C:\temp\morphir-fsharp\src\Morphir.FSharp\bin\Debug\netstandard2.0\Morphir.FSharp.dll
  Morphir.FSharp -> C:\temp\morphir-fsharp\src\Morphir.FSharp\bin\Debug\netstandard2.1\Morphir.FSharp.dll
  build -> C:\temp\morphir-fsharp\build\bin\Debug\net6.0\build.dll
  Morphir.MSBuild -> C:\temp\morphir-fsharp\src\Morphir.MSBuild\bin\Debug\net472\Morphir.MSBuild.dll
  Morphir.FSharp.Tests -> C:\temp\morphir-fsharp\tests\Morphir.FSharp.Tests\bin\Debug\net6.0\Morphir.FSharp.Tests.dll
  Morphir.MSBuild -> C:\temp\morphir-fsharp\src\Morphir.MSBuild\bin\Debug\net6.0\Morphir.MSBuild.dll

C:\temp\morphir-fsharp>dotnet msbuild samples/msbuild/Morphir.MSBuild.ConsoleSample/Morphir.MSBuild.ConsoleSample.fsproj
MSBuild version 17.3.2+561848881 for .NET
  Morphir.MSBuild.ConsoleSample -> C:\temp\morphir-fsharp\samples\msbuild\Morphir.MSBuild.ConsoleSample\bin\Debug\net6.0\Morphir.MSBuild.ConsoleSample.dll
  Morphir.MSBuild.ConsoleSample -> C:\temp\morphir-fsharp\samples\msbuild\Morphir.MSBuild.ConsoleSample\bin\Debug\net472\Morphir.MSBuild.ConsoleSample.exe

C:\temp\morphir-fsharp>
````

**Comment by KevinRansom** [comment] 2024-04-19 16:59
I'm closing this by design. the way msbuild works with build tasks is unfortunate.  In general for F#, your build task should match the dependencies that ship in that version of the sdk.

**Closed by KevinRansom** 2024-04-19 16:59 UTC
Labels: Resolution-By Design, Area-ProjectsAndBuild
