### ISSUE TITLE
Attribute is ignored for tuple return type

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#10903] opened 2021-01-20 09:32 UTC
```fsharp
type I =
    abstract M1: int -> [<A>] int * int // expecting error on `A`
    abstract M2: int -> [<A>] (int * int)
    abstract M3: int -> [<A>] int
```
<img width="353" alt="Screenshot 2021-01-20 at 14 31 39" src="https://user-images.githubusercontent.com/3923587/105155284-3a50e200-5b2c-11eb-8c3d-50c956105f2d.png">

The following code does not produce errors in fsi either:
```fsharp
type I =
    abstract M1: int -> [<A>] int * int // expecting error on `A`
```
```
type I =
  interface
    abstract member M1 : int -> int * int
  end
```

**Comment by dsyme** [comment] 2022-04-04 15:38
Duplicate of https://github.com/dotnet/fsharp/issues/462

**Closed by dsyme** 2022-04-04 15:38 UTC
Labels: Bug, Area-Compiler, Impact-Low
