### ISSUE TITLE
FS0243 - Unrecognized option: '--realsig-'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#17561] opened 2024-08-19 15:31 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FS0243---Unrecognized-option:---realsig/10721916)._

---
[severity:I'm unable to use this version] [regression]
I upgraded from VS 2022 17.10.4 to 17.11.0 and now when I build my solution (either in the IDE or via build agent VSBuild task), the build fails with the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	FS0243	Unrecognized option: '--realsig-'	Semaphore.Accelerus.Fs.UI.Core	C:\Development\Accelerus\Accelerus\Semaphore.Accelerus.Fs.UI.Core\FSC	1	

There are 4 F# / Fable projects in the solution and all 4 report the same error.

---
#### Feedback Bot on 8/14/2024, 09:31 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment] 2024-08-19 15:35
Same as
https://developercommunity.visualstudio.com/t/F-projects-fail-to-build/10722863?sort=newest&topics=visual+studio+2019&WT.mc_id=WD-MVP-5003763

**Comment by vzarytovskii** [comment] 2024-08-19 17:20
Turns out it's a bug when options are passed anyway to the underlying compiler, even if it doesn't support it (17.11 passes realsig- and 17.12 will pass realsig+). Fix would be to not pass the "default" one, and rely on compiler taking care of it. 
We should backport the fix to 17.11.

**Comment by baronfel** [comment] 2024-08-19 17:25
I was looking at this too, and I think it's maybe a bit more fundamental - FSharp in VS loads targets from VS but the compiler from the SDK. Those shouldn't ever be mismatched like that - we should keep targets + compiler in alignment for compatibility/understandability purposes. I was talking to @jaredpar and @rainersigwald earlier today and this split confused all of us. Roslyn allows choosing which one you want by way of a package that sets certain properties to load targets and compiler references, perhaps that could be a way forward?

**Comment by vzarytovskii** [comment] 2024-08-19 17:30
> and this split confused all of us

Are you referring to this issue or something else?

**Comment by baronfel** [comment] 2024-08-19 17:33
@TheAngryByrd gave me a binlog of this issue and I was taking a look, and brought Jared and Rainer on because I had questions about how Roslyn solved this same 'tearing' problem.

**Comment by jaredpar** [comment] 2024-08-19 19:01
> FSharp in VS loads targets from VS but the compiler from the SDK. Those shouldn't ever be mismatched like that - we should keep targets + compiler in alignment for compatibility/understandability purposes

There are three components to a build: targets, task and tool. Where is the build task loaded from?

**Comment by baronfel** [comment] 2024-08-19 19:30
In the binlog I was looking at the Task was loaded from VS as well. So you have

| Component | Location | 
| - | - |
| Targets | VS |
| Task | VS | 
| Compiler | SDK |

**Comment by KevinRansom** [comment] 2024-08-19 19:35
@jaredpar the issue is much more straightforward than that.

You are correct that when executing within VS and under MSBUILD we use the targets and build task from Visual Studio.  We do this because we allow the project file to specify the desktop version of the tools, or the sdk version of the compiler.

This is necessary because groan!!!!  ... 'TypeProviders'    there used to exist and probably still do, projects dependent on TPs with only a desktop framework build.

However, we have known of this issue and when we update the build task, we ensure that it does not add switches, not specifically mention in the project or targets file.  Unfortunately, when I updated the build task, I forgot to do it right.  Copy paste error on my part, I'm afraid.

I will do a targeted fix to ensure the build task does not gratuitously add switches, the compiler knows it's defaults the build task shouldn't manage that.

Thanks

Kevin

**Comment by KevinRansom** [comment] 2024-08-19 19:38
And longer term, I want to remove the desktop version of the F# Compiler and FSI from Visual Studio, somehow I was too late to remove it from this autumns release, but maybe next year I will be able to push it through.

**Comment by KevinRansom** [comment] 2024-08-21 02:06
This is fixed by:

https://github.com/dotnet/fsharp/pull/17577
https://github.com/dotnet/fsharp/pull/17563

**Closed by KevinRansom** 2024-08-21 02:06 UTC
Labels: Bug, Impact-High, Area-ProjectsAndBuild

**Comment by nbevans** [comment] 2024-08-28 10:37
> And longer term, I want to remove the desktop version of the F# Compiler and FSI from Visual Studio, somehow I was too late to remove it from this autumns release, but maybe next year I will be able to push it through.

That sounds terrifying. You're removing the legacy version of F#?!

**Comment by vzarytovskii** [comment] 2024-08-28 10:44
> > And longer term, I want to remove the desktop version of the F# Compiler and FSI from Visual Studio, somehow I was too late to remove it from this autumns release, but maybe next year I will be able to push it through.
> 
> That sounds terrifying. You're removing the legacy version of F#?!

Desktop compiler, yes. There's no reason to not use CoreCLR version really.

**Comment by nbevans** [comment] 2024-08-28 10:45
> > > And longer term, I want to remove the desktop version of the F# Compiler and FSI from Visual Studio, somehow I was too late to remove it from this autumns release, but maybe next year I will be able to push it through.
> > 
> > 
> > That sounds terrifying. You're removing the legacy version of F#?!
> 
> Desktop compiler, yes. There's no reason to not use CoreCLR version really.

We have 100,000s of lines of net48 code. A sudden removal of F# support of would be catastrophic?

**Comment by vzarytovskii** [comment] 2024-08-28 10:59
> > > > And longer term, I want to remove the desktop version of the F# Compiler and FSI from Visual Studio, somehow I was too late to remove it from this autumns release, but maybe next year I will be able to push it through.
> > > 
> > > 
> > > That sounds terrifying. You're removing the legacy version of F#?!
> > 
> > 
> > Desktop compiler, yes. There's no reason to not use CoreCLR version really.
> 
> We have 100,000s of lines of net48 code. A sudden removal of F# support would be catastrophic?

It's only compiler, CoreCLR can target net48. We ship two compilers, one which is built with TFM net472, and one for net8 (net9 in couple of months). You can use both to build for any supported TFM (net4, net5, 6, 7, 8). We want to leave one, the one which is built for net8 (9), this + hosting out of process in VS will allow us to use more modern BCL/Runtime features.

**Comment by vzarytovskii** [comment] 2024-08-28 11:10
> Are you referring to fsc.exe? We don't call that directly, no. And our .fsproj typically start with `<Project Sdk="Microsoft.NET.Sdk">` but use `<TargetFramework>net48</TargetFramework>` so I would assume that's already using the CoreCLR compiler then based upon what you wrote?
> 

It might, or might not, depending on the project properties. I think we prefer CoreCLR by default.

> But we do use fsi.exe and fsiAnyCpu.exe for scripting on customer environments. But this is a lesser concern and could be migrated to `dotnet fsi` more easily I think.

That's fine, they can also be transparently (without any changes) be "substituted" by coreclr versions.

In other words, I don't expect anything change really for customers. We will be doing some thorough testing before we roll it out.

**Comment by nbevans** [comment] 2024-08-28 11:15
> It might, or might not, depending on the project properties. I think we prefer CoreCLR by default.

I don't see any project properties that could possible influence the compiler selection:

<img width="708" alt="image" src="https://github.com/user-attachments/assets/e1012741-4996-430a-a5c8-f48ce3d30ffd">

So it's likely using the default? A few other projects are using a lot of WebSharper 4.x code, so maybe that's a bit different though.

**Comment by nbevans** [comment] 2024-08-28 11:17
> This is fixed by:
> 
> #17577 #17563

Whilst we wait for those fixes to be released, how do we rollback or implement a workaround? My team can only rollback to 17.11 which still contains the issue.

**Comment by vzarytovskii** [comment] 2024-08-28 11:24
> > This is fixed by:
> > #17577 #17563
> 
> Whilst we wait for those fixes to be released, how do we rollback or implement a workaround? My team can only rollback to 17.11 which still contains the issue.

@KevinRansom is working on porting it back 17.11, it needs to go through approval

**Comment by nbevans** [comment] 2024-08-28 11:26
> > It might, or might not, depending on the project properties. I think we prefer CoreCLR by default.
> 
> I don't see any project properties that could possible influence the compiler selection:
> 
> <img...>
> So it's likely using the default? A few other projects are using a lot of WebSharper 4.x code, so maybe that's a bit different though.

I set up SysInternals ProcMon with filters on `fsc.exe` `fsi.exe` `fsianycpu.exe` and ran the build of our .sln - there was no activity recorded. I then executed `fsi.exe` via Explorer and there was loads of activity recorded. Looks like our .sln is not using those "desktop compiler tools" as part of its build process then?

**Comment by vzarytovskii** [comment] 2024-08-28 11:27
> > > It might, or might not, depending on the project properties. I think we prefer CoreCLR by default.
> > 
> > 
> > I don't see any project properties that could possible influence the compiler selection:
> > <img...>
> > So it's likely using the default? A few other projects are using a lot of WebSharper 4.x code, so maybe that's a bit different though.
> 
> I set up SysInternals ProcMon with filters on `fsc.exe` `fsi.exe` `fsianycpu.exe` and ran the build of our .sln - there was no activity recorded. To verify my filters were valid and working, I then executed `fsi.exe` via Explorer and there was loads of activity recorded. Looks like our .sln is not using those "desktop compiler tools" as part of its build process then?

Yeah, it probably uses dotnet/msbuild which launches `fsc.dll`

**Comment by nbevans** [comment] 2024-08-28 11:29
> > > > It might, or might not, depending on the project properties. I think we prefer CoreCLR by default.
> > > 
> > > 
> > > I don't see any project properties that could possible influence the compiler selection:
> > > <img...>
> > > So it's likely using the default? A few other projects are using a lot of WebSharper 4.x code, so maybe that's a bit different though.
> > 
> > 
> > I set up SysInternals ProcMon with filters on `fsc.exe` `fsi.exe` `fsianycpu.exe` and ran the build of our .sln - there was no activity recorded. To verify my filters were valid and working, I then executed `fsi.exe` via Explorer and there was loads of activity recorded. Looks like our .sln is not using those "desktop compiler tools" as part of its build process then?
> 
> Yeah, it probably uses dotnet/msbuild which launches `fsc.dll`

Not seeing fsc.dll in ProcMon during a .sln build either

**Comment by TheAngryByrd** [comment] 2024-09-19 13:24
@KevinRansom @vzarytovskii do you know if this was released in a 17.11.x hotfix? I can't find [a mention in the release notes](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#version-17114) and my team has conflicting reports on still hitting this.

**Comment by vzarytovskii** [comment] 2024-09-19 13:31
I think it is. @KevinRansom PR was merged, right?

**Comment by KevinRansom** [comment] 2024-09-19 18:04
@TheAngryByrd - two questions:
1. Do you have examples of it working and failing?
2. can i get a binlog where it succeeds and where it fails:
````
msbuild /t:rebuild /bl
````

As far as I can tell, buildtools and vs have both been updated for **vs 17.11.4**.
At least the code in them looks how I would expect it to look.

You can email them to me via github my alias at microsoft is kevinr

Thanks

Kevin

**Comment by KevinRansom** [comment] 2024-09-19 18:55
@TheAngryByrd ---
I have just confirmed with a clean vm that VS **17.11.0** reproduces your issue, and when we upgrade to **vs 17.11.3** or **vs 17.11.4** the issue is fixed.

**Comment by TheAngryByrd** [comment] 2024-09-20 20:11
Yep I got it to work. Thanks for checking! I think it's one of those "clean the `bin/`and `obj/` folders you dummy" moments.
