### ISSUE TITLE
LineLens leaves stray annotations at incorrect locations in the file

### ISSUE THREAD

**Issue by chadunit** [dotnet/fsharp#5960] opened 2018-11-28 03:59 UTC
LineLens leaves stray annotations at incorrect locations in the file.

Below is a repro GIF using the FSharpPlus solution cloned from https://github.com/fsprojects/FSharpPlus.git

My actions were:

Pressed CTRL+END to navigate to the end of file. This appeared to affix the original top-of-file annotations to the same screen locations at the end of file, where they stuck around even after some scrolling and editing.

Highlighted a block of code, pressed CTRL+K CTRL+C to comment it out, then pressed DEL to delete it. This appeared to leave behind some concatenated annotations which then persisted through attempts at deleting and editing.

![vs codelens 2](https://user-images.githubusercontent.com/25489524/49127974-0c92ea00-f28f-11e8-98be-d7b35dafcca0.gif)

#### Expected behavior

Extraneous LineLens annotations should not appear in incorrect locations.

#### Actual behavior

Extraneous LineLens annotations appear in incorrect locations.

#### Known workarounds

Close and reopen the file.

#### Related information 

Visual Studio Community 2017 Version 15.9.2

Visual F# Tools nightly 15.8.20181127.3

**Comment by realvictorprm** [comment] 2018-11-28 13:23
This is a duplicate of #5138 for which I already created a fix (which is also approved but not approved by enough persons yet).

**Comment by cartermp** [comment] 2018-11-28 16:40
Closing as dupe of #5138, thanks @realvictorprm

**Closed as completed by cartermp** 2018-11-28 16:40 UTC

**Comment by chadunit** [comment] 2018-11-28 17:37
Great to hear there's already a pending fix, hope it can make it into a nightly at some point, this one's fairly distracting.

**Comment by realvictorprm** [comment] 2018-11-28 18:16
I can’t deny that, the fix is waiting for approval from Kevin I think.

Von: chadunit
Gesendet: Mittwoch, 28. November 2018 18:37
An: Microsoft/visualfsharp
Cc: Victor Peter Rouven Müller; Mention
Betreff: Re: [Microsoft/visualfsharp] LineLens leaves stray annotations atincorrect locations in the file (#5960)

Great to hear there's already a pending fix, hope it can make it into a nightly at some point, this one's fairly distracting.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
