### ISSUE TITLE
Normal editing of open F# files in 72 seconds causes 75MB of allocations due to synactic colorization

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#6492] opened 2019-04-11 01:07 UTC
![image](https://user-images.githubusercontent.com/6309070/55923685-4ff55180-5bbb-11e9-9f35-320664c82e21.png)

Although 75MB of data isn't terribly large, what's worrying is that we're re-classifying things.

75MB also seems like a lot.

**Comment by dsyme** [comment] 2019-04-12 19:03
I don't think we should consider transient allocations a measure here - we should only measure something user-perceptible.

**Comment by cartermp** [comment] 2019-04-12 19:12
It ends up mattering. We're no longer punishing the LOH, but we do have a problem where too much data gets promoted to gen2 over time, eventually leading to UI pauses. It's nowhere near as bad as before, but it's still there. Little things like this, especially if data is cached, add up. The short answer is we should consider _all_ allocations we do to be a problem, especially if they don't logically need to happen, until we can get proof under profiling that they aren't a problem.

Speaking with @TIHan, this could be related to Roslyn calling the classification API a lot, in which case we couldn't do anything about it. But I need to dig back into this part of the trace to know for sure.

**Comment by dsyme** [comment] 2019-04-12 20:11
> The short answer is we should consider all allocations we do to be a problem, especially if they don't logically need to happen, until we can get proof under profiling that they aren't a problem.

If we took that approach, the F# compiler would end up being C code, to no user benefit (because we haven't linked the allocations to any user-perceptible measure).

Further, you can write really, really slow C code that doesn't allocate.  And that can easily happen when you try to remove allocations ("make everything a struct") and end up copying data like crazy.

Slowness is bad.   We should care about slowness.  

> It ends up mattering. We're no longer punishing the LOH, but we do have a problem where too much data gets promoted to gen2 over time, eventually leading to UI pauses. It's nowhere near as bad as before, but it's still there. Little things like this, especially if data is cached, add up. The short answer is we should consider all allocations we do to be a problem, especially if they don't logically need to happen, until we can get proof under profiling that they aren't a problem.

What you are saying is that objects that make it into Gen 1 and Gen 2 are bad.  So it's not the allocations per se - it's the allocations of promoted data.  That's a very different problem and I'd agree there's evidence to link those to GC pauses.  But the graph above doesn't show promoted data does it?  If there was a way we could get that I'd be more interested

**Comment by cartermp** [comment] 2019-04-12 20:14
@dsyme I'm aware of theoretical issues here, but this is based on weeks of profiling after addressing LOH allocation issues and not speculation. The fundamental problems we have now are that too many things make their way to gen2. We may have to dive in to find out why, but the fundamental problem is that we are _concretely_ doing too much stuff and it becomes difficult to manage over time.

This is one (small) case where we're allocating 75MB over 72 seconds when we logically shouldn't be allocating much from that specific code path. It may be that we can't control it.

**Comment by cartermp** [comment] 2019-04-12 20:17
Just to add more overall context, this was the GC stats in that short snapshot of editing already-opened files after using VS for about an hour in our solution and noticing slowdowns and UI pauses:

![image](https://user-images.githubusercontent.com/6309070/56063779-1b050e00-5d25-11e9-8fe6-d2f101797a5f.png)

![image](https://user-images.githubusercontent.com/6309070/56063798-26f0d000-5d25-11e9-969c-2fa1ad8dc0af.png)

Based on seeing similar results over the past few weeks, I'm interpreting this as, "we're just doing too much stuff".

**Comment by dsyme** [comment] 2019-04-13 00:03
That's great data, much more useful

I interpret it as "Four Gen 2 collections with mean 1 second pauses happened".  Those pauses are the only thing the user notices here. 

The question is then what causes those Gen2 collections. My understanding is that we can happily allocate transient data in Gen0 and Gen1 for eternity and never trigger a Gen2.  

So allocations **in general** don't cause those Gen2 collections - those must surely be caused by growth and churn in long lived data that actually enters Gen2.  If we could somehow restrict the views of allocated objects to those that had ever entered Gen2 it would be much, much more useful.  Transient allocations which never enter Gen2 are not the issue here.

**Comment by dsyme** [comment] 2019-04-13 00:09
I notice all 4 Gen2 collections are "Induced" - I haven't read it carefully but the InducedNotForced ETW events are described in Maoni's blog here: https://blogs.msdn.microsoft.com/maoni/2014/12/25/gc-etw-events-2/

**Comment by dsyme** [comment] 2019-04-13 00:13
Also I notice we do have a `GC.Collect` in our codebase when solutions are unloaded - I presume a GC.Collect _might_ cause an `Induced` Gen2 collection.  But I assume you didn't unload any solutions in that snippet

Do you think you were noticing the Gen1 collections too?  A max pause of 33msec would be noticeable in scrolling text I suppose, but it seems below the threshold when typing, I'm not sure though, would be good to get a measure on that.

**Comment by dsyme** [comment] 2019-04-13 00:15
Note this comment:

> The easiest way to get to the bottom of induced GCs is to get the stacks for this event called GC/Triggered which is fired every time a GC is triggered. Let's click on the Events view and in the Filter textbox ....

Getting those stacks for those Induced Gen2 would be very useful

**Comment by vzarytovskii** [comment] 2023-11-10 15:32
Lots have changed since, I am going to close it for now, since we're focusing on out-of-proc hosting in VS as well as LSP for next iteration.

**Closed by vzarytovskii** 2023-11-10 15:32 UTC
Labels: Feature Improvement, Area-LangService-Colorization
