### ISSUE TITLE
Typing / sending unicode characters in FSI is broken

### ISSUE THREAD

**Issue by RonaldSchlenker** [dotnet/fsharp#7733] opened 2019-10-15 07:59 UTC
Since F# 4.7, typing or sending unicode chars in FSI results not in the typed char, but in an unexpected one.

Example:

Typing ```let über = 42;;``` in F# 4.5 works; in F# 4.7, it doesn't.

![image](https://user-images.githubusercontent.com/472222/66811985-4f56c280-ef32-11e9-9953-75a3cb754fdf.png)

The behavior is also present using VSCode + Ionide (sending text via Alt ENTER).

**Comment by ronaldschlenker** [comment] 2019-12-18 07:38
Any news on this one? This breaks quite a lot of my working scripts.

**Comment by forki** [comment] 2020-01-18 08:14
@KevinRansom any chance you can look at this? This is really annoying in languages that are not English

**Comment by cartermp** [comment] 2020-02-18 22:03
Another case here: https://developercommunity.visualstudio.com/content/problem/911485/bad-unicode-encoding-from-literal.html

Likely the same underlying issue. We'll treat this as in scope for .NET 5 probably.

**Comment by cartermp** [comment] 2020-02-18 22:03
Note that FSI in VS doesn't have this issue.

**Comment by ronaldschlenker** [comment] 2020-02-21 07:48
In Rider, it also works:

![image](https://user-images.githubusercontent.com/472222/75014558-d7bc1580-5486-11ea-9be4-fecb53f09ab8.png)

See also: https://twitter.com/auduchinok/status/1207260258483286021?s=20

> 
>Eugene Auduchinok
>@auduchinok
>18. Dez. 2019
>They seem to use a different fsi console integration mode, while we're using the same one as in VS.
>

**Comment by larjo** [comment] 2020-11-12 07:02
With F# 5.0 and a freshly installed net 5.0 I still get the error. It is not exactly the same though. It seems the keys I type gets mistranslated in a different way:
![image](https://user-images.githubusercontent.com/1218329/98904724-73306300-24ba-11eb-9a3f-d6351970f74f.png)

However, if I change the code pages when calling fsi it works!:
![image](https://user-images.githubusercontent.com/1218329/98906025-affd5980-24bc-11eb-92e8-f9800ea1d83a.png)

**Comment by larjo** [comment] 2020-11-12 07:57
And with this setting it works in vscode + ionide as well:
```
  "FSharp.fsiExtraParameters": [
    "--fsi-server-input-codepage:28591",
    "--fsi-server-output-codepage:65001"
  ]
```

**Comment by wildart** [comment] 2020-12-08 03:07
The problem persist in F# 5.0. If you paste a string that contains larger then 51 symbol, all Unicode symbols starting from 52st position substituted with several instances of '\uFFFD'.

```
Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→";;
val it : string = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→"

// string that was pasted: "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→"
> "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→���";;
val it : string = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→���"

> let ustr = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→";;
val ustr : string = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→"

// string that was pasted: let ustr = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→";;
> let ustr = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→���";;
val ustr : string = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→���"

> →→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→;;

  →→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→;;
  ^

/stdin(5,1): error FS0010: Unexpected character '→' in interaction

> →→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→��� 

// string that was pasted: let ustr = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→ü";;
> let ustr = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→��";;
val ustr : string = "→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→→��"
```

**Comment by wildart** [comment] 2020-12-08 04:32
It looks like the bug related to a terminal emulator. I got the this problem in VS Code internal terminal and Jupyter web terminal.

I run `ReadLineConsole.ReadLine` function of current `console.fs` file ([slightly modified version to show bad output after Console.ReadKey call](https://gist.github.com/wildart/bec4f1e4a7bb1878e142b90f8ee1db01#file-console-fsx-L427-L439)), and got the error in VS Code internal terminal.

![vs-code](https://user-images.githubusercontent.com/38350/101439753-39991f00-38e3-11eb-9a1d-4b4c7fbdd3f5.png)

But when I'm running the same function in [Alacritty terminal](https://github.com/alacritty/alacritty), everything is ok.

![alacritty](https://user-images.githubusercontent.com/38350/101439845-706f3500-38e3-11eb-87e2-47d2ef2ba5fe.png)

**Comment by bonjune** [comment] 2021-08-08 10:36
I think it has something to do with the method used to send from the editor to interactive shell.
I suspect a buffer holding the characters.


I tested with Korean unicode characters.

I sent the string of Korean characters to F# interactive using Alt + Enter (send to F# interactive shortcut)

<img width="796" alt="Screen Shot 2021-08-08 at 7 32 23 PM" src="https://user-images.githubusercontent.com/7106939/128629026-c71bd875-bdba-4e7a-82e5-67822da6e70e.png">

<img width="1152" alt="Screen Shot 2021-08-08 at 7 32 47 PM" src="https://user-images.githubusercontent.com/7106939/128629040-9a016f5f-056a-4ab9-a156-8f4a851c7ed9.png">

And it failed to send those when it is longer than a certain length.

<img width="457" alt="Screen Shot 2021-08-08 at 7 34 50 PM" src="https://user-images.githubusercontent.com/7106939/128629095-bd02eff3-be76-43c8-8c00-3a81623dd75c.png">

<img width="520" alt="Screen Shot 2021-08-08 at 7 35 01 PM" src="https://user-images.githubusercontent.com/7106939/128629100-2e1500d7-7d3d-4539-9500-376dbeed571e.png">

The bug here is that, after a certain position of characters, all the characters are turned into broken unicode.

**Comment by cartermp** [comment] 2021-08-08 17:20
@bonjune this issue still persists for umlauts. As you noticed, hangul doesn't have an issue in `dotnet fsi` proper. But if you try to do something like `let ümlaut = 12` it'll have an encoding issue.

<img width="175" alt="image" src="https://user-images.githubusercontent.com/6309070/128640163-86d51af2-8065-4da4-89e1-10b178675493.png">

**Comment by bonjune** [comment] 2021-08-09 09:55
I tried sending the same codes to F# Interactive in Rider on MacOS. It worked well without producing any broken hangul characters. So I suppose my issue is from VSCode + Ionide.

**Comment by cartermp** [comment] 2021-08-09 16:17
VSCode has some quirks I think. @Krzysztof-Cieslak may be able to give a hint as to some of them.

**Comment by dsyme** [comment] 2022-04-27 07:05
I finally looked into this long standing regression.

[This change](https://github.com/dotnet/fsharp/compare/Visual-Studio-2019-Version-16.0..Visual-Studio-2019-Version-16.3#diff-12467ce4bfeeafc44e30497d5660154b11cb2b13a9a29d29bd3fa24fe33706a9L27) looks suspicious - `fixNonUnicodeSystemConsoleReadKey` should be considered false and it appears someone falsely thought `!fixNonUnicodeSystemConsoleReadKey` meant `not fixNonUnicodeSystemConsoleReadKey`.

**Comment by dsyme** [comment] 2022-04-27 07:09
Fixed by https://github.com/dotnet/fsharp/pull/13054

**Closed** 2022-04-27 12:40 UTC
Labels: Bug, Regression, Area-FSI, Impact-Medium
