### ISSUE TITLE
Use of generic zero causes System.InvalidProgramException runtime error

### ISSUE THREAD

**Issue by hvester** [dotnet/fsharp#7605] opened 2019-09-20 13:10 UTC
The following program compiles, but throws "System.InvalidProgramException: 'JIT Compiler encountered an internal limitation.'" when executed.

```
open Microsoft.FSharp.Data.UnitSystems.SI.UnitSymbols

let foo (x : float<'u>) =
    let y = 0.0<_>
    let z = y + x
    printfn "%f" z

[<EntryPoint>]
let main argv =
    foo 1.0<m>
    0
```

Type of `y` is inferred to be float<'v>, but still `let z = y + x` does not result in compilation error.

**Repro steps**

Run above program

**Expected behavior**

Program should print "1.000000" and exit with code 0

**Actual behavior**

System.InvalidProgramException is thrown.

**Known workarounds**

If `let y = 0.0<_>` is replaced with `let y = LanguagePrimitives.GenericZero` then everything works as expected.

**Related information**

* Operating system: Windows 10
* Reproduces both with .NET Core 2.2 and .NET Framework 4.7.2
* IDE: Visual Studio 2019 Version 16.2.5

**Comment by Happypig375** [comment] 2019-09-21 13:28
Not reproducible in F# Interactive 10.5.0.0 for F# 4.6.

**Comment by cartermp** [comment] 2019-09-21 16:31
This doesn't reproduce for me in F# interactive, but it does in a console app. So there's definitely a bug here. cc @dsyme as I haven't a clue about the history of this part of the language

**Comment by dsyme** [comment] 2019-09-27 22:34
How odd.  Will take a look

**Comment by gsomix** [comment] 2021-11-02 18:18
Cannot to reproduce on .NET 6 RC2.

```
> dotnet run -c Release
1.000000

> dotnet --version
6.0.100-rc.2.21505.57
```

**Comment by vzarytovskii** [comment] 2021-11-02 18:20
Going to close it, since there's no repro (and the issue is 2yrs old).

**Closed by vzarytovskii** 2021-11-02 18:20 UTC
Labels: Bug, Area-Compiler, Impact-Medium

**Comment by hvester** [comment] 2021-11-02 20:36
Seems to be indeed fixed in .NET 6 RC2. Just out of curiosity I tested with .NET 5.0 SDK (v5.0.402) and it generates invalid IL.
