### ISSUE TITLE
Regression: Cannot use two or more open sessions in FCS 43.7.200+

### ISSUE THREAD

**Issue by nightroman** [dotnet/fsharp#16118] opened 2023-10-12 11:18 UTC
Regression: Cannot use two or more open sessions in FCS 43.7.200+

Please find attached two projects, new (bad), old (good):
[_231012_1018-43.7.200-regression.zip](https://github.com/dotnet/fsharp/files/12880755/_231012_1018-43.7.200-regression.zip)

**Last good packages, see the project folder `old_good`**
`dotnet run` works fine, it creates and invokes two sessions.

```
    <PackageReference Include="FSharp.Core" Version="7.0.0" />
    <PackageReference Include="FSharp.Compiler.Service" Version="42.7.101" />
```

**Regression starts with these packages, see the project folder `new_bad`**
`dotnet run` fails to invoke the second session.

```
    <PackageReference Include="FSharp.Core" Version="7.0.200" />
    <PackageReference Include="FSharp.Compiler.Service" Version="43.7.200" />
```

**Error**
```
[Loading C:\Users\roman.kuzmin\source\repos\FSCS\43.7.200-regression\new_bad\Test2\Test4.fsx]
System.TypeLoadException: Could not load type 'FSI_0001.Test3' from assembly 'FSI-ASSEMBLY, Version=0.0.0.32767, Culture=neutral, PublicKeyToken=null'.
   at <StartupCode$FSI_0002>.$FSI_0002_Test4$fsx.main@()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
```

**Known workarounds**

Close all opened sessions before opening and invoking a new session.
(But in my case using 2+ open sessions is the design, not a mistake).

**Related information**

* Operating system - Windows 10
* .NET Runtime kind .NET Core 7
* Editing Tools - Visual Studio 2022, 17.7.5

**Comment by vzarytovskii** [comment] 2023-10-12 15:58
@KevinRansom can you look into it? Sounds about related to the multiemit fix you did earlier

**Comment by KevinRansom** [comment] 2023-10-13 17:51
I am pretty sure that I know what caused it, and it should be relatively easily fixable.  I believe it was caused by the change to using assembly versioning rather than assembly naming to enable fsi internals visibility.

**Comment by nightroman** [comment] 2023-10-18 11:01
When is the fix and updated package expected approximately?

**Comment by vzarytovskii** [comment] 2023-10-18 11:05
> When is the fix and updated package expected approximately?

Probably together with 8.0.200, not entirely sure when it's going to be released. 8.0.100 is locked down, and it won't hit the fix bar for 7.0.xxx.

**Comment by KevinRansom** [comment] 2023-10-19 00:03
I have a fix, it is a depressingly tiny fix.

The issue was assembly resolution under multi-emit fell back to simple name matching which is not super helpful when parts of the script exist in many different assemblies with the same simple name, varying only by version number.

https://github.com/dotnet/fsharp/pull/16139

**Comment by psfinaki** [comment] 2023-10-20 11:10
Closing as been fixed by the PR above.

**Closed by psfinaki** 2023-10-20 11:10 UTC
Labels: Bug, Needs-Triage

**Comment by nightroman** [comment] 2023-10-25 05:00
@vzarytovskii @KevinRansom 
The PR with the fix was merged, great. But I have tried the just released FSharp.Compiler.Service 43.7.401 and the problem is still there. Is it how it should be?

**Comment by vzarytovskii** [comment] 2023-10-25 05:21
> @vzarytovskii @KevinRansom 
> 
> The PR with the fix was merged, great. But I have tried the just released FSharp.Compiler.Service 43.7.401 and the problem is still there. Is it how it should be?

It was not backported to that version. Only to 43.8.xxx
