### ISSUE TITLE
Wrong `when` expression parsing

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#9762] opened 2020-07-23 17:36 UTC
The `when` expression in the following code is expected to be parsed as a sequence of `ignore true` and `true`, and the latter should be what the whole expression evaluates to.
```fsharp
match () with
| _ when
        ignore true
        true ->
    ()
```

The sequence expression is instead parsed as an application, `ignore true true`, and producing an error:
<img width="269" alt="Screenshot 2020-07-23 at 20 35 05" src="https://user-images.githubusercontent.com/3923587/88318840-04b97080-cd24-11ea-9ea3-a76c296d66c5.png">
```
idea-sandbox\config\scratches\scratch_4.fsx(3,9):
  error FS0003: This value is not a function and cannot be applied.
```

[AST Viewer](https://jindraivanek.gitlab.io/ast-viewer/#?code=LYQwLgxgFgBAFAShgdwJZigKAD4wPopQCmAdpjBZRagOYkD2ATkTGIwK5HlWVucwBaAHzcKiTEA&defines=Q&filename=Q)

This is similar to #7741.

**Comment by TIHan** [comment] 2020-07-28 10:12
Don't know if it's a bug yet or not. Will need to look at the design spec.

**Comment by auduchinok** [comment] 2020-07-28 11:56
F# 4.1 spec doesn't cover this particular case in the Lexical Filtering part. It looks like a SeqBlock is missing for `when` expressions and should be added, because currently such expressions are clearly not being parsed as the rest of expressions with the light syntax enabled.

**Comment by dsyme** [comment] 2020-08-24 17:59
The expression after a `when` must be a `declExpr` which is a category of expression that excludes sequential `expr1; expr2`

```
patternGuard: 
  | WHEN declExpr 
     { Some $2 }

  | /* EMPTY */
     { None }
```

So this would be considered by design and needs to be clarified in the specification.

The workaround is to use `(...)`

```fsharp
match 1 with
| _ when
       (ignore true
        true) ->
    ()
```

**Comment by dsyme** [comment] 2020-08-24 18:03
I'll close this as by design, I've noted above that a spec clarification is needed

**Closed by dsyme** 2020-08-24 18:04 UTC
Labels: Area-Compiler

**Comment by auduchinok** [comment] 2020-09-01 11:17
> The expression after a when must be a declExpr which is a category of expression that excludes sequential expr1; expr2
Could we allow at least the light-syntax implicit seqExpr here? I find it very counter-intuitive when this error is shown on more real-life code samples.

**Comment by dsyme** [comment] 2021-01-11 13:48
I'm not sure what the best approach is here

From a design perspective, it does feel right that the `when` should introduce an offside block, even if a `declExpr` is ultimately required.

But I suspect that making that change would lead to a fairly substantial breaking change - or at least it would be difficult to code to avoid that change.  There are going to be plenty of pathological examples, likely occurring in the real world, as people do tend to use fairly messy formatting after the `when`

In balance I have not yet any real opinion on this beyond "if we can improve it without making a breaking change, then let's do that".

**Comment by auduchinok** [comment] 2021-01-11 14:00
It seems that making more cases allowed than it's now is not a that bad change, though, yes, I agree it may be difficult to code it this properly. I'd happy to try working on it, though, if there's now a chance it could be accepted!
