### ISSUE TITLE
Error: Microsoft.FSharp.targets not found while trying to load F# old style format project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#11554] opened 2021-05-12 16:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error:-MicrosoftFSharptargets-not-foun/1399227)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.10.0 Preview 1.0]
While trying to load F# project which was loadable in 16.10 Preview 1.0 I get error that file Microsoft.FSharp.targets was not found. 

This file in version Preview 1.0 was located in:

`c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\commonextensions\microsoft\fsharp`

but in Preview 2.0 was moved to:

`c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\commonextensions\microsoft\fsharp\Tools`

Project file is in old style format, not in SDK style.

---
#### Feedback Bot on 4/16/2021, 07:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment] 2021-05-12 16:07
I believe that this was caused by this PR: https://github.com/dotnet/fsharp/pull/11390

The PR fixed an issue where `fsc` and friends were not on the path in the VS Developer Command Prompt. Clearly, that had unintended side effects because legacy project files stamp the `FSharpTargetsPath` directly into the project file. This brittle approach does mean that they're broken if we ever change that.

**Comment by cartermp** [comment] 2021-05-12 23:56
Should be resolved by https://github.com/dotnet/fsharp/pull/11558

**Closed by cartermp** 2021-05-12 23:56 UTC
Labels: Area-Setup, Severity-High, regression

**Comment by euphbriggs** [comment] 2021-06-23 21:37
> Should be resolved by #11558

Hey Phillip, thanks for tracking this issue.

I'm experiencing this after upgrading to the latest release version of VS. I also tried it with the last preview version.

What do I need to do to be able to build my load and build my project?

**Comment by euphbriggs** [comment] 2021-06-24 14:27
Updating the fsproj file with this change fixed the issue for me. Hopefully this will help someone else.

![image](https://user-images.githubusercontent.com/20155143/123280364-54716080-d4ce-11eb-9e06-3f7a607af111.png)
