### ISSUE TITLE
A test in F# passes in 16.5.2 but not 16.6.0 Preview 2.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8913] opened 2020-04-09 16:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/977802/a-test-in-f-passes-in-1652-but-not-1660-preview-21.html)._

---
<p>[regression] [worked-in:16.5.2]<br>
A test in F# passes in 16.5.2 but not 16.6.0 Preview 2.1.</p>
<p>A minimal failing example is available here: <a href="https://github.com/dharmaturtle/objectdumptofile/tree/vstestbug">https://github.com/dharmaturtle/objectdumptofile/tree/vstestbug</a></p>
<p>Specifically: <a href="https://github.com/dharmaturtle/objectdumptofile/blob/vstestbug/FSharpTests/Tests.fs">https://github.com/dharmaturtle/objectdumptofile/blob/vstestbug/FSharpTests/Tests.fs</a></p>
<p>The error thrown is:</p>
<blockquote>
<p>System.MissingMethodException : Method not found: ‘Void System.Text.RegularExpressions.Regex…ctor(System.String)’.</p>
</blockquote>
<p>The test fails for the Preview version for the native Test Explorer as well as NCrunch, a 3rd party testing plugin. Both work in the VS non-Preview though.</p>

---
#### Visual Studio Feedback System on 4/7/2020, 02:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment] 2020-04-09 17:01
Possibly related:

https://github.com/dotnet/fsharp/issues/8881
https://github.com/dotnet/fsharp/issues/8743

**Comment by dharmaturtle** [comment] 2020-04-09 17:05
Here are my SDKs:

	C:\Users\dharmaturtle>dotnet --list-sdks
	2.1.700 [C:\Program Files\dotnet\sdk]
	2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
	2.1.801 [C:\Program Files\dotnet\sdk]
	2.2.300 [C:\Program Files\dotnet\sdk]
	2.2.400-preview-010219 [C:\Program Files\dotnet\sdk]
	2.2.401 [C:\Program Files\dotnet\sdk]
	3.0.100 [C:\Program Files\dotnet\sdk]
	3.1.201 [C:\Program Files\dotnet\sdk]
	3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

I don't think it's related to .Net 5, unless VS Preview comes with something built in?

**Comment by cartermp** [comment] 2020-04-09 17:07
@dharmaturtle It could be related, since the same compiler that ships in a .NET SDK is also present in VS, and this includes .NET 5.

**Comment by KevinRansom** [comment] 2020-04-16 07:02
@cartermp, have you been successfull reproducing this issue?  It passes fine on my laptop.

**Comment by cartermp** [comment] 2020-04-16 15:08
@KevinRansom this requires being on the `vstestbug` branch. I can confirm it fails on the latest internal dogfood:

![image](https://user-images.githubusercontent.com/6309070/79472999-6053bf80-7fb9-11ea-9c24-dcae0043800d.png)

Did you run it before you added your fix for the `MissingMethodException`s with type providers?

**Comment by KevinRansom** [comment] 2020-04-16 17:33
@brett, okay mate, thanks

**Comment by dharmaturtle** [comment] 2020-04-26 21:13
It now passes in VS 16.6.0 Preview 4.0, but I just discovered that it fails at run time in v16.5.4 despite tests passing 🙄

Oh well, I'll assume that whatever broke between 16.5.2 and 16.5.4 got fixed with #8971. Thanks peeps!

**Comment by cartermp** [comment] 2020-04-27 20:27
Thanks for confirming @dharmaturtle - things all pass in the preview for me as well. I'll close this out and tag it with the 16.6 milestone.

**Closed by cartermp** 2020-04-27 20:27 UTC
Labels: Area-Compiler, bug
