### ISSUE TITLE
FSharp.Compiler.Service for NetStandard 2 uses AssemblyLoadContext that is NetCore

### ISSUE THREAD

**Issue by amieres** [dotnet/fsharp#8721] opened 2020-03-14 21:46 UTC
[This](https://github.com/fsharp/FSharp.Compiler.Service/blob/66d507395f19b75b8ee5b8c6a3f9542a6630965e/src/fsharp/Interactive.DependencyManager/AssemblyResolveHandler.fs#L53) seems incorrect to me:

    #if NETSTANDARD
        let handler = Func<AssemblyLoadContext, AssemblyName, Assembly>(resolveAssemblyNetStandard)
        do AssemblyLoadContext.Default.add_Resolving(handler)

According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-3.1&viewFallbackFrom=netstandard-2.0) `AssemblyLoadContext` is NetCore but not NetStandard.

This causes issues when targeting Mono-Wasm which is NetStandard 2.0 but does not implement `AssemblyLoadContext`.

`AppDomain` is part of [NetStandard 2.0 & 2.1](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain?view=netstandard-2.0)

**Comment by cartermp** [comment] 2020-03-14 23:17
I believe this was resolved in https://github.com/dotnet/fsharp/pull/8677

**Comment by baronfel** [comment] 2020-03-14 23:58
I'll try to get a release out in the next day or two of FCS to roll up these and other fixes.

**Comment by amieres** [comment] 2020-03-15 00:37
I maybe reading it wrong, and if that is the case then please disregard my comment, but I think that change actually introduced the [problem](https://github.com/dotnet/fsharp/pull/8677/commits/95fba818f8385155766b1604395fc398455a0958):

    #if NETSTANDARD

    open System.Runtime.Loader

Those 2 lines contradict each other because `System.Runtime.Loader` is not part of NetStandard but part of NetCore .

**Comment by cartermp** [comment] 2020-03-15 17:02
The change I'm mentioning came after that latest version of FCS - there isn't a fixed FCS available yet. The [entire component](https://github.com/dotnet/fsharp/blob/master/src/fsharp/Interactive.DependencyManager/Interactive.DependencyManager.fsproj) is .NET Standard 2.0, and the System.Runtime.Loader package targets .NET Standard 1.5. You can read about the issue that was fixed here: https://github.com/dotnet/fsharp/issues/8676#issuecomment-595971313

I suspect it is the same problem.

**Comment by amieres** [comment] 2020-03-15 17:17
When looking at the documentation for `System.Runtime.Loader`:

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader?view=netcore-3.1&viewFallbackFrom=netstandard-1.5

I get the message:

> The requested page is not available for .NET Standard 1.5. 

and then get redirected to Net Core 3.1

**Comment by Happypig375** [comment] 2020-03-15 17:33
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader?view=netcore-3.1&viewFallbackFrom=netcore-3.1
>The requested page is not available for .NET Core 3.1.

:trollface:

**Comment by amieres** [comment] 2020-03-15 18:17
Funny, I fixed the link: 

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader?view=netstandard-1.5

**Comment by KevinRansom** [comment] 2020-03-22 00:16
@amieres this works fine on the windows desktop, what happens is we never actually try to load the assemblyloadcontext when running on the desktop.  Because of the way the type loader works this works fine.

On the desktop, you can use assemblyloadcontext, you have to ship the System.Runtime.Loader.dll along with your .exe.

We chose not to require that with fsi, fsc and fcs because AssemblyResolveHandler on the desktop satisfies the scenarios we care about for the desktop fsi.

As for targeting mono-wasm - that is a long way out of scope, but super cool, I suppose the issue is happening when trying to cross compile the fcs.dll and it will likely have an issue failing to load the type.  However, for that scenario, you should ensure that the System.Runtime.Loader nuget package is referenced.  However, if that doesn't work if you can give me repro steps to achieve your failure I can try to figure out some other factorization which will work in the WASM scenario too.

I hope this helps, 

Kevin

**Comment by amieres** [comment] 2020-03-22 18:04
@KevinRansom thanks you for your help.
In my case I'm not even compiling fsc just using the netstandard version on mono-wasm interpreted. When compiling a simple hello-world program I get `The method or operation is not implemented.`
  at `System.Runtime.Loader.AssemblyLoadContext.get_Default ()` which I think may come from this implementation that uses `throw new NotImplementedException ();` in every method:   https://github.com/mono/mono/blob/master/mcs/class/Facades/System.Runtime.Loader/AssemblyLoadContext.cs

When I asked them if they supported AssemblyLoadContext for wasm they said right now they are supporting .net framework not netcore.

Here is the full output that you can test here https://amieres.github.io/WASM.html loading FCS version 34:

```
 Information: 0 : Reactor: 64,352.582 enqueue Unknown.Compile (), length 0
 Information: 0 : Reactor: 64,352.622 --> Unknown.Compile (), remaining 0
 Information: 0 : Reactor: 64,352.763 <-- Unknown.Compile, took 138.585 ms
Failed evalExpression: System.NotImplementedException: The method or operation is not implemented.
  at System.Runtime.Loader.AssemblyLoadContext.get_Default () <0x3e934d8 + 0x00008> in <filename unknown>:0 
  at Interactive.DependencyManager.AssemblyResolveHandler..ctor (Interactive.DependencyManager.AssemblyResolutionProbe assemblyProbingPaths) <0x3e933e0 + 0x00032> in <filename unknown>:0 
  at Interactive.DependencyManager.DependencyProvider..ctor (Interactive.DependencyManager.AssemblyResolutionProbe assemblyProbingPaths, Interactive.DependencyManager.NativeResolutionProbe nativeProbingRoots) <0x3e67540 + 0x0001e> in <filename unknown>:0 
  at Interactive.DependencyManager.DependencyProvider..ctor (Interactive.DependencyManager.NativeResolutionProbe nativeProbingRoots) <0x3e67150 + 0x0000c> in <filename unknown>:0 
  at FSharp.Compiler.CompileOps+TcConfigBuilder.CreateNew (FSharp.Compiler.ReferenceResolver+Resolver legacyReferenceResolver, System.String defaultFSharpBinariesDir, FSharp.Compiler.AbstractIL.ILBinaryReader+ReduceMemoryFlag reduceMemoryUsage, System.String implicitIncludeDir, System.Boolean isInteractive, System.Boolean isInvalidationSupported, FSharp.Compiler.CompileOps+CopyFSharpCoreFlag defaultCopyFSharpCore, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] tryGetMetadataSnapshot) <0x3e015e8 + 0x00318> in <filename unknown>:0 
  at FSharp.Compiler.Driver.main0[a] (a ctok, System.String[] argv, FSharp.Compiler.ReferenceResolver+Resolver legacyReferenceResolver, System.Boolean bannerAlreadyPrinted, FSharp.Compiler.AbstractIL.ILBinaryReader+ReduceMemoryFlag reduceMemoryUsage, FSharp.Compiler.CompileOps+CopyFSharpCoreFlag defaultCopyFSharpCore, FSharp.Compiler.ErrorLogger+Exiter exiter, FSharp.Compiler.Driver+ErrorLoggerProvider errorLoggerProvider, FSharp.Compiler.Driver+DisposablesTracker disposables) <0x3df50e0 + 0x00108> in <filename unknown>:0 
  at FSharp.Compiler.Driver.typecheckAndCompile (FSharp.Compiler.AbstractIL.Internal.Library+CompilationThreadToken ctok, System.String[] argv, FSharp.Compiler.ReferenceResolver+Resolver legacyReferenceResolver, System.Boolean bannerAlreadyPrinted, FSharp.Compiler.AbstractIL.ILBinaryReader+ReduceMemoryFlag reduceMemoryUsage, FSharp.Compiler.CompileOps+CopyFSharpCoreFlag defaultCopyFSharpCore, FSharp.Compiler.ErrorLogger+Exiter exiter, FSharp.Compiler.Driver+ErrorLoggerProvider loggerProvider, Microsoft.FSharp.Core.FSharpOption`1[T] tcImportsCapture, Microsoft.FSharp.Core.FSharpOption`1[T] dynamicAssemblyCreator) <0x3dd1190 + 0x0006c> in <filename unknown>:0 
  at FSharp.Compiler.Driver.mainCompile (FSharp.Compiler.AbstractIL.Internal.Library+CompilationThreadToken ctok, System.String[] argv, FSharp.Compiler.ReferenceResolver+Resolver legacyReferenceResolver, System.Boolean bannerAlreadyPrinted, FSharp.Compiler.AbstractIL.ILBinaryReader+ReduceMemoryFlag reduceMemoryUsage, FSharp.Compiler.CompileOps+CopyFSharpCoreFlag defaultCopyFSharpCore, FSharp.Compiler.ErrorLogger+Exiter exiter, FSharp.Compiler.Driver+ErrorLoggerProvider loggerProvider, Microsoft.FSharp.Core.FSharpOption`1[T] tcImportsCapture, Microsoft.FSharp.Core.FSharpOption`1[T] dynamicAssemblyCreator) <0x3dca230 + 0x00028> in <filename unknown>:0 
  at FSharp.Compiler.SourceCodeServices.CompileHelpers+result@169-6.Invoke (FSharp.Compiler.ErrorLogger+Exiter exiter) <0x3dc9ac0 + 0x00036> in <filename unknown>:0 
  at FSharp.Compiler.SourceCodeServices.CompileHelpers.tryCompile (FSharp.Compiler.ErrorLogger+ErrorLogger errorLogger, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] f) <0x3dc1278 + 0x00094> in <filename unknown>:0 
  at FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ReraiseIfWatsonable (System.Exception exn) <0x3f54890 + 0x00056> in <filename unknown>:0 
  at FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ErrorLogger.ErrorRecovery (FSharp.Compiler.ErrorLogger+ErrorLogger x, System.Exception exn, FSharp.Compiler.Range+range m) <0x3eacae8 + 0x00104> in <filename unknown>:0 
  at FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ErrorLogger.StopProcessingRecovery (FSharp.Compiler.ErrorLogger+ErrorLogger x, System.Exception exn, FSharp.Compiler.Range+range m) <0x3eac650 + 0x000d0> in <filename unknown>:0 
  at FSharp.Compiler.SourceCodeServices.CompileHelpers.tryCompile (FSharp.Compiler.ErrorLogger+ErrorLogger errorLogger, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] f) <0x3dc1278 + 0x000c6> in <filename unknown>:0 
  at FSharp.Compiler.SourceCodeServices.CompileHelpers.compileFromArgs (FSharp.Compiler.AbstractIL.Internal.Library+CompilationThreadToken ctok, System.String[] argv, FSharp.Compiler.ReferenceResolver+Resolver legacyReferenceResolver, Microsoft.FSharp.Core.FSharpOption`1[T] tcImportsCapture, Microsoft.FSharp.Core.FSharpOption`1[T] dynamicAssemblyCreator) <0x3dc02e8 + 0x00044> in <filename unknown>:0 
  at <StartupCode$FSharp-Compiler-Service>.$Service+Compile@1030-1.Invoke (Microsoft.FSharp.Core.Unit unitVar) <0x3daa468 + 0x0001a> in <filename unknown>:0 
  at FSharp.Compiler.AbstractIL.Internal.Library+CancellableModule+delay@746[T].Invoke (System.Threading.CancellationToken ct) <0x3daa258 + 0x0000e> in <filename unknown>:0 
  at FSharp.Compiler.AbstractIL.Internal.Library+CancellableModule.run[a] (System.Threading.CancellationToken ct, FSharp.Compiler.AbstractIL.Internal.Library+Cancellable`1[TResult] _arg1) <0x3daa088 + 0x0005a> in <filename unknown>:0 
  at <StartupCode$FSharp-Compiler-Service>.$Reactor+EnqueueAndAwaitOpAsync@181-2[T].Invoke (FSharp.Compiler.AbstractIL.Internal.Library+CompilationThreadToken ctok) <0x3da9838 + 0x0002a> in <filename unknown>:0 
```

**Comment by KevinRansom** [comment] 2020-03-22 19:20
Can you post the repro, steps, so I can see what is happening locally.

Thanks

Kevin

**Comment by KevinRansom** [comment] 2020-03-22 19:38
@amiers, the System.Runtime.Loader being executed in your example is the reference assembly version.  And the lib version does a type forward to mscorlib, which would presumably fail on mono-wasm.  If you can give me a repro, I will try to figure out a factorization that will not try to load and use AssemblyContext on wasm.

**Comment by amieres** [comment] 2020-03-24 00:18
@KevinRansom 

Here is Repo to reproduce the issue: https://github.com/amieres/WasmRepo/tree/FCS-34.1.1

Please let me know if the instructions are clear enough or not.

**Comment by KevinRansom** [comment] 2020-03-24 00:19
Thank you

**Comment by amieres** [comment] 2020-03-25 13:21
Sorry, the repo was marked private. Now is public.

**Comment by cartermp** [comment] 2020-05-29 17:53
This should be resolved by https://github.com/dotnet/fsharp/pull/8722

**Closed by cartermp** 2020-05-29 17:53 UTC
Labels: Area-Compiler, bug
