### ISSUE TITLE
All my F# projects cannot be loaded anymore by Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#14666] opened 2023-01-26 16:33 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/All-my-F-projects-cannot-be-loaded-anym/10258423)._

---
My F# solution / projects don't load anymore.
Getting these 2 types of error for all projects:

C:\Users\denis\Source\Repos\Crazy Wild Wines\Common\Common.fsproj : error  : The path is not of a legal form.
C:\Users\denis\Source\Repos\Crazy Wild Wines\FastKpis\FastKpis.fsproj : error  : Unrecognized Guid format.

**VS 17.4.4**

**Comment by vzarytovskii** [comment] 2023-01-26 16:44
fyi, I was not able to reproduce it on 17.4.4 on a mixed C#/F# project

**Comment by vzarytovskii** [comment] 2023-02-03 12:58
I was not able to repro it in neiter 17.4, 17.5 or 17.6. Going to close it, until we have a repro

**Closed by vzarytovskii** 2023-02-03 12:58 UTC
Labels: Needs-Repro, Area-VS, Needs-Triage
