### ISSUE TITLE
Offside rule doesn't work for attributes

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#7752] opened 2019-10-19 15:48 UTC
```fsharp
 [<AbstractClass;
  Sealed>] 
type T =
    class end 
```

<img width="214" alt="Screenshot 2019-10-19 at 18 48 11" src="https://user-images.githubusercontent.com/3923587/67147809-093a8f80-f2a1-11e9-900e-d4c6d07ca0aa.png">

<img width="227" alt="Screenshot 2019-10-19 at 18 46 48" src="https://user-images.githubusercontent.com/3923587/67147799-f2943880-f2a0-11e9-8731-71e90298d81d.png">

**Comment by BentTranberg** [comment] 2019-10-20 10:35
You can't expect the syntax inside to follow the same rules as F# in general. Attributes need to be separated with semicolon.

**Comment by auduchinok** [comment] 2019-10-20 10:53
> Attributes need to be separated with semicolon.
The same way that sequential expressions need it. Offside rules make these separators optional unless the modern syntax is disabled.

**Comment by cartermp** [comment] 2019-10-20 16:50
I'd expect this not to require a semicolon. @dsyme should this be a language suggestion?

**Comment by auduchinok** [comment] 2019-10-21 11:33
@cartermp I'd vote for fixing it in another language version, like 4.8 or 5.0, so the tooling would be able to tell if semicolon is needed.

**Comment by dsyme** [comment] 2019-10-22 10:55
> I'd expect this not to require a semicolon. @dsyme should this be a language suggestion?

Yes, this should be an approved-in-principle language suggestions

**Comment by cartermp** [comment] 2019-10-23 17:07
Closing as dupe of https://github.com/fsharp/fslang-suggestions/issues/798

**Closed by cartermp** 2019-10-23 17:07 UTC
