### ISSUE TITLE
Some strange in matching Active Patterns

### ISSUE THREAD

**Issue by greatim** [dotnet/fsharp#9054] opened 2020-04-27 16:57 UTC
I'm testing the actual work of Active Patterns. This is my test code:
```
let (|Str|) (x: int) =
    Console.WriteLine("{0}", x)
    x.ToString()

let Foo(a: int) =
    match a with
    | 10 -> 1
    | Str "9" -> 2
    | Str "8" -> 3
    | _ -> 5
```
I am glad that it is optimized very well, `(|Str|)` will be executed by (0-1) times.
The code it generates is equivalent to:
```
public static int Foo(int a) {
	switch (a)	{
	default:	{
		Console.WriteLine("{0}", a);
		string a2 = a.ToString();
		if (string.Equals(a2, "9"))
			return 2;		
		if (string.Equals(a2, "8"))
			return 3;		
		return 5;
	}
	case 10:
		return 1;
	}
}
```
But when I added the `when` condition, the situation changed.
```
let Foo(a: int) =
    match a with
    | 10 -> 1
    | Str "9" -> 2
    | Str x when x = "8" -> 4
    | Str x when x = "7" -> 5
    | _ -> 5
```
The code it generates like this:
```
public static int Foo(int a) {
	switch (a)	{
	default:	{
		Console.WriteLine("{0}", a);  // one
		string a2 = a.ToString();
		if (string.Equals(a2, "9"))
			return 2;
		if (string.Equals(a2, "8"))
			return 4;
		Console.WriteLine("{0}", a);  // two
		string x = a.ToString();
		if (string.Equals(x, "7"))
			return 5;
		return 5;
	}
	case 10:
		return 1;
	}
}
```
I tested and found.. When I add one `when` condition, the times of  execution  will not increase,  added two, it will be executed once more, and then it will be executed once for each additional one.

Is there any semantic difference between them ( `Str "5"` and `Str x when x = "5"` )?

**Comment by abelbraaksma** [comment] 2020-04-27 22:11
> Is there any semantic difference between them

Yes, they're very different. A so-called when-clause, also known as when-guard, or just guard-clause is free form statement that limits the cases where the case-match is applied. The compiler does not check what you have in the clause, and cannot optimize it for completeness checking (for instance, the clause could involve a current date check, or existence of a file on disk, it doesn't have to do anything with the actual matching case).

The active patterns, in contrast, are evaluated once, assuming you use "normal" active patterns. That is, an active pattern that returns its case names, possibly with a value. For instance:

```f#
let (|Small|Large|) x =
    if x > 0 then Large x
    else Small x

let f value =
    match value with
    | Small x -> printfn "Value %i is small"
    | Large x -> printfn "Value %i is large"
```

The difference with your code being that here, the cases are explicit. Internally, they're translated to `Choice`, and only a single call is made to the active pattern, even though there are two cases.

In your code, you return a string from the integer argument, and compare that to another string. This is then translated as if you wrote a matching pattern on strings (which I try to avoid, as it only ever translates into a bunch of if-statements, as opposed to the table lookup of matching cases). 

A good resource on active patterns, including partial active patterns, can be found in F# For Fun And Profit.

**Comment by greatim** [comment] 2020-04-28 06:00
sometimes  mixed pattern matching brings a easy way for multiple checks . ex:
```
let (|Decrypt|) (encodedText: string) = // [| ... |]

let foo license =
    match license with
    | null | "" -> raise ArgumentNullException()
    | Decrypt [| 1; 2; x |] -> x
    | _ -> 3
```
Reference:
```
let decrypt (encodedText: string) = // [| ... |]

let foo license = 
    match license with
    | null  | "" -> raise ArgumentNullException()
    | _ -> match decrypt license  with
           | [| 1; 2; x |] -> x
           | _ -> 3
```
I prefer the former, If the function is not call  more than once. As `Decrypt` maybe a complex calculation.

> which I try to avoid, as it only ever translates into a bunch of if-statements, as opposed to the table lookup of matching cases
uh, It's a sad story. when I change the code to :
```
let str (x: int) =
    Console.WriteLine("{0}", x)
    x.ToString()

let foo(a: int) =
    match a with
    | 10 -> 1
    | _ -> match str a with
           | "9" -> 2
           | "8" -> 3
           | _ -> 5
```
It also translates into a bunch of if-statements :
```
public static int foo(int a)
{
	switch (a)	{
	default: {
		Console.WriteLine("{0}", a);
		string a2 = a.ToString();
		if (string.Equals(a2, "9"))
			return 2;
		if (string.Equals(a2, "8"))
			return 3;
		return 5;
	}
	case 10:
		return 1;
	}
}
```
I think using 'Equals' by default abandons the table lookup.


> A good, extensive resource on active patterns, including partial active patterns, can be found at Jason Down: http://www.jason-down.com/2017/01/24/f-pattern-matching-part-2-active-patterns/

Thank a lot, for recommending.

**Comment by abelbraaksma** [comment] 2020-04-28 09:51
> It also translates into a bunch of if-statements 

I should've been more explicit. Whenever you use `match` with a type other than a DU, it'll have to be translated into corresponding if-statements. That's why you see so often in F# that data is first translated into DU and any subsequent operations are done on the DU's. These are very efficient age translate into table lookup in the IL. If, instead, you use active patterns, it'll depend how you write the active patterns. They can be closed (all cases are explicit) or open (partial pattern, or a pattern not returning a choice). If possible, try to use closed form patterns.

**Comment by greatim** [comment] 2020-04-29 02:19
> > It also translates into a bunch of if-statements
> 
> I should've been more explicit. Whenever you use `match` with a type other than a DU, it'll have to be translated into corresponding if-statements. That's why you see so often in F# that data is first translated into DU and any subsequent operations are done on the DU's. These are very efficient age translate into table lookup in the IL. If, instead, you use active patterns, it'll depend how you write the active patterns. They can be closed (all cases are explicit) or open (partial pattern, or a pattern not returning a choice). If possible, try to use closed form patterns.

Oh, now I understand what you said. When I use DU, it does Swith conditional jumps through tags, and because tags are sequential small integers, IL will be optimized into jump tables when compiled.

**Comment by cartermp** [comment] 2020-06-20 01:01
I think this can be closed as by design. The nature of APs ultimately can affect what gets emitted here. I think @abelbraaksma's analysis is spot on.

**Closed by cartermp** 2020-06-20 01:01 UTC
Labels: Resolution-By Design
