### ISSUE TITLE
Source link support

### ISSUE THREAD

**Issue by lostmsu** [dotnet/fsharp#9612] opened 2020-07-03 06:45 UTC
**Is your feature request related to a problem? Please describe.**
NuGet recently introduced an official way to ship symbols and sources for packages: [Source Link](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink).

Currently, F# compiler is able to generate a symbol package in `snupkg` format, but it does not appear to be linking sources repository URL and commit hash.

**Describe the solution you'd like**
The following should be enough to produce Source Link info in the resulting `nupkg` when doing `dotnet pack`:

```xml
<DebugSymbols>true</DebugSymbols>
<IncludeSymbols>true</IncludeSymbols>
<SymbolPackageFormat>snupkg</SymbolPackageFormat>
    
<PublishRepositoryUrl>true</PublishRepositoryUrl>
<RepositoryType>git</RepositoryType>
```

**Describe alternatives you've considered**
N/A

**Additional context**
See screenshot
![image](https://user-images.githubusercontent.com/239520/86439675-db299e00-bcbd-11ea-8b14-f8668f3f795a.png)

In case this is actually supposed to work, my `dotnet --version` is `3.1.400-preview-015178`

**Comment by cartermp** [comment] 2020-07-06 00:51
Closing as duplicate of https://github.com/dotnet/fsharp/issues/5682

**Closed by cartermp** 2020-07-06 00:51 UTC
Labels: Feature Request

**Comment by lostmsu** [comment] 2020-07-06 02:40
@cartermp this does not seem to be a duplicate. The other issue mentions nothing about F# compiler being able to emit Source Link related stuff.

**Comment by cartermp** [comment] 2020-07-06 18:01
The F# compiler isn't a NuGet package or a library, so it's unclear what you'd accomplish by having it source linked. The issue linked tracks FSharp.Core which is a library and package, which is a valid feature request. Could you elaborate on what you're trying to do?

**Comment by lostmsu** [comment] 2020-07-06 19:19
@cartermp the problem is NuGet packages generated from F# projects by F# compiler do not have source link. You can see it if you try to `dotnet pack` on [my project](https://github.com/losttech/Gradient.FSharp/blob/master/src/Gradient.FSharp.fsproj).

**Comment by baronfel** [comment] 2020-07-06 19:22
@lostmsu you're misunderstanding how this all works. The compiler's don't emit all of the sourcelink information, there is another component that you need to add to your project in order to make that work. You should read and follow the directions [here](https://github.com/dotnet/sourcelink), then all should be made clear. This is what I did on the F# Compiler Services Nuget, and many other community projects, to enable sourcelink for them.

**Comment by lostmsu** [comment] 2020-07-06 19:25
@baronfel thanks, that clears it up. TL;DR; you must also have

```xml
<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
```
