### ISSUE TITLE
Visual Studio 17.5.1 broke F# intellisense

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#14901] opened 2023-03-15 11:30 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-1751-broke-F-intellisen/10299854)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.5]
After upgrading to Visual studio 17.5.1 (from 17.5), Intellisense in F# source files doesn't work properly anymore. The most visible effect is that no errors are shown and I need to build to see errors in Error List pane

---
#### Feedback Bot on 3/6/2023, 01:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment] 2023-03-15 11:43
I saw once this but couldn't reproduce. I wonder if it's a result of the incremental builder issue, or vallinkage issue.

**Comment by MaxWilson** [comment] 2023-03-16 03:47
I have also had this issue. Sometimes even building does not make the errors show up in the error pane or inline in the code, only in the Output window. Known workaround: closing Visual Studio and re-opening it fixes it for a while.

For a while I thought it might be because I had Text Macro extensions installed, or Github Copilot, but I've reproed the issue without them.

If I find a screenshot I will post it but for now I can merely confirm that the issue is real.

**Comment by MaxWilson** [comment] 2023-03-19 00:54
Solved for now by rolling back to VS 2022 Version 17.4.2

**Comment by ghostinside** [comment] 2023-09-08 01:57
just updated today to 17.7, F# intellisense stopped recognizing c# references despite the solution being built successfully

**Comment by vzarytovskii** [comment] 2023-09-08 06:23
> just updated today to 17.7, F# intellisense stopped recognizing c# references despite the solution being built successfully 

We'll need a bit more info here.

Is it new style or old style project?
Does it work in 17.8 preview?

**Comment by ghostinside** [comment] 2023-09-08 11:38
it does not work in preview, 

C# project (.net 4.8):     <ProjectGuid>{3A499F41-1A5A-46A1-BF01-8ECADB9C4223}</ProjectGuid>
F# project (.net 4.8, fsharp.core 7 ):     <ProjectGuid>{50b30417-ae00-46c5-9fd1-f5094510cf4d}</ProjectGuid>

**Comment by ghostinside** [comment] 2023-09-08 14:09
![image](https://github.com/dotnet/fsharp/assets/10547793/6a39f3eb-46a6-4f1d-8d72-51f8efa0fb27)

**Comment by ghostinside** [comment] 2023-09-08 14:58
it recognize System namespace, but not any "custom"

**Comment by vzarytovskii** [comment] 2023-09-08 17:49
@0101 it looks like the same issue we had with old projects, do you remember where the link for vsix is?

**Comment by 0101** [comment] 2023-09-09 10:58
Yeah, here's a [VSIX that fixes the issue with _old-style_ projects](https://1drv.ms/u/s!AjcsfNXXyVs57hYGfRE2XKVSioNw?e=pnmomr). You can install it and see if it helps.

**Comment by ghostinside** [comment] 2023-09-09 15:15
live is getting better 

![image](https://github.com/dotnet/fsharp/assets/10547793/7428dfdf-780b-4eb1-8b18-b6986f9a3a57)

**Comment by ghostinside** [comment] 2023-09-09 15:16
@0101 what do you mean by old-style projects? where I can read about old vs new, should I upgrade existing projects?

**Comment by MaxWilson** [comment] 2023-09-10 15:03
> Solved for now by rolling back to VS 2022 Version 17.4.2. ~**Edit**: switching errors to "Build Only" instead of "Build + Intellisense" tentatively seems to be a viable workaround too--after Control + Shift + B, build errors show up correctly in Intellisense.~ Never mind, it eventually recurred even with "Build Only".
> 
> My current workaround to is jump back and forth between VS 2022 and VS Code.

Follow-up: this issue does not currently repro for me in Version 17.8.0 Preview 1.0. Intellisense is a bit slow because I'm using a weak computer, but it does eventually update and remove errors after 5-6 seconds, whereas previously the errors would remain indefinitely.

**Comment by 0101** [comment] 2023-09-11 08:05
> @0101 what do you mean by old-style projects? where I can read about old vs new, should I upgrade existing projects?

Can't really find any good docs about this. But with .NET Core came a new format for csproj/fsproj files. It starts with:
```xml
<Project Sdk="Microsoft.NET.Sdk">
```

Whereas the old format starts with

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

And they are handled differently by VS.

If you can it's probably a good idea to upgrade to the new format, but I don't know if there's an easy automatic way to do that. 

Here's an article to possibly get you started: https://www.hanselman.com/blog/upgrading-an-existing-net-project-files-to-the-lean-new-csproj-format-from-net-core

**Comment by vzarytovskii** [comment] 2023-09-11 10:12
There is a semi-automatic way of migrating old projects: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-migrate

**Comment by vzarytovskii** [comment] 2023-09-11 10:14
There's a tool for migrating them:
https://github.com/dotnet/try-convert

I haven't tried it personally, but it should "just work" for uncomplicated projects..

**Comment by T-Gro** [comment] 2023-11-02 10:48
Closing as the issue does not repro anymore (see comments above), can be reopened if it happens on latest tooling again.

**Closed by T-Gro** 2023-11-02 10:48 UTC
Labels: Bug, Impact-High, Area-LangService-Diagnostics
