### ISSUE TITLE
F# Interactive - "Cancel Interactive Evaluation" does not work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12652] opened 2022-01-26 22:55 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-Interactive---Cancel-Interactive-Eva/1630856)._

---
F# Interactive - "Cancel Interactive Evaluation" does not work, nothing happens.

..................

---
#### Feedback Bot on 1/6/2022, 10:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dsyme** [comment] 2022-01-31 13:07
This is a duplicate of https://github.com/dotnet/fsharp/issues/9397

**Closed by dsyme** 2022-01-31 13:07 UTC
