### ISSUE TITLE
Error list not showing build errors/warnings if "only build" not chosen

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#16624] opened 2024-01-31 12:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-list-not-showing-build-errorswarn/10567139)._

---
[severity:It bothers me. A fix would be nice]
![image](https://github.com/dotnet/fsharp/assets/1260985/0ec38d35-46cc-4ab2-a5b2-922b8a82fcde)

![image](https://github.com/dotnet/fsharp/assets/1260985/c9552b7f-d678-463a-8271-246823187020)

---
#### Feedback Bot on 1/24/2024, 06:53 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by T-Gro** [comment] 2024-02-12 18:00
This issue is a duplicate of https://github.com/dotnet/fsharp/issues/16330 .
The analysis for TailCallAttribute is only running when optimizations are run - those determine how recursive constructs can be rewritten. Which means it is not done while typing in the IDE, and only on a full build.

More information in the linked ticket.

**Closed by T-Gro** 2024-02-12 18:00 UTC
Labels: Needs-Triage
