### ISSUE TITLE
Type inference for overloaded methods is not ideal

### ISSUE THREAD

**Issue by dhwed** [dotnet/fsharp#3563] opened 2017-09-07 23:07 UTC
The following fails to compile:
```fsharp
open System.Threading.Tasks

type AsyncBuilder with
    member __.Bind(t: Task, f: unit -> Async<'U>): Async<'U> = async.Bind(Async.AwaitTask t, f)
    member __.Bind(t: Task<'T>, f: 'T -> Async<'U>): Async<'U> = async.Bind(Async.AwaitTask t, f)

type Class(p) =
    member __.Property: string = p

[<EntryPoint>]
let main _ =
    let x =
        async {
            let! result = Task.FromResult(Class "result")
            return result.Property
        } |> Async.RunSynchronously

    printf "%s" x
    0
```
with this error:
![image](https://user-images.githubusercontent.com/10184638/30187767-9f1573b0-93f0-11e7-91de-833fba9fa8ae.png)

There's two solutions I have found for this.  You can either use a type annotation:
```fsharp
let! (result: Class) = Task.FromResult(Class "result")
```

Or you can use this abomination:
```fsharp
type Abomination = Abomination with
    static member ($)(Abomination, t: Task<'T>): Async<'T> = Async.AwaitTask t
    static member ($)(Abomination, t: Task): Async<unit> = Async.AwaitTask t

type AsyncBuilder with
    member inline __.Bind(t, f: 'T -> Async<'U>): Async<'U> = async.Bind(Abomination $ t, f)
```

**Comment by dhwed** [comment] 2017-09-07 23:13
I've come up with a more minimal example:

```fsharp
type Static =
    static member Apply(t: obj, f: obj -> 'U): 'U = f t
    static member Apply(t: 'T, f: 'T -> 'U): 'U = f t

type Class(p) =
    member __.Property: string = p

[<EntryPoint>]
let main _ =
    let x = Static.Apply(Class "value", fun x -> x.Property)
    printf "%s" x
    0
```

Still fails with the same error, but the VS tooltips can figure out the type of x:
![image](https://user-images.githubusercontent.com/10184638/30189130-cb5ef3a4-93f7-11e7-9d33-fc795d24c524.png)

BTW, csharp's type inference can handle this:
```csharp
using System;

static class Static {
    public static TResult Apply<TResult>(object t, Func<object, TResult> f) => f(t);
    public static TResult Apply<T, TResult>(T t, Func<T, TResult> f) => f(t);
}

class Class {
    public string Property { get; }
    public Class(string value) => Property = value;
}

class Program {
    static void Main(string[] args) {
        var result = Static.Apply(new Class("value"), x => x.Property);
        Console.WriteLine(result);
    }
}
```

**Comment by dsyme** [comment] 2017-09-07 23:28
This should really be a language suggestion + RFC.  But leave it open - the example is a good one and perhaps we can trial a change then put it through the RFC process

**Comment by dhwed** [comment] 2017-09-08 01:42
After reading the spec, I've come to two conclusions:

1. I can make it mostly work with this hack using `Func<Async<'U>>` instead of `unit -> Async<'U>`:

```fsharp
type AsyncBuilder with
    member __.Bind(t: Task, f: Func<Async<'U>>): Async<'U> = async.Bind(Async.AwaitTask t, f.Invoke)
    member __.Bind(t: Task<'T>, f: 'T -> Async<'U>): Async<'U> = async.Bind(Async.AwaitTask t, f)
```

2. My head hurts.  If I ever design a language, it's not going to have method overloading :)
Besides, the real solution for this is probably [type classes](https://github.com/dotnet/csharplang/issues/164), not even more complex method overloading rules.

**Comment by dsyme** [comment] 2017-09-08 09:44
@dhwed Yes, method overloading adds extraordinary complexity and many corner cases. The problem is if you want to consume those .NET libraries.... 

The real solution is that ``Task`` should never have existed, and C#/.NET should have had a ``unit`` type.  Type classes are good for systematizing things that are _regular_, but no parametric system easily survives the complexities of encountering late-1990s object-oriented programming unscathed.

That said, I would like that the use of .NET Func and F# curryable-function types was regular - and there was never an incentive to use Func like this

**Comment by brianrourkeboll** [comment] 2021-04-08 21:39
I've run into this issue recently also when implementing a computation expression builder.

Though the issue has to do with overload resolution generally, it is perhaps most noticeable in computation expressions, because the errors can be quite ugly (the entire computation expression can turn into red squigglies).

<details>

<summary>Sample squigglies</summary>

![image](https://user-images.githubusercontent.com/14795984/114096801-36ac3c00-988d-11eb-829d-c346297b2af1.png)


</details>

### Underlying issue

Since I don't see it spelled out as such above, the underlying issue appears to be this: given two generic overloads, both of whose signatures would fit the type of the argument at hand, the F# compiler cannot decide between them. While in theory it seems like it could simply choose the more specific overload, it does not.

I'm not sure whether this exact behavior has been discussed elsewhere or perhaps is by design. For comparison, the C# compiler _does_ choose the more specific overload, but then it obviously doesn't need to worry as much as the F# compiler does about the choice of overload affecting inferred types elsewhere.

### Repro

Here's an even more minimal repro of the F# and C# compilers' respective overload resolution behavior in this case:

#### F#

```fsharp
type C =
    static member M (t : 'T) = ()
    static member M (t : 'T []) = ()

C.M 0     // Compiles.
C.M [|0|] // Doesn't compile ("FS0041: A unique overload for method 'M' could not be determined...").
```

#### C#

```csharp
public static class C
{
    public static void M<T>(T t) { }
    public static void M<T>(T[] t) { }
}

C.M(0);           // Compiles.
C.M(new[] { 0 }); // Compiles, using the more specific (T[]) overload.
```

### Workaround

One workaround I discovered for this problem that can be used for computation expression builders as well as generally takes advantage of the different overload resolution priority the F# compiler gives to (C#-style) extension methods.

If either the more specific or less specific overload is defined as a C#-style extension method, the ambiguity is resolved.

#### More specific overload as extension

```fsharp
type C () =
    member _.M (t : 'T) = ()

open System.Runtime.CompilerServices

[<Extension>]
type CExtensions =
    [<Extension>]
    static member M (_c : C, t : 'T []) = ()

C().M 0     // Compiles.
C().M [|0|] // Compiles.
```

#### Less specific overload as extension

```fsharp
type C () =
    member _.M (t : 'T []) = ()

open System.Runtime.CompilerServices

[<Extension>]
type CExtensions =
    [<Extension>]
    static member M (_c : C, t : 'T) = ()

C().M 0     // Compiles.
C().M [|0|] // Compiles.
```

@dhwed @dsyme @cartermp

**Comment by dsyme** [comment] 2022-04-20 06:29
There are duplicates of this in the language suggestion, and some other duplicates in the repo, closing this

**Closed by dsyme** 2022-04-20 06:29 UTC
Labels: Feature Request

**Comment by JustinChristensen** [comment] 2024-04-02 21:25
@dsyme Where is this being tracked in the language suggestion? I ran into this exact issue while building computation expression that acts like a `Reader`, `Async`, and `Task` all-in-one. I might have missed it, but all I see is an umbrella issue saying that type inference should be improved.

Is the `Func` trick that @dhwed mentioned the preferred workaround, or is there a better way to handle this?
