### ISSUE TITLE
The compiler can put a method-only attribute on a property and a literal

### ISSUE THREAD

**Issue by Happypig375** [dotnet/fsharp#8689] opened 2020-03-10 03:58 UTC
**Repro steps**

https://sharplab.io/#v2:DYLgZgzgPgtg9gEwK7AKYAICy6C8BYAKHWPTgAdUA7dAZQE8IAXVGQk9Rui9AbQB4Ago0YAnAJYAjJMwCqEAIYBzVAAohoydNQAVeSOWMIAOkypGAC0QBKAHwBdLGcsIA8pWB114qcxVXc6GKU5qjijOhemr5WbCRo4fymFohuHvZYAQDMQA

```fs
module M =
    open System
    type [<AttributeUsage(AttributeTargets.Method)>] MethodOnlyAttribute() = inherit Attribute()
    let [<MethodOnly>] M = 3
```
https://sharplab.io/#v2:DYLgZgzgPgtg9gEwK7AKYAICy6C8BYAKHWPTgAdUA7dAZQE8IAXVGQk9Rui9AbQB4Ago0YAnAJYAjJMwCqEAIYBzVAAohoydNQAVeSOWMIAOkypGAC0QBKAHwBdLGcsIA8pWB114qcxVXc6GKU5qjijOhemr5WbCRo4fymFohuHgDc6AAyYswi8sD2WAEAzEA===
```fs
module M =
    open System
    type [<AttributeUsage(AttributeTargets.Method)>] MethodOnlyAttribute() = inherit Attribute()
    let [<MethodOnly; Literal>] M = 3
```

**Expected behavior**

Errors on `MethodOnly`.

**Actual behavior**

The attribute is put on the property.

**Known workarounds**

N/A

**Comment by cartermp** [comment] 2020-03-10 15:54
Closing as a dupe of https://github.com/dotnet/fsharp/issues/8547

Unfortunately, this one is a bit tricky.

**Closed by cartermp** 2020-03-10 15:54 UTC
