### ISSUE TITLE
Using --staticlink:<assembly-name>compiler option results in Build FAILED

### ISSUE THREAD

**Issue by bikallem** [dotnet/fsharp#5451] opened 2018-08-02 09:12 UTC
I am trying to create a standalone executable using F# .NET (not .NET core). In addition to the --standalone option, I have used --staticlink:CSVHelper so that the external assembly is inline as well in the final executable. However, using the --staticlink option results in the Build FAILED error. 

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a F# Console application (.NET framework) 

2. Add an external lib reference to it. In the project Build settings, Other flags, enter --standalone --staticlink:<external dll name> 

3. Build the application. 

#### Expected behavior

An executable that executes without both FSharp.Core and exeternal dll.

#### Actual behavior

fsc crashes.
![image](https://user-images.githubusercontent.com/315907/43574338-d7259c8c-963b-11e8-93ec-8577cb8d080d.png)

Compiler error.

1>output error FS0193: error : Index was outside the bounds of the array.
1>parameter error FS0193: error : Index was outside the bounds of the array.

#### Known workarounds

Remove --staticlink option

#### Related information 

Provide any related information 

* Windows 7 Enterprise
* .NET Runtime
* Visual Studio 2017 15.7.4

**Comment by TIHan** [comment] 2018-08-02 20:28
Thank you for reporting this. It's not good that `fsc` will just outright crash; we should investigate.

**Comment by cartermp** [comment] 2020-06-06 20:37
Closing this because with .NET Core SDK 3.1.201, this will work. However, newer SDKs to exhibit a regression here: https://github.com/dotnet/fsharp/issues/9255

**Closed by cartermp** 2020-06-06 20:37 UTC
Labels: Area-Compiler, Urgency-Later, bug
