### ISSUE TITLE
Generic arguments of Aspnetcore AddHttpClient method are wrongly inferred (silent bug)

### ISSUE THREAD

**Issue by jkone27** [dotnet/fsharp#12957] opened 2022-04-07 12:25 UTC
Wrong overload (with generics) is picked over the correct one (non generic)

<img width="728" alt="image" src="https://user-images.githubusercontent.com/10419217/162198193-d48517ad-9c76-49c5-ab8f-02938a459196.png">

this causes the factory to never be invoked and the app to have unexpected behaviours as parts of it never run as expected

```
dotnet new webapi --language F#
```

make a call to [here available overloads](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-6.0)
```
service.AddHttpClient(fun c -> ())
```
in startup the generic overload AddHttpClient<T1,T2> is taken, which causes the http client settings not to be registered at all
Provide the steps required to reproduce the problem:

**Expected behavior**

The F# compiler should warn if generic parameters are not passed in a "VOID or UNIT" call not assigned to any left hand operator

SomeGenericMethod<T>()

shouldnt be confused with

SomeGenericMethod()

by the compiler

**Actual behavior**

the generic implementation is used, without generic types being passed and the httpclient is not configured correctly (has null base address e.g.)

**Known workarounds**

explicitly state the named arguments, so that the right overload is picked

```
        //make sure this is not the generic one
        services.AddHttpClient("externalApiClient",
            configureClient = fun httpClient ->
                httpClient.BaseAddress <- new Uri("https://www.google.com/")
                ()
        )
```

**Related information**

Provide any related information (optional):

* .NET6 and latest aspnetcore
* macos

**Comment by dsyme** [comment] 2022-04-20 02:03
This should be a language suggestion please, preferably with a repro that is in F# alone (unless that is not possible). The current overload selection will be by design, but we can look at warnings or refinements

**Comment by vzarytovskii** [comment] 2022-10-24 17:12
@jkone27 as per @dsyme's comment, I am going to close the issue. Please feel free to open a language suggestions at https://github.com/fsharp/fslang-suggestions

**Closed by vzarytovskii** 2022-10-24 17:12 UTC
Labels: Resolution-By Design, Needs-Triage
