### ISSUE TITLE
Add dotnet sdk build support for warnon to

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#10883] opened 2021-01-15 17:40 UTC
This is silly:
````
 <OtherFlags>$(OtherFlags) /warnon:3218 /warnon:1182 /warnon:3390 --maxerrors:20 --extraoptimizationloops:1 --times</OtherFlags>
````

--warnon is an F# extension to the warning structure of other languages.  It means enable a warning that is off by default.

Off by default warnings are ones that we introduced to avoid breaking changes, the way that we use them is to make them off by default and then turn them back on in new project templates.

**Comment by vzarytovskii** [comment] 2021-01-15 18:17
I believe it's a duplicate of https://github.com/dotnet/fsharp/issues/10882

**Closed** 2021-01-15 18:32 UTC
