### ISSUE TITLE
Inconsistent syntax coloring of generic parameters on static members

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#6516] opened 2019-04-12 20:03 UTC
```
type MyType() =
    static member GenericStatic<'a> (a:'a) = a

[<EntryPoint>]
let main _ =
    let c = MyType.GenericStatic<string> "" // The generic parameters and brackets are colored as functions
    0
```
![image](https://user-images.githubusercontent.com/1631157/56062982-1730b600-5d3c-11e9-9974-8f488d8dfd9f.png)

#### Expected behavior
Brackets "< >" should be colored with the default and the type parameter should be colored as a type.

#### Actual behavior
The whole thing is colored as a function.

#### Related information 
There are several inconsistencies around this, perhaps it would be better to consolidate into a single bug?
https://github.com/Microsoft/visualfsharp/issues/4792
https://github.com/Microsoft/visualfsharp/issues/2585

Here's a picture showing all the inconsistencies around generic type colorization that I know of:
![image](https://user-images.githubusercontent.com/1631157/56063095-5bbc5180-5d3c-11e9-94bf-841c7bbc9347.png)

VS2019 16.0.1

**Comment by cartermp** [comment] 2020-06-20 01:19
Thanks for reporting - this is definitely a dupe of #2585. I'll close this out and leave an explanation in that canonical issue

**Closed by cartermp** 2020-06-20 01:19 UTC
Labels: Area-FCS, bug
