### ISSUE TITLE
F# folder order not displayed correctly in Solution Explorer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#13948] opened 2022-09-21 13:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-folder-order-not-displayed-correctly-/10149550)._

---
[severity:It's more difficult to complete my work]
I'm working in an F# project (using .NET 6 and VS 2022 17.3.4) and my files are randomly not showing up in the correct order. In this case, the F# files under a subfolder are displayed with all of the folders on top and all of the files in the folder underneath, despite the fact that in the *.fsproj file there are 4 files, two folders, then one file at the end.

This appears to work in another subfolder under the same project that is showing 1 file, 2 folders, and 1 file at the end correctly.

---
#### Joshua Marner on 9/15/2022, 09:15 PM: 

(private comment, text removed)
#### Feedback Bot on 9/16/2022, 04:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment] 2022-09-21 14:19
Duplicate of #12155

**Closed** 2022-09-21 14:19 UTC
Labels: Area-VS
