### ISSUE TITLE
Visual Studio Project Properties shows C# warning levels in dropdown that don't apply to F# at all

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#17136] opened 2024-05-11 09:35 UTC
The available options dropdown in VS 2022 and VS 2022 Preview lists them in relation to C#, and shows too many of them:
![image](https://github.com/dotnet/fsharp/assets/16015770/d9caf05f-0f66-4c5f-b4f5-0d85973b3a06)

### Repro steps

1. Open any F# project
2. Select menu <kbd>Project</kbd> → <kbd>Properties</kbd>
3. Scroll to Warnings section and select the dropdown shown above

### Expected behavior

a. Only options 0 - 5, as these are the levels supported by F#. 
b. Descriptions matching the F# spec, not the C# spec (we don't throw C# 11 warnings, do we?)

### Actual behavior

Showing 9 options, and showing descriptions not matching F#.

### Known workarounds

None.

### Related information

* Visual Studio 2022 (with or w/o Preview)

PS: I've no problem issuing a PR for this, but I've no clue wherefrom this list is populated. This may very well be "external", as in: a bug of VS itself, which is closed source.

**Comment by vzarytovskii** [comment] 2024-05-13 16:52
Duplicate of https://github.com/dotnet/fsharp/issues/13714

**Comment by abonie** [comment] 2024-05-13 16:52
Closing as a duplicate

**Closed by abonie** 2024-05-13 16:52 UTC
Labels: Bug

**Comment by abelbraaksma** [comment] 2024-05-14 14:41
@abonie, I prefer not to use the `closed as completed` when that's not the case (though, in fairness, `closed as not planned` isn't entirely true either, but the dropdown on GitHub suggests that for duplicates).

**Comment by abonie** [comment] 2024-05-14 16:56
Good point, I simply forgot there is a qualifier to closing an item on github
