### ISSUE TITLE
Throwing exceptions expected to be availalble in a spanified (or byreflike) environment

### ISSUE THREAD

**Issue by zpodlovics** [dotnet/fsharp#9302] opened 2020-05-26 18:10 UTC
It seems that it's not possible to throw exception in an environment in a spanified (or byreflike) environment. It seems that this limitation also affect other functionality from [prim-types.fs](https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L3274) 

(I am well aware of the F# Span implementation limitations, however it still seems that "not all batteries included".)

**Repro steps**

Provide the steps required to reproduce the problem:

1. Please consider the following C# and F# example:

```csharp
using System;

public interface I {
    public Span<Byte> GetSpan();
}

public class C : I {
    public Span<Byte> GetSpan() {
        throw new NotImplementedException();
    }
}
```
[SharpLab Link](https://sharplab.io/#v2:C4LglgNgPgAgTARgLAChUwMwAIwDtgCmATgGYCGAxgVgJJYDeqWzWmWAygA5m4A8AQgE9CAPiwBxAsC48AFAEoA3KgC+qdNnhYAwlhC0GTFmxl8hoiVNMLDKFvazAAFkQD2Adyy4CngHKvgGgBbTggCIIJ8AgATAFEADypOYDBXXAVlOxY1FBUgA)

```fsharp
open System

[<Interface>]
type I =
    abstract member GetSpan: unit -> Span<byte>

type C() =
    interface I with
        member this.GetSpan() : Span<byte> =
            raise(System.NotImplementedException())
```

[SharpLab Link](https://sharplab.io/#v2:DYLgZgzgPg9gDgUwHYAIDKBPCAXBBbAWAChjSiBtAHgEklcAnMAQwGMEA+AXWOw0RWooAvMRRiUTAEY56rbCjz5JCeigDiCbGjhMkIFAFckAS3kBaduh1JKkjLnZle/AMIAKAJTDR443RXMbAIoAO6mABY+4uKKeMqq2OHGEAB0GlrWnij62rq29hzeRNEl4rLJCG6YOPgpAHIw2NR4cMD4yLgAJgCiAB5scNjGMEieHlGl4kA==
)

**Expected behavior**

Should be able to throw NotImplementedException.

**Actual behavior**

Compilation error: "error FS0412: A type instantiation involves a byref type. This is not permitted by the rules of Common IL."

**Known workarounds**

Implement a C# Helper

**Related information**

Provide any related information (optional):

* Operating system
* .NET Runtime: .NET Core 3.1, Ubuntu 20.04
* Visual Studio Core

**Comment by cartermp** [comment] 2020-05-26 18:44
Closing as duplicate of https://github.com/dotnet/fsharp/issues/5776

Language suggestion here: https://github.com/fsharp/fslang-suggestions/issues/872

You can put in a dummy return value, `Span<byte>.Empty` after the return value as a workaround

**Closed** 2020-05-26 18:44 UTC
Labels: Resolution-Duplicate
