### ISSUE TITLE
Build warnings: FSharp.Compiler.Service 41.0.2 depends on missing packages

### ISSUE THREAD

**Issue by nightroman** [dotnet/fsharp#12758] opened 2022-02-21 12:46 UTC
Build warnings: FSharp.Compiler.Service 41.0.2 depends on missing packages

**Repro steps**

1. dotnet new console -lang f#
2. dotnet add package FSharp.Compiler.Service
3. dotnet build

Output:

```
C:\tmp\Fcs220221-2\Fcs220221-2.fsproj : warning NU1603: FSharp.Compiler.Service 41.0.2 depends on Microsoft.Build.Framework (>= 17.0.0-preview-21515-03) but Microso
ft.Build.Framework 17.0.0-preview-21515-03 was not found. An approximate best match of Microsoft.Build.Framework 17.0.0 was resolved.
C:\tmp\Fcs220221-2\Fcs220221-2.fsproj : warning NU1603: FSharp.Compiler.Service 41.0.2 depends on Microsoft.Build.Tasks.Core (>= 17.0.0-preview-21515-03) but Micros
oft.Build.Tasks.Core 17.0.0-preview-21515-03 was not found. An approximate best match of Microsoft.Build.Tasks.Core 17.0.0 was resolved.
C:\tmp\Fcs220221-2\Fcs220221-2.fsproj : warning NU1603: FSharp.Compiler.Service 41.0.2 depends on Microsoft.Build.Utilities.Core (>= 17.0.0-preview-21515-03) but Mi
crosoft.Build.Utilities.Core 17.0.0-preview-21515-03 was not found. An approximate best match of Microsoft.Build.Utilities.Core 17.0.0 was resolved.
C:\tmp\Fcs220221-2\Fcs220221-2.fsproj : warning NU1603: FSharp.Compiler.Service 41.0.2 depends on Microsoft.Build.Framework (>= 17.0.0-preview-21515-03) but Microso
ft.Build.Framework 17.0.0-preview-21515-03 was not found. An approximate best match of Microsoft.Build.Framework 17.0.0 was resolved.
C:\tmp\Fcs220221-2\Fcs220221-2.fsproj : warning NU1603: FSharp.Compiler.Service 41.0.2 depends on Microsoft.Build.Tasks.Core (>= 17.0.0-preview-21515-03) but Micros
oft.Build.Tasks.Core 17.0.0-preview-21515-03 was not found. An approximate best match of Microsoft.Build.Tasks.Core 17.0.0 was resolved.
C:\tmp\Fcs220221-2\Fcs220221-2.fsproj : warning NU1603: FSharp.Compiler.Service 41.0.2 depends on Microsoft.Build.Utilities.Core (>= 17.0.0-preview-21515-03) but Mi
crosoft.Build.Utilities.Core 17.0.0-preview-21515-03 was not found. An approximate best match of Microsoft.Build.Utilities.Core 17.0.0 was resolved.
    6 Warning(s)
    0 Error(s)
```

**Comment by dsyme** [comment] 2022-03-01 17:52
Duplicate of #12753

**Comment by nightroman** [comment] 2022-03-01 18:05
Hi @dsyme I would not say it's a duplicate (without explicit mention in that issue at least) but as soon as it is addressed and does not come back next time with different missing versions, it's fine indeed.

**Comment by dsyme** [comment] 2022-03-01 18:09
I see, yes, it's a bit different.  I don't know the underlying cause, @KevinRansom and @brettfo might know

**Comment by dsyme** [comment] 2022-03-01 18:28
This is almost certainly totally benign, so I think don't worry about it and accept warnings for now.

**Comment by KevinRansom** [comment] 2022-03-01 18:30
Now that the 64 bit build is behind us we should move to a released Microsoft.build set of packages.

**Comment by KevinRansom** [comment] 2022-03-05 22:53
Shipped an updated fcs:   https://www.nuget.org/packages/FSharp.Compiler.Service/41.0.3

**Closed by KevinRansom** 2022-03-05 22:53 UTC
Labels: Bug, Impact-Low, Area-FCS
