### ISSUE TITLE
ValueOption equality on expression trees causes crash

### ISSUE THREAD

**Issue by Thorium** [dotnet/fsharp#13370] opened 2022-06-23 23:01 UTC
I'm trying to have an expression tree to compare a struct with the same item, and it fails?

```fsharp
open System
open System.Linq.Expressions
//let tester = Some "a" //works
//let tester = Guid.NewGuid() //works
let tester = ValueSome "b" //crash

let equalExpr = Expression.Equal(Expression.Constant(tester), Expression.Constant(tester))

//System.InvalidOperationException: The binary operator Equal is not defined for the types 
// 'Microsoft.FSharp.Core.FSharpValueOption`1[System.String]' and 
// 'Microsoft.FSharp.Core.FSharpValueOption`1[System.String]'.
//   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
//   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
```

**Comment by Thorium** [comment] 2022-06-23 23:38
Ok,
I found a workaround that is enough good for me: I lie the types to the expression tree:

```fsharp
open System
open System.Linq.Expressions
//let tester = Some "a" //works
//let tester = Guid.NewGuid() //works
let tester = ValueSome "b"
let ty = typeof<obj>

let equalExpr = Expression.Equal(Expression.Constant(tester, ty), Expression.Constant(tester, ty))
```

**Comment by Thorium** [comment] 2022-06-24 12:03
More practical example:

```fsharp
open System.Linq
let datasource1 = [1; 2].AsQueryable() // primary key
let datasource2 = [ValueSome 1; ValueSome 2].AsQueryable() //foreign key
query { // crossjoin
   for d1 in datasource1 do
   for d2 in datasource2 do
   where (ValueSome(d1) = d2)
   select (d1, d2)
} |> Seq.toList;;

// System.InvalidOperationException: The binary operator Equal is not defined for the types 'Microsoft.FSharp.Core.FSharpValueOption`1[System.Int32]' and 'Microsoft.FSharp.Core.FSharpValueOption`1[System.Int32]
```

**Comment by Thorium** [comment] 2022-07-12 10:39
If these are wrapped to `box` or option `Some`, then the LINQ compiles but does **incorrect runtime result**:
```fsharp
let datasource1 = [1; 2].AsQueryable() // primary key
let datasource2 = [ValueSome 1; ValueSome 2].AsQueryable() //foreign key
query { 
   for d1 in datasource1 do
   for d2 in datasource2 do
   where (box(ValueSome(d1)) = box(d2))
   select (d1, d2)
} |> Seq.toList;;
// val it: (int * int voption) list = []
// Empty???
```
If I change the `=` to Equals, then it produces a different result:

```fsharp
open System.Linq
let datasource1 = [1; 2].AsQueryable() // primary key
let datasource2 = [ValueSome 1; ValueSome 2].AsQueryable() //foreign key
query { 
   for d1 in datasource1 do
   for d2 in datasource2 do
   where (ValueSome(d1).Equals(d2))
   select (d1, d2)
} |> Seq.toList;;
// val it: (int * int voption) list = [(1, ValueSome 1); (2, ValueSome 2)]
```

The original issue can be reproduced with custom types. It seems the LINQ compiler cannot work with StructuralEquality:

```fsharp
open System
open System.Linq.Expressions

[<StructuralEquality; StructuralComparison>]
[<Struct>]
type Person(name:string, age:int) =
  member x.Name = name
  member x.Age = age

let a = Person("Joe", 42)
let a2 = Person("Joe", 42)
let equalExpr = Expression.Equal(Expression.Constant(a), Expression.Constant(a2))
// System.InvalidOperationExceptio
```

In the case of LINQ it's often maintainability over performance, so I'd prefer some extra-boxing or whatever just to make things work correctly.

**Comment by Happypig375** [comment] 2022-07-12 13:43
```fs
let makeEq (left: System.Linq.Expressions.Expression) (right: System.Linq.Expressions.Expression) =
    System.Linq.Expressions.Expression.Equal(left, right, false, typeof<_ option>.Assembly.GetType("Microsoft.FSharp.Core.Operators").GetMethod("op_Equality").MakeGenericMethod(left.Type))
let a = ValueSome 1
printfn $"🌄{System.Linq.Expressions.Expression.Lambda((makeEq (System.Linq.Expressions.Expression.Constant a) (System.Linq.Expressions.Expression.Constant a)), [||]).Compile().DynamicInvoke([||])}"
```

**Comment by Happypig375** [comment] 2022-07-12 13:46
This issue can be closed as by design

**Comment by Thorium** [comment] 2022-07-12 13:53
@Happypig375 will the Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter be using this custom operator constructor when you do F# Linq query?

**Comment by T-Gro** [comment] 2022-12-29 13:24
https://github.com/dotnet/fsharp/pull/11681 is merged, this can be closed (by design, solution exists)

**Closed by T-Gro** 2022-12-29 13:24 UTC
Labels: Bug, Impact-Low, Area-Queries
