### ISSUE TITLE
C# to F# go to definition navigates to metadata, and not the source code

### ISSUE THREAD

**Issue by oleksandr-bilyk** [dotnet/fsharp#13882] opened 2022-09-12 13:53 UTC
Every year we have to buy Rider because Rider allows to navigate from C# code to F# method definition. 
We had big expectations that VS2022 will support such a basic feature but not.
Our team decided to use F# in solution where we have many C# and F# projects calling each other. 
This small feature is very important for future use of F# in our solutions.

**Comment by vzarytovskii** [comment] 2022-09-12 13:55
@tmat do you have any insights on how should we approach it?

**Comment by smoothdeveloper** [comment] 2022-09-12 20:59
@oleksandr-bilyk please consider appending your experience in this discussion: https://github.com/dotnet/csharplang/discussions/6412#discussioncomment-3536860

it is about "C#-adjacent tooling experience" from C# Language Design Meeting notes discussions.

The reverse navigation works (Go To Definition on C# member from F# code reaches), which I think came at some point in VS 2019.

**Comment by tmat** [comment] 2022-09-13 17:39
@CyrusNajmabadi IIRC LSP should be able to handle this, correct?

**Comment by vzarytovskii** [comment] 2022-09-15 10:00
https://github.com/dotnet/roslyn/pull/64010 is in, will experiment with it next week

**Comment by kerams** [comment] 2022-09-15 10:01
> The reverse navigation works (Go To Definition on C# member from F# code reaches),

You said that, but it stopped working for me with yesterday's VS preview update :).

**Comment by vzarytovskii** [comment] 2022-09-15 10:07
> > The reverse navigation works (Go To Definition on C# member from F# code reaches),
> 
> You say that, but it stopped working for me with yesterday's VS preview update :).

Works for me:
![image](https://user-images.githubusercontent.com/1260985/190377140-cb6d6801-e141-483e-8d54-9dd3b2b378c9.png)
![image](https://user-images.githubusercontent.com/1260985/190377177-83bdc45c-16f5-4d00-a033-1fd315ac2c68.png)

**Comment by kerams** [comment] 2022-09-15 10:11
![image](https://user-images.githubusercontent.com/5063478/190377387-09c72c71-b4bb-43f9-839a-653d4702b843.png)

BCL metadata navigation. I'm pressing F12 on this to no avail (it used to work). Perhaps it's a different use case.

**Comment by vzarytovskii** [comment] 2022-09-15 10:16
> ![image](https://user-images.githubusercontent.com/5063478/190377387-09c72c71-b4bb-43f9-839a-653d4702b843.png)
> 
> BCL/external dependency metadata navigation. I'm pressing F12 on this to no avail (it used to work). Perhaps it's a different use case.

Yep, doesn't work for me for `Newtonsoft.Json`.

**Comment by vzarytovskii** [comment] 2022-09-15 10:22
I hopefully can fix it in one batch with C#->F# navigation.

**Comment by smoothdeveloper** [comment] 2022-09-15 10:43
@kerams / @vzarytovskii I noticed in some F# editor "go to definition" use cases, it will generate F# signature (of C# code).

IMO, generating F# signatures is relevant, only if those cases don't resolve:
* project reference, with the source file
* assembly reference with pdb pointing to source file
* sourcelink

AND if, the assembly referenced is compiled with F#.

If it is not the case, it is probably better to do what the C# editor would do.

@vzarytovskii and @CyrusNajmabadi, thanks for giving a shot at the C# -> F# code navigation, this is going to help a lot.

**Comment by vzarytovskii** [comment] 2022-09-15 10:48
> IMO, generating F# signatures is relevant, only if those cases don't resolve:
 
> * project reference, with the source file

I think, if we know that we have source, we will navigate to it.
 
> * assembly reference with pdb pointing to source file
> * sourcelink

Not sure about these. Will try to remember and look at it. When I navigate to "WriteLine" source code now, it brings me to the source (not sure whether via sourcelink ok pdbs).

**Comment by dsyme** [comment] 2022-09-23 14:03
@vzarytovskii I removed the VS label - trying to keep to one most-specific Area label per issue, unless it really is across multiple areas

**Comment by dsyme** [comment] 2022-09-26 19:14
Closing https://github.com/dotnet/fsharp/issues/3497 as a duplicate of this more recent one.  There is interesting information there on prototype attempts to address this

**Comment by vzarytovskii** [comment] 2022-10-10 17:27
Note: new API with assembly name included: https://github.com/dotnet/roslyn/pull/64475
Will make changes once back next week.

**Closed** 2023-01-09 13:13 UTC
Labels: Feature Request, Area-LangService-Navigation, release/17.5
