### ISSUE TITLE
Type declaration isn't checked when base ctor has errors

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#5924] opened 2018-11-19 11:01 UTC
When the base constructor in `inherits` has errors (e.g. different number of arguments) the whole type isn't being type checked. Type checker could recover and even try to choose best matching (or some, at least) base constructor overload.
```fsharp
type A() =
    inherit B(123)
```

**Comment by dsyme** [comment] 2022-04-01 04:34
Duplicate of https://github.com/dotnet/fsharp/issues/5399, or close enough

**Closed by dsyme** 2022-04-01 04:34 UTC
Labels: Area-Compiler, Feature Improvement
