### ISSUE TITLE
[LiveShare] Adding new item crashes LiveShare for F# project 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12976] opened 2022-04-11 23:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/LiveShare-Adding-new-item-crashes-Live/10009659)._

---
When 2 users with Visual Studio connected to Live Share in the F# project and one of them adds a new F# file via project context menu -> Add -> New Item... then some files in the F# project are being removed.

However, if I add a new file via file context menu -> Add above/Add beloved -> New Item... this does not happen.

The most ridiculous is that files are being physically deleted from the disc and disappear!

![image.png](https://aka.ms/dc/image?name=B381a0e9a7b934f2d932c714123f1257d637850388461031220_20220408-212045-image.png&tid=381a0e9a7b934f2d932c714123f1257d637850388461031220)

---
#### Feedback Bot on 4/11/2022, 03:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by xperiandri** [comment] 2022-04-12 09:46
![image](https://user-images.githubusercontent.com/2365592/162931960-fcf9644a-e3f9-4309-9a08-8ca9314dec5f.png)

**Comment by xperiandri** [comment] 2022-04-12 09:48
I tried to add to the top (**Add above** the top one) and again the last one (Program.fs) was just removed.
So **Add above** also corrupts the project.

**Comment by xperiandri** [comment] 2022-04-12 09:49
Also enabling Code Lenses corrupts the text buffer or text rendering. So that when I close the file and open it back again the code appears again.
But when I edit the single line function, the whole line disappears and typing any characters adds them to the beginning of the line.

**Comment by dsyme** [comment] 2022-04-20 02:13
This must surely be some bug in https://github.com/dotnet/project-system?  I can't imagine how F# would need to have code specific to LiveShare

**Comment by xperiandri** [comment] 2022-04-20 08:03
@dsyme would you like me to create the issue there?

**Comment by vzarytovskii** [comment] 2022-04-20 09:10
> @dsyme would you like me to create the issue there?

Yeah, it's probably better to create an issue for them to investigate.

**Comment by dsyme** [comment] 2022-04-21 01:15
I'll close as duplicate of https://github.com/dotnet/fsharp/issues/9148

I just don't really understand how a Live Share system would be language specific, though I have no idea how this is implemented.

**Closed by dsyme** 2022-04-21 01:15 UTC
Labels: Resolution-External
