### ISSUE TITLE
Can't build, can't download MSBuild

### ISSUE THREAD

**Issue by 0x53A** [dotnet/fsharp#7062] opened 2019-06-25 10:18 UTC
when I run ``build.cmd`` I get an error:

![image](https://user-images.githubusercontent.com/4236651/60090684-4c498380-9743-11e9-8041-a12e5cd42b5e.png)

**Comment by 0x53A** [comment] 2019-06-25 10:20
The second invocation fails with a different error:

![image](https://user-images.githubusercontent.com/4236651/60090798-7dc24f00-9743-11e9-86a9-a4556ceddbeb.png)

It created an empty directory ``.tools\msbuild\16.1.0-alpha``, if I delete that, I get back to the first error.

**Comment by dsyme** [comment] 2019-06-25 12:10
Duplicate of https://github.com/dotnet/fsharp/issues/7056

**Closed by dsyme** 2019-06-25 12:10 UTC
