### ISSUE TITLE
[Core] GenerateBundle task for single file publishing fails with v5.0.1

### ISSUE THREAD

**Issue by NicoVIII** [dotnet/fsharp#11111] opened 2021-02-14 10:33 UTC
I'm using the code generator lib [Myriad](https://github.com/MoiraeSoftware/myriad) in my project, which adds a dependency for FSharp.Compiler.Service. This dependency suddenly breaks single file publishing when I'm using v39. With v38 everything works fine.
It looks like the problem is the dependency on FSharp.Core 5.0.1 (https://github.com/dotnet/fsharp/issues/11111#issuecomment-786026543).

**Repro steps**

_Edit: I created a minimal repro: https://github.com/dotnet/fsharp/issues/11111#issuecomment-787057831_

I got the problem in one of my [repos](https://github.com/NicoVIII/MagicCollectionHelper).
As you can see in the commit history and look at the CI results:
the deployment works, if I pin the Service to v38 and does not work, if I use v39 (which depends on FSharp.Core 5.0.1).
1. commit (works): https://github.com/NicoVIII/MagicCollectionHelper/commit/46f09c4e5b19dccf216e2f253a49aaebd01e5cb1
2. commit (broken): https://github.com/NicoVIII/MagicCollectionHelper/commit/b0e874cc14f27d8bb455f30b5ffab1ab7589e20e

With v5.0.1 if I execute following commands in src/MagicCollectionHelper/AvaloniaApp:

```dotnet publish -c Release -r linux-x64 -o "../../../deploy"```

This works.

```dotnet publish -c Release -r linux-x64 -o "../../../deploy" -p:PublishSingleFile=true```

This produces the following error:

```
error MSB4018: The "GenerateBundle" task failed unexpectedly. [/workspaces/MagicCollectionHelper/src/MagicCollectionHelper/AvaloniaApp/MagicCollectionHelper.AvaloniaApp.fsproj]
error MSB4018: System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath [/workspaces/MagicCollectionHelper/src/MagicCollectionHelper/AvaloniaApp/MagicCollectionHelper.AvaloniaApp.fsproj]
error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [/workspaces/MagicCollectionHelper/src/MagicCollectionHelper/AvaloniaApp/MagicCollectionHelper.AvaloniaApp.fsproj]
error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [/workspaces/MagicCollectionHelper/src/MagicCollectionHelper/AvaloniaApp/MagicCollectionHelper.AvaloniaApp.fsproj]
error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/workspaces/MagicCollectionHelper/src/MagicCollectionHelper/AvaloniaApp/MagicCollectionHelper.AvaloniaApp.fsproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/workspaces/MagicCollectionHelper/src/MagicCollectionHelper/AvaloniaApp/MagicCollectionHelper.AvaloniaApp.fsproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/workspaces/MagicCollectionHelper/src/MagicCollectionHelper/AvaloniaApp/MagicCollectionHelper.AvaloniaApp.fsproj]
```

**Expected behavior**

Publishing as single file works also with the current version of FSharp.Core.

**Actual behavior**

See Repro steps. Publishing as single file throws an error.

**Known workarounds**

Use v5.0.0.

**Related information**

Provide any related information (optional):

* OS: Manjaro (Development happens inside of a devcontainer)
* .NET 5.102
* Visual Studio Code

**Comment by njlr** [comment] 2021-02-25 16:24
I had this issue but due to `FSharp.Core` version `5.0.1`. 

This line in `paket.dependencies` is a work-around:

```
nuget FSharp.Core 5.0.0
```

**Comment by NicoVIII** [comment] 2021-02-26 08:14
Alright, the compiler service seems to depend on FSharp.Core 5.0.1.
I will try to reproduce that without the CompilerService but I updated the issue to FSharp.Core.

**Comment by cartermp** [comment] 2021-02-26 16:07
I can't reproduce this on the latest macOS with a console app + updated FSharp.Core to 5.0.1 and FCS 39 on the .NET SDK 5.0.103, regardless of paket or nuget.

@njlr did you see this also on linux?

**Comment by njlr** [comment] 2021-02-26 17:56
> I can't reproduce this on the latest macOS with a console app + updated FSharp.Core to 5.0.1 and FCS 39 on the .NET SDK 5.0.103, regardless of paket or nuget.
> 
> @njlr did you see this also on linux?

We saw this on Linux and macOS. Our solution has multiple projects with interdependencies too.

Some of the settings:

```xml
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <PublishTrimmed>true</PublishTrimmed>
        <PublishReadyToRun>false</PublishReadyToRun>
        <Deterministic>true</Deterministic>
        <DeterministicSourcePaths>true</DeterministicSourcePaths>
    </PropertyGroup>
```

**Comment by NicoVIII** [comment] 2021-02-27 11:22
I created a repro repo (has a nice ring to it :smile:).
It started failing, if I have a project without OutputType (should be library) and reference that from a Project with OutputType Exe.
https://github.com/NicoVIII/single-file

This works with FSharp.Core 5.0.0, but not with FSharp.Core 5.0.1.

**Comment by cartermp** [comment] 2021-03-03 06:46
Labeling as a regression and adding to the 16.10 milestone for now. Thanks @NicoVIII for the repro.

**Comment by daz10000** [comment] 2021-03-11 02:16
Ha,  was up till 1am this morning with this problem and I tracked it down (and also built a very minimal repro attached).  This is a delightful collision of things.   The single file publishing has an absolute prohibition against two files getting published to the same output file path but isn't smart enough to deconflict cases where the files are identical.   There seem to be some cases where the build machinery adds two copies of FSharp.Core to a project.  It doesn't affect regular builds because one probably just gets pasted over the other and they are identical.   With 5.0.1 there was an xml file added to the package

`diff -u3 5.0.0/fsharp.core.nuspec 5.0.1/fsharp.core.nuspec`

```
+    <contentFiles>
+      <files include="**/FSharp.Core.xml" buildAction="None" copyToOutput="true" flatten="true" />
+    </contentFiles>

```

That file gets copied twice in some cases and the bundler gets upset.  If you run net6 prerelease it even emits a helpful message here (of course this highlights another opportunity to make the bundler a little less mindless - if the paths are the same it shouldn't care, even if they are different it should probably do a binary check but anyway if this list is multiple, it fails)

```
System.ArgumentException: Invalid input specification: Found entries 
'C:\xxxxx\.nuget\packages\fsharp.core\5.0.1\contentFiles\any\netstandard2.0\FSharp.Core.xml', 
'C:\xxxxx\.nuget\packages\fsharp.core\5.0.1\contentFiles\any\netstandard2.0\FSharp.Core.xml' with the same BundleRelativePath 'FSharp.Core.xml
```

Fix is to get rid of the xml file from the package for now (or pin to 5.0.0).  My repro attached - it's a two project case where one project brings in the second (empty) project.  Oddly this trips things only with paket adding the packages.  If I simply add the library to two projects directly, something is smart enough to remove the dups but not with the more complex paket build.

[Playground.zip](https://github.com/dotnet/fsharp/files/6119990/Playground.zip)

**Comment by daz10000** [comment] 2021-03-11 20:13
The nice runtime bundlefolks [seem (justifiably) unenthusiastic about patching the bundling](https://github.com/dotnet/sdk/issues/16311) to work around what is probably in the end an SDK issue.  I don't understand why the project setup I attached above results in the FSharp.Core xml file getting added twice but that's probably the root issue really.  Removing the xml file will stop the pain but it's not really at fault.

**Comment by cartermp** [comment] 2021-03-26 04:46
Thanks for the repro. @KevinRansom any thoughts here? It's related to the recent FSharp.Core changes.

**Comment by dsyme** [comment] 2021-08-24 11:23
My understanding is that this is a duplicate of #11143 and was fixed by https://github.com/dotnet/fsharp/pull/11160

**Closed by dsyme** 2021-08-24 11:23 UTC
Labels: Bug, Regression, Area-Compiler, Impact-Medium, Area-Library
