### ISSUE TITLE
F# poject can't be created successfully  

### ISSUE THREAD

**Issue by Jepson109** [dotnet/fsharp#6639] opened 2019-04-26 08:55 UTC
#### Repro steps

1. Open vs 
2. Create a fsharp project

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

#### Expected behavior

the project can be created and build & restore successfully

#### Actual behavior

1. The solution drop list missing 
Note : Except for F# ASP.NET Core Web Application, other f# project can't be created successfully(only for vs)

![image](https://user-images.githubusercontent.com/38854445/56795104-4b2ecf80-6842-11e9-93b3-8ab6ad02fefb.png)

####Environment data 
c:\>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011560
 Commit:    13c0a5fdb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011560\

Host (useful for support):
  Version: 3.0.0-preview5-27624-11
  Commit:  7b5103a1f6

.NET Core SDKs installed:
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010050 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011560 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19225-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27624-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27624-11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Pilchie** [comment] 2019-04-26 21:09
Tagging @brettfo  - what version of VS is this?

**Comment by brettfo** [comment] 2019-04-26 21:30
I'm able to create F# projects in 16.0 RTM; this looks exactly like a current bug in the 16.1 preview, though I'm also confused about the screenshot; it shows a C# file.

**Comment by cartermp** [comment] 2019-04-28 21:00
@Jepson109 Which VS version was used here? AFAIK all project open issues in the 16.1 preview have been resolved.

**Comment by Jepson109** [comment] 2019-04-29 08:31
@cartermp 16.1.0 preview 3.0 [28824.287.d16.1]

**Comment by brettfo** [comment] 2019-04-29 17:02
The F# build in that version of VS is 20190418.1 which still has project issues.  Looking through the 16.1 builds, any build after `28826.107.d16.1` will have the updated F# package, but how and when those builds get promoted, I'm not sure.  My suggestion is to regularly open the VS installer tool and check for updates to the preview until the appropriate build gets pushed through all of the release channels.

**Comment by KevinRansom** [comment] 2019-04-30 21:20
@Jepson109, 

could you please let us know which version of VS you are using:
Use help about, and select the copy info button to collect the info on the clip board.

BTW.  your screenshot shows this happening with a C# file loaded, did you also see this for C# projects, or did the C# file, just happen to be on screen at the time?


Thanks

Kevin.

**Comment by cartermp** [comment] 2019-05-19 22:36
Closing issue - 16.1 seems to be just fine for F# in my testing, please re-open if there's a new reproduction

**Closed by cartermp** 2019-05-19 22:36 UTC
Labels: needs repro
