### ISSUE TITLE
Error about missing symbols when trying to build a project using types from Feliz.PrimeReact

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#17813] opened 2024-09-27 14:45 UTC
Consider this project:
```fsproj
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Program.fs"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Feliz" Version="2.8.0" />
      <PackageReference Include="Feliz.PrimeReact" Version="0.3.0" />
    </ItemGroup>
</Project>
```

```fsharp
open Feliz

Prime.button |> ignore
```

When trying to build it, there's an unusual error:
```
Error FS0193 : The module/namespace 'ReactApi' from compilation unit 'Feliz' did not contain the val 'ValLinkagePartialKey(createElement)'
```

**Comment by kerams** [comment] 2024-09-28 14:52
If the point of this issue is the cause of the error rather than the message itself, it's because Feliz.PrimeReact is not compatible with Feliz 2, which no longer contains `createElement`. My guess is that because `button` is inline, the "method body transplant" fails in an atypical way, since the `createElement` referenced from Feliz.PrimeReact.dll does not exist. Were the function not inline (and the project run in .NET, not Fable), you'd probably get a type load exception at run time.

**Comment by T-Gro** [comment] 2024-09-30 10:37
Which means the error should also go away if only "Feliz.PrimeReact" is referenced and it takes the right Feliz version as a dependency?

Can I close this issue, or do you there is anything actionable?

**Closed** 2024-10-07 16:57 UTC
Labels: Bug, Needs-Triage
