### ISSUE TITLE
FS3511 warning when using `for...in` in task CE with .NET SDK 6.0.400 in Release builds

### ISSUE THREAD

**Issue by sasmithjr** [dotnet/fsharp#13657] opened 2022-08-09 22:01 UTC
In the latest SDK (6.0.400), I'm receiving a FS3511 warning with `for...in` loops in `task` when building for Release. This warning wasn't present in previous SDKs (e.g. 6.0.302)

**Repro steps**

1. In a new console application, replace Program.fs with the following code:

```fsharp
let v =
    task {
        for value in [1;2;3] do
            printfn $"{value}"
    }
    
printfn "Hello from F#"
```
2. `dotnet build -c Release`

Can repro with https://github.com/sasmithjr/FS3511-repro-for..in

**Expected behavior**

Builds without warning

**Actual behavior**

Receive the warning `warning FS3511: This state machine is not statically compilable. A resumable code invocation at '(2,4--2,8)' could not be reduced. An alternative dynamic implementation will be used, which may be slower. Consider adjusting your code to ensure this state machine is statically compilable, or else suppress this warning.`

**Known workarounds**

Suppressing the warning or using collection `iter` functions.

**Related information**

* Operating system: macOS 12.5 on an M1 MBP
* .NET Runtime kind (.NET Core, .NET Framework, Mono) .NET Core, SDK 6.0.400

Thanks for the help, and please let me know if I can provide anymore info.

**Comment by edgarfgp** [comment] 2022-08-10 08:30
Might be work checking if this fixed in VS and VS4Mac 17.3 as I think there was a fix a similar code generation BUG see https://github.com/dotnet/fsharp/pull/13415 ?

**Comment by TimLariviere** [comment] 2022-08-10 08:41
I encountered the exact same issue a few days ago, but it only shows up when I build in Release mode.
Debug mode doesn't seem to give me any warning. 

Tried today building against dotnet `6.0.303` and `6.0.400`. Both have the same behavior: no warning in debug build, warning `FS3511` in release mode because of `for .. in .. do`

**Comment by vzarytovskii** [comment] 2022-08-10 10:07
> Might be worth checking if this fixed in VS and VS4Mac 17.3 as I think there was a fix a similar code generation BUG see #13415 ?
No, I pretty sure it's a different issue. But that fix might've caused it to break in .400.

**Comment by jcmrva** [comment] 2022-08-10 20:21
We have several functions with `for ... in` inside a Task CE, but only one of them is now getting the warning (an error in our project).

**Comment by Thorium** [comment] 2022-08-11 07:36
13415 is totally separate issue of this.

- 13415 is a fix for the situation where F# did incorrect things when the warning FS3511 happens.
- This issue is that the warning happens.

As Tim said this issue is not related to 6.0.400 and happened also before.

**Closed** 2022-08-16 11:01 UTC
Labels: Bug, Area-Compiler-StateMachines

**Comment by cmeeren** [comment] 2022-09-14 10:49
I'm also seeing this crop up in CI, whereas it wasn't there previously (for the same code). As the OP describes, this specifically happens when using `for ... in` in a `task` CE.

> As Tim said this issue is not related to 6.0.400 and happened also before.

@TimLariviere said this happened in 6.0.303. @sasmithjr said in the OP that this did not happen with  6.0.302. There's no inconsistency; the behavior seems to have been introduced in 6.0.303.

> I'm closing as a duplicate of this: #12038

Considering the above, how is this a duplicate of #12038? This has nothing to do with `task` CEs defined as top-level values.
