### ISSUE TITLE
Show literal value, not just type, on mouse over in editor

### ISSUE THREAD

**Issue by BentTranberg** [dotnet/fsharp#7026] opened 2019-06-21 07:48 UTC
Feature request: Show the value of the literal when mousing over in VS editor, and not just the type.

Literal values are compile time, so I assume VS should be able to retrieve this information easily enough.

Often use of several literals can be found clumped together in a match sequence or something. It would be nice not to have to look up every one of them to see their value, but simply mouse over one after another.

Perhaps even the value as expressed in the source can be shown in certain cases. E.g. an int literal defined as hex should also be shown in hex when mousing over, and maybe even exactly as defined in the source.

For large strings or strings with invisible characters, some shortening and reformatting might be vise.

**Comment by drvink** [comment] 2019-06-21 08:31
> Perhaps even the value as expressed in the source can be shown in certain cases. E.g. an int literal defined as hex should also be shown in hex when mousing over

This is how it is done in C# in VS. Given:

```csharp
namespace csscratch {
[Flags]
enum T {
    X = 1,
    Y = 2,
    Z = 4
}

class Hober {
    const T T_XY = T.X | T.Y;
    const int Y = 1 + 1;
}
}
```

...hovering over `T_XY` gives a popup of `(constant) T Hober.T_XY = T.X | T.Y`, and hovering over `Y` gives a popup of `(constant) int Hober.Y = 1 + 1`. (I haven't seen any IDE which does stuff like folding constants in editor popups, with the exception of some (language supporting type-level integers, tooling) tuples; regardless, it seems preferable here to just show the literal source for the sake of clarity--just my two cents.)

**Comment by cartermp** [comment] 2019-06-21 17:15
Closing as duplicate of #5300

**Closed by cartermp** 2019-06-21 17:15 UTC
Labels: Feature Request
