### ISSUE TITLE
Broken F# shadowed variables evaluation

### ISSUE THREAD

**Issue by eterekhin** [dotnet/fsharp#11908] opened 2021-08-02 14:00 UTC
**Version Used**: 
Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 2.1

**Steps to Reproduce**:
Simple F# solution on .net framework or core. Use the screenshot to reproduce, please
![image](https://user-images.githubusercontent.com/48148702/127867765-7da7bd32-e7f9-4850-939b-45f1e102c506.png)

```fs
[<EntryPoint>]
let main argv =
    let x = [1;2;3;4;5;6]
    let x = List.filter (fun x -> x % 2 = 0) x
    let x = List.tail x
    printf "%A" x
    0
```

**Expected Behavior**:
I expected that the popup evaluation of the shadowed variable ```x``` to show me a list containing 2 items, not six. Seems like CSharpExpressionCompiler can't emit the correct IL for the debugger interpreter. The result of whatever  ```x``` I tried to evaluate is a list defined on a 4th line. Is it a bug in Roslyn expression compiler or is the compiler not designed to compile in F# context?  I noticed that it works fine with evaluation of ordinary F# variables (not shadowed), may it be possible to fix that for shadowed ones?

**Actual Behavior**:
Whatever  ```x```  I am trying to evaluate the debugger returns the same result (value of  variable ```x``` defined on the 4th line)

**Comment by cartermp** [comment] 2021-08-03 03:10
This is a duplicate of https://github.com/dotnet/fsharp/issues/3704

**Comment by auduchinok** [comment] 2021-08-03 06:17
@TIHan @cartermp It seems it should be possible to fix it on the Roslyn side, since it knows what variables are in scope at given `ilOffset` and simply ignores the offset, taking the first variable with the used name instead.

**Comment by dsyme** [comment] 2021-08-25 12:36
Fixed and in main

**Closed by dsyme** 2021-08-25 12:36 UTC
Labels: Area-Debug, Impact-Low, Feature Improvement

**Comment by auduchinok** [comment] 2022-01-05 07:18
@dsyme I've just found the screenshot of the case after which we'd initially started the discussion on the team the last summer and wanted to share it. The case used immutable values and it'd really helped if it was possible to inspect how they differed by hovering each one after stepping down:

<img width="624" alt="Screenshot 2021-07-26 at 22 03 34" src="https://user-images.githubusercontent.com/3923587/148175287-f2561f19-bad2-4cf5-a962-ca82b33f915e.png">
