### ISSUE TITLE
F# find all references does not find any.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8823] opened 2020-03-27 20:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/731217/f-find-all-references-does-not-find-any.html)._

---
Find all references doe not find any references at all..  I reduced it to the simplest example.

open System

let ValueUsedSomewhere = TimeSpan.FromMinutes 1.0

[<EntryPoint>]
let main argv =
    printfn "Value is %A" ValueUsedSomewhere
    0

Selecting find all references on "let ValueUsedSomewhere =" finds none at all even though it is clearly used.

---
#### Visual Studio Feedback System on 9/11/2019, 10:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/17/2019, 10:03 PM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Visual Studio Feedback System on 3/27/2020, 11:47 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by realparadyne** [comment] 2020-03-27 21:16
On 16.6 preview 2, it will find the references after doing a build or after closing / re-opening the solution.

But it still doesn't seem to find them after editing only.

**Comment by cartermp** [comment] 2020-03-28 01:00
Formatted code sample here:

```fsharp
open System

let ValueUsedSomewhere = TimeSpan.FromMinutes 1.0

[<EntryPoint>]
let main argv =
    printfn “Value is %A” ValueUsedSomewhere
    0
```

Possibly related issues:

* https://github.com/dotnet/fsharp/issues/6243
* https://github.com/dotnet/fsharp/issues/3308
* https://github.com/dotnet/fsharp/issues/3372
* https://github.com/dotnet/fsharp/issues/3053

We should audit all of these and close->dupe things as needed

**Comment by cartermp** [comment] 2020-03-28 01:02
Thanks for confirming that @realparadyne - I suspect it's related to some other issues we have in the F# hookups to VS, since this does not reproduce with Ionide. The core routine in the compiler service seems fine.

**Comment by cartermp** [comment] 2020-08-14 03:49
fixed by https://github.com/dotnet/fsharp/pull/9934

**Closed by cartermp** 2020-08-14 03:49 UTC
Labels: Area-IDE Language Service, bug, regression
