### ISSUE TITLE
Request: Shared Project Support

### ISSUE THREAD

**Issue by webwarrior-ws** [dotnet/fsharp#3666] opened 2017-09-29 13:44 UTC
F# Shared Project type is not available in Visual Studio, unlike C# Shared Project.

Visual Studio 2017 version 15.3.5

See https://bugzilla.xamarin.com/show_bug.cgi?id=40954

**Comment by cartermp** [comment] 2017-10-02 01:36
Dupe of this: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/6429294-add-support-for-universal-apps-shared-projects

But I'm likely to go through and close out the old uservoice things since we see far more activity in GitHub and the tools are OSS.

**Comment by 0x53A** [comment] 2018-08-31 13:41
Would be nice to have (if it works well) for isomorphic f# projects using fable.

That would make it clear which code is shared between client and server.

**Comment by zpodlovics** [comment] 2018-08-31 17:31
Even if you have nearly the same source F# code, your project files will be really different for each target. Recently created something like this with symlinked source files and project files for each target (.NET Core/Fable1/Fable2/WebSharper).

**Comment by 0x53A** [comment] 2018-08-31 17:35
The SAFE-Bookstore does something similar: https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Shared/Shared.props

**Comment by cartermp** [comment] 2020-09-03 01:56
I think I'll close this one out as by design, as usage of shared projects is fairly low and isn't the way to do stuff with modern .NET tooling in VS. I suspect there will always be some usage but in the .NET Core -> .NET 5 era of .NET it has little relevance.

**Closed by cartermp** 2020-09-03 01:56 UTC
Labels: Feature Request
