### ISSUE TITLE
VS CodeLens - FSharpCodeLensService throw exception on Visual Studio 2022 preview

### ISSUE THREAD

**Issue by KiruyaMomochi** [dotnet/fsharp#11738] opened 2021-06-28 03:03 UTC
When using F# with CodeLens enabled on Visual Studio 2022, it throws exception "The option value was None".
This also makes user can't save a file.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Create a new F# project in Visual Studio 2022 Preview ("VS").
2. Turn on "Editor > F# > CodeLens" in VS options.
3. Open "program.fs". If it's already open, close it firstly.
4. Edit the code.
5. Press "Ctrl+S" more than two times.
6. If it saves normally, make sure CodeLens is enabled, then try again from step 3.

The solution directory is attached below:
[FSharpReport.zip](https://github.com/dotnet/fsharp/files/6723018/FSharpReport.zip)

**Expected behavior**

The file is correctly saved.

**Actual behavior**

A "save file as" dialog is opened, and when you try to save file, you will get an error.
    ![image](https://user-images.githubusercontent.com/65301509/123572350-a7b11f00-d7fe-11eb-8b3b-1eef91126adf.png)

**Known workarounds**

Disable CodeLens.

**Related information**

When inspecting "F# language service" output, you will find an exception message.
```
[F#][ERROR 10:43:03 AM] Context: Buffer Changed
Exception Message: The option value was None
Parameter name: option
Stack Trace:    at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 11
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@159-188.Invoke(Unit _arg15) in D:\workspace\_work\1\s\vsintegration\src\FSharp.Editor\CodeLens\FSharpCodeLensService.fs:line 159
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at <StartupCode$FSharp-Editor>.$FSharpCodeLensService.clo@155-186.Invoke(AsyncActivation`1 ctxt) in D:\workspace\_work\1\s\vsintegration\src\FSharp.Editor\CodeLens\FSharpCodeLensService.fs:line 155
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105
```

* Operating system: Windows 10 Build 21390.co_release.210521-1658
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET 6.0.100-preview.5.21302.13
* Editing Tools (e.g. Visual Studio Version, Visual Studio): Visual Studio 2022 Version 17.0.0 Preview 1.1

**Comment by psfinaki** [comment] 2022-10-06 13:33
So I believe this should have been fixed in #14019 
Basically, I removed all the instances of `Option.get` in the CodeLens code so this thing shouldn't happen there anymore.

That said, I cannot reproduce this even in the mainstream VS without the above fix. 

Anyway, closing for now, please reopen if this error somehow pops up again.

**Closed by psfinaki** 2022-10-06 13:33 UTC
Labels: Bug, Impact-Low, Area-LangService-CodeLens
