### ISSUE TITLE
FSC.exe crashes compiling high fieldcount records in Optimize/Release builds (>= 103)

### ISSUE THREAD

**Issue by supergrade** [dotnet/fsharp#6754] opened 2019-05-16 19:21 UTC
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. In F# code, make a record that has > 103 fields
2. Build with "Optimize" turned on (in a trivial project, this is release mode)

Repro solution
[FSCompilerCrasher.zip](https://github.com/dotnet/fsharp/files/3188672/FSCompilerCrasher.zip)

Basically, I just put in a record with 110 named 'int' fields.

#### Expected behavior

Can compile release / optimizing mode without FSC.exe crashing out

#### Actual behavior

Build of release/optimizing mode errors out with:

Microsoft.FSharp.Targets(277,9): error MSB6006: "fsc.exe" exited with code -1073741571

#### Known workarounds

Cut down the number of fields in the records, or turn off optimization.

#### Related information 

Provide any related information 

Windows 10
Visual Studio 2019 16.0.4
Severe if you want a large record

**Comment by KevinRansom** [comment] 2019-05-16 19:24
@supergrade, 

110 isn't really **that**  large a number of fields :-) , so for sure it should be able to cope with this.  We will take a look, and thanks for the  report.

**Comment by cartermp** [comment] 2019-05-16 20:13
This is a duplicate of #6258 and has been fixed. It will be available in the bits that correspond to the 16.1 release.

**Closed by cartermp** 2019-05-16 20:13 UTC

**Comment by KevinRansom** [comment] 2019-05-16 20:35
@supergrade,

@cartermp is correct, VS2019.1 is quite close to release, you can download the preview from here:

https://visualstudio.microsoft.com/downloads/

click on download preview.

Thanks

Kevin
