### ISSUE TITLE
Namespaces are highlighted as symbols when module name is a substring of a namespace

### ISSUE THREAD

**Issue by nosami** [dotnet/fsharp#4816] opened 2018-05-02 12:18 UTC
In the screenshot below, we have a module named `Test` and a namespace `Test.Namespace`. The `open Test.Namespace` statement is highlighted incorrectly. It looks as if `checkResults.GetSemanticClassification(range)` is returning incorrect colorization. Probably related to this PR https://github.com/Microsoft/visualfsharp/pull/3932/files

I haven't tested in VS on Windows yet, but I would assume that it has the same issue.

![image](https://user-images.githubusercontent.com/667194/39522765-2377f86a-4e0b-11e8-879a-ccf3a22ca451.png)

#### Repro steps

Paste this code into an editor

```fs
namespace Test.Namespace
module Test = ()
open Test
namespace Test.Namespace
open Test.Namespace
```

#### Expected behavior

`open Test.Namespace` shouldn't be highlighted any differently to any other namespace.

#### Actual behavior

`Test` is highlighted as if it were the `Test` module

**Comment by auduchinok** [comment] 2018-05-02 12:42
Dupe of #4658?

**Comment by cartermp** [comment] 2020-06-20 01:25
This doesn't resolve anymore for me in 16.6 + https://github.com/dotnet/fsharp/pull/9511 (classification likely had nothing to do with this)

![image](https://user-images.githubusercontent.com/6309070/85188269-3ee1af00-b25a-11ea-95f5-a3b3caa1db2f.png)

**Closed by cartermp** 2020-06-20 01:25 UTC
Labels: Resolution-Fixed
