### ISSUE TITLE
Interpolated strings have indentation issues

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#15105] opened 2023-04-17 19:14 UTC
Compile this:

````
module Repro

    let doSomeWork () =
        let hide () =
            """#interactiveprompt "hide" """

        let interaction () = $"""
{   hide()}
"""
        interaction()

    printfn "%s" (doSomeWork())
````
That it compiles correctly.
Now replace 
````{   hide()}````
With
````{hide()}````

And observe these errors:
````
>C:\Users\kevinr\source\repos\ConsoleApp19\ConsoleApp19\Program.fs(8,7): warning FS0058: Possible incorrect indentation: this token is offside of context started at position (7:9). Try indenting this token further or using standard formatting conventions.
1>C:\Users\kevinr\source\repos\ConsoleApp19\ConsoleApp19\Program.fs(7,9): error FS0588: The block following this 'let' is unfinished. Every code block is an expression and must have a result. 'let' cannot be the final code element in a block. Consider giving this block an explicit result.
1>C:\Users\kevinr\source\repos\ConsoleApp19\ConsoleApp19\Program.fs(10,9): error FS0010: Unexpected identifier in binding. Expected incomplete structured construct at or before this point or other token.
1>C:\Users\kevinr\source\repos\ConsoleApp19\ConsoleApp19\Program.fs(3,5): error FS3118: Incomplete value or function definition. If this is in an expression, the body of the expression must be indented to the same column as the 'let' keyword.
1>C:\Users\kevinr\source\repos\ConsoleApp19\ConsoleApp19\Program.fs(12,5): error FS0010: Incomplete structured construct at or before this point in definition. Expected incomplete structured construct at or before this point or other token.
1>    1 Warning(s)

````

**Comment by abonie** [comment] 2023-06-01 15:03
This is actually duplicate of https://github.com/dotnet/fsharp/issues/13728

**Closed** 2023-06-01 15:04 UTC
Labels: Bug, Area-Compiler-Syntax
