### ISSUE TITLE
Autocompletion incorrectly inserting "double" and "in" keywords in some scenarios

### ISSUE THREAD

**Issue by chadunit** [dotnet/fsharp#6099] opened 2019-01-15 02:28 UTC
Using these settings:

![image](https://user-images.githubusercontent.com/25489524/51150945-4fecec00-182e-11e9-84f9-a98522580360.png)

Observe this behavior:

![vs completion](https://user-images.githubusercontent.com/25489524/51151003-87f42f00-182e-11e9-9d13-55deec10af3c.gif)

First, it inserted `double` upon hitting enter, when I wanted `do`. (This is with nightly; non-nightly exhibits same completion behavior without inserting a newline.)

Second, it inserted `in` upon hitting space, when I wanted `i` for the loop variable. (With nightly and non-nightly.) Granted in this case there was invalid syntax in the file, but I find this is not an uncommon temporary occurrence during heavy editing. If that throws off autocompletion then maybe it should avoid or be less aggressive about auto-inserting when there is an issue in the file.

Third, is there any way to configure it to never guess/auto-insert anything upon space or enter, and only ever accept upon tab key? (For instance, consider Visual Studio Code which has the `"editor.acceptSuggestionOnEnter": "off"` setting, and I think by default never accepts on space.) 

#### Known workarounds

Disable `Show completion list after a character is typed`.

#### Related information 

Visual Studio Community 2017 15.9.4
Visual F# Tools release 15.8.20181029.1 and nightly 15.8.20181217.1
.NET Core SDK 2.2.101

**Comment by abelbraaksma** [comment] 2019-01-15 11:03
>  is there any way to configure it to never guess/auto-insert anything upon space or enter, and only ever accept upon tab key?

This issue happens all the time in different guises, and this suggestion could be the silver bullet. I've gotten so used to hitting escape each time, I hardly notice it.

Also, an artificial delay of 400ms or so can help a lot. Other editors have that, which prevents it from popping up if you hit the space key before the timeout elapses.

**Comment by dsyme** [comment] 2021-10-30 16:13
Looks to me like a duplicate of #11145, at least should be considered with it in #12318

**Comment by dsyme** [comment] 2021-10-30 16:13
I'll close as we should have

**Closed by dsyme** 2021-10-30 16:13 UTC
Labels: Bug, Area-IDE Language Service, Impact-Low
