### ISSUE TITLE
Unnecessary base ctor virtual call

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#4757] opened 2018-04-19 12:58 UTC
```fsharp
type I() = class end
```
```
.method public specialname rtspecialname 
            instance void .ctor () cil managed 
        {
            // Method begins at RVA 0x2050
            // Code size 9 (0x9)
            .maxstack 8

            IL_0000: ldarg.0
            IL_0001: callvirt instance void [mscorlib]System.Object::.ctor()
            IL_0006: ldarg.0
            IL_0007: pop
            IL_0008: ret
        } // end of method I::.ctor
```
Compare to C#:
```csharp
class I 
{
    public I() {}
}
```
```il
.method public hidebysig specialname rtspecialname 
        instance void .ctor () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 7 (0x7)
        .maxstack 8

        IL_0000: ldarg.0
        IL_0001: call instance void [mscorlib]System.Object::.ctor()
        IL_0006: ret
    } // end of method I::.ctor
```

**Comment by dsyme** [comment] 2018-05-01 08:52
My understanding is that the choice of call instruction makes no difference, as .ctor are always known to be non-virtual

**Comment by dsyme** [comment] 2018-05-01 08:53
(Reopening and labelling as "Feature improvement" since parity with C# codegen is a reasonable goal)

**Comment by dsyme** [comment] 2022-03-31 14:17
Closing as duplicate of https://github.com/dotnet/fsharp/issues/2844

**Closed by dsyme** 2022-03-31 14:17 UTC
Labels: Area-Compiler, Feature Improvement
