### ISSUE TITLE
Projects fail to load in Visual Studio Code

### ISSUE THREAD

**Issue by EverybodyKurts** [dotnet/fsharp#11144] opened 2021-02-25 02:47 UTC
I know this issue is probably a duplicate somewhere but was unable to find it among the repo's issues. My apologies if you have to deal with an issue like this yet again.

```
macOS Big Sur
.NET SDK: 5.0.103
code: 1.53.2
ionide: 5.3.2
```

<img width="753" alt="Screen Shot 2021-02-24 at 9 37 26 PM" src="https://user-images.githubusercontent.com/879734/109094762-88877100-76e8-11eb-9c0c-0b6ee642eef6.png">
<img width="425" alt="Screen Shot 2021-02-24 at 9 36 58 PM" src="https://user-images.githubusercontent.com/879734/109094763-89200780-76e8-11eb-90ed-abe56733a1b2.png">

Building `/src/fsharp/FSharp.Core` succeeds but puts the compiled dll in `artifacts/bin/FSharp.Core/Debug/netstandard2.0/FSharp.Core.dll`.

**Comment by baronfel** [comment] 2021-02-25 02:48
This is tracked [here](https://github.com/ionide/proj-info/issues/95), as Proj-Info is the component that Ionide uses for cracking.

**Comment by cartermp** [comment] 2021-02-25 04:06
Will close as a duplicate of dotnet-proj-info. No worries about filing in the wrong place. It's a lot to know all the different repos where things can be! Thanks @baronfel for the pointer.

**Closed by cartermp** 2021-02-25 04:06 UTC
Labels: Resolution-External
