### ISSUE TITLE
Infers incorrect type for record with similar shape

### ISSUE THREAD

**Issue by MCluck90** [dotnet/fsharp#8982] opened 2020-04-17 14:58 UTC
Given two record types with the same keys but different values, a function which returns one of those types attempts to infer the other type in some situations.

**Setup**

```fsharp
type IOError =
| CannotReadFile
| CannotWriteFile
type NetworkError =
| SocketClosed
| ConnectionRefused

type FileError = { Reason : string; Code : IOError }
type ServerError = { Reason : string; Code : NetworkError }
```

**Reproduce**

```fsharp
let f () : FileError =
    let x = {
        Reason = "reason"
        Code = IOError.CannotReadFile
        (*     ^^^^^^^^^^^^^^^^^^^^^^
          This expression was expected to have type
              'NetworkError'    
          but here has type
              'IOError'  
        *)
    }
    x
```

**Expected behavior**

The return type should help with inferring the correct type for `x`.

**Actual behavior**

The type of `x` is determined based on the declaration order of `FileError` and `ServerError`.

**Known workarounds**

```fsharp
let f () : FileError =
    {
        Reason = "reason"
        Code = IOError.CannotReadFile
    }
```

```fsharp
let f () : FileError =
    let x : FileError = {
        Reason = "reason"
        Code = IOError.CannotReadFile
    }
    x
````

```fsharp
let f () : FileError =
    let x = {
        FileError.Reason = "reason"
        Code = IOError.CannotReadFile
    }
    x
```

* Windows 10
* .NET Core

**Comment by cartermp** [comment] 2020-04-22 20:07
This isn't always intuitive, but this behavior my be improved, but it quite tightly locked into the core design of record inference. When there are no type annotations or type-directed rules to follow, record inference will pick whatever it saw last when binding to a particular "shape". You can see a similar example like this.

```fsharp
type A = { X: int; Y: double }
type B = { X: int; Y: string }

let f x : A = { x with Y = 12 }
```

Perhaps the presence of the outer type annotation could be used to influence type inference here, but this could get awfully tricky for larger functions or methods with many different kinds of record "shapes" to consider. This is why the usual resolution in F# (and other ML-style languages) is to add a type annotation.

**Comment by abelbraaksma** [comment] 2020-04-23 11:25
The alternative "rule of thumb" that I use is to make sure that each record has at least one unique field name. This doesn't help with partial updates with `with`, if the field name is not involved, but generally it helps a lot, both for visual distinction (you don't have to hover to find the type), and for type inference.

(this won't help when types overlap that are outside of your code base)

**Comment by cartermp** [comment] 2020-08-31 23:01
I will close this as by design, since I don't think there's a way to change this without breaking some other code out there. Just a quirk of names and type inference.

**Closed by cartermp** 2020-08-31 23:01 UTC
Labels: Resolution-By Design
