### ISSUE TITLE
type check internal error for interface with static abstract member that is implemented as instance member

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/fsharp#16156] opened 2023-10-22 20:26 UTC
Reported by @pblasucci.

```fsharp
type IFoo<'T> =
   abstract DoIt: unit -> string
   static abstract Other : int -> int
type MyFoo = {
   Value : int
} with
  interface IFoo<MyFoo> with
    member me.DoIt() = string me.Value
    member _.Other(value) = value + 1
```

**Actual behavior**

> error FS0193: internal error: Unable to load one or more of the requested types.
> Method not found: 'Int32 IFoo`1.Other(Int32)'.

**Expected behavior**

For now, suggesting to default to the existing message for missing override:

> error FS0855: No abstract or interface member was found that corresponds to this override

It could also be more explicit about the member existing but not being defined as static.

**Comment by T-Gro** [comment] 2023-10-23 16:45
This should give a better typechecking error about the missing member.
Should have been `static membe Other()` (without the instance pointer)

**Comment by edgarfgp** [comment] 2023-10-24 21:48
Duplicate of https://github.com/dotnet/fsharp/issues/14316

**Closed** 2023-11-02 10:34 UTC
Labels: Bug, Impact-Medium, Area-Diagnostics, Area-Compiler-Checking
