### ISSUE TITLE
`dotnet test` command error when building new project

### ISSUE THREAD

**Issue by jkone27** [dotnet/fsharp#15819] opened 2023-08-17 15:40 UTC
```
Testhost process for source(s) '/workspaces/DualSourceAdapter/test/DualSourceAdapter.Tests/bin/Debug/net7.0/DualSourceAdapter.Tests.dll' exited with error: Error:
  An assembly specified in the application dependencies manifest (DualSourceAdapter.Tests.deps.json) was not found:
    package: 'FSharp.Core', version: '7.0.300'
    path: 'lib/netstandard2.1/FSharp.Core.dll'
. Please check the diagnostic logs for more information.
```

here is a reference for repro , run `dotnet test` : https://github.com/jkone27/DualSourceAdapter

**Comment by vzarytovskii** [comment] 2023-08-17 16:50
It looks like it's testhost issue, with loading assemblies? Should it be transferred to vstest? 

@nohwnd @Evangelink can you folks please help us figuring out what's the problem?

**Comment by vzarytovskii** [comment] 2023-08-17 16:54
Though the lack of FSharp.Core.dll in the output is weird, might be an issue.

@KevinRansom do you know why would it happen?

**Comment by vzarytovskii** [comment] 2023-08-17 17:00
`FSharp.Core.dll` gets copied to `test\DualSourceAdapter.Example\DualSourceAdapter.Example.csproj` when you build, but not to the test project, and not to the lib output itself (not sure if it happens by default though).

Is it something test sdk not doing? It works in the compiler project though.

**Comment by KevinRansom** [comment] 2023-08-17 21:10
Add this line to the project file:

````
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.1" />
````
````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.1" />
    <PackageReference Include="xunit" Version="2.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DualSourceAdapter\DualSourceAdapter.fsproj" />
  </ItemGroup>

</Project>
````

````
C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [c:\kevinransom\DualSourceAdapter\src\DualSourceAdapter\DualSourceAda
pter.fsproj]
  DualSourceAdapter -> c:\kevinransom\DualSourceAdapter\src\DualSourceAdapter\bin\Debug\net7.0\DualSourceAdapter.dll
  DualSourceAdapter.Tests -> c:\kevinransom\DualSourceAdapter\test\DualSourceAdapter.Tests\bin\Debug\net7.0\DualSourceAdapter.Tests.dll
Test run for c:\kevinransom\DualSourceAdapter\test\DualSourceAdapter.Tests\bin\Debug\net7.0\DualSourceAdapter.Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.7.0-preview-23317-01+919ec8358820228cc5fa77ef000051c1d6875399 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 36 ms - DualSourceAdapter.Tests.dll (net7.0)
````

**Comment by baronfel** [comment] 2023-08-17 21:15
A bit of clarity - the `Microsoft.NET.Test.Sdk` PackageReference is what drives the integration with `dotnet test` - no project without it is reasonably expected to work here. It's technically possible to make a project without this reference function with `dotnet test`, but you'd have to set a number of MSBuild knobs yourself that aren't super well-documented.

**Comment by vzarytovskii** [comment] 2023-08-18 09:02
Ok, closing this, since it's by design.

**Closed by vzarytovskii** 2023-08-18 09:02 UTC
Labels: Bug, Needs-Triage
