### ISSUE TITLE
Autocomplete Not Working for Some Type Extensions outside their Source Project

### ISSUE THREAD

**Issue by bryanedds** [dotnet/fsharp#7073] opened 2019-06-27 22:31 UTC
**Reproduction steps**

1. Clone the Nu Game Engine - https://github.com/bryanedds/Nu.git
2. Open Nu.sln.
3. Build all (doing a nuget Package Restore if required).
4. Open Nelmish.fs sample project and go to line 29 - https://github.com/bryanedds/Nu/blob/master/Projects/Nelmish/Nelmish.fs#L29
Attempt to trigger auto-complete on the dot after `DecrementButton.`

**Expected behavior**

Show a drop-down box for autocomplete on the `DecrementButton` reference.

**Actual behavior**

No drop-down box is shown, instead the status bars says "Locating the symbol under the caret..." indefinitely.

**Known workarounds**

None. This is a very major issue because the Entity type is the most important type in Nu, and not having autocomplete for this basically makes the engine unusable for client.

**Related information**

I know this used to work fine, but since I've been in the engine code for many months, I don't remember exactly when it last worked. Autocomplete on an Entity will work if you're in the engine code (it works fine in, say, https://github.com/bryanedds/Nu/blob/master/Nu/Nu/WorldTests.fs#L42), but outside of the project in which the type extensions are defined, it doesn't work. Autocomplete also does work everywhere for similar types Layer, Screen, and Game. It just doesn't work for Entity types when they are used outside the project in which they are defined.

* Operating system

Windows 10 Home

* .NET Runtime kind (.NET Core, .NET Framework, Mono)

.Net Framework 4.6

* Editing Tools (e.g. Visual Studio Version, Visual Studio)

Visual Studio 16.4.1
Visual Studio 15.9.13
Visual Studio 15.8.7 (an old version I happened to have lying around)

I've attempted to make a smaller reproduction case for this issue, but I've not yet found a way to do so successfully. Sometimes these things are too tough to isolate to make that a practical approach.

**Note on Urgency**

A user complained that this bug makes the engine basically unusable -

bryanedds/Nu#233

I can't disagree with him - autocomplete for the engine's primary type, Entity, is absolutely crucial because Entity properties are defined with type extensions due to their dynamic nature. Game engine entities must have some sort of dynamic property system in order to be customized by end-users.

This is the highest priority bug in Nu right now and a show-stopper for a new release and advocacy campaign I was about to undertake. I'm glad it came up now rather than later, but I feel helpless.

Sorry to sound too panicky, but this regression puts the engine dead in the water as far as adoption is concerned. If need be, I can ramp up on building and debugging these tools to fix this issue myself. I am really that impacted.

**Comment by bryanedds** [comment] 2019-06-27 22:41
A user complained that this bug makes the engine basically unusable -

https://github.com/bryanedds/Nu/issues/233

I can't disagree with him - autocomplete for the engine's primary type, Entity, is absolutely crucial because Entity properties are defined with type extensions due to their dynamic nature. Game engine entities must have some sort of dynamic property system in order to be customized by end-users.

This is the highest priority bug in Nu right now and a show-stopper for a new release and advocacy campaign I was about to take.

Sorry to sound too panicky, but this regression puts the engine dead in the water as far as adoption is concerned.

**Comment by dsyme** [comment] 2019-06-28 15:57
I agree that autocomplete should be showing here. 

There is something in the solution horking autocomplete on the "Entity" type.  If I add an extension member into 'Nu' for the 'string' type then it shows correctly:

```
[<AutoOpen>]
module FacetModule =

    type System.String with 
       member x.P = 1

    type Entity with 
        ...
```

I can then use it from the location where things are failing

@bryanedds If you have time to reduce down the repro size by binary chopping away on the set of content/extension-members etc included in `Nu` then it might reveal which combination of things is proving problematic.  I can look at it on Monday if you don't have time.

**Comment by cartermp** [comment] 2019-06-28 17:41
Labeling as a bug for now since this also reproduces in VS 2017 as per the report. Is there an older VS where this doesn't reproduce? If so, we'll adjust this label to call it a regression.

As for priority for others (@TIHan, @KevinRansom, @brettfo), we're currently locking down on F# 4.7/.NET Core 3.0. Once that's in good shape we'll probably take a look at the issues to address for the next milestone.

**Comment by cartermp** [comment] 2019-06-28 17:42
Of course, if @dsyme or someone else supplies a fix in the interim, we'll gladly review it with aims to merge for the next available milestone 🙂.

**Comment by nanodesu88** [comment] 2019-06-28 18:19
Autocomplete does not works in Rider too

**Comment by bryanedds** [comment] 2019-06-28 18:35
Thank you so much for looking into this! I admit I was literally worried sick with worry when I found out how big this problem was for my engine.

I can actually remove about 95% of the Entity extension declarations, and did do this yesterday in an attempt to localize the problem. However, I still could not find a workaround.

With your suggestion, I will work more on my side to attempt to assist in this endeavor.

Thank you all!

**Comment by bryanedds** [comment] 2019-06-28 18:56
> As for priority for others (@TIHan, @KevinRansom, @brettfo), we're currently locking down on F# 4.7/.NET Core 3.0. Once that's in good shape we'll probably take a look at the issues to address for the next milestone.

Is there any way to push out this lock down? Without this feature, my game engine is effectively valueless in the eyes of potential adopters, and waiting for the fix until the next release will delay my upcoming adoption campaign. I have yet to be able to get Don's workaround to solve the problem.

@dsyme - Are you saying that inserting just that one string type extension worked around the issue for you locally? That workaround is not currently duplicating for me.

**Comment by bryanedds** [comment] 2019-06-28 19:36
@dsyme - Okay, thanks to your binary search suggestion, I've actually narrowed the problem down to a single line -

https://github.com/bryanedds/Nu/blob/5b40993e07ac884ddd8a613e009ba3afdda30ca5/Nu/Nu/WorldDispatchers.fs#L132

`        member this.GetEffectHistory world : Effects.Slice Deque = this.Get Property? EffectHistory world`

I tried changing the method name and the parameter names, and I tried replacing `Property? EffectHistory` with `"EffectHistory"`, but that did not fix the issue on that line. Then I tried changing the type from `Effects.Slice Deque` to `Effects.Slice list`, and that restored autocomplete!

So the problem has something to do with the Nito.Collections.Deque type being returned from a type extension function! Utterly mysterious! There must be something about that type that is horking the autocomplete engine. I tried explicitly qualifying that type, but that didn't make any difference.

Okay, now that I know the specifics, I can certainly workaround by inlining the GetEffectHistory function. It will be a minor omission in my API, but frankly, that property is really not going to be something most users would need to access anyway.

Next, I will attempt to create a smaller repro case using this type.

Thank you again, everyone!

**Comment by bryanedds** [comment] 2019-06-28 19:51
Okay, I've pushed the work-around here - https://github.com/bryanedds/Nu/commit/de12cb797912cbcc1f46d3790bb061daee377470

So **this is no longer a high-priority for Nu** - the workaround is sufficient. However, I'm currently still trying to create the smaller repro example in another project.

**Comment by dsyme** [comment] 2019-07-01 11:44
@bryanedds Your project `Nelmish` is missing a reference to `Nito.Collections.Deque` . This is causing an internal failure when generating the completion list.  The error shows when you actually use the extension member.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0074	The type referenced through 'Nito.Collections.Deque`1' is defined in an assembly that is not referenced. You must add a reference to assembly 'Nito.Collections.Deque'.	Nelmish	C:\GitHub\tmp\Nu\Projects\Nelmish\Nelmish.fs	31	Active
```

It may be better to use nuget packages with correct dependencies rather than referencing assemblies by hand, that should avoid this kind of problem.

It's interesting that this doesn't repro in VS2017.  I suppose it is still a regression in error recovery from the missing assembly reference.

**Comment by bryanedds** [comment] 2019-07-02 06:23
Ah, thank you. Looks like you got the repro case figured out sooner than I could!

I'll look into finding Nito.Collections.Deque via nuget - I think I originally put it in there manually because it wasn't yet available via nuget.

**Comment by cartermp** [comment] 2019-09-04 18:36
Locked for non-technical reasons. For those who are interested in this suggestion and have more to add, please file a new issue and we will close this and triage it appropriately.

**Closed** 2021-08-24 00:59 UTC
Labels: Area-IDE Language Service, Feature Improvement
