### ISSUE TITLE
Generated assembly raise System.BadImageFormatException at runtime

### ISSUE THREAD

**Issue by Twinside** [dotnet/fsharp#11484] opened 2021-04-25 13:39 UTC
A well typed F# program explode with a System.BadImageFormatException at runtime

**Repro steps**

Executing the following program raise immediately at runtime, this is an extract and reduction of production code

```fsharp
open System.Collections.Generic

type 'a IDummyInterface = interface end

type public CharDummy() =
    interface char IDummyInterface with

type RS<'a, 'aEnum> when 'a : struct =
    {
        Ranges : struct('a * 'a)[]
    }
    static member Empty = { Ranges = Array.empty } : RS<'a, 'aEnum>

    member self.Union b =
        let aux _ _ = failwith "Just to have something in here"
        // removing the call make the program pass somehow
        let built =
            aux (Array.toList self.Ranges) (Array.toList b.Ranges) : _ List
        failwith "Just to have something in here" : RS<'a, 'aEnum>

type Builder<'vertex, 'tag, 'a, 'aEnum>
    when 'a : struct
     and 'aEnum :> 'a IDummyInterface =
    {
        Transitions : RS<'a, 'aEnum> List
    }
    /// <summary>
    /// Calling this method raise a System.BadImageFormatException exception
    /// </summary>
    member self.Freeze () =
        let mergeRange (acc : RS<'a, 'aEnum>) range = acc.Union range
        Seq.fold mergeRange RS<'a, 'aEnum>.Empty self.Transitions

    /// <summary>
    /// This method pass with the added type annotation
    /// </summary>
    member self.FreezePass () =
        let mergeRange (acc : RS<'a, 'aEnum>) (range : RS<'a, 'aEnum>) = acc.Union range
        Seq.fold mergeRange RS<'a, 'aEnum>.Empty self.Transitions

    static member Fresh =
        { Transitions = List() } : Builder<'vertex, 'tag, 'a, 'aEnum>

[<EntryPoint>]
let main argv =
    Builder<int, int, char, CharDummy>.Fresh.Freeze() |> ignore
    0
```

Call the `FreezePass` raise no exception.

Attached to the ticket, a small F# project with the code from the ticket along with a project file:

[fsharp-report.zip](https://github.com/dotnet/fsharp/files/6372020/fsharp-report.zip)

**Expected behavior**

No `System.BadImageFormatException`, but the one generated by the `failwith` call, or, if not possible a compile time error.

**Actual behavior**

`System.BadImageFormatException` is raised

**Known workarounds**

Specifying the precise type signature make the code generation better.

**Related information**

I dug around and decompiled the generated assembly using dnSpy, and we can see the following C# decompiled code for Freeze

```csharp
public Program.RS<a, aEnum> Freeze()
{
	object mergeRange = Program<a, aEnum>.mergeRange@31.@_instance;
	return SeqModule.Fold<Program.RS<a, aEnum>, Program.RS<a, aEnum>>(((Program<a, aEnum>.mergeRange@31$contract)mergeRange).DirectInvoke<a, aEnum>(), Program.RS<a, aEnum>.Empty, this.Transitions@);
}
```

with the following IL:

```il
// Token: 0x0600001F RID: 31 RVA: 0x00002438 File Offset: 0x00000638
.method public hidebysig 
	instance class Program/RS`2<!a, !aEnum> Freeze () cil managed 
{
	// Header Size: 12 bytes
	// Code Size: 34 (0x22) bytes
	// LocalVarSig Token: 0x11000017 RID: 23
	.maxstack 5
	.locals init (
		[0] object mergeRange
	)

	/* (hidden)-(hidden) D:\Users\Vince\Documents\Coding\fsharp-report\Program.fs */
	/* 0x00000644 7E3700000A   */ IL_0000: ldsfld    class Program/mergeRange@31<!0, !1> class Program/mergeRange@31<!a, !aEnum>::@_instance
	/* 0x00000649 0A           */ IL_0005: stloc.0
	/* (32,9)-(32,66) D:\Users\Vince\Documents\Coding\fsharp-report\Program.fs */
	/* 0x0000064A 06           */ IL_0006: ldloc.0
	/* 0x0000064B A51B00001B   */ IL_0007: unbox.any class Program/mergeRange@31$contract<!a, !aEnum>
	/* 0x00000650 6F1000002B   */ IL_000C: callvirt  instance class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Program/RS`2<!0, !1>, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Program/RS`2<!!0, !!1>, class Program/RS`2<!0, !1>>> class Program/mergeRange@31$contract<!a, !aEnum>::DirectInvoke<!a, !aEnum>()
	/* 0x00000655 283900000A   */ IL_0011: call      class Program/RS`2<!0, !1> class Program/RS`2<!a, !aEnum>::get_Empty()
	/* 0x0000065A 02           */ IL_0016: ldarg.0
	/* 0x0000065B 7B3300000A   */ IL_0017: ldfld     class [System.Collections]System.Collections.Generic.List`1<class Program/RS`2<!2, !3>> class Program/Builder`4<!vertex, !tag, !a, !aEnum>::Transitions@
	/* 0x00000660 281100002B   */ IL_001C: call      !!1 [FSharp.Core]Microsoft.FSharp.Collections.SeqModule::Fold<class Program/RS`2<!a, !aEnum>, class Program/RS`2<!a, !aEnum>>(class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!1, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0, !!1>>, !!1, class [System.Runtime]System.Collections.Generic.IEnumerable`1<!!0>)
	/* 0x00000665 2A           */ IL_0021: ret
} // end of method Builder`4::Freeze
```

Whereas the Freezepass method produce the following:

```csharp
public Program.RS<a, aEnum> FreezePass()
{
	FSharpFunc<Program.RS<a, aEnum>, FSharpFunc<Program.RS<a, aEnum>, Program.RS<a, aEnum>>> mergeRange = Program<a, aEnum>.mergeRange@38-2.@_instance;
	return SeqModule.Fold<Program.RS<a, aEnum>, Program.RS<a, aEnum>>(mergeRange, Program.RS<a, aEnum>.Empty, this.Transitions@);
}
```

```cil
.method public hidebysig 
	instance class Program/RS`2<!a, !aEnum> FreezePass () cil managed 
{
	// Header Size: 12 bytes
	// Code Size: 24 (0x18) bytes
	// LocalVarSig Token: 0x11000019 RID: 25
	.maxstack 5
	.locals init (
		[0] class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Program/RS`2<!a, !aEnum>, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Program/RS`2<!a, !aEnum>, class Program/RS`2<!a, !aEnum>>> mergeRange
	)

	/* (hidden)-(hidden) D:\Users\Vince\Documents\Coding\fsharp-report\Program.fs */
	/* 0x00000674 7E3B00000A   */ IL_0000: ldsfld    class Program/'mergeRange@38-2'<!0, !1> class Program/'mergeRange@38-2'<!a, !aEnum>::@_instance
	/* 0x00000679 0A           */ IL_0005: stloc.0
	/* (39,9)-(39,66) D:\Users\Vince\Documents\Coding\fsharp-report\Program.fs */
	/* 0x0000067A 06           */ IL_0006: ldloc.0
	/* 0x0000067B 283900000A   */ IL_0007: call      class Program/RS`2<!0, !1> class Program/RS`2<!a, !aEnum>::get_Empty()
	/* 0x00000680 02           */ IL_000C: ldarg.0
	/* 0x00000681 7B3300000A   */ IL_000D: ldfld     class [System.Collections]System.Collections.Generic.List`1<class Program/RS`2<!2, !3>> class Program/Builder`4<!vertex, !tag, !a, !aEnum>::Transitions@
	/* 0x00000686 281100002B   */ IL_0012: call      !!1 [FSharp.Core]Microsoft.FSharp.Collections.SeqModule::Fold<class Program/RS`2<!a, !aEnum>, class Program/RS`2<!a, !aEnum>>(class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!1, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!0, !!1>>, !!1, class [System.Runtime]System.Collections.Generic.IEnumerable`1<!!0>)
	/* 0x0000068B 2A           */ IL_0017: ret
} // end of method Builder`4::FreezePass
```

I was not expecting the `object` type for `mergeRange` in the wrong version

Additional information:

* Windows 10
* .net5.0
* Using visual studio but can reproduce using `dotnet run`

**Comment by cartermp** [comment] 2021-06-09 01:49
Sorry for no update recently. I believe that this is a duplicate of the issue logged here: https://github.com/dotnet/fsharp/issues/11620

Another workaround is to build in Release mode, although neither workaround is ideal. We've investigated the issue and will be supplying a fix.

**Closed by cartermp** 2021-06-09 01:49 UTC
