### ISSUE TITLE
Byref parameter can't be passed if defined in another file

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#6088] opened 2019-01-13 14:51 UTC
Reference-type byref parameter can't be passed if defined in another file

#### Repro steps

Provide the steps required to reproduce the problem

```
//file1.fs
module File1
 
let mutable y: byte[] = null
 
//Program.fs
open System
open File1
 
let byrefFun (x: byref<byte[]>) =
    x <- Array.zeroCreate 10
 
[<EntryPoint>]
let main argv =
    byrefFun &y
    printfn "%A" y
    0
```

#### Expected behavior

The code above works

#### Actual behavior
I see two errors

```
Error	FS0073	internal error: One of your modules expects the type '<StartupCode$ConsoleApp19>.$ConsoleApp19' to be defined within the module being emitted.  You may be missing an input file	ConsoleApp19	C:\Users\odind\source\repos\ConsoleApp19\unknown	1	Active

Error	FS0073	internal error: The local field y@3-1 was referenced but not declared	ConsoleApp19	C:\Users\odind\source\repos\ConsoleApp19\unknown	1	Active
```

#### Known workarounds

For some reason this code still builds (build works, but not rebuild), but doesn't work stable. This particular example works, but in more complex case I get 
`InvalidProgramException: Common Language Runtime detected an invalid program.`

#### Related information 

Provide any related information 

.Net Core 2.2
Fsharp 4.5.4

**Comment by TIHan** [comment] 2019-01-14 21:39
This is indeed a bug. It doesn't build the first time, but it does the second and after is very weird.

My expectation is that it should work, like you said.

**Comment by dsyme** [comment] 2022-04-01 04:47
Duplicate of #4715

**Closed by dsyme** 2022-04-01 04:47 UTC
Labels: Bug, Area-Compiler, Impact-Medium
