### ISSUE TITLE
Abstract properties are allowing additional generic arguments

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/fsharp#12198] opened 2021-09-28 02:02 UTC
We're seeing F# compiler emitting generic properties (which are invalid in the .NET assembly file format).

**Repro steps**

From Don in https://github.com/dotnet/linker/issues/2281#issuecomment-928334425

For example this: should be invalid but isn't being ruled out by the F# compiler:

```fsharp
type Thing =
    abstract Foo : 'Out with get, set
```
F# Interactive reports an error for this:
```fsharp
> type Thing =
-     abstract Foo : 'Out with get, set
- ;;


error FS0192: internal error: want tyvar #0, but only had 0 tyvars
```

**Expected behavior**

The code fails to compile.

**Actual behavior**

The code compiles and produces a property that doesn't work at runtime (CLR will throw `BadImageFormatException` when trying to use a `PropertyInfo` for it).

**Known workarounds**

Don't write such code.

**Comment by jwosty** [comment] 2021-09-28 04:02
I would like to take a crack at this one.

**Comment by dsyme** [comment] 2021-09-28 10:54
> I would like to take a crack at fixing this.

The problem is here:
```
    let ComputeCanInferExtraGeneralizableTypars (parentRef, canInferTypars, memFlagsOpt: SynMemberFlags option) =
        canInferTypars &&
        (match memFlagsOpt with
         | None -> true
         | Some memberFlags ->
            match memberFlags.MemberKind with
            // can't infer extra polymorphism for properties
            | SynMemberKind.PropertyGet | SynMemberKind.PropertySet -> false
            // can't infer extra polymorphism for class constructors
            | SynMemberKind.ClassConstructor -> false
            // can't infer extra polymorphism for constructors
            | SynMemberKind.Constructor -> false
            // feasible to infer extra polymorphism
            | _ -> true) &&
        (match parentRef with
         | Parent tcref -> not tcref.IsFSharpDelegateTycon
         | _ -> true) // no generic parameters inferred for 'Invoke' method
```

An abstract property with get and set is falling through to `// feasible to infer extra polymorphism`

The fix may be as simple as adding a cases for SynMemberKind.PropertyGetSet.  

```
            | SynMemberKind.PropertyGetSet
            | SynMemberKind.PropertyGet
            | SynMemberKind.PropertySet -> false
```
At this stage, the get and set haven't been split apart into separate metadata items for abstract properties. This also explains to me why the bug hasn't been noticed before - abstract properties which are only `get` or `set` are checked properly.  Notive the difference below:


```
> type IA = abstract P : 'T with get;;

  type IA = abstract P : 'T with get;;
  -----------------------^^

stdin(1,24): error FS0039: The type parameter 'T is not defined.

> type IA = abstract P : 'T with get, set;;


error FS0192: internal error: want tyvar #0, but only had 0 tyvars
```

**Comment by edgarfgp** [comment] 2022-10-09 17:34
Now that https://github.com/dotnet/fsharp/pull/13978 is merged . I think we can close this @vzarytovskii ?

**Closed** 2022-10-09 17:35 UTC
Labels: Bug, Impact-Medium, Area-Compiler-Checking
