### ISSUE TITLE
Expecting a warning or error in match expression using "OR" patterns

### ISSUE THREAD

**Issue by laurentiudiaconu** [dotnet/fsharp#7267] opened 2019-07-23 09:48 UTC
The compiler does not report either an error or a warning if the same union case is present in two (or more) "OR" patterns in a match expression.

**Repro steps**
See the following code:

    type SomeUnion = 
        | A 
        | B
        | C

    let test (x: SomeUnion) =
        match x with 
        | A | B -> false
        | C | A -> true

Case 'A' appears in both match blocks, but the compiler does not report either an error or a warning. While here the problem can be easily spotted, it's easy to imagine much more complicated situations where that is not the case (e.g., discriminated union with many cases).

**Expected behavior**
I'd expect a warning to be reported by the compiler. It already does that when "OR" patterns are not used. E.g.,

    let testWarning (x: SomeUnion) =
         match x with 
         | A -> false
         | B -> false
         | A -> true // warning!
         | C -> true

**Actual behavior**

The compiler does not report either an error or a warning.

**Known workarounds**

The workaround is to avoid using "OR" patterns.

**Comment by cartermp** [comment] 2019-07-23 16:57
This is definitely a bug, the A rule should give a warning saying that it's never going to valid for a match on the OR case.

**Comment by dsyme** [comment] 2020-08-31 15:41
Well, by our current implied spec for unused match clauses this is not a bug - the checking isn't for unused parts of a pattern, but rather if the entire clause is unused.

I'll label this as feature improvement, but it would require a complete rejig of the completeness checking logic I believe.

**Comment by abelbraaksma** [comment] 2020-08-31 21:37
@dsyme This is a duplicate of this: https://github.com/dotnet/fsharp/issues/7878

We should probably turn them into a language suggestion.

**Comment by cartermp** [comment] 2020-08-31 21:52
Cloing as duplicate, thanks @abelbraaksma

**Closed by cartermp** 2020-08-31 21:52 UTC
Labels: Area-Compiler, Feature Improvement, Resolution-Duplicate
