### ISSUE TITLE
Unused Declarations throws internal error in FSharpPlus

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#10346] opened 2020-10-27 23:08 UTC
1. Using latest `main`, build a hive and open FSharpPlus.sln: https://github.com/fsprojects/fsharpplus
2. Open `Enumerator.fs` under `FSharpPlus.TypeLevel`

![image](https://user-images.githubusercontent.com/6309070/97371409-5bc46980-186e-11eb-9b52-12223c39bba7.png)

Stack trace:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected exception raised in compiler: field curr not found in type MapEnumerator`1
FSharp.Compiler.ErrorLogger+InternalError: field curr not found in type MapEnumerator`1C:\Users\phcart\source\scratch\FSharpPlus\src\FSharpPlus\Extensions\Enumerator.fs (216,9--216,22) IsSynthetic=false



   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorR(ErrorLogger x, Exception exn) in C:\Users\phcart\source\repos\fsharp\src\fsharp\ErrorLogger.fs:line 377

   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.Error[b](ErrorLogger x, Exception exn) in C:\Users\phcart\source\repos\fsharp\src\fsharp\ErrorLogger.fs:line 396

   at FSharp.Compiler.ErrorLogger.error[a](Exception exn) in C:\Users\phcart\source\repos\fsharp\src\fsharp\ErrorLogger.fs:line 475

   at FSharp.Compiler.TypedTree.RecdFieldRef.get_RecdField() in C:\Users\phcart\source\repos\fsharp\src\fsharp\TypedTree.fs:line 3887

   at FSharp.Compiler.Infos.RecdFieldInfo.get_RecdField() in C:\Users\phcart\source\repos\fsharp\src\fsharp\infos.fs:line 1811

   at FSharp.Compiler.SourceCodeServices.SymbolHelpers.rangeOfRecdFieldInfo(FSharpOption`1 preferFlag, RecdFieldInfo rfinfo) in C:\Users\phcart\source\repos\fsharp\src\fsharp\symbols\SymbolHelpers.fs:line 381

   at FSharp.Compiler.SourceCodeServices.SymbolHelpers.rangeOfItem(TcGlobals g, FSharpOption`1 preferFlag, Item d) in C:\Users\phcart\source\repos\fsharp\src\fsharp\symbols\SymbolHelpers.fs:line 390

   at FSharp.Compiler.SourceCodeServices.UnusedDeclarations.definitions@320.Invoke(FSharpSymbolUse su)

   at Microsoft.FSharp.Collections.ArrayModule.Filter.populateMask[a](FSharpFunc`2 f, a[] src, UInt32[] maskArray) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\array.fs:line 532

   at Microsoft.FSharp.Collections.ArrayModule.Filter.createMask[a](FSharpFunc`2 f, a[] src, UInt32[]& maskArrayOut, UInt32& leftoverMaskOut) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\array.fs:line 574

   at Microsoft.FSharp.Collections.ArrayModule.Filter.filter[a](FSharpFunc`2 f, a[] src) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\array.fs:line 670

   at Microsoft.FSharp.Collections.ArrayModule.Filter[T](FSharpFunc`2 predicate, T[] array) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\array.fs:line 677

   at FSharp.Compiler.SourceCodeServices.UnusedDeclarations.getUnusedDeclarationRanges(FSharpSymbolUse[] symbolsUses, Boolean isScript) in C:\Users\phcart\source\repos\fsharp\src\fsharp\service\ServiceAnalysis.fs:line 318

   at FSharp.Compiler.SourceCodeServices.UnusedDeclarations.getUnusedDeclarations@346-1.Invoke(FSharpSymbolUse[] _arg1) in C:\Users\phcart\source\repos\fsharp\src\fsharp\service\ServiceAnalysis.fs:line 346

   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 404

   at <StartupCode$FSharp-Compiler-Private>.$FSharpCheckerResults.GetAllUsesOfAllSymbolsInFile@1927-3.Invoke(AsyncActivation`1 ctxt) in C:\Users\phcart\source\repos\fsharp\src\fsharp\service\FSharpCheckerResults.fs:line 1927

   at <StartupCode$FSharp-Editor>.$UnusedDeclarationsAnalyzer.Microsoft-CodeAnalysis-ExternalAccess-FSharp-Diagnostics-IFSharpUnusedDeclarationsDiagnosticAnalyzer-AnalyzeSemanticsAsync@39-13.Invoke(AsyncActivation`1 ctxt) in C:\Users\phcart\source\repos\fsharp\vsintegration\src\FSharp.Editor\Diagnostics\UnusedDeclarationsAnalyzer.fs:line 39

   at Microsoft.VisualStudio.FSharp.Editor.Pervasive.Bind@118-3.Invoke(AsyncActivation`1 ctxt) in C:\Users\phcart\source\repos\fsharp\vsintegration\src\FSharp.Editor\Common\Pervasive.fs:line 118

   at Microsoft.VisualStudio.FSharp.Editor.FSharpCheckerExtensions.FSharpChecker-ParseAndCheckDocument@62-6.Invoke(AsyncActivation`1 ctxt) in C:\Users\phcart\source\repos\fsharp\vsintegration\src\FSharp.Editor\LanguageService\FSharpCheckerExtensions.fs:line 62

   at Microsoft.VisualStudio.FSharp.Editor.FSharpCheckerExtensions.FSharpChecker-ParseAndCheckDocument@53-2.Invoke(AsyncActivation`1 ctxt) in C:\Users\phcart\source\repos\fsharp\vsintegration\src\FSharp.Editor\LanguageService\FSharpCheckerExtensions.fs:line 53

   at Microsoft.VisualStudio.FSharp.Editor.FSharpCheckerExtensions.FSharpChecker-ParseAndCheckDocument@51-7.Invoke(AsyncActivation`1 ctxt) in C:\Users\phcart\source\repos\fsharp\vsintegration\src\FSharp.Editor\LanguageService\FSharpCheckerExtensions.fs:line 51

   at <StartupCode$FSharp-Core>.$Async.AwaitAndBindChildResult@1509-7.Invoke(AsyncActivation`1 ctxt) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 1509

   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 104

   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 169

   at <StartupCode$FSharp-Core>.$Async.AwaitWaitHandle@1444-4.Invoke(Object _arg3, Boolean timeOut) in C:\Users\phcart\source\repos\fsharp\src\fsharp\FSharp.Core\async.fs:line 1449

   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object state, Boolean timedOut)

   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by vzarytovskii** [comment] 2021-07-22 15:41
I couldn't reproduce it on latest main (both dev16 and dev17), gonna close it.

**Closed by vzarytovskii** 2021-07-22 15:41 UTC
Labels: Area-FCS, Bug, Needs-More information
