### ISSUE TITLE
Duplicate DU cases in match should be a compiler warning or error

### ISSUE THREAD

**Issue by l3m** [dotnet/fsharp#15217] opened 2023-05-12 11:20 UTC
```fsharp 
type Number = 
| One 
| Two 
| Three

let isEven = 
   function 
   | Number.Two -> true
   | Number.One
   | Number.Two  // <- duplicate case that is an error and can never be matched for a Number.Two input
   | Number.Three -> false
```

When matching a DU, a duplicate case that can never be reached should lead to a compiler error. With larger DUs (many cases) and more complex matches, a developer might spot the second entry first and come to an erroneous conclusion about which path is taken. 

**Repro steps**

See inline example above.

**Expected behavior**

The compiler should complain about the second Number.Two entry

**Actual behavior**

The compiler silently compiles this code. It works as expected when the case can never be reached (putting the first Number.Two last), but not in the case above.

**Known workarounds**

None as far as I can see.

**Comment by sudqijawabreh** [comment] 2023-06-02 15:18
I've tried this on F# interactive F# 12.5.0 for F# 7.0 and it raised this warning : "warning FS0026: This rule will never be matched" . 
@l3m Is this expected or we want another warning?

**Comment by morgankenyon** [comment] 2023-07-11 15:12
Trying to provide a bit of context, would this be the [relevant section](https://github.com/dotnet/fsharp/blob/main/src/Compiler/Checking/PatternMatchCompilation.fs#L1653-L1657) in the compiler that generates that current warning?

```fsharp
if warnOnUnused then
    let used = HashSet<_>(accTargetsOfDecisionTree dtree [], HashIdentity.Structural)

    clauses |> List.iteri (fun i c ->
        if not (used.Contains i) then warning (RuleNeverMatched c.Range))
```

Then where the [actual warning](https://github.com/dotnet/fsharp/blob/main/src/Compiler/FSStrings.resx#L996-L998) is defined.

As @sudqijawabreh said, were we wanting to upgrade this to an actual error?

**Comment by kerams** [comment] 2023-07-11 15:17
Duplicate of https://github.com/dotnet/fsharp/issues/3448.

**Comment by Martin521** [comment] 2024-02-11 18:58
As mentioned above, this is a duplicate of #3448 and should be closed.

**Closed** 2024-02-12 12:18 UTC
Labels: good first issue, Feature Improvement, Theme-Simple-F#, Area-Compiler-PatternMatching, help wanted
