### ISSUE TITLE
Poor GetAllUsesOfAllSymbolsInFile results (on bigger files?)

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#6583] opened 2019-04-19 18:32 UTC
After we've got chunking in https://github.com/Microsoft/visualfsharp/pull/6089 I get truncated results on bigger files. E.g. `GetAllUsesOfAllSymbolsInFile` for TypeChecker.fs only returns symbol uses up to ~3400 line. Reverting this PR locally fixes it for me.

**Comment by cartermp** [comment] 2019-04-23 03:19
@auduchinok I tried using document highlights in that file today (and others), since that relies on that specific API. It was able to highlight all usages of what I needed, though it could be that what it "found" was small enough in scope that it didn't matter. Looking at the code I can't see why this would happen though, since the code processes each chunk...

**Comment by auduchinok** [comment] 2019-05-14 17:17
@cartermp I've just tried to find usages of `SynExpr` type in Visual Studio 2019 (16.0.3). Results indeed missed lots of the references in TypeChecker.fs. In addition to that, highlighting usages of the symbol under caret stops working at some point when moving caret down in that file. It behaves in a somewhat similar way to what I get in Rider without reverting #6089, with the difference is it at least adds the semantic highlighting beyond the point where some features stop working..

Rider (2019.1 dev):
![missingSymbolsRider](https://user-images.githubusercontent.com/3923587/57717636-54160280-7684-11e9-9ab8-15aecd300c07.gif)

Visual Studio 2019 (16.0.3)
![missingSymbolsVS16](https://user-images.githubusercontent.com/3923587/57717640-55dfc600-7684-11e9-8b47-90319124fbd4.gif)

**Comment by cartermp** [comment] 2019-12-17 16:15
@tihan this might be a good one to look at while you're digging into the ` TcSymbolUseData` issues

**Comment by dsyme** [comment] 2020-09-01 20:23
@auduchinok Do you know the status of this?  Or a specific repro?

**Comment by cartermp** [comment] 2020-09-01 20:24
I've noticed this from time to time when selecting a symbol in Typechecker.fs. No other files though.

**Comment by dsyme** [comment] 2020-09-01 20:33
Well, I did "Find all references" on "SynExpr" and got plenty of results all the way through TypeChcker.fs.  The main problem is a large number of duplicates:

![image](https://user-images.githubusercontent.com/7204669/91903176-b55b4e00-ec9a-11ea-9c61-723b2165f8e8.png)

**Comment by cartermp** [comment] 2020-09-01 20:47
Duplicate data shouldn't shown anymore if you are using the latest dogfood (i.e., what will ship in 16.8). So if that's still the case in dogfood then there's a separate issue at play.

This one shouldn't be affected by Find Refs, since Find Refs doesn't call GetAllUsesOfAllSymbolsInFile in either the "symbol is declared in this file" or "symbol is declared elsewhere" cases in VS. Perhaps it's used by Rider?

Either way there is certainly an issue here.

**Comment by auduchinok** [comment] 2020-09-02 11:16
The stable repro was bigger files like `TypeChecker.fs` and we still have #6089 reverted, otherwise it reproduces for us in Rider. I can try looking at it again when updating our repo for the next rider release. Though, we don't yet use the FCS symbols cache, so now there's even more difference compared to what VS does.

**Comment by auduchinok** [comment] 2020-09-02 11:18
@cartermp @dsyme Does symbol usages under caret highlighting work reliably for you in TypeChecker.fs when invoked somewhere down the file (e.g. near the file end)? It's where I've seen it working bad in Visual Studio, as recorded in the gif above.

**Comment by cartermp** [comment] 2020-09-02 14:56
I have noticed symbol highlighting not necessarily getting kicked off in TypeChecker.fs. But it's hard to reproduce.

**Comment by dsyme** [comment] 2022-04-06 06:46
I'm closing this as we haven't seen this problem reported separately and I'm pretty sure it was either a performance or point-in-time problem.

**Closed by dsyme** 2022-04-06 06:46 UTC
Labels: Bug, Impact-Medium, Area-FCS

**Comment by dsyme** [comment] 2022-09-26 23:25
@auduchinok your initial analysis was spot on - the chunking PR was just broken for large files. Presumably this caused the duplicates I saw as well. 

Really annoying we let this slip for so long, especially since you'd reported it.
