### ISSUE TITLE
Custom operation with MaintainsVariableSpaceUsingBind is missing Source translation

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#9858] opened 2020-08-02 18:31 UTC
```fs
type OptionBuilder() =
   member _.Source(x) = Some x
   member _.Return(x) = Some x
   member _.Bind(x, f) = Option.bind f x
   
   [<CustomOperation("custom", MaintainsVariableSpaceUsingBind = true)>]
   member _.Custom(x, arg) = arg

let test() = 
   let option = OptionBuilder()
   option {
      custom 1
      return ()
   }
```

>error FS0001: This expression was expected to have type
    ''a option'    
but here has type
    'int'    

This is missing a call similar to https://github.com/dotnet/fsharp/issues/9406

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEAzAzmgFxAENcBbAHwIE8AHGAAgHlaCBLCAOwCEBXNjABMYUABQBKBgF4AsACgGisjDLARDAPoA6AMoReUMDFEJJUhnuUME8xQ2Wr12gEowCBzibMWIVmwqUVNShNLW42TkETNAZsbxZ2Li1gCMFY61tFTIYAbQAeAGFeXAJfFhFiRM8AIjBi0rJqmIBZYgiCNs5cADViKDZiYAwYHVpiIwBVXAiAc3DI6QYCKF4YcQA+AF1sh2DQopLfaIY+me9T+XlhgiWYEolF7OuGCFYOTkWE974BYTFxbKvKoMADe2TsdUOZAYAEZwYpYO4oB8JNkAL5AA=

EDIT:
Looking at the spec it does not mention a source translation for custom op with bind.

Spec defines custom op with bind as:
``` 
T([<CustomOperator("Cop", MaintainsVarSpaceUsingBind=true)>]cop arg; e, V, C, q) = Assert (q); 
    CL(cop arg; e, V, C(b.Return exp(V)), false)
```

First off Maintains**Var**SpaceUsingBind should read Maintains**Variable**SpaceUsingBind

Then looking at the definition of `CL` we see 

<img width="742" alt="Screenshot 2020-08-02 at 22 19 53" src="https://user-images.githubusercontent.com/4218809/89131601-532df280-d50e-11ea-9e2e-3ee5eb57318f.png">

Specifically: 
>bind: indicator if it is for Bind (true) or iterator (false).

Yet the definition of custom op with bind states false for `bind` while it should clearly be true.

I also believe the definition right after it
```
T([<CustomOperator("Cop")>]cop arg; e, V, C, q) = Assert (q); CL(cop arg; e, V, C(b.Yield exp(V)), false)
```

Should instead be 
```
T([<CustomOperator("Cop", MaintainsVariableSpace=true)>]cop arg; e, V, C, q) = Assert (q); CL(cop arg; e, V, C(b.Yield exp(V)), false)
```

As the spec has multiple issues here I'm not super confident MaintainsVariableSpaceUsingBind not specifying a Source translation as such was explicitly decided on.

**Comment by dsyme** [comment] 2020-08-08 09:38
Hmm interesting from a design-point of view.  

It is by design that source translation is not done on MaintainsVariableSpaceUsingBind - for example, none of the custom operators using MVSUB in queries take sources as arguments, c.f. https://github.com/dotnet/fsharp/blob/master/src/fsharp/FSharp.Core/Query.fsi and it would be incorrect to start apply Source there.  The few custom query operators that take sources (like Join and Group) use the special syntax options where the source positions are known

That said I can see the use case for paramaters that do get source translation for MaintainsVariableSpaceUsingBind  custom operators.  However I think this counts as a design suggestion and would require an additional attribute to indicate this?

If you agree please close this and add a design suggestion, or use the same suggestion as for #9860 as an overall issue for small tweaks to the CE Source translation.

**Comment by dsyme** [comment] 2020-08-24 16:32
Closing as by design

**Closed by dsyme** 2020-08-24 16:32 UTC
Labels: Resolution-By Design
