### ISSUE TITLE
Needless emit of callvirt for nullcheck when C# doesn't do it in corresponding code

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#2844] opened 2017-04-13 05:06 UTC
This link checks out the code for a relatively simple construct.  F# does not necessarily do well.

https://github.com/Spreads/Spreads/commit/b12b3be3b911cb82784ab5e8d10fe1043d3e6dff

**Comment by Huqin-China** [comment] 2017-04-13 06:18
Ah,I think MS should give u more resources.Spreads's author also give his editiong feeling about current F#.

- [ ] the IDE is still not responsive and compilation is slow,While C# projects fly on this machine even with R#

- [ ] Project recompilation is slow and happens on every build, even if there are no changes.do not see changes in referenced C# projects when compiled separately

- [ ] Reload sln times slow than C#(Agree,when open large F project like visualfsharp itself ,it will take 30s or longer to colorize type,or it will be just white text).

- [ ] File and folder ordering and management.(It will be fixed in VS2017 update as I heard recently) 

- [ ] Too slow for the project system for .NetCore

Here are my opnions:

Python PTVS experience even better than F#,that's embarrassing.
drive other team like VBasic here-_-!
Community can only feed back or provide little fixes,most people like me can only describe the issue but no ability to fix that.

**Comment by vasily-kirichenko** [comment] 2017-04-13 07:38
@Huqin-China I don't think any of issues you described will ever be fixed. If they hurt you a lot, switch to another language and IDE.

**Comment by Huqin-China** [comment] 2017-04-13 07:51
@KevinRansom No offence.
I just suggest MS giving u more resource.
What I list before is a copy of Spreads's author  idea.
[https://github.com/Spreads/Spreads/issues/68](url)

**Comment by dsyme** [comment] 2017-04-13 13:52
@Huqin-China  The main issue we will track with this bug is the emit of ``callvirt`` in cases where C# doesn't do it.  

You can suppress this with ``--alwayscallvirt-`` as mentioned on [twitter](https://twitter.com/buybackoff/status/852359143478493184) by @buybackoff .  Some details are https://github.com/Microsoft/visualfsharp/issues/468. But this is not ideal since it's rare that people even know about this flag (I'd forgotten about it).   It's really perfectly safe to use this flag - because in practice the F# values in question are just never null.

I wonder if we should really go back to making ``call`` the default - @v2m convinced us we should be using ``callvirt`` to get more accurate exceptions in the cases where nulls incorrectly leak into F# coding - but I wonder if it's the wrong default having looked at this.  I need to look at the specific test cases again that motivated this.

But what I also really want to know is why we are emitting callvirt at all in a situation where C# doesn't.

**Comment by buybackoff** [comment] 2017-04-13 14:39
@Huqin-China that post was mostly caused by a major frustration with .NET Core in project.json era and the situation is visibly improving, esp. with F# 4.1 and VS2017. Taking a pause did not hurt, but F# will stay there and is getting better.  Remaining issues are either well known and being taken care of, or there is always a workaround with using a C# assembly for low-level imperative things, like in Spreads and Hopac, and this issue is from using that approach.

@KevinRansom  Thanks for reacting to this so fast. I wanted to create an issue mentioning #1637 with some samples and additional benchmarks. In my case I have a collection that often calls small private methods (which suffer from `callvirt`) as well as large (but simple inlineable) private methods with `AggressiveInlining` attribute, which get a double hit. I have confirmed that calling instance methods of the same class in F# also uses `callvirt` instead of `call`, not only in a parent class method calls case. `AggressiveInlining` is also quite important and is often a free lunch for improving performance where JIT is too lazy, and that attribute has nothing to do with F# itself.

@dsyme --alwayscallvirt- is a very easy solution, but there is a compiler warning for that flag saying it is for experiments only. Plus with the comments in the issue #468 it doesn't sound like a good idea to apply it to a non-trivial assembly.

**Comment by dsyme** [comment] 2017-04-13 15:49
The case for using "callvirt" is explained here: http://v2matveev.blogspot.com/2010/11/null-stringgetenumerator.html

Here are some relevant snippets quoted then:

> For more details please refer to the post by Eric Gunnerson [Why does C# always use callvirt](http://blogs.msdn.com/b/ericgu/archive/2008/07/02/why-does-c-always-use-callvirt.aspx). or to Eric Lippert’s comment here: Summing up: Case (1) invoke virtual method: generate callvirt. Case (2) invoke instance method on nullable receiver: generate callvirt to get cheap null check -- yes, this is typesafe. Case (3) invoke instance method on known non-nullable receiver: generate call to avoid null check. Your first example falls into category (2), your second example falls into category (3). (The compiler knows that new never returns null and therefore need not check again.).

**Comment by buybackoff** [comment] 2017-04-13 16:08
Now F# compiler doesn't use the knowledge for case 3 (calling `this.` and `base.` methods). I have noticed that F# compiler inlines small methods at IL level more aggressively than C# (which probably relies more on JIT for that, not sure if C# ever inlines methods in IL), so the issue doesn't affect properties and small methods in most cases.

**Closed** 2024-01-04 20:08 UTC
Labels: Feature Request, Area-Compiler-Optimization
