### ISSUE TITLE
Statically resolved type parameter definition requires space after <

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#8753] opened 2020-03-19 15:07 UTC
It's not obvious that extra space is required unless you actually find it out somehow, especially since regular type parameters don't require it.

```fsharp
type C<'T> =
    class end

type C1< ^T> =
    class end

type C2<^T> =
    class end
```

<img width="566" alt="Screenshot 2020-03-19 at 18 04 58" src="https://user-images.githubusercontent.com/3923587/77081775-2fa95600-6a0c-11ea-99d0-36c37cc71f06.png">

**Comment by cartermp** [comment] 2020-03-20 23:38
I recall this being reported a while ago and the conclusion was that it was effectively a parser bug. It should just get fixed as such.

**Comment by abelbraaksma** [comment] 2020-03-21 23:59
Yes, there have indeed been some reports (not necessarily a complete list, this issue has been popping up from time to time):

* https://github.com/dotnet/fsharp/issues/4794
* https://github.com/fsharp/fslang-suggestions/issues/668
* (related, but not the same) https://github.com/dotnet/fsharp/issues/4607

**Comment by cartermp** [comment] 2020-03-23 02:00
Thanks @abelbraaksma - I'll close this out as a duplicate of https://github.com/fsharp/fslang-suggestions/issues/668 - perhaps I'll write the RFC for that (shouldn't be terribly large) as well since this feels awfully unexpected

**Closed by cartermp** 2020-03-23 02:00 UTC
Labels: Area-Compiler, bug
