### ISSUE TITLE
Async try/with doesn't support breakpoint in handler

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#6353] opened 2019-03-21 12:33 UTC
```
[<EntryPoint>]
let main argv =
    let a = async {
        try
            printfn "hello"
        with
        | e -> 
            printfn "%A" e // Cannot set a breakpoint here while debugging.
    }
    Async.RunSynchronously a
    0
```

During debugging, setting a breakpoint on that line will actually set it on the whole try-with block. It _will_ be hit when the exception is handled, and it _is_ possible to inspect the value of the exception in the Locals window, just not by hovering over it in the debugger. The experience is just not intuitive. I didn't think the breakpoint would hit before actually trying it to make sure.

![image](https://user-images.githubusercontent.com/1631157/54752748-8986fe00-4bb5-11e9-8c9c-2b24947396a2.png)

#### Known workarounds
Add a second line. for example:
```
        | e -> 
            printfn "%A" e // Now a breakpoint can be set
            ()
```
This will allow setting a breakpoint as expected.

#### Related information 
VS 2017 15.9.9
netcoreapp2.1 Console App

**Comment by TIHan** [comment] 2019-03-26 21:18
I can confirm this, and just as a note, setting breakpoints in this code below in the exception handling part also work:
```fsharp
[<EntryPoint>]
let main argv =
    let a = async {
        try
            failwith "hello"
        with
        | e -> 
            printfn "%A" e
            printfn "%A" e
    }
    Async.RunSynchronously a
    0
```

@KevinRansom you may know more about this than me.

**Comment by dsyme** [comment] 2019-03-26 22:50
Looking at this
```
fsc -g --optimize- a.fs
ildasm /out=a.il /linenum a.exe
```
there are several places where emitted sequence point line number ranges span lines 4 to 8, all of which seem suspect.
```
      .line 4,8 : 9,27 ''
...
      .line 4,4 : 9,12 ''
...
``
Ideally we'd track down where these originate from - really nothing coming out of `TcComputationExpression` should span the whole range of the `TryWith`.  Looking at the code:
```
        | SynExpr.TryWith (innerComp, _mTryToWith, clauses, _mWithToLast, mTryToLast, spTry, _spWith) ->
            let mTry = match spTry with SequencePointAtTry(m) -> m | _ -> mTryToLast
            
            if isQuery then error(Error(FSComp.SR.tcTryWithMayNotBeUsedInQueries(), mTry))
            let clauses = clauses |> List.map (fun (Clause(pat, cond, clauseComp, patm, sp)) -> Clause(pat, cond, transNoQueryOps clauseComp, patm, sp))
            let consumeExpr = SynExpr.MatchLambda(true, mTryToLast, clauses, NoSequencePointAtStickyBinding, mTryToLast)
            if isNil (TryFindIntrinsicOrExtensionMethInfo cenv env  mTry ad "TryWith" builderTy) then error(Error(FSComp.SR.tcRequireBuilderMethod("TryWith"), mTry))
            if isNil (TryFindIntrinsicOrExtensionMethInfo cenv env mTry ad "Delay" builderTy) then error(Error(FSComp.SR.tcRequireBuilderMethod("Delay"), mTry))
            Some(translatedCtxt (mkSynCall "TryWith" mTry [mkSynCall "Delay" mTry [mkSynDelay2 (transNoQueryOps innerComp)]; consumeExpr]))
```
the uses of `mTryToLast` look very suspect - though they may not be the only issue - changing these to `mTry` might be a place to start

**Comment by dsyme** [comment] 2019-03-26 23:01
Note that the parser and TypeChecker _tries_ to separate ranges used for debugging (sequence points) from ranges used for error reporting (where you tend to want larger ranges) - by putting ranges used for debugging inside `sp` values, e.g. `SequencePointAtTry(range)`.  This technique generally means we know we're only emitting "good" sequence points no matter how much inlining, closure generation, etc. that we've done - i.e. sequence points that definitely relate back to source text locations. In this case, this means that those `mTryToLast` shouldn't really be relevant to debugging (because they are not inside sequence point values)

The problem is that this methodology is imperfect, especially when doing inlining, or closure-generation or something.  

Anyway ot would be nice to extend the `sp` regime to handle this case.

**Comment by dsyme** [comment] 2021-11-05 14:57
This still repros in main

**Comment by dsyme** [comment] 2022-02-15 18:57
This is fixed in main, for debug code.

![image](https://user-images.githubusercontent.com/7204669/154129890-fc705834-a200-49dc-b3c1-95950a0c2852.png)

**Closed by dsyme** 2022-02-15 18:57 UTC
Labels: Bug, Impact-Medium, Area-Debug
