### ISSUE TITLE
fsi error on ubuntu 19.04 and debian 10 

### ISSUE THREAD

**Issue by scalablecory** [dotnet/fsharp#7633] opened 2019-09-26 18:02 UTC
_From @snashikkar on Thursday, September 26, 2019 2:17:36 PM_

[fsierr.txt](https://github.com/dotnet/core/files/3658199/fsierr.txt)
# Issue Title

Starting dotnet fsi on the cli emits an error on ctrl-c handler installation failure
# General
Details:
snashik@hanuman ~> dotnet fsi                                                                             (base)

> Failed to install ctrl-c handler - Ctrl-C handling will not be available. Error was:
	Could not load file or assembly 'Mono.Posix, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'. The system cannot find the file specified.

_Copied from original issue: dotnet/core#3482_

**Comment by cartermp** [comment] 2019-09-27 15:52
Closing as dupe of #7277

This is resolved and we'll push to get it into the .NET Core 3.1 SDK.

**Closed** 2019-10-01 00:26 UTC
Labels: Resolution-Duplicate
