### ISSUE TITLE
Inconsistent syntax highlighting of type arguments when inheriting a generic base class

### ISSUE THREAD

**Issue by chillitom** [dotnet/fsharp#4792] opened 2018-04-26 13:12 UTC
In VS 15.6 the syntax highlighting of type arguments is inconsistent when inheriting from a base class.

![image](https://user-images.githubusercontent.com/74433/39307500-df5cc9ee-495a-11e8-8564-724c532cc270.png)

In this example the `<` and `>` character are in white for the `handler` function's type definition but the angle brackets on the `GenericController`'s type arguments are in green.  This also applies to commas in between type arguments.

I think the correct behavior should be for `<`, `>` and `,` to be rendered in white here too.

**Comment by smoothdeveloper** [comment] 2018-04-26 19:40
maybe related: #2585

**Comment by cartermp** [comment] 2020-06-20 01:19
Closing as dupe of #2585

**Closed by cartermp** 2020-06-20 01:19 UTC
Labels: Resolution-Duplicate
