### ISSUE TITLE
Regression in dotnet SDK 6.0.300: recursive function value

### ISSUE THREAD

**Issue by Jand42** [dotnet/fsharp#13176] opened 2022-05-22 20:23 UTC
Add following code in a new F# console application project and run it:

```fsharp
do
    let rec sum: list<int> -> int =
        function
        | [] -> 0
        | x :: xs -> x + sum xs

    printfn "Sum: %d" (sum [1; 2; 3])
```

**Expected behavior**

This program should print "Sum: 6". This works as expected with dotnet SDK up to 6.0.203.

**Actual behavior**

Running the program in either VS2022 Version 17.2.1, or via dotnet SDK 6.0.300 or 7.0.100 preview 4 fails with a NullReferenceException.

ILSpy shows that the function value is initialized as null:

```csharp
public static void main@()
{
	FSharpFunc<FSharpList<int>, int> sum = new Program.sum@3(sum);
	ExtraTopLevelOperators.PrintFormatLine(new PrintfFormat<FSharpFunc<int, Unit>, TextWriter, Unit, Unit, int>("Sum: %d")).Invoke(sum.Invoke(FSharpList<int>.Cons(1, FSharpList<int>.Cons(2, FSharpList<int>.Cons(3, FSharpList<int>.Empty)))));
}
```

Exception is thrown on the `sum.Invoke` call.

**Known workarounds**

Rewriting a recursive function value to a normal recursive function works.

Also the bug happens only if the recursive value is not a module member, but happens in a body of a member (or startup code, as with the `do` block in the example).

But more surprisingly, by removing the type annotation from `sum: list<int> -> int`, it gets inferred as the same, but now the code compiles as expected.

This also compiles ok with VS2022 Version 17.2.1, only failing with dotnet SDK 6.0.300 or 7.0.100 preview 4.

**Related information**

I have tested in Windows x64 only, project targeting .NET 6.0.

**Comment by vzarytovskii** [comment] 2022-05-23 09:41
Duplicate of https://github.com/dotnet/fsharp/issues/13043

**Closed** 2022-05-23 09:41 UTC
Labels: Bug
