### ISSUE TITLE
Code lens doesnot appear for net sdk project that is opened with file already open

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#4551] opened 2018-03-16 00:14 UTC
@realvictorprm 

The codelens feature pretty reliably fails to work on a netsdk project for already open source files

If the source file is closed and then re-opened codelens appears in all of its glory.  In fact is appears to interfere with general intellisense as well.

This may be due to some project system stuff, so I will also take a look to see if I can figure out what is causing it.

Repro:
open a dotnetsdk project that was previously closed with still open source files

It may be me, but I don't see it at all in a legacy F# project.
Although the Output log says:

`````
[F#][INFO 05:21:02 PM] Trackingspan V0 →←@[112..128) is being added.
[F#][INFO 05:21:02 PM] Finished updating line lens.
````

**Comment by KevinRansom** [comment] 2018-03-16 00:23
Hmmm the log said:

````
[F#][INFO 05:21:38 PM] Tagged text seq
  [Microsoft.FSharp.Compiler.Layout+NavigableTaggedText;
   Internal.Utilities.StructuredFormat.TaggedTextOps+tag@122;
   Microsoft.FSharp.Compiler.Layout+NavigableTaggedText;
   Internal.Utilities.StructuredFormat.TaggedTextOps+tag@122; ...]
[F#][INFO 05:21:38 PM] Adding ui element for Microsoft.FSharp.Control.FSharpAsync`1[Microsoft.FSharp.Core.FSharpOption`1[System.Tuple`2[System.Collections.Generic.List`1[Internal.Utilities.StructuredFormat.TaggedText],Microsoft.VisualStudio.FSharp.Editor.QuickInfoNavigation]]]

````
And then linekens appeared in the ide.

**Comment by realvictorprm** [comment] 2018-03-16 01:01
This is unnecessary debug output, I've removed it in my last commit to my
branch. Everything which has a warning before is really a warning / meant
as something happened which should not happen at all.

The bug appears on other Pc's too? Darn, OK let's fix this.

Am 16.03.2018 01:23 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by KevinRansom** [comment] 2018-03-16 07:40
@realvictorprm of course we'll fix it my friend.  It's committed so now we are .... that is unfortunately one of the costs associated with our choice of Job :-)

**Comment by realvictorprm** [comment] 2018-03-19 09:23
@KevinRansom In about one week I have time again to put up the PR, before I'm busy with learning :/

**Comment by realvictorprm** [comment] 2018-03-29 10:42
Okay I have now time again to collect my fixes and push them up.

@KevinRansom Should I make an PR with the fixes to the dev15.8 branch or should I create another complete Code Lens PR for master?

**Comment by KevinRansom** [comment] 2018-03-29 17:00
@realvictorprm 

You my friend are surfing in the future and working in dev15.8, the rest of us will catch up after 15.7 ships.

Kevin

**Comment by cartermp** [comment] 2020-10-18 20:19
This no longer reproduces. Tested on a .NET 5 asp.net core application. It also doesn't appear to interfere with the time until colorization. The main thing is that it does appear to require you to have moved the viewport by scrolling to have them fault back in. I'll close this out since the original issue doesn't appear to be the case.

**Closed by cartermp** 2020-10-18 20:19 UTC
Labels: Area-IDE Language Service, Severity-Low, bug
