### ISSUE TITLE
Does `--mlcompatibility` work as intended?

### ISSUE THREAD

**Issue by adam-becker** [dotnet/fsharp#9403] opened 2020-06-08 04:16 UTC
I'm unable to use ML infix operators as identifiers even with the `--mlcompatibility` flag.

**Repro steps**

Provide the steps required to reproduce the problem:

```fsharp
// This causes an error, regardless of the presence of `--mlcompatibility`
let lsr a b = a >>> b
```

**Expected behavior**

According to the documentation, passing the `--mlcompatibility` flag should allow these keywords to be used as identifiers in regular F# code. I would expect this compatibility layer to be disabled by default, as trying to use the `lsr` infix just gives another error:

```fsharp
// This also causes an error
let shiftRight a b = a lsr b
```

So the compiler basically says "how dare you try and misuse this keyword that we also won't accept if used properly."

**Actual behavior**

The flag has no effect in this scenario.

**Known workarounds**

The work around is to change the name of the function, which might be feasible but unsavory. Especially since there's supposed to be a way to change this behavior.

**Related information**

Provide any related information (optional):

```
$ dotnet --version
3.1.300

$ dotnet /usr/share/dotnet/sdk/3.1.300/FSharp/fsc.exe
Microsoft (R) F# Compiler version 10.9.1.0 for F# 4.7
Copyright (c) Microsoft Corporation. All Rights Reserved.```

* Operating system
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
* Editing Tools (e.g. Visual Studio Version, Visual Studio)

**Comment by abelbraaksma** [comment] 2020-06-08 10:43
Did you try this with FSI or the compiler? FSI has some issues with not getting all fsc compiler options through correctly.

**Comment by adam-becker** [comment] 2020-06-08 14:34
@abelbraaksma This was with the compiler. Specifically, invoking the compiler with `dotnet build`. The logging of that command shows that the flag is indeed passed on the command line, but with no change in behavior.

**Comment by cartermp** [comment] 2020-06-08 21:47
I don't think redefining existing keywords as new identifiers has ever been supported, regardless of the mlcompatibility flag. The code isn't valid in OCAML either, which is probably why it's not valid in F# with the flag.

**Comment by adam-becker** [comment] 2020-06-08 22:19
I hate to be a stickler, but the spec says the exact opposite:

```
19.2 Extra Syntactic Forms for ML Compatibility
The following identifiers are also keywords primarily because they are keywords in OCaml. Although F# reserves several OCaml keywords for future use, the /mlcompatibility option enables the use of these keywords as identifiers.

token ocaml-ident-keyword =
    asr land lor lsl lsr lxor mod
```

**Comment by cartermp** [comment] 2020-06-08 22:22
I suspect the spec is wrong here.

**Comment by adam-becker** [comment] 2020-06-08 22:32
I would expect the identifiers to be used as keywords in ML compatibility mode, or usable otherwise. The spec makes it sounds like it works the opposite way (although in reality it doesn't have any effect whatsoever). Needless to say, this is confusing. Can the spec at least be updated to the intended behavior? I'd much prefer just letting these be valid identifiers in regular F# code.

**Comment by cartermp** [comment] 2020-06-08 22:37
I think it's reasonable to update the spec. I wouldn't support adding this to the compiler. @dsyme could speak more about spec updates

**Comment by TheJayMann** [comment] 2020-06-09 00:01
Well, I just ran `fsc /?` and, in the help description, it states the following for the flag.
```
--mlcompatibility              Ignore ML compatibility warnings

**Comment by cartermp** [comment] 2020-07-12 17:50
Closing this out as by design. The spec could be updated to be a bit more clear.

**Closed by cartermp** 2020-07-12 17:50 UTC
Labels: Resolution-By Design
