### ISSUE TITLE
f# intellisense does not list all possible types of entities of the same name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9036] opened 2020-04-23 23:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/987245/f-intellisense-does-not-list-all-possible-types-of.html)._

---
If there are more than one of the same name, say, a module and a type of the same name, the auto completion will only display one of the two.

---
#### Visual Studio Feedback System on 4/12/2020, 11:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by cartermp** [comment] 2020-04-23 23:37
Basic repro:

```fsharp
type MyFancyClass() = class end

module MyFancyClass =
    let clone c = MyFancyClass()


let x = myFa
```

![image](https://user-images.githubusercontent.com/6309070/80159778-ae039580-8580-11ea-9f65-4df42956e67c.png)

Interesting one that's worth thinking about

**Comment by abelbraaksma** [comment] 2020-04-24 08:26
Is this really a bug? I thought this was by design. I vaguely remember that auto complete had, at some time, many the same names and that was considered confusing. Maybe it's not entirely correct, but the pop-out shows the variants, as your screenshot shows. 

Maybe, to prevent confusion (it now shows the last defined, which here is the module), we could add another icon, say an asterisk, which then means "different types of this identifier exist"?

**Comment by cartermp** [comment] 2020-04-24 16:19
@abelbraaksma That's like the what the expectation of the original report is coming from, since modules and classes are distinguished by different icons in the completion list. Of course just having the text `MyFancyClass` is ambiguous between the module and the class, and the "pick what we saw last" behavior will resolve it to the last-seen symbol. This is likely getting surfaced in the completion list, which makes sense because until you type the `()` it will be ambiguous.

So I think it warrants some consideration, but I don't think there's a way to accomplish this without some confusing behavior.

**Comment by cartermp** [comment] 2020-08-31 23:02
Will close this as by design, since the completion list is ultimately influenced by what name resolution picks up. Here, the module "wins" the ambiguity check.

**Closed by cartermp** 2020-08-31 23:02 UTC
Labels: Resolution-By Design
