### ISSUE TITLE
#time in FSI reports instant evaluation on long-running sequence code.

### ISSUE THREAD

**Issue by nhirschey** [dotnet/fsharp#11514] opened 2021-05-01 07:18 UTC
If you have `#time` on and then run code in a sequence pipeline, the evaluator immediately reports `Real: 0.0.0 ...` while the code is still running. If you wrap the same code in List, #time works properly. I can reproduce this at the command line and running interactively in Visual Studio 16.10.0 preview 2.1.

FSI is ``Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0``. 

**Repro steps**

```fsharp
#time "on"

[1..3]
|> Seq.map(fun x ->
    System.Threading.Thread.Sleep(1_000)
    x)
//Real: 00:00:00.000, CPU: 00:00:00.000, GC gen0: 0, gen1: 0, gen2: 0
//val it : seq<int> = seq [1; 2; 3]

[1..3]
|> List.map(fun x ->
    System.Threading.Thread.Sleep(1_000)
    x)
//Real: 00:00:03.011, CPU: 00:00:00.000, GC gen0: 0, gen1: 0, gen2: 0
//val it : int list = [1; 2; 3]    
```
**Expected behavior**

I expect the Sequence version to show that the computation took 3 seconds.

**Actual behavior**

It says that the Sequence version was instant (but the wall clock time is actually 3 seconds).

**Known workarounds**
Use eager collections like List.

* Windows 10

**Comment by kerams** [comment] 2021-05-01 08:58
Well, the code is not running, is it. The sequence is lazy, but in order for FSI to pretty print the resulting value, enumeration needs to take place, and that blocks the UI. In other words, the timing info is correct, because if you do

```fsharp
[<EntryPoint>]
let main _ =
    [1..3]
    |> Seq.map(fun x ->
        System.Threading.Thread.Sleep(1_000)
        x)
    0
```

the application will exit immediately.

**Comment by nhirschey** [comment] 2021-05-01 10:42
It’s not a printing issue. The actual bug came from timing more complicated code, eg parsing a csv file that takes 3 minutes but #time says 0.0 seconds. 

I was going for a simple reproducible example. Maybe ‘sleep’ wasn’t the right choice, but do CsvFile.Rows |> Seq.length on a big file and you’ll see the same thing.

**Comment by kerams** [comment] 2021-05-01 10:44
```fsharp
> seq { 1 .. 100000000 } |> Seq.length;;
//Real: 00:00:00.189, CPU: 00:00:00.187, GC gen0: 0, gen1: 0, gen2: 0
//val it : int = 100000000
```

**Comment by nhirschey** [comment] 2021-05-01 11:32
Better example closer to how it appeared in my code. The last block of code starting with `file.Rows` is the problem section. It does not take 0 seconds.

```fsharp

#time "on"

#r "nuget: FSharp.Data"

open FSharp.Data
open FSharp.Data.CsvExtensions

open System.IO

let tempfile = Path.GetTempFileName()

seq { 1 .. 10_000_000 }
|> Seq.map(fun x -> sprintf "%i,%i,%i,%i" x x x x)
|> Seq.append ["a,b,c,d"]
|> fun lines -> File.WriteAllLines(tempfile,lines)

File.ReadAllLines(tempfile)
// Real: 00:00:03.668, CPU: 00:00:03.703, GC gen0: 153, gen1: 53, gen2: 1
let file =  CsvFile.Load(tempfile)
file.Headers

file.Rows
|> Seq.filter(fun x -> x.["c"].AsFloat() > 50_000.0)
|> Seq.map(fun x -> 
    x.["a"].AsFloat() + x.["b"].AsFloat())
|> Seq.countBy(fun x -> x > 100_000.0)
// Real: 00:00:00.001, CPU: 00:00:00.000, GC gen0: 0, gen1: 0, gen2: 0
// val it : seq<bool * int> = seq [(true, 9950000)]
```

**Comment by kerams** [comment] 2021-05-01 11:44
You're using a lazy sequence on the last couple of lines and it does not get enumerated in your code, but only for the purposes of pretty printing, which brings me back to my original message that this is perfectly fine in my opinion.

**Comment by nhirschey** [comment] 2021-05-01 12:29
I get lazy/eager and that toList forces eager. But countBy forces enumeration of the sequence as well. #time returns info before the sequence is finished enumerating is my point.

**Comment by kerams** [comment] 2021-05-01 12:36
Are you sure? When I run this, nothing is printed until I do `Seq.toList`.

```fsharp
[<EntryPoint>]
let main argv =
    let a =
        seq {
            1 .. 10
        }
        |> Seq.countBy (fun x -> printfn "%A" x; x)

    0
```

**Comment by nhirschey** [comment] 2021-05-01 13:26
@kerams I appreciate the help. Your example is different from mine. Can you try my 2nd example and see if you get what I’m getting or something different? I see #time print 0 seconds immediately while the cpu and IO continue to chug away reading the file and counting; then after awhile the countBy result is printed to fsi.

**Comment by kerams** [comment] 2021-05-01 13:47
I was just reducing the snippet to where your misunderstanding lies. Anyway, I ran your entire file in FSI and it behaves as you're saying. Then I ran it in a console application with a breakpoint on `file.Headers` and after pressing F5 it then exits immediately. I'm not going to repeat myself again, but hopefully someone more authoritative will be able to explain it better.

**Comment by nhirschey** [comment] 2021-05-01 16:33
> I don't think the timing info should include the time/resources it takes FSI to pretty print something (which is what triggers the enumeration here). 

ok, I now see what you mean here. I appreciate the help in pinpointing the issue. 

I understand argument for why the current behavior is the correct behavior. It’s perfectly reasonable. But it feels wrong for *interactive* timing.  

If fsi printed the type signature of the sequence without forcing enumeration, then I would agree that it makes sense. But for the interactive experience, if the fsi printer forces enumeration that thrashes the CPU and causes lots of garbage collection, it’s weird to say nothing happened. The sequence did get enumerated, the cpu was pegged, it did cause garbage collection, and the counts happened.

**Comment by nhirschey** [comment] 2021-08-19 10:01
FYI, I'm fine with this issue being closed with "behavior is as designed", but I'd include this in the realm of "things that make it harder for python/R/matlab people to understand f#."  I now see that the fsi printer behavior for sequences is the reason that I never understood why sometimes a lazy sequence evaluated and sometimes it didn't.

Some examples for how the fsi printer leads to inconsistent evaluation of sequence expressions. 

1. This code does not evaluate the sequence and executes instantly:
```fsharp
> let x = seq { 1 .. 100_000_000 } |> Seq.countBy id;;
Real: 00:00:00.000, CPU: 00:00:00.000, GC gen0: 0, gen1: 0, gen2: 0
val x : seq<int * int>
```

2. This code does not evaluate the sequence and executes instantly:
```fsharp
> seq { 1 .. 100_000_000 } |> Seq.countBy id
- let x = 4;;
Real: 00:00:00.000, CPU: 00:00:00.031, GC gen0: 0, gen1: 0, gen2: 0
val x : int = 4
```

3. This code **does** evaluate the sequence and takes wall clock time to execute, but #time says it executes instantly:
```fsharp
> seq { 1 .. 100_000_000 } |> Seq.countBy id;;
Real: 00:00:00.000, CPU: 00:00:00.000, GC gen0: 0, gen1: 0, gen2: 0
val it : seq<int * int> = seq [(1, 1); (2, 1); (3, 1); (4, 1); ...]
```

4. This code **does** evaluate the sequence (it should take the same wall clock time as example 3) and #time reports the actual times to evaluate it:
```fsharp
> let x = seq { 1 .. 100_000_000 } |> Seq.countBy id
- Seq.item 0 x;;
Real: 00:00:03.910, CPU: 00:00:03.968, GC gen0: 0, gen1: 0, gen2: 0
val x : seq<int * int>
val it : int * int = (1, 1)
```

**Comment by dsyme** [comment] 2022-03-03 23:45
I will indeed close this as by design :)

**Closed by dsyme** 2022-03-03 23:45 UTC
Labels: Impact-Low
