### ISSUE TITLE
Updating dotnet interactive to FSharp.Core and FSharp.Compiler.Service 8.0.400 causes test errors

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#17793] opened 2024-09-25 20:34 UTC
This PR in the dotnet interactive repo updates the F# packages to the latest RTM packages. 

https://github.com/dotnet/interactive/pull/3679

This causes tests issues for interactive:
![image](https://github.com/user-attachments/assets/6655755b-164e-4741-ac0e-6e2b9de68ed1)

![image](https://github.com/user-attachments/assets/c52dde30-1bb9-4535-a91d-9b51adbdeaff)

**Comment by vzarytovskii** [comment] 2024-09-26 09:11
Issue is caused by https://github.com/dotnet/fsharp/pull/16168

FYI @DedSec256 

@KevinRansom @T-Gro can you please handle the revert. It will need to go to both 8 and 9 asap.

**Comment by T-Gro** [comment] 2024-09-26 12:05
This reproes for FSI when used with the /usesdkrefs- flag.
Under it, the typedefiniton for "MemoryExtensions" signals that it does not contain extension methods (the regression added by #16168 ).

I will try a fix-forward rather than a revert here.

**Comment by T-Gro** [comment] 2024-09-27 08:10
Fixed with #17799

**Closed by T-Gro** 2024-09-27 08:10 UTC
Labels: Bug, Regression, Needs-Triage
