### ISSUE TITLE
Regression with ByRef

### ISSUE THREAD

**Issue by gusty** [dotnet/fsharp#11713] opened 2021-06-23 04:45 UTC
There seems to be a regression related to using ByRefs.

**Repro steps**

```
let inline tryParse (_: 'R) = fun x ->
        let mutable r = Unchecked.defaultof< ^R>
        if (^R: (static member TryParse : _ * _ -> _) (x, &r)) then Some r else None ;;
```

**Expected behavior**

Compile.

**Actual behavior**

`error FS0193: internal error: Field of ByRef type. (Exception from HRESULT: 0x801312E4)`

**Known workarounds**

Use `--langversion:4.7`

**Related information**

Provide any related information (optional):

* Operating system: Windows
* FSI: Microsoft (R) F# Interactive version 11.3.2.0 for F# 5.0

**Comment by dsyme** [comment] 2021-06-23 15:05
Could you add more detailed repro steps and log?  I don't repro this in `main`.  My `a.fs` contains

```
let inline tryParse (_: 'R) = fun x ->
        let mutable r = Unchecked.defaultof< ^R>
        if (^R: (static member TryParse : _ * _ -> _) (x, &r)) then Some r else None ;;

```

I try each of 

```
artifacts\bin\fsc\Release\net472\fsc.exe --optimize-  a.fs
artifacts\bin\fsc\Release\net472\fsc.exe --optimize+  a.fs
```
and I always get
```
Microsoft (R) F# Compiler version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

a.fs(3,88): warning FS0988: Main module of program is empty: nothing will happen when it is run

```

**Comment by dsyme** [comment] 2021-06-23 15:05
Actually, yes, it repros in F# Interactive
```
C:\GitHub\dsyme\fsharp>artifacts\bin\fsi\Release\net472\fsi.exe

Microsoft (R) F# Interactive version 11.3.1.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let inline tryParse (_: 'R) = fun x ->
-         let mutable r = Unchecked.defaultof< ^R>
-         if (^R: (static member TryParse : _ * _ -> _) (x, &r)) then Some r else None ;;


error FS0193: internal error: Field of ByRef type. (Exception from HRESULT: 0x801312E4)
```

**Comment by dsyme** [comment] 2021-06-23 15:24
This is a problem with witness passing - witnesses are represented using F# functions, which can't accept byref values, so it is not possible to generate a witness for a trait constraint involving byrefs.  

This is detected by F# Interactive where the System.Reflection.Emit codegen fails early when a field type for the witness closure.

This is actually a general limitation of witness passing, which isn't really isn't able to work with witnesses for such SRTP constraints.  I will work out a way to automatically disable witness passing on inline code that uses such constraints. It is possible we can also make a more general fix to support these, though it is instrinsically difficult, because we would need to pass delegates for witnesses in this situation, but a potenttially unbounded number of delegate types is needed - one for a byref in first position, one for a byref in second position and so on, all for varying numbers of arguments.

There is no way to selectively disable witness passing besides using `--langversion:4.7`, so that's the only workaround right now.

**Comment by gusty** [comment] 2021-06-23 17:52
Thanks @dsyme for the detailed analysis.

As hard as it seems, it feels like this should be supported. Otherwise tools like Fable would always have some limitations.

**Comment by dsyme** [comment] 2021-06-23 18:26
> As hard as it seems, it feels like this should be supported. Otherwise tools like Fable would always have some limitations.

Yes, I suppose FCS can report the witnesses, and this is a limitation of quotations

**Comment by TIHan** [comment] 2021-09-29 16:27
I probably spent too much time trying to make a fix until I realized it is not reproducible in our latest previews.
![witness_byref](https://user-images.githubusercontent.com/1278959/135308968-dff5c567-44d0-4e0f-ade4-74219ac4a5d1.png)

@dsyme - I'm curious what change we made that allowed this to be fixed.

**Comment by TIHan** [comment] 2021-09-29 16:28
Closing as it seems to have been resolved.

**Closed by TIHan** 2021-09-29 16:28 UTC
Labels: Bug, Regression, Area-Compiler, Impact-Low
