### ISSUE TITLE
Could not load file or assembly 'FSharp.Core, Version=5.0.0.0. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

### ISSUE THREAD

**Issue by tforkmann** [dotnet/fsharp#10486] opened 2020-11-17 08:39 UTC
My project compiles but if I run the .NET5 project I run into the following error message.

The initWriter from Chia looks like this:
[initWriter](https://github.com/DanpowerGruppe/Chia/blob/master/src/Chia/InitBuilder.fs) 

Chia is running to .NET5 and all test a passing.

I get the following error message:

```Could not load file or assembly 'FSharp.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
Unhandled exception. System.TypeInitializationException: The type initializer for '<StartupCode$Server>.$LogConfig' threw an exception.
 ---> System.Exception: Could not init initWriter Could not load file or assembly 'FSharp.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1639.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1639
   at <StartupCode$Server>.$LogConfig..cctor() in 
```

**Expected behavior**

Code compiles 

**Actual behavior**

match the assembly reference. (0x80131040) - Exited with error code -532462766

**Known workarounds**

none I know of

**Related information**

Provide any related information (optional):

* Operating system
* .NET Runtime kind: .NET5
* Editing Tools: VS Code

**Comment by cartermp** [comment] 2020-11-17 22:19
Do you have a standalone repro you can share? It looks like this is intended to run in Azure Functions, which is kind of an odd environment and doesn't support .NET 5 to my understanding.

**Comment by KevinRansom** [comment] 2020-11-26 23:18
@tforkmann ,

hi,

I am closing this, since an F# app is expected to work fine on .NET5.  There is not really enough details for me to investigate the issue.

However ... it should be noted that if you are using an assembly that is built to reference FSharp.Core version 5.0.0.0 and your build is deploying FSharp.Core 4.7.0.0 to the execution directory then you will see the error you are reporting.

please reopen this issue with details that will allow me to reproduce and thus investigate the issue you have seen.

Thank you,

Kevin

**Closed by KevinRansom** 2020-11-26 23:18 UTC
Labels: needs repro
