### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#6237] opened 2019-02-16 07:15 UTC
Dev 16.0 Preview 

Paste into F# editor caused this exception

````
  <entry>
    <record>690</record>
    <time>2019/02/16 07:08:53.561</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>
        System.NullReferenceException: Object reference not set to an instance of an object.;
       at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommandWorker(PasteCommandArgs args, Action nextHandler, CancellationToken cancellationToken);
       at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(PasteCommandArgs args, Action nextHandler, CommandExecutionContext context);
       at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext);
       at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.&lt;&gt;c__DisplayClass13_1`1.&lt;Execute&gt;b__1();
       at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter);
    --- End of stack trace from previous location where exception was thrown ---;
       at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   </description>
  </entry>
````

**Comment by KevinRansom** [comment] 2019-02-16 08:53
It has locked up on me twice in the last hour following a paste.  It needs to be looked at.

/cc @cartermp, @TIHan, @brettfo.

**Comment by cartermp** [comment] 2019-02-16 13:47
https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Formatting/EditorFormattingService.fs#L191

**Comment by cartermp** [comment] 2019-02-17 05:05
Thought the stack implicates the editor, not us

**Comment by cmeeren** [comment] 2019-05-23 06:12
I experience this a lot, too, in both 16.0 and 16.1. Pasting code often causes this error (far from always, but I experience this at least a couple of times a day). Note that I have turned on the F# smart indentation feature. There seems to be no ill effects other than possibly incorrect indentation on paste, which could be a different bug for all I know.

**Comment by nbevans** [comment] 2020-02-03 10:29
Still happening sometimes on VS 16.4.3

**Comment by abelbraaksma** [comment] 2020-02-04 14:28
Is there a reproducible example of this? I have not seen this in practice yet.

**Comment by cmeeren** [comment] 2020-02-04 14:30
Unfortunately it seems to happen completely randomly for me, but it happens at least couple of times per day.

**Comment by nbevans** [comment] 2020-02-04 14:51
Yeah - I get it at least once a day really. Sometimes more. It's functionally harmless but jarring and annoying.

**Comment by cmeeren** [comment] 2020-02-04 17:51
> Pretty sure it only happens to me when pasting a block of code.

Same for me; to clarify, I meant randomly when pasting a block of code.

**Comment by cartermp** [comment] 2020-02-05 17:19
I've seen this from time to time but it is not reproducible. Based on the stack trace it appears to throw in the editor, but it's not clear if the issue is there or if we're just passing bad data every once in a while. cc @gundermanc

**Comment by cartermp** [comment] 2020-09-02 00:57
This is external. I have a repro from internal builds that involves pasting code that will not compile.

https://developercommunity.visualstudio.com/content/problem/1163822/nullreferenceexception-in-editor-and-duplicated-te.html

Not sure if anyone other than MS internal people can view it, but I will close this out since it is an external issue

**Closed by cartermp** 2020-09-02 00:57 UTC
Labels: Area-External, needs repro
