### ISSUE TITLE
FS1156: This is not a valid numeric literal - external nuget source fails

### ISSUE THREAD

**Issue by jkone27** [dotnet/fsharp#15072] opened 2023-04-12 13:46 UTC
Ofter when running a script in vscode i get this error, even though vscode shows no compiler errors, it fails at runtime.

**Repro steps**

fsx script try execute , no errors in ionide just at runtime

```fsharp
#i "nuget: https://my-private-source.myget.org/F/private-nuget/auth/<GUID>/api/v3/index.json"
#r "nuget: My.Private.Package"

//rest of script

```

**Expected behavior**

the nuget source is referenced correctly

**Actual behavior**

```
error FS1156: This is not a valid numeric literal. Valid numeric literals include 1, 0x1, 0o1, 0b1, 1l (int/int32), 1u (uint/uint32), 1L (int64), 1UL (uint64), 1s (int16), 1us (uint16), 1y (int8/sbyte), 1uy (uint8/byte), 1.0 (float/double), 1.0f (float32/single), 1.0m (decimal), 1I (bigint).

```

**Known workarounds**

restart vscode, not always works

**Related information**

Provide any related information (optional):

* MacOs
* .NET7
* vscode + ionide

**Comment by KevinRansom** [comment] 2023-06-09 17:42
Closing as a duplicate of:    https://github.com/dotnet/fsharp/issues/11392

FSharp Interactive does not have a design mechanism allowing for authenticated feeds, other than the Nuget.config mechanism specified here:
https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/consuming-packages-authenticated-feeds.md

**Note F# does not allow --interactive to be specified.**

We do want to better support authenticated feeds, but we do not have a design yet that we want to implement.

**Closed by KevinRansom** 2023-06-09 17:42 UTC
Labels: Bug, Area-DependencyManager
