### ISSUE TITLE
Open incorrectly considered unused

### ISSUE THREAD

**Issue by bender2k14** [dotnet/fsharp#7111] opened 2019-07-03 16:42 UTC
I have an `open` statement that Visual Studio says is unused, but if I remove it, then the code doesn't compile.

**Repro steps**

When using the `open` statement:
> Open declaration can be removed.

![Screenshot 2019-07-03 08 19 00](https://user-images.githubusercontent.com/34664007/60608858-0a918c00-9d86-11e9-95a1-ee34e27af106.png)

With the `open` statement removed:
> Lookup on object of indeterminate type based on information prior to this program point.  A type annotation may be needed prior to this program point to constrain the type of the object.  This may allow the lookup to be resolved.

![Screenshot 2019-07-03 08 20 09](https://user-images.githubusercontent.com/34664007/60608938-2eed6880-9d86-11e9-8814-dc10acad32ec.png)

**Expected behavior**

I think this `open` statement is being used, so my expectation is that Visual Studio would not suggest to remove it.

**Actual behavior**

Visual Studio suggests to remove an `open` statement that seems to be in use.

**Known workarounds**

Ignore the suggestion from Visual Studio to remove the `open` statement.

**Related information**

* Operating system: Windows 10
* .NET Runtime kind: .NET Core 3.0 Preview 6
* Editing Tools: Visual Studio Enterprise 2019 version 16.1.4

**Comment by cartermp** [comment] 2020-08-06 06:17
Closing as duplicate of https://github.com/dotnet/fsharp/issues/3347

Unfortunately there is definitely a bug in the open declarations analyzer. Subtle, but this will happen from time to time.

Would definitely welcome a PR that investigated this - the feature is fairly testable.

**Closed by cartermp** 2020-08-06 06:17 UTC
Labels: Resolution-Duplicate

**Comment by bender2k14** [comment] 2020-08-11 23:59
Better than being a duplicate...I think this bug was fixed.  I can't reproduce it any more with this environment.

Operating system: Windows 10
.NET Runtime kind: .NET Core 3.1
Editing Tools: Visual Studio Enterprise 2019 version 16.6.5

Not sure how to obtain that environment again to reproduce the bug either.

**Comment by cartermp** [comment] 2020-08-12 00:40
There's definitely been a lot of bug fixes and general improvements since the VS 16.1 release. Glad it doesn't reproduce!

**Comment by auduchinok** [comment] 2020-09-02 13:59
This issue was fixed in https://github.com/dotnet/fsharp/pull/6846.
