### ISSUE TITLE
Opening a single file can lead to 2GB of increase in memory, repro with FSharp.sln

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9637] opened 2020-07-07 00:54 UTC
I've often try to pinpoint this (reduced performance, increase in mem) in a reproducible way, but failed. However, maybe today I've got something (found this after the 2nd crash of today)

**Repro steps**

* Open FSharp.sln
* Make sure there's only one small file open from FSharp.Core.UnitTests and wait for coloring to appear and bg proc to seize
* Note the memory pressure at this point (in my case, 900MB for VS 2019)
* Open `ComparersRegression.fs`. This is a large file, 58k lines, 3.5MB
* Wait until file is loaded and coloring and tooltips work again (can take a bit)
* Note the mem pressure again, in my case a whopping 2.8GB!

Then you may try:

* close the file
* note the mem pressure. Hardly any decrease.

**Expected behavior**

Increase in mem is expected, 10, maybe even 100x the size of the file, but certainly not by almost 2GB. And after closing it, I'd expect mem to go back to normal, give or take a few dozens of MB.

**Actual behavior**

As described in repro steps.

Editing in many other files becomes very slow and often VS is unresponsive.

**Known workarounds**

Restart VS after using large files, or a sizable number of files open at the same time.

**Related information**

Current version of FSharp.sln, either with Preview or VS 2019 16.6.

Putting this out there as I know from time to time there's research into mem pressure in VS and maybe it'll help the research. Not a real bug per se, as long as you restart VS after you're done with this file, to get back to normal levels.

**Comment by cartermp** [comment] 2020-07-10 15:22
Closing out as duplicate of https://github.com/dotnet/fsharp/issues/9069

Worth noting that this is a multi-tfm project, so it is twice the work happening

**Closed by cartermp** 2020-07-10 15:22 UTC

**Comment by abelbraaksma** [comment] 2020-07-10 17:05
Oh, wow, how could I have missed that, I remember now that you reported that, and even down rui the same file. Getting old ;p.
