### ISSUE TITLE
Completion doesn't show properties in object initialization for fully qualified types.

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#3954] opened 2017-11-15 23:34 UTC
Given the code:
```fsharp
module M =
    type A() =  
        member val SettableProperty = 1 with get, set
        member val AnotherSettableProperty = 1 with get, set
        member val NonProperty = 1
```

When constructing type A with a fully qualified name and using object initialization syntax, no properties show in completion. Example:

![unable_to_set](https://user-images.githubusercontent.com/1278959/32865994-6a37e53c-ca1a-11e7-9aa5-c5ebc632d702.png)

**Comment by dsyme** [comment] 2017-11-17 14:10
Would love to see this fixed.  See also https://github.com/Microsoft/visualfsharp/issues/554 which I think is much the same kind of issue

**Comment by TIHan** [comment] 2017-11-22 18:05
I want to note that this bug is without the ending paren.

**Comment by dsyme** [comment] 2017-11-22 18:51
IIRC there are some systematic problems with imbalanced parnetheses and there may be some kind of general fix which improves a lot of situations

Off the top of my head I remember cases where

    let x = f (g (abc,def    // two missing parentheses

and

    let x = f (abc,def    // one missing parentheses

and

    let x = f (g (abc,def    // some missing parentheses
    ... someOtherCode ...

would all give different behaviour for completion - and again depending on the "someOtherCode" and in particular how soon it triggers an error.

I'm not sure of the exact underlying problems but they are probably related to the combination of the indentation-aware rules and the error recovery in the parse.  The annoying thing about this is that it is "obvious" in modern F# code (using indentation aware syntax) that something has gone wrong pretty early and it feels like we should be able to recover well and give good syntax errors early on.

Anyway I just want to mention this as I think it systematically affects ``x.M(abc`` more than other cases because there is nearly always a missing parenthesis (unless your using an editor like VSCode, when the parentheses insertion will have added a closing parenthesis automatically)

**Comment by cartermp** [comment] 2021-03-18 03:38
This is (mostly) a non-issue now that we have automatic brace completion. This is from just typing things out normally. I had to intentionally delete the end paren to reproduce:

![image](https://user-images.githubusercontent.com/6309070/111569783-9e74d880-8760-11eb-9d4f-33352be48ceb.png)

So I'll close this out since people are quite unlikely to run into it now.

**Closed by cartermp** 2021-03-18 03:38 UTC
Labels: Area-IDE Language Service, Severity-Medium, bug
