### ISSUE TITLE
`task` CE: awaits within `if..then..else` result in compiler error

### ISSUE THREAD

**Issue by melanore** [dotnet/fsharp#12555] opened 2021-12-29 12:11 UTC
Awaits inside `if..then..else` branches result in compiler error when used within `task` CE. 

![image](https://user-images.githubusercontent.com/12952261/147660603-c0066134-4a6e-41e0-84d7-75dd78d23bb2.png)

**Repro steps**
Minimal reproduce of this issue can be found in this repository - https://github.com/melanore/FSharp6.Tasks.BugReport/blob/master/FSharp6.Tasks.BugReport.Branching/Program.fs

Reproduce below mimics interop with AWS s3 client library.

```
module Main

open System.IO
open System.Threading.Tasks

[<AllowNullLiteral>]
type Request() = class end

[<AllowNullLiteral>]
type Response() =
    member val ResponseStream = new MemoryStream() with get

type Client() =
    member x.GetResponseAsync(request : Request) =
        Response() |> Task.FromResult

let getFileContent () =
    task {
        let client = Client()
        let request = Request()
        if isNull request then
            return None
        else
            let! response = client.GetResponseAsync(request)
            if isNull response then
                return failwith "Failed to receive the item from blob." 
            
            use stream = response.ResponseStream
            let length = (stream.Length |> int)
            printfn $"File size is {length} bytes."
            return Some length
    }
    
let getFileContentWorkaround () =
    task {
        let client = Client()
        let request = Request()
        let! response =
            if isNull request then
                Task.FromResult None
            else
                client.GetResponseAsync(request).ContinueWith(fun (s : Task<Response>) -> Some s.Result)
        
        match response with
        | None ->
            return None
        | Some null ->
            return failwith "Failed to receive the item from blob."
        | Some r ->
            use stream = r.ResponseStream
            printfn $"File size is %i{stream.Length} bytes."
            return Some stream.Length
    }
```

**Expected behavior**

Compiler is able to figure type constraints within `if` branches inside `task` CE similarly to Ply.

**Actual behavior**
```
  Program.fs(30, 17): [FS0193] Type constraint mismatch. The type 
    'TaskCode<int option,int option>'    
is not compatible with type
    'TaskCode<unit,'a>'

  Program.fs(26, 17): [FS0193] Type constraint mismatch. The type 
    'TaskCode<unit,'b>'    
is not compatible with type
    'TaskCode<'a option,'a option>'
```

**Related information**

* Operating system: Windows 10
* .NET Runtime: 6.0.100

**Comment by dsyme** [comment] 2022-01-04 13:29
Hmmmm this looks important to fix.  It would be really great to get a minimal repro that doesn't depend on the AWS library

**Comment by Happypig375** [comment] 2022-01-04 13:59
Minimal repro?
```fs
type C() =
    member _.M() = task {
        if true then return Some true // error FS0001: The 'if' expression needs to have type 'unit' to satisfy context type requirements. It currently has type ''a option'.
        do! System.Threading.Tasks.Task.CompletedTask // error FS0193: Type constraint mismatch. The type 'TaskCode<bool option,bool option>' is not compatible with type 'TaskCode<unit,'a>'   
        return Some false
    }
    member _.N() = async {
        if true then return Some true // error FS0001: The 'if' expression needs to have type 'unit' to satisfy context type requirements. It currently has type ''a option'.
        do! async { return () }
        return Some false
    }
```

**Comment by dsyme** [comment] 2022-01-04 15:35
Yeah I think this is by design for the built-in task support tbh, I don't expect that to compile

You need to use if/then/else, e.g.

```fsharp
type C() =
    member _.M() = task {
        if true then return Some true // error FS0001: The 'if' expression needs to have type 'unit' to satisfy context type requirements. It currently has type ''a option'.
        else
            do! System.Threading.Tasks.Task.CompletedTask // error FS0193: Type constraint mismatch. The type 'TaskCode<bool option,bool option>' is not compatible with type 'TaskCode<unit,'a>'   
            return Some false
    }
    member _.N() = async {
        if true then
            return Some true // error FS0001: The 'if' expression needs to have type 'unit' to satisfy context type requirements. It currently has type ''a option'.
        else
            do! async { return () }
            return Some false
    }
```

**Comment by dsyme** [comment] 2022-01-04 15:40
@melanore I realise now that you'd already minimized the repro, thanks

**Comment by dsyme** [comment] 2022-02-08 15:24
Closing as this is by design

**Closed by dsyme** 2022-02-08 15:24 UTC
Labels: Bug, Impact-High

**Comment by TheAngryByrd** [comment] 2024-04-17 18:04
cc @edgarfgp
