### ISSUE TITLE
MethodAccessException on equality comparison of a type private to module

### ISSUE THREAD

**Issue by iminashi** [dotnet/fsharp#17541] opened 2024-08-15 10:30 UTC
Something that has worked previously now fails with a MethodAccessException when using SDK 9.0.100.

**Repro steps**

Calling a public function that does an equality comparison on a type that is private to the module.

```fsharp
module Module =
    type private DU = ABC | YYZ

    let publicFunction () : bool =
        ABC = YYZ

Module.publicFunction () |> printfn "%b"
```

**Expected behavior**

`false` is printed.

**Actual behavior**

> Unhandled exception. System.MethodAccessException: Attempt by method 'Program+Module.publicFunction()' to access method 'Program+Module+DU.Equals(DU, System.Collections.IEqualityComparer)' failed.

**Related information**

* 9.0.100-preview.7.24407.12

**Comment by vzarytovskii** [comment] 2024-08-15 10:53
Duplicate of https://github.com/dotnet/fsharp/issues/17447

**Comment by iminashi** [comment] 2024-08-15 10:55
I ran into this when testing if #17447 was fixed in 9.0.100 (it is).

**Comment by iminashi** [comment] 2024-08-15 11:11
The example above works in 8.0.400, but fails in 9.0.100.

The example in #17447 fails in 8.0.400, but works in 9.0.100.

**Comment by T-Gro** [comment] 2024-08-15 11:11
Still repro's in main -> issue has to be fixed.

**Comment by KevinRansom** [comment] 2024-08-15 21:31
@iminashi - Thank you for raising this issue, it forced me to properly think about the codegen that needs to happen for Equality(typed, IComparable) which is wierdly enough different from all of the other Augmented Equals and Compare methods.

**Closed** 2024-08-19 09:57 UTC
Labels: Bug, Needs-Triage
