### ISSUE TITLE
Some files have no IntelliSense due to "The type referenced through '...' is defined in an assembly that is not referenced"

### ISSUE THREAD

**Issue by saul** [dotnet/fsharp#2962] opened 2017-04-30 09:19 UTC
I believe this is another regression since @vasily-kirichenko's #2644 PR.

![image](https://cloud.githubusercontent.com/assets/64654/25563180/4dc1b9b0-2d8e-11e7-828e-e026b87f60a3.png)

Note that I'm getting absolutely no autocompletion as some type somewhere requires another assembly. This shouldn't be the case - I should only get the <Note> item if I'm directly trying to get intellisense on IWpfTextView.

Note you can reproduce this anywhere in AppConfigHelper.fs in the ProjectSystem project in VisualFSharp.

The stack trace for the error being thrown is here:

```
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at Microsoft.FSharp.Compiler.Tast.CcuThunk.EnsureDerefable(String[] requiringPath)
   at Microsoft.FSharp.Compiler.Tast.NonLocalEntityRef.TryDeref(Boolean canError)
   at Microsoft.FSharp.Compiler.Tast.EntityRef.Resolve(Boolean canError)
   at Microsoft.FSharp.Compiler.Tast.EntityRef.get_Deref()
   at Microsoft.FSharp.Compiler.Tastops.stripTyEqnsA(TcGlobals g, Boolean canShortcut, TType ty)
   at Microsoft.FSharp.Compiler.Tastops.stripTyEqns(TcGlobals g, TType ty)
   at Microsoft.FSharp.Compiler.Tastops.stripTyEqnsAndErase(Boolean eraseFuncAndTuple, TcGlobals g, TType ty)
   at Microsoft.FSharp.Compiler.Tastops.stripTyEqnsWrtErasure(Erasure erasureFlag, TcGlobals g, TType ty)
   at Microsoft.FSharp.Compiler.Tastops.typeAEquivAux(Erasure erasureFlag, TcGlobals g, TypeEquivEnv aenv, TType ty1, TType ty2)
   at Microsoft.FSharp.Collections.ListModule.forall2aux[a,b](FSharpFunc`3 f, FSharpList`1 list1, FSharpList`1 list2)
   at Microsoft.FSharp.Collections.ListModule.ForAll2[T1,T2](FSharpFunc`2 predicate, FSharpList`1 list1, FSharpList`1 list2)
   at Microsoft.FSharp.Collections.ListModule.forall2aux[a,b](FSharpFunc`3 f, FSharpList`1 list1, FSharpList`1 list2)
   at Microsoft.FSharp.Collections.ListModule.ForAll2[T1,T2](FSharpFunc`2 predicate, FSharpList`1 list1, FSharpList`1 list2)
   at Microsoft.FSharp.Collections.ListModule.TryFind[T](FSharpFunc`2 predicate, FSharpList`1 list)
   at Microsoft.FSharp.Compiler.Tast.ModuleOrNamespaceType.TryLinkVal(CcuThunk ccu, ValLinkageFullKey key)
   at Microsoft.FSharp.Compiler.Tast.ValRef.get_Deref()
   at Microsoft.FSharp.Compiler.Tast.ValRef.get_MemberInfo()
   at Microsoft.FSharp.Compiler.InfoReader.GetIntrinsicConstructorInfosOfType@437-5.Invoke(ValRef vref)
   at Microsoft.FSharp.Primitives.Basics.List.choose[T,TResult](FSharpFunc`2 f, FSharpList`1 xs)
   at Microsoft.FSharp.Collections.ListModule.Choose[T,TResult](FSharpFunc`2 chooser, FSharpList`1 list)
   at Microsoft.FSharp.Compiler.InfoReader.GetIntrinsicConstructorInfosOfType(InfoReader infoReader, range m, TType ty)
   at Microsoft.FSharp.Compiler.NameResolution.ResolveObjectConstructorPrim[a](NameResolver ncenv, DisplayEnv edenv, a resInfo, range m, AccessorDomain ad, TType typ)
   at Microsoft.FSharp.Compiler.NameResolution.ResolveObjectConstructor(NameResolver ncenv, DisplayEnv edenv, range m, AccessorDomain ad, TType typ)
   at Microsoft.FSharp.Compiler.NameResolution.InfosForTyconConstructors(NameResolver ncenv, range m, AccessorDomain ad, EntityRef tcref)
   at Microsoft.FSharp.Compiler.NameResolution.constructors@3802-3.Invoke(EntityRef tcref)
   at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons)
   at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list)
   at Microsoft.FSharp.Compiler.NameResolution.ResolvePartialLongIdentPrim(NameResolver ncenv, NameResolutionEnv nenv, ResolveCompletionTargets isApplicableMeth, FullyQualifiedFlag fullyQualified, range m, AccessorDomain ad, FSharpList`1 plid, Boolean allowObsolete)
   at Microsoft.FSharp.Compiler.SourceCodeServices.TypeCheckInfo.GetEnvironmentLookupResolutions(NameResolutionEnv nenv, AccessorDomain ad, range m, FSharpList`1 plid, TypeNameResolutionFlag filterCtors, Boolean showObsolete)
   at Microsoft.FSharp.Compiler.SourceCodeServices.TypeCheckInfo.GetDeclaredItems[a](FSharpOption`1 parseResultsOpt, String lineStr, FSharpOption`1 origLongIdentOpt, Int32 colAtEndOfNamesAndResidue, FSharpOption`1 residueOpt, Int32 line, Int32 loc, TypeNameResolutionFlag filterCtors, ResolveOverloads resolveOverloads, FSharpFunc`2 hasTextChangedSinceLastTypecheck, Boolean isInRangeOperator, FSharpFunc`2 allSymbols)
   at Microsoft.FSharp.Compiler.SourceCodeServices.TypeCheckInfo.GetDeclItemsForNamesAtPosition(CompilationThreadToken ctok, FSharpOption`1 parseResultsOpt, FSharpOption`1 origLongIdentOpt, FSharpOption`1 residueOpt, Int32 line, String lineStr, Int32 colAtEndOfNamesAndResidue, TypeNameResolutionFlag filterCtors, ResolveOverloads resolveOverloads, FSharpFunc`2 getAllSymbols, FSharpFunc`2 hasTextChangedSinceLastTypecheck)
   at <StartupCode$FSharp-LanguageService-Compiler>.$Service.GetDeclarations@1254.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Compiler.ErrorScope.Protect[a](range m, FSharpFunc`2 f, FSharpFunc`2 err)
```

**Comment by saul** [comment] 2017-05-01 14:14
@vasily-kirichenko any ideas as to how we could get around this? Really I think we should just show the name and then this message beside the causing symbol.

**Comment by vasily-kirichenko** [comment] 2017-05-01 18:52
@saul due to https://github.com/Microsoft/visualfsharp/issues/2970 I cannot investigate this further.

**Comment by dsyme** [comment] 2017-05-03 00:11
@saul Looking at the stack trace ``GetIntrinsicConstructorInfosOfType`` in the stack trace should have a use of ``protectAssemblyExploration`` returning no constructors for  particular type if an assembly exploration error happened

**Comment by dsyme** [comment] 2017-05-09 09:42
Fixed

**Comment by cartermp** [comment] 2018-11-17 16:46
See here: https://www.reddit.com/r/fsharp/comments/9xeml0/intellisense_weirdness_with_extension_methods/

Repro project: https://github.com/JordanMarr/FSharpExtensionMethodBug

I can reproduce this with VS 15.9.

**Comment by cartermp** [comment] 2021-03-18 04:15
This doesn't reproduce anymore with .NET SDK-style projects. I'll close this out since it might be related to the old F# project system, but we won't be making tweaks there.

![image](https://user-images.githubusercontent.com/6309070/111572480-e0544d80-8765-11eb-93a8-dbdccde9fe12.png)

**Closed by cartermp** 2021-03-18 04:15 UTC
Labels: Area-IDE Language Service, Severity-Low, bug
