### ISSUE TITLE
"Assembly reference <referenced C# project> was not found or is invalid

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#4090] opened 2017-12-09 09:30 UTC
15.6 pre 1

1. Create a new F# .NET 4.6 console project
2. Add a C# .NET 4.6 library project
3. Reference the C# project from the F# one
4. Build solution (success)
5. Open `Program.fs`

Result:

![image](https://user-images.githubusercontent.com/873919/33794378-574df9f0-dcdc-11e7-9f53-75a03ec39ec1.png)

**Comment by vasily-kirichenko** [comment] 2017-12-09 09:32
6. Restart VS

Result: everything works as expected.

**Comment by forki** [comment] 2017-12-09 09:34
@cartermp I think this is basically the same thing as what I sent to you in
private. But much much smaller repro.

Am 09.12.2017 10:30 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by cartermp** [comment] 2019-05-23 14:32
Closing as dupe of #4000 as it has the same behavior for .NET SDK, so it's a language service problem.

**Closed by cartermp** 2019-05-23 14:32 UTC
Labels: Area-IDE Legacy Project System, Urgency-Later, bug
