### ISSUE TITLE
IDE0005 is not fixed solution-wise in F# in 17p2.1

### ISSUE THREAD

**Issue by TIHan** [dotnet/fsharp#11892] opened 2021-07-26 08:02 UTC
Reported by @WhiteBlackGoose

Version Used: 17p2.1

Steps to Reproduce:

Create an empty F# console app:
```fsharp
open System

printfn $"Hello world {5}"
```
Go to System, Ctrl+. and remove it document-wise, project-wise or solution-wise. All of those will do nothing (although it will remove the current open if you press enter).

**Comment by psfinaki** [comment] 2023-06-15 13:14
Duplicate of #14967 (or rather the other way round) and was fixed by @T-Gro recently. Works in VS preview as of now. Closing.

**Closed by psfinaki** 2023-06-15 13:14 UTC
Labels: Bug, Impact-Low, Area-LangService-CodeFixes
