### ISSUE TITLE
Hovering over a greater-than operator, or any operator starting with '>' does not show tooltip

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#10276] opened 2020-10-19 14:47 UTC
At some time, hovering over operators stopped showing the tooltip for _operators that start with a greater-than-sign_. Single-char operators `>` and `<` also don't show, but multi-char operators starting with `<` work correctly, while starting with `>` don't.

This problem extends to the bug "cannot navigate to symbol under caret" when hitting F12 in VS.

I tracked this back to VS 2017, so this isn't a "new" bug.

**Repro steps**

```f#
let x = 12 + 13                     // shows
let x = 12 > 13                     // does not show
let x = 12 < 13                     // does not show

let y = 12 |> printfn "%A"          // shows
let y = printfn "%A" <| 12          // shows
let y = string >> string            // does not show
let y = string << string            // shows

/// Testing tee operator
let (>|) a f = f a; a               // does not show (on the declaration)
/// Another testing tee operator
let (|>>) a f = f a; a              // shows (on the declaration)
let tee = 12 >| printfn "%A"        // does not show
let tee = 12 |>> printfn "%A"       // shows
```

**Expected behavior**

All operators should show tooltips.

**Actual behavior**

Some do, some don't show tooltips.

**Known workarounds**

Don't use operators that start with `>`. 

**Related information**

Any version of VS at least since VS 2017.

**Comment by cartermp** [comment] 2020-10-19 15:17
Closing as a dupe of https://github.com/dotnet/fsharp/issues/3462

It's also custom colors and some other stuff.

**Closed by cartermp** 2020-10-19 15:17 UTC
