### ISSUE TITLE
Can't use some types in `dotnet fsi` due to missing `System.Diagnostics.DebuggerBrowsableAttribute`

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#8549] opened 2020-02-11 15:35 UTC
While experimenting with the AWS SDK in `dotnet fsi`, I couldn't actually use some types due to an error locating `System.Diagnostics.DebuggerBrowsableAttribute`.

**Repro steps**

* Install .Net Core SDK 3.1.100
* Download the [AWSSDK.S3](https://www.nuget.org/packages/AWSSDK.S3/3.3.110.22) package from nuget and extract locally so that the dlls are available
* start a `dotnet fsi` session with required dlls preloaded: AWSSDK.Core.dll, AWSSDK.S3.dll
* input the following script:

```fsharp
open Amazon.S3

let c = new AmazonS3Client()
```

**Expected behavior**

the `c` value is bound and available for use.

**Actual behavior**

The following error is thrown:

```
error FS0193: Could not load file or assembly '"The system type 'System.Diagnostics.DebuggerBrowsableAttribute' was required but no referenced system DLL contained this type", Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

**Known workarounds**

None found. I've been manually adding `#r` for dlls (from the runtime-dll-location) that I think might contain the type but I haven't found one yet.

**Related information**

* Operating system: Debian Buster (10)
* .NET Runtime kind: .Net Core SDK 3.1.100, Runtime 3.1.0
* Editing Tools: `dotnet fsi`

**Comment by cartermp** [comment] 2020-02-12 18:01
Using `#r "nuget:...` and the Jupyter Kernel I see this instead:

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/6309070/74362996-82914d00-4d7e-11ea-9648-aac35ef11088.png">

**Comment by cartermp** [comment] 2020-02-12 18:01
Tagging with `needs repro` for now, since the "modern FSI" set to be available later this year doesn't exhibit the same problem - but it's unclear if what I'm seeing is good or bad

**Comment by baronfel** [comment] 2020-02-12 18:14
Your error is what I would expect to see on a machine that's not an Amazon EC2 compute instance. The parameterless constructor triggers some auto-resolution logic that your runtime environment doesn't have.

Good to know that it works on nightlies.

**Comment by cartermp** [comment] 2020-02-12 20:04
Awesome. In that case I'll close this out, but definitely ping back again if it continutes to reproduce when stuff is shipped.

**Closed by cartermp** 2020-02-12 20:04 UTC
Labels: needs repro
