### ISSUE TITLE
GraphBasedChecking can break compilation when having unused `open`

### ISSUE THREAD

**Issue by BoundedChenn31** [dotnet/fsharp#16225] opened 2023-11-03 19:16 UTC
Not sure if it's a real problem though.

**Repro steps**
Project file:
```fsproj
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <OtherFlags>$(OtherFlags) --test:GraphBasedChecking</OtherFlags>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="File1.fs" />
        <Compile Include="File2.fs" />
        <Compile Include="Program.fs"/>
    </ItemGroup>

</Project>
```
File1:
```fsharp
namespace My.Great.Namespace
```
File2:
```fsharp
namespace My.Great.Namespace

open My.Great.Namespace

type Foo = class end
```
Program:
```fsharp
printfn "Hello"
```

Compilation fails with error 
`
1>File2.fs(3,6): Error FS0039 : The namespace or module 'My' is not defined.
`

But with commented out `<OtherFlags>` line compilation is successful.
[NamespaceIsNotDefRepro.zip](https://github.com/dotnet/fsharp/files/13253814/NamespaceIsNotDefRepro.zip)

**Comment by vzarytovskii** [comment] 2023-11-03 19:34
@nojaf @safesparrow fyi

**Comment by vzarytovskii** [comment] 2023-11-03 19:35
@BoundedChenn31 saw your message in the chat, thanks for the minimal repro

**Comment by nojaf** [comment] 2023-11-03 20:04
Problematic in what SDK? Reproduceable on main?

**Comment by safesparrow** [comment] 2023-11-03 20:05
I reproduced it now on `8.0.100-rc.2`. Note that namespace names must match (as showcased in the example code).

**Comment by safesparrow** [comment] 2023-11-03 20:09
This fails:
1.
```
// A.fs
namespace A

// B.fs
namespace A
open A
type Foo = class end
```
while these succeed:
2.
```
// A.fs
namespace A

// B.fs
namespace A
open A
module X = ()
```
3.
```
// A.fs
namespace A

// B.fs
namespace B
open A
type Foo = class end
```

**Comment by safesparrow** [comment] 2023-11-03 20:37
@nojaf this is reproducible on latest main.

**Comment by safesparrow** [comment] 2023-11-03 20:41
Separately, we should consider either escaping the contents of Mermaid graphs, or at least replacing `\` with `/` to avoid `\n` being presented as a newline:
![image](https://github.com/dotnet/fsharp/assets/2478401/e03e651c-6fb0-411a-bfad-3fff330976c4)

**Comment by nojaf** [comment] 2023-11-04 09:29
I can reproduce this with RC2 but not with my local compiler.
@safesparrow could you try:
- `git clean -xdf` (of fsharp repo)
- `dotnet build src/fsc/fscProject/fsc.fsproj /p:BUILDING_USING_DOTNET=true`
- `<DotnetFscCompilerPath>C:\YourProjectFolder\fsharp\artifacts\bin\fsc\Debug\net8.0\fsc.dll</DotnetFscCompilerPath>`

**Comment by safesparrow** [comment] 2023-11-04 09:41
@nojaf You're right, my test setup was wrong (I haven't used the compiler from source in a while).

Looks like this is already fixed on main.

Code:
```
// A.fs
namespace A

// B.fs
namespace A
open A
type Foo = class end
```

Graph:
```mermaid
flowchart RL
    0["obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.fs"]
    1["obj\Debug\net7.0\fmodule.AssemblyInfo.fs"]
    2["A.fs"]
    3["B.fs"]
    3 --> 2
```

Trie:
```mermaid
 classDiagram

class root

root <|-- ns_Microsoft
class ns_Microsoft {

    .NETCoreApp,Version=v7.0.AssemblyAttributes.fs(0)
}

ns_Microsoft <|-- ns_BuildSettings
class ns_BuildSettings {

    .NETCoreApp,Version=v7.0.AssemblyAttributes.fs(0)
}

root <|-- ns_FSharp
class ns_FSharp {

    fmodule.AssemblyInfo.fs(1)
}

root <|-- ns_A
class ns_A {

    A.fs(2)
}
```

**Closed** 2023-11-13 17:56 UTC
Labels: Bug, Needs-Triage
