### ISSUE TITLE
error FS0193: internal error: Illegal characters in path.

### ISSUE THREAD

**Issue by matthid** [dotnet/fsharp#1224] opened 2016-05-27 08:25 UTC
When sending some lines in Visual Studio to fsi the error from the title appears. It seems to be related to binary dependencies and the current-directory variable.
I couldn't reproduce the problem without Visual Studio
#### Repro steps
1. open git bash
2. `git clone https://gist.github.com/76cdf91d1e526d63405c05e1f416f35b.git fs0193`
3. `cd fs0193`
4. `./build.sh`
5. Now (if everything is green, sorry I couldn't repro without python binaries and a working setup) open FS0193.fsx in Visual Studio 2015 and execute line by line.
#### Expected behavior

print `val it : unit = ()` and work
#### Actual behavior

```
> 


error FS0193: internal error: Illegal characters in path.


error FS0193: internal error: Illegal characters in path.


error FS0193: internal error: Illegal characters in path.
Stopped due to error
```
#### Known workarounds

Execute the line again (works second time). Note that everything works in a standalone fsi or when executing the script file directly (which is actually shown in the build script).
#### Related information
- FSI: Microsoft (R) F# Interactive version 14.0.23413.0
- Visual Studio Version 2015 (latest stable)
- Windows 10 (stable)
- I would say the impact is low-medium after you figured out it works the second time.
- You most likely need Windows 64 bit for these particular repro steps otherwise the script will install the wrong native dependency. But I'm pretty sure this would happen on 32 bit as well.
- You need standard installations or need to edit the `build.fsx` file because I hardcoded some paths.
- The script downloads `WinPython-64bit-3.5.1.3Zero.exe` (~20MB) and installs a portable version

**Comment by forki** [comment] 2016-05-27 10:08
I tried to reproduce, but didn't get the described error.

![image](https://cloud.githubusercontent.com/assets/57396/15605028/b09987b0-2403-11e6-85a7-45d710b5ec90.png)

**Comment by matthid** [comment] 2016-05-27 10:33
@forki Thanks. Seems like your fsi is not running with the correct arch. Can you verify that you have 64 bit enabled. 

![fsi_options_1](https://cloud.githubusercontent.com/assets/1866463/15605553/e30f2918-2406-11e6-8ecb-feec23d19f7a.jpg)
![fsi_options_2](https://cloud.githubusercontent.com/assets/1866463/15605554/e33c4038-2406-11e6-9f60-95a32f720e77.jpg)

Alternatively you can change the build script to download 32 bit versions (of python) and change some hard coded strings ...

**Comment by QuantApp** [comment] 2018-06-26 12:00
Specifically for Pythonnet I found that when loading through FSI, the systems tries to load Assemblies with names containing '<' and '>'... this breaks the runtime.
I solved it by editing the assemblymanager.cs file in the pythonnet library and in the LoadAssembly function just return null if certain characters are in the name.....

hope this helps.

public static Assembly LoadAssembly(string name)
        {
            if(name.Contains("@") || name.Contains("$") || name.Contains("__") || name.Contains("<") || name.Contains(">"))
            
                return null;
               Assembly assembly = null;
               try
              {
                  assembly = Assembly.Load(name);
              }

**Comment by abelbraaksma** [comment] 2018-06-26 12:52
@quantapp oops I think your layout got lost. You can surround the coffee with triple backticks ``````

**Comment by QuantApp** [comment] 2018-06-27 12:04
@abelbraaksma thanks for you comment. I have edited above. I hope its not too cryptic... if so please let me know and I will try to add more colour....
Basically the problem is that the Assembly.Load(name) breaks the runtime if the "name" contains strange characters like '<' and '>'... It breaks the runtime even if its around a TRY-CATCH... the FSI runtime also loads many many assemblies that I dont BELIEVE (not sure) are necessary for python net. This is why I filter out names that contains '@', '$' and '__' also.... 
In my tests... filtering out the characters above brings the initial loading of the Pythonnet runtime from 33seconds to 5seconds in  my machine...

**Comment by dsyme** [comment] 2022-03-31 03:47
I'm going to close this as I went through the original repro and it involves Mono, so would need to update the repro.

**Closed by dsyme** 2022-03-31 03:47 UTC
Labels: Bug, Up for Grabs, Area-Compiler, Impact-Low
