### ISSUE TITLE
Renaming an F# project in VS2017 sometimes fails with "The name you provided is not a valid project name"

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#5989] opened 2018-12-06 16:23 UTC
Sometimes I see the following error when I try to rename a project, while the name used is actually a valid identifier:

![image](https://user-images.githubusercontent.com/16015770/49596591-f5cd5100-f97a-11e8-93f6-4e88fa8b47d5.png)

### Repro steps

I've provided the whole solution file, as in some solutions it "just works" and in others it doesn't. I haven't found a reason where and when it succeeds, but at least on my machine, it fails with the attached solution (cleared to the minimum).

See: [FSharpBug#5989.zip](https://github.com/Microsoft/visualfsharp/files/2653904/FSharpBug.5989.zip)

### Expected behavior

Renaming (to a valid name) should always be allowed.

### Actual behavior

Renaming gives the mentioned error.

### Known workarounds

Rename by hand (change the filename and any references in the `fsproj` file and `sln` file). 

### Related information 

VS 2017 15.9.3, Windows 7, Windows 10, .NET Framework 4.7.x.

EDIT: Also attempted it in 15.7.0, that I had hanging around somewhere, and it repros there as well, so this bug (unless it is something really odd in my `fsproj` file), has been around for some time at least. Would be interesting to know what triggers it, and why it doesn't always occur.

**Comment by cartermp** [comment] 2018-12-06 18:57
Can reproduce this as well, though as you've mentioned, I cannot reproduce it if I create a new project.

**Comment by jgscherber** [comment] 2019-11-25 15:51
I've also experience this in VS2019
[ProblemSolution_VS2019.zip](https://github.com/dotnet/fsharp/files/3887390/ProblemSolution_VS2019.zip)

**Comment by cartermp** [comment] 2020-08-15 17:53
Since this is a legacy project system issue I'll close this out. The C# and F# teams are intentionally freezing support for the legacy proejct systems, addressing only absolutely critical (i.e., VS will flat out crash) problems. All new .NET FX projects with F# also use the new project file format.

**Closed by cartermp** 2020-08-15 17:53 UTC
Labels: Area-IDE Legacy Project System, Resolution-Wont Fix, bug
