### ISSUE TITLE
Microsoft.CodeAnalysis.Formatting.ISyntaxFormattingService is required.

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/fsharp#13010] opened 2022-04-19 03:23 UTC
Cursor up when in a single line comment on dogfood builds of VS yield Microsoft.CodeAnalysis.Formatting.ISyntaxFormattingService is required.

Works fine in retail builds.

![image](https://user-images.githubusercontent.com/5175830/163913732-a94ef1ba-641b-406e-a115-71fd6ffa71c7.png)

**Comment by vzarytovskii** [comment] 2022-04-27 18:34
I can't reproduce it anymore on latest main, gonna try fresh install.

**Comment by vzarytovskii** [comment] 2022-04-29 08:11
I've checked the latest 17.2 preview as well as 17.3 from `main`, and don't see it anymore. I will close it for time being.

**Comment by vzarytovskii** [comment] 2022-04-29 08:33
Disregard. I can't reproduce it in 17.2, but can in 17.3, reopening for tracking.

**Comment by dsyme** [comment] 2022-05-02 13:32
Closing as #13071 is merged to dev17.3

**Comment by vzarytovskii** [comment] 2022-05-03 12:49
It wasn't fixed in the latest dev17.3

**Comment by vzarytovskii** [comment] 2022-05-09 10:49
I've verified latest `Int Preview`

**Closed by vzarytovskii** 2022-05-09 10:49 UTC
Labels: Bug, Regression, Impact-High, Area-VS-Editor
