### ISSUE TITLE
VS Create assembly resources

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#14550] opened 2023-01-06 04:43 UTC
**Repro steps**

![image](https://user-images.githubusercontent.com/4289161/210931392-9a337ea5-7fd8-4704-8289-79ea5ecee9da.png)

**Expected behavior**

There should be a windows shown like in a C# project
![image](https://user-images.githubusercontent.com/4289161/210931478-9c0fcb65-42f8-4a93-985f-d2ea8f609426.png)

**Actual behavior**

It said it cannot find the file...

**Known workarounds**

None

**Related information**

* Operating system: Windows Server 2019
* .NET Runtime: .NET 7.101
* Editing Tools: Visual Studio 2022 17.4.3

**Comment by 0101** [comment] 2023-01-16 17:50
Looks like a duplicate of https://github.com/dotnet/fsharp/issues/13762

**Closed by 0101** 2023-01-16 17:50 UTC
Labels: Bug, Needs-Triage
