### ISSUE TITLE
Does F# support ProduceReferenceAssembly

### ISSUE THREAD

**Issue by xperiandri** [dotnet/fsharp#8642] opened 2020-02-28 20:23 UTC
I use F# in Xamarin.Forms and discovered `ProduceReferenceAssembly` element in C# template of a common project.
So I wonder if this feature works in F#

**Comment by abelbraaksma** [comment] 2020-02-28 21:46
That would be either `/refonly` or `/refout` as available for the C# compiler. Checking this: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options suggests that `fsc.exe` does not support it. Don't know if there's a workaround.

**Comment by cartermp** [comment] 2020-03-01 18:40
The compiler doesn't support producing or consuming reference assemblies, no. This is something we'd like to do in the long-term since it can very positively affect memory consumption in IDEs. But it's not on the immediate roadmap yet.

**Comment by KevinRansom** [comment] 2020-03-06 19:30
@xperiandri,
We consume ref assemblies fine, they are after all just assemblies.  However, we don't produce them yet.

**Comment by charlesroddie** [comment] 2020-11-22 22:27
This has large benefits:

- When compiling in msbuild, if project A is changed in a way that does not change its public API, projects dependent on A do not need to be rebuilt. The msbuild implementation described here: https://github.com/dotnet/msbuild/issues/1986. These changes are very common and going from O(n) to O(1) compilation time, where n is the number of projects, is a large benefit.
- I believe (ok, I guess) that when an F# dll is read when referenced in another F# project, everything gets put in memory (including private/internal members, local functions). With a reference assembly, this waste wouldn't happen.

**Comment by charlesroddie** [comment] 2020-11-22 22:33
Some additional discussion here: https://github.com/dotnet/fsharp/issues/8044#issuecomment-570742437

It's worth testing whether https://github.com/ImperialPlugins/ReferenceAssemblyGenerator or https://github.com/JetBrains/Refasmer can preserve enough F# metadata for the resulting assembly to be understood by dependent F# projects.

**Comment by charlesroddie** [comment] 2020-11-22 22:55
Copied from other thread:

> @smoothdeveloper In large dotnet projects, tools like Resharper or Rider already support incremental recompilation at solution/project level, shaving off a lot of time spent on building the solution, even when a project depended upon is changed, it won't recompile the depending projects unless there is top level API surface change.

> @0x53A Roslyn/MsBuild added support for reference assemblies, would be great if fsc also supported this. Here is a good writeup from the MsBuild side: dotnet/project-system#2254 This is not directly related to the incremental build of a single assembly, but having this would enable to skip a lot of redundant recompilations.

> @cartermp Reference assembly support is another good (also challenging) thing to add. Another benefit is a significant reduction in memory usage - for very large projects it could be upwards of 10% or less.

> @TIHan Also, regarding reference assemblies: We will gain nothing when it comes to F#-to-F# referencing in tooling since we do not even build assembly data anyway. Our "reference assembly" in this case is the signature metadata. But, if we were to have better integration with C#/VB projects, it would be nice.

@TIHan I believe this comment assumes that in-memory cross-project references is enabled. I don't think that's a good assumption given the poor performance of in-memory cross-project references when there are many projects. Maybe with a good incremental compiler the need for reference assemblies reduces - although at some point you will have to build!

**Comment by KevinRansom** [comment] 2020-11-23 04:37
Closing: due to this thread is a dupe of this older thread:  https://github.com/dotnet/fsharp/issues/3066 ,

**Closed by KevinRansom** 2020-11-23 04:37 UTC
Labels: Area-Compiler, Feature Request
