### ISSUE TITLE
Using ToFSharpFunc unconditionally nullifies purpose of LeafExpressionConverter.QuotationToLambdaExpression

### ISSUE THREAD

**Issue by blaulaub** [dotnet/fsharp#11744] opened 2021-06-29 12:35 UTC
This issue concerns the line https://github.com/dotnet/fsharp/blob/ec83cf9072a906764744fb42a8da286f2338ddae/src/fsharp/FSharp.Core/Linq.fs#L661

I need to write an F# code quotation that the Entity Framework can translate into SQL. The code src/fsharp/FSharp.Core/Linq.fs (linked above) provides the function LeafExpressionConverter.QuotationToLambdaExpression for converting F# code quotation to LINQ expressions. This works fine on a materialised LINQ IQueryable (in memory, e.g. usually backed by an IEnumerable). However, it fails on other IQueryables, in particular when backed by an SQL database.

In these cases, some translator tries to translate the LINQ expression (produced by LeafExpressionConverter.QuotationToLambdaExpression) to native DB code, e.g., SQL (e.g., the Entity Framework does this). The purpose of that translation is to gain efficiency, by offloading data operations from the .NET Core code to the database engine.

Problem is that LeafExpressionConverter.QuotationToLambdaExpression at present will always wrap the expression into a method call to ToFSharpFunc, which most translators (usually being F# agnostic) do not know how to handle. This nullifies the purpose of converting the F# code quotation into a LINQ expression (I do not want to run the operation in memory when the underlying dataset is gigantic, I want to keep that offloaded to the DB engine.)

Of course F# code quotations are not generally translatable to SQL, so ToFSharpFunc may be viable/necessary for general cases. However, when using LeafExpressionConverter.QuotationToLambdaExpression to interact with e.g. Entity Framework, the F# code quotations usually used _should_ be convertible/translatable, not only to LINQ expressions, but to actual SQL. In such cases, the LeafExpressionConverter.QuotationToLambdaExpression should _not_ add any function calls specific to F#.

I have also documented my troubles in https://stackoverflow.com/questions/68170451/strip-tofsharpfunc-from-leafexpressionconverter-quotationtolambdaexpression

**Comment by blaulaub** [comment] 2021-06-30 20:06
Would a runnable example of the problem be of help? I could construct one using Sqlite-in-memory, so it could run unit-test-style without external dependencies.

**Comment by baronfel** [comment] 2021-06-30 20:15
I _think_ I hit something similar in helping a PR for the Akka.net project back in [December](https://github.com/akkadotnet/akka.net/pull/4696#issuecomment-752249875). Not strictly the same, as the component being used (FSharp.Quotations.Evaluator) doesn't live in this repo, but it similarly has a compilation method that, while correct in terms of execution, is not ideal for direct translation to other LINQ backends.

**Comment by dsyme** [comment] 2021-06-30 22:53
I'm not quite sure what the ask is.  We can't remove the line, since part of the contract of the code is if you put in a quotation of an expression of type T (`Expr<T>`), then you get a LINQ Expression of type `T` out.  

If you want a delegate-typed expression tree out, you should give it a delegate-typed expression tree as input, see `NewDelegate` https://github.com/dotnet/fsharp/blob/ec83cf9072a906764744fb42a8da286f2338ddae/src/fsharp/FSharp.Core/Linq.fs#L600

So F# queries, for example, will work on `Expr<Func<int,int>>` and so on, converting to the appropriate LINQ expression trees.  The delegate-typed quotations are created from F# function lambdas, e.g. `foo.Select(fun x -> x + 1)` where the implicit conversion from F# functions to delegates kicks in (the argument has type `Expression<Func<int,int>>`).

If your input must be FSharpFunc-typed quotations then you could of course strip and reassemble the quotation from FSharpFunc --> Delegate (on the input) or the LINQ expression from FSharpFunc --> Delegate (on the input)?

**Comment by defaultbranch** [comment] 2021-07-02 09:28
Thanks for the explanation and pointing to Line 600; seems to me the problem is _not_ in Linq.fs, but in the quotation splicing I do before;

The following case seems to work as expected (looks like the LeafExpressionConverter passes through Line 600 you mentioned, case `| Patterns.NewDelegate(dty, vs, b)`)
```
<@ System.Func<int,int>( fun x -> x+1 ) @>
|> LeafExpressionConverter.QuotationToLambdaExpression
```

But the following case does not work as expected (the LeafExpressionConverter passes though Line 661, case `| Patterns.Lambda(v, body)`)
```
let e = <@ fun x -> x+1 @>
<@ System.Func<int,int>( %e ) @>
|> LeafExpressionConverter.QuotationToLambdaExpression
```

**Comment by defaultbranch** [comment] 2021-07-02 09:29
Since the problem is _not_ in Linq.fs, but in the input I generated, feel free to close this issue.
Thanks for the help!

**Closed** 2021-07-02 15:07 UTC

**Comment by blaulaub** [comment] 2021-07-02 18:34
I have posted a follow-up-question on SO for why the spliced quotation is different from the direct quotation,
https://stackoverflow.com/questions/68228386/why-does-direct-code-quotation-of-system-func-yield-a-delegate-and-spliced-quota

**Comment by dsyme** [comment] 2021-07-05 16:52
Thank you!  It's actually also a great example of where type-directed-conversions (in this cases from lambda to delegate) add additional confusion for the user.
