### ISSUE TITLE
Pattern `DUCase` matches `DUCase _`

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/fsharp#9520] opened 2020-06-21 09:17 UTC
```fsharp
type DU = | DUCase of int
let y =
    function
    | DUCase -> () // This should fail with FS0019: This constructor is applied to 0 argument(s) but expects 1
```

This type-checks in VS tooling and works in F# interactive. Behaviour is as if the user had written the correct `| DUCase _ -> ()`

This doesn't apply to active patterns, which fail without arguments as expected.

Tested on VS 2019 16.6.0 and "F# Interactive version 10.9.1.0 for F# 4.7".

SharpLab doesn't have the problem and gives expected error.

**Comment by abelbraaksma** [comment] 2020-06-21 17:13
This must be a recent regression. When I try it in FSI in VS 2019 16.5.4 (yep, still had a copy that wasn't updated), I can see:

```f#
> type DU = | DUCase of int
let y =
    function
    | DUCase -> ();;

      | DUCase -> ();;
  ------^^^^^^

C:\[...]\stdin(6,7): error FS0019: This constructor is applied to 0 argument(s) but expects 1
```

**Comment by KevinRansom** [comment] 2020-06-21 21:17
This is fixed by this recent PR:  https://github.com/dotnet/fsharp/pull/9426

**Comment by cartermp** [comment] 2020-06-21 21:28
Closing as duplicate of https://github.com/dotnet/fsharp/issues/9420

**Closed by cartermp** 2020-06-21 21:28 UTC
Labels: Resolution-Duplicate
