### ISSUE TITLE
Quick fix fails to open nested module

### ISSUE THREAD

**Issue by asik** [dotnet/fsharp#6732] opened 2019-05-14 19:42 UTC
#### Repro steps
File1.fs
```
module File1

module SubModule =

    let Foo = 3
```
Program.fs
```
[<EntryPoint>]
let main argv =
    let a = Foo
    0
```

Use suggestion to add open declaration on Foo.
![image](https://user-images.githubusercontent.com/1631157/57726948-43eb2c80-765e-11e9-8501-d551c696ba03.png)

#### Expected behavior

Suggests `open File1.SubModule`

#### Actual behavior

Suggests `open File1`
This does not fix the issue and the code still doesn't compile.

#### Related information 
Visual Studio 16.0.2
Visual F# Tools 10.4 for F# 4.6 - 16.0.0.0

**Comment by dsyme** [comment] 2020-08-31 14:55
Duplicate of https://github.com/dotnet/fsharp/issues/4223

**Closed by dsyme** 2020-08-31 14:55 UTC
Labels: Area-IDE Language Service, bug
