### ISSUE TITLE
Incomplete `match` breaks collapsing of previous `match`

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/fsharp#7081] opened 2019-06-29 15:23 UTC
**Repro steps**

1. Open your IDE of choice (tested in VS2019 and Rider 2019.1.2) and write the following code:

   ```fsharp
   let main argv =
       match 1 with
       | 1 -> ()
       | 2 -> ()
       | 3 -> ()
   
       
       0
   ```
2. Now, collapse the `match 1 with` block.
3. Then, write a new `match` near the end of the function:
   ```fsharp
   let main argv =
       match 1 with
       | 1 -> ()
       | 2 -> ()
       | 3 -> ()
   
       match
       0
   ```

Here's a GIF with steps:
![matches](https://user-images.githubusercontent.com/92793/60386198-50b3ca80-9abc-11e9-9f9c-0a2233207c6a.gif)

**Expected behavior**

Previous `match` block should still be collapsed.

**Actual behavior**

Previous `match` block uncollapses automatically.

**Related information**

* **Operating system:** Windows
* **Editing Tools:** VS2019 v16.1.4, Rider 2019.1.2 (both show the same behavior)

**Comment by cartermp** [comment] 2019-07-01 03:12
I'll close this as a dupe of #7078, since it seems like it's the same root problem.

**Closed by cartermp** 2019-07-01 03:12 UTC
