### ISSUE TITLE
Runtime error when loading and runnning assembly with big types

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/fsharp#16039] opened 2023-09-25 12:03 UTC
**Please, read the first comment for more details and TL;DR**

When compiling assembly with one namespace, which contains 3 types, and each type contains 40_000 instance methods, running the assembly fails with:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Program+Main.main(System.String[])
NativeCommandExitException: Program "dotnet.exe" ended with non-zero exit code: -1073741819.
```

Script to generate Program.fs (which then can be just built using normal .NET):
```fsharp
open System.Text
open System.IO

#nowarn "20"

let generateTypes (x:int) (y:int) =
    let sb = StringBuilder()
    for i in 1..x do
        sb.Append("[<NoComparison; NoEquality>]\n")
        sb.Append(sprintf "type Type%d() =\n" i)
        for j in 1..y do
            sb.Append(sprintf "    member _.Method%d() = printfn \"Type%d Method%d\"\n" j i j)
        sb.Append('\n')
    sb

let generatedCode = generateTypes 1 (65533)

generatedCode.Append("module Main =\n")
generatedCode.Append("    [<EntryPoint>]\n")
generatedCode.Append("    let main _ =\n")
generatedCode.Append("        printfn \"Fin\"\n")
generatedCode.Append("        0\n")

File.WriteAllText("Program.fs", generatedCode.ToString())
```

**Update:** so, 1 type with `65532` methods causes no issues `65533` methods (+1 more) shows the issue.

It seems we overflow somewhere above `65535` (`65532` + main + `.ctor`(s)), `MethodDef` table shows `65535` in both cases, however in the second case (case of failure) it seems all the methods' type is the same (AssemblyAttribute), meaning when we have more than 65k methods in total, all of them go to one type int the table.

**Update 2:** if we have much more methods (70k) we get AccessViolation, if we have exactly 65535/65536 - we get te initial issue:

**Update 3:** My initial testing methodology is incorrect - it is obvious that the limitation for one type is 65k (known CLR limitation), however if you will generate `2` types with `32766` methods each, it will still fail,

Codegen for 2 types:
```fsharp
open System.Text
open System.IO

#nowarn "20"

let generateTypes (x:int) (y:int) =
    let sb = StringBuilder()
    for i in 1..x do
        sb.Append("[<NoComparison; NoEquality>]\n")
        sb.Append(sprintf "type Type%d() =\n" i)
        for j in 1..y do
            sb.Append(sprintf "    member _.Method%d() = printfn \"Type%d Method%d\"\n" j i j)
        sb.Append('\n')
    sb

let generatedCode = generateTypes 2 (32766)

generatedCode.Append("module Main =\n")
generatedCode.Append("    [<EntryPoint>]\n")
generatedCode.Append("    let main _ =\n")
generatedCode.Append("        printfn \"Fin\"\n")
generatedCode.Append("        0\n")

File.WriteAllText("Program.fs", generatedCode.ToString())

```

```
Unhandled exception. System.TypeLoadException: Type '<StartupCode$helloworld>.$.NETCoreApp,Version=v7.0.AssemblyAttributes' from assembly 'helloworld, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' contains more methods than the current implementation allows.
```

Provide any related information (optional):
* Win 11, latest .NET8 RC

**Comment by T-Gro** [comment] 2023-09-25 14:48
Another tip:

If you do want structural equality and comparison (they are useful), another way to reduce methods is to apply `[<DefaultAugmentation(false)>]`. This reduces the codegen of DU methods which are typically consumed by C# code.

**Comment by cataggar** [comment] 2023-11-28 16:08
This does look like it may be the cause of the `AccessViolation` exceptions ([internal Teams thread](https://teams.microsoft.com/l/message/19:e12c01940a254f19b92d9422cabb772c@thread.tacv2/1687437238147?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=c3909f28-1aca-4aca-ac23-59f272020603&parentMessageId=1687437238147&teamName=Friends%20of%20F%23&channelName=General&createdTime=1687437238147)). Any executable or test that includes a reference to our `Domain` project ends up with an `AccessViolation` when built without `<Optimize>false</Optimize>`, which `Debug` configuration normally does and is important for debugging.

We are using an F# JSON library and my guess is that we exceeded the 65535 barrier described above for methods on a type. I wonder if there is an easy way to inspect the assembly to see. I wonder why it is not impacting optimized assemblies. Will be impacted when more serialization is added?

For us, I would say this is high impact.

**Comment by cataggar** [comment] 2023-11-29 17:55
It would be great if there was a utility that could count the methods in an assembly to see if it exceeds 65535. This misses all of the internal and compiler generated method. It would be nice to have something similar that worked.

``` fsharp
let dllPath = @"C:\Users\cataggar\ms\Domain.dll"
open Mono.Cecil
let mdl = ModuleDefinition.ReadModule dllPath
let mutable methodCount = 0
for typ in mdl.Types do
    methodCount <- methodCount + typ.Methods.Count
printfn "Types: %d, Methods: %d" mdl.Types.Count methodCount
```

**Comment by vzarytovskii** [comment] 2023-11-29 20:00
> It would be great if there was a utility that could count the methods in an assembly to see if it exceeds 65535. This misses all of the internal and compiler generated method. It would be nice to have something similar that worked.
> 
> 
> 
> ``` fsharp
> 
> let dllPath = @"C:\Users\cataggar\ms\Domain.dll"
> 
> open Mono.Cecil
> 
> let mdl = ModuleDefinition.ReadModule dllPath
> 
> let mutable methodCount = 0
> 
> for typ in mdl.Types do
> 
>     methodCount <- methodCount + typ.Methods.Count
> 
> printfn "Types: %d, Methods: %d" mdl.Types.Count methodCount
> 
> ```

Ilspy can do that, it shows methods in the MethodDef table.

**Comment by KevinRansom** [comment] 2023-12-08 23:55
So there are three different bugs here:

1. Shown by vlads repro.   Release builds where the last method has a type Id of 0x0000ffff, I.e there are exactly 65535 methods in an assembly cause an error message similar to:
````
Unhandled exception. System.TypeLoadException: Type '<StartupCode$helloworld>.$.NETCoreApp,Version=v7.0.AssemblyAttributes' from assembly 'helloworld, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' contains more methods than the current implementation allows.
````
This is a loader error, actually ... it looks more like a poorly designed part of the Ecma spec to me.  Although they may have just described the implementation, I suppose.

This can be reproduced with the C# compiler.
For funsies a zip file with a C# repro can be found here: [CSharp.zip](https://github.com/dotnet/fsharp/files/13621693/CSharp.zip)

````
dotnet run -c release
Unhandled exception. System.TypeLoadException: Type 'ConsoleApp50.AfterProgram' from assembly 'CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' contains more methods than the current implementation allows.
````
and an F# repro here: [FSharp.zip](https://github.com/dotnet/fsharp/files/13621805/FSharp.zip)
````
C:\Users\kevinr\source\repos\ConsoleApp48\FSharp>dotnet run -c release
Unhandled exception. System.TypeLoadException: Type '<StartupCode$FSharp>.$.NETCoreApp,Version=v8.0.AssemblyAttributes' from assembly 'FSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' contains more methods than the current implementation allows.
````
Also ... marvel at how much quicker F# is than C# at this.  Note, these samples do not lay out the type for execution and so, in each case they have a few more methods than the runtime really allows.

We could add an dummy extra method in the very rare circumstance it happens, although I don't really think it's necessary given how specific the circumstances are that fails.

2.  An AV happens in source files with greater then 65K methods this is due to portable pdb symbol generation, there is a limit on the method id's associated with a single document.  This bug will be managed here:  https://github.com/dotnet/fsharp/issues/16399
The work around is to split the methods accross several source code files, that should solve the problem, until we get a proper fix which will be slightly more sophisticated.

3. F# classes with more than 64K methods blow up when the class is laid out for execution by the loader, this bug will be managed here:   https://github.com/dotnet/fsharp/issues/16398
The solution will be to add a compiler error when a developer tries to compile a file with more than 64K methods with a decent error message.


Since we intend doing nothing about issue 1.  I propose we close this bug and manage it at the other two more specific bugs that we do intend fixing.

**Comment by KevinRansom** [comment] 2023-12-11 21:34
Closing in favour of: #16398 and #16399

**Closed by KevinRansom** 2023-12-11 21:34 UTC
Labels: Bug, Impact-Low, Area-Compiler-CodeGen
