### ISSUE TITLE
Build error when using inline async methods from libraries built with another version of FSharp.Core

### ISSUE THREAD

**Issue by dkcsiltberg** [dotnet/fsharp#6450] opened 2019-04-07 22:37 UTC
##### Option a)

1. Download the sample repo here: https://github.com/dkcsiltberg/FSharpCoreErrorExample
2. Try to build it with Visual Studio 2019

##### Option b)

1. Create a new FSharp library project in VS2019. This will have FSharp.Core 4.6.2.
2. Downgrade FSharp.Core to 4.5.2 in this project
3. Add the following method somewhere: `let inline f x = async.Return x`
4. Create another FSharp library project (keeping FSharp.Core at 4.6.2 in this one) in the same solution, and reference the previous one
5. Add the following method somewhere `let f = <Module from first project>.f`
6. Try to build the solution
7. (optional) Do the same again but with the versions of FSharp.Core reversed.

#### Expected behavior

It builds correctly

#### Actual behavior

Both referencing project fail with `FS0193	The module/namespace 'Control' from compilation unit 'FSharp.Core' did not contain the val 'ValLinkagePartialKey(OnSuccess)'`

#### Known workarounds

Either:
1. Make sure libraries and projects you use are either
    1. all built with "Old Core" (see related information)
    2. all built with "New Core"
2. Do not use inline async methods

#### Related information

* Operating system: Windows 10
* Editing Tools: Visual Studio 2019

First, let's establish some terminology. I want to divide the verison of FSharp.Core into two groups,
FSharp.Core <= 4.5.2 (henceforth "Old Core") and FSharp.Core >= 4.5.4 (henceforth "New Core"). The reason for this is that the "break" seemed to happen between those two versions (and possibly it happened between 4.5.0 and 4.5.1 as well, but was reversed in 4.5.2).

As can be seen in the example, this is a symmetric issue. It occurs both if the referencing project is built with New Core and the reference project is built with Old Core, and vice versa.

Granted, this is only a problem if you try to use inline async methods (and maybe some other cases we haven't noticed, of course), so this might not be as big of an issue as I fear. However, we've already run into it a couple of times, both shortly after FSharp.Core 4.5.4 was released. The first one was when using the somewhat popular https://suave.io/ which uses async signatures a lot. The second time was from an internal https://github.com/fsprojects/FSharpPlus like library, that uses inline to create generic map and bind functions for monadic types.

So at least in our experience it is a real problem. And if you use two or more libraries all built with different versions, there might be no way out of this, apart from keeping track of which versions of which nuget packages are built with which verison of FSharp.Core. And that is virtually impossible already with just a few packages.

When we first encountered this issue, some googling revealed the following issue that gave the same error and might thus be related: https://github.com/Microsoft/visualfsharp/issues/5378

It was this post that cemented our working theory of the problem. While no changes to signatures were made between Old Core and New Core, this post indicates that some functions were either inlined or deinlined (or something along those lines), and it was this that created a sort of binary incompatibility issue between the two versions that the F# compiler is unable to resolve. Now, the problem might of course be way more complex than that, and this is really not our forte, so we'll leave it at that.

In this post a sort of official answer was also provided, and it went something like this: "why would you ever use another version of FSharp.Core than the one you get when creating a new project from our official templates? That is the only officially supported version for the F# compiler".

While I belive that this position &ndash; that the latest version of FSharp.Core available on nuget is not an officially supported one &ndash; is not neccessarily a great one since this unspoken rule might cause all sorts of problems unless 100% of the F# community are both aware of it (we were not) and adheres to it (which I sincerely doubt), we said fair enough. Since we only ran into this problem a couple of months ago, we decided to use workarounds and just wait for VS 2019, which would bring with it a new version of the F# compiler and a new "officially supported" version of FSharp.Core according to the unspoken rule. And now this day has come.

But alas, the problem still remains, as can be seen in the example solution. And this is no longer when using unsupported versions of FSharp.Core. And regardless of your position on this unspoken rule, I think we can all agree that being able to use inline async methods from older libraries when using the latest "officially supported" version of FSharp.Core is a pretty decent feature to have.

I apologize in advance if I come off as passive aggressive about this, that is not my intent. Well, maybe a smidge. It DID cause us quite a bit of headache after all. And I really don't like this unspoken rule, in case that was unclear.

**Comment by cartermp** [comment] 2019-04-07 23:14
Thanks for the report and repro. I can also confirm this fails on my machine using .NET Core:

* Library project explicitly using FSharp.Core 4.5.2
* Console app referencing the library
* Same code as your example with the same error

@dsyme can speak more towards the inlining of async members that was done for F# 4.5 and the ramifications of that. This one feels like a subtle breaking change, but I could be wrong.

I do want to clarify the support position here:

* FSharp.Core is backwards compatible, meaning you should be able to reference an older FSharp.Core through some means and not have to change your code
* FSharp.Core is binary compatible, meaning you could hot-swap your binaries and runtime and the application would still run
* FSharp.Core **is not** forwards-compatible. That is, use of an arbitrary newer FSharp.Core from an arbitrary older F# compiler is not supported and not guaranteed to work. Although we take strides to make sure this doesn't generally happen, eventually we'll add new concepts to the binary that older compilers do not understand. Failing to take this position would mean we cannot feasibly evolve the F# language.

The linked issue was a binary compatibility issue where the F# binary format was inadvertently changed in a version of the package that is now delisted. You can view the full writeup here: https://github.com/Microsoft/visualfsharp/issues/5369#issuecomment-408205550

As far as I understand it, _this_ issue is a binary breaking change, so it should be looked at.

**Comment by dsyme** [comment] 2019-04-08 16:13
I need to understand this issue - it is unexpected.  I'll look into it.

**Comment by dsyme** [comment] 2019-04-08 16:14
(If there is a regression here, as appears to be the case, then it is likely there's little we can do about it, except give good guidance)

**Comment by cartermp** [comment] 2019-04-08 16:39
If we determine it's a regression then I'll post a blog post on the .NET Blog, update release notes accordingly, file an issue in the fslang-designs repo, update the RFC, and keep this issue (even if closed) as a canonical source of the problem.. At the very least, we should have a fully traceable set of documentation around the problem.

**Comment by dsyme** [comment] 2019-04-09 11:01
In the repro, in any situation, project `BuildErrorExample52.fsproj` gives a warning because it references `ExampleAsyncLib62`, which is invalid, since that uses a higher FSharp.Core.

After changing that, this _only_ repros with FSharp.Core `4.5.2`.  I tried global replace `4.5.2` for all of these and the solution built clean:

* `4.5.1`
* `4.5.0`
* `4.4.0`
* `4.3.4`
* `4.5.4`

Given this, I think it's just a glitch in `4.5.2` related to #5378.  Guidance should be that libraries using `inline` on async code should either target FSharp.Core `4.5.1` or `4.6.2`

**Comment by dkcsiltberg** [comment] 2019-04-09 13:07
Ok, we've definitely had issues in more cases than that, so I did some more experimenting.
<table>
  <tr>
    <th>Referenced \ Referencing</th>
    <th>4.5.0</th>
    <th>4.5.1</th>
    <th>4.5.2</th>
    <th>4.5.4</th>
    <th>4.6.x</th>
  </tr>
  <tr>
    <td>4.3.4</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
  <tr>
    <td>4.5.0</td>
    <td>Ok</td>
    <td>Error</td>
    <td>Error</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
  <tr>
    <td>4.5.1</td>
    <td>Other</td>
    <td>Wtf?</td>
    <td>Error</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
  <tr>
    <td>4.5.2</td>
    <td>Error</td>
    <td>Error</td>
    <td>Ok</td>
    <td>Error</td>
    <td>Error</td>
  </tr>
  <tr>
    <td>4.5.4</td>
    <td>Other</td>
    <td>Error</td>
    <td>Error</td>
    <td>Ok</td>
    <td>Ok</td>
  </tr>
</table>

The most surprising thing here is that 4.5.1 seems to get the error with itself! So perhaps telling people to use 4.5.1 is not the best option.

I also included some "invalid" examples where we use a higher version for the referenced project than the referencing. When it says "Other", it means we get a slightly different error message. The reason for including this is twofold:
1. The warning you mentioned does not appear if it is only between minor versions, e.g. 4.5.1 references 4.5.2.
2. Many nuget packages do not specify the specific version of FSharp.Core in their dependecies, they might just state >= 4.0.0.0, when they are in fact using 4.5.0 or something, and it is quite a pain to figure out which specific version it uses.

**Comment by dkcsiltberg** [comment] 2019-04-09 14:19
Yes, I am all for unlisting 4.5.0-4.5.2, that is a great start. It won't make the problem go away immediately tho.

Take a look at this package for instance, which is one of those that caused us problems: https://www.nuget.org/packages/Suave/2.5.3
The dependency is listed as FSharp.Core (>= 4.0.0 && < 5.0.0), so it will be perfectly happy to continue existing unaltered and be resolved properly by package managers even after that unlisting. However, it is actually built with 4.5.0, and there is no way of knowing that until you actually run into the problem, or use ildasm to inspect the dll in the package. Or look at the source, I guess.

But I guess it is the responsibility of library authors to read the guidance and update the packages accordingly. I just don't trust everyone to do that in a timely fashion. Or ever, in some cases.

**Comment by BentTranberg** [comment] 2019-04-10 18:37
I have spent two days working through the Suave Music Store demo, and now I got stuck on this issue and landed here. I got the exact error reported here. Using FSharp.Core 4.5.2 from NuGet solved the issue, but I am not sure if that is a workaround I can accept when using Suave for my business projects. If I understand correctly, a solution would be to have Suave compiled with a later FSharp.Core, so I will consider bringing attention to this issue in the Suave repo on GitHub.

It looks like you don't need another repro for this issue, but you can have my demo if it helps - just let me know. (Note to self: revision 382.) It does not depend on a DB like the original demo, so it's just compile and run. VS 2019. Project is a .NET Core 2.2 console application.

**Comment by dsyme** [comment] 2020-08-24 19:46
I believe we can close this as things are fine with more recent FSHarp.Core.

**Closed by dsyme** 2020-08-24 19:46 UTC
Labels: Area-Library, regression
