### ISSUE TITLE
Build fails when no source code

### ISSUE THREAD

**Issue by Thorium** [dotnet/fsharp#6305] opened 2019-03-02 20:18 UTC
Steps to reproduce:
Create a fsproj-projectfile with following content:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net461;netcoreapp2.0;netstandard2.0</TargetFrameworks>
    <PackageId>MyPackage</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SQLProvider" Version="1.1.59" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>

</Project>
```

Run: `dotnet restore` and `dotnet build`

Expected result: a meta-package would be generated like [here](https://stackoverflow.com/a/50012416).
Actual result:

```cmd
A:\>dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 30.53 ms for A:\MyPackage.fsproj.
  MyPackage -> A:\bin\Debug\net461\MyPackage.dll
  MyPackage -> A:\bin\Debug\netcoreapp2.0\MyPackage.dll
C:\Program Files\dotnet\sdk\2.1.504\FSharp\Microsoft.FSharp.Targets(265,9): error MSB6006:
 "RunFsc.cmd" exited with code -1073741571. [A:\MyPackage.fsproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.1.504\FSharp\Microsoft.FSharp.Targets(265,9): error MSB6006:
 "RunFsc.cmd" exited with code -1073741571. [A:\MyPackage.fsproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:09.70

```

**Comment by cartermp** [comment] 2019-03-05 06:59
cc @KevinRansom

**Comment by KevinRansom** [comment] 2019-03-05 07:02
@Thorium, nice.

Thanks for finding this I will take a look.

**Comment by Thorium** [comment] 2020-02-11 12:35
Any news on this? It's almost a year old, and I'd guess it'd be an easy fix?

**Comment by dsyme** [comment] 2020-08-26 18:21
This does still fail for `netstandard2.0`

However I think the workaround is so simple - just have an empty F# source file in your project - that it's barely even a bug

**Comment by abelbraaksma** [comment] 2020-08-27 17:39
@dsyme, apparently this is a trick used with csc.exe to create a meta package: https://stackoverflow.com/q/50009877/111575.

Though I'm not sure whether fsc.exe should be aligned with that feature.

**Comment by cartermp** [comment] 2020-08-27 17:58
For scenarios like this I just use a `.proj` folder. A good example is here: https://github.com/SaturnFramework/Saturn.Template/blob/master/Saturn.Template.proj

Given this I will close it as by design, since this isn't really a goal for F#.

**Closed by cartermp** 2020-08-27 17:58 UTC
Labels: Area-Compiler, Feature Improvement

**Comment by KevinRansom** [comment] 2020-08-27 18:52
This is absolutely by design.  

C# projects, collect source code for the build from the sub directory.  F# can't do this because source code order is important to F#.  The equivalent project for F# looks like below:  The only difference is that a developer must provide a source file for the compiler to use and the build to ignore.  Before you cry foul ... the C# compiler builds a dll that it doesn't use when performing the pack operation.

````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PackageId>MyPackage</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="NuGet.Versioning" Version="4.7.0-rtm.5104" />
    <PackageReference Include="NUnit" Version="3.10.1" />
  </ItemGroup>

</Project>

````
