### ISSUE TITLE
Visual studio intellisense on attribute not working

### ISSUE THREAD

**Issue by padzikm** [dotnet/fsharp#9053] opened 2020-04-26 19:32 UTC
Hi, intellisense in visual studio 2019 suggests nothing for fscheck's property attribute:
```
module Tests
open System
open Xunit
open FsUnit.Xunit
open FsCheck
open FsCheck.Xunit

[<Property>]
let ``reverse of reverse is the same list`` (xs: int list) =
    List.rev (List.rev xs) = xs
```

Property attribute has for example MaxTest property, which is not shown when typing [<Property()>]

Expected result is showing list of properties for fscheck's property attribute:
```
module Tests
open System
open Xunit
open FsUnit.Xunit
open FsCheck
open FsCheck.Xunit

[<Property(MaxTest=200)>]
let ``reverse of reverse is the same list`` (xs: int list) =
    List.rev (List.rev xs) = xs
```

**Comment by cartermp** [comment] 2020-05-06 18:41
@padzikm just to confirm, you're expecting that `MaxTest` shows in a completion list, yes? Since the `Property` attribute itself does appear.

If so, this is not specific to FsCheck but rather any attribute where you want to set properties in the constructor. I swear we had a bug for this somewhere but I couldn't find it.

**Comment by abelbraaksma** [comment] 2020-05-06 19:34
@cartermp, possibly you remembered this one? https://github.com/dotnet/fsharp/issues/3312. It was solved by not letting auto complete do its thing when equal or comma is typed.

Perhaps that fix made the auto complete mentioned by the OP disappear?

**Comment by cartermp** [comment] 2020-05-06 20:10
No, I'm not sure this has ever worked. The fix for that issue is only about committing completion based on certainly characters typed. Triggering completion and getting the right symbols is a different matter altogether.

**Comment by dsyme** [comment] 2020-09-01 14:17
I think we can treat this as a duplicate of https://github.com/dotnet/fsharp/issues/554 and track the issue there

**Closed by dsyme** 2020-09-01 14:17 UTC
Labels: Area-FCS, bug
