### ISSUE TITLE
Missing text-cursor-focus when going to definition in VS2019

### ISSUE THREAD

**Issue by JanWosnitza** [dotnet/fsharp#9923] opened 2020-08-12 13:10 UTC
This is a _Visual F# Tools_ problem:

If you go to the definition of a type within an F# file, where the type is defined in another file (doesn't matter if F# or C#), the file is opened as expected and the correct line is shown. But the text-cursor is not showing up. This only happens if tabs are place left or right. No problem if tabs are placed on top.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Create a new F# ConsoleApp (doesn't matter if dotnetcore or other framework)
2. Click right on the tab of opened file `Program.fs` and select "**Set Tab Layout -> Place Tabs on the Left**"
3. Create a file `File1.fs`.
4. Create a `type MyType() = class end` in `File1.fs`
5. Use `MyType` in `Program.fs` (e.g. `let x = typeof<File1.MyType>`)
6. Right click on `File1.MyType` and select "Go To Definition"
7. Notice that you can't type or move the text-cursor (though selection still works)

A solution with described reproduction steps: [ConsoleApp.zip](https://github.com/dotnet/fsharp/files/5062797/ConsoleApp.zip)

**Expected behavior**

On 7. the text-cursor should be blinking and you should be able to type.

**Actual behavior**

On 7. the text-cursor doesn't blink and you can't type.

**Known workarounds**

Click into the window with the mouse cursor.

**Related information**
This was fixed for C# recently: [Problem with F12 (Edit.GoToDefinition): After jumping to a different file the cursor disappears](https://developercommunity.visualstudio.com/content/problem/843952/problem-with-f12-editgotodefinition-after-jumping.html)

About Microsoft Visual Studio -> Copy Info (in short: pretty vanilla setup)
```
Microsoft Visual Studio Community 2019
Version 16.7.1
VisualStudio.16.Release/16.7.1+30406.217
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

C# Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   4.7.1.0
Visual Studio Tools for Unity
```

**Comment by cartermp** [comment] 2020-08-13 00:35
Eeek, reproduced this in 16.7, but it no longer reproduces in the 16.8 preview on my machine. The cursor gets stuck in the dropdown lists.

This is definitely an editor problem. Could you file an issue with the VS Report a Problem tool? I highly suspect there's a duplicate by now, and if there is then the tool should be good about finding a duplicate as you type out the issue.

But since this is external and resolved in the latest preview, I'll close this out and tag it appropriately.

**Closed by cartermp** 2020-08-13 00:35 UTC

**Comment by JanWosnitza** [comment] 2020-08-13 08:39
@cartermp [here we go](https://developercommunity.visualstudio.com/content/problem/1148347/missing-text-cursor-focus-when-going-to-definition.html). Though, auto-title-issue-search didn't give any matching results, so it's a new issue now.

**Comment by cartermp** [comment] 2020-08-13 17:24
Thanks @JanWosnitza

**Comment by JanWosnitza** [comment] 2020-10-08 12:13
😞
