### ISSUE TITLE
Exception that occurs in Seq.initInfinite cannot be handled

### ISSUE THREAD

**Issue by cdoool** [dotnet/fsharp#6922] opened 2019-06-02 07:11 UTC
# Description

Any Exception raised in the code of Seq.initInfinite bypass the try ... with block and bubbles up as "Exception User-Unhandled" 

# Repro steps

```
open System.IO
open System

[<EntryPoint>]
let main argv =
    let v =
        try   
            let read i =
                failwith "Exception!"
                i
            let values = Seq.initInfinite read |> Seq.takeWhile (fun x -> x < 5) |> Seq.toArray   
            values
        with
        | ex ->
            printfn "%s" "Exception!"
            Array.empty<int>
    printfn "%A" v
    Console.ReadKey() |> ignore
    0
```
# Expected behavior

Exception caught in try ... with block, v = Array.empty<int>

# Actual behavior

Unhandled user exception

# Version

Windows 10
Visual Studio Community 2019 Version 16.0.3
Microsoft .NET Framework 4.8.03752
Microsoft Visual F# Tools 10.4 for F# 4.6

**Comment by vasily-kirichenko** [comment] 2019-06-03 12:56
I cannot reproduce it:

![image](https://user-images.githubusercontent.com/873919/58803417-1e779000-8618-11e9-8a33-5057e654f5b3.png)

**Comment by cartermp** [comment] 2019-06-03 14:58
@cdoool  I cannot reproduce this either.

Here's my attempt to repro on VS 2019 16.1.

Exception thrown:

![image](https://user-images.githubusercontent.com/6309070/58811698-85c41e80-85dd-11e9-8354-43ae515ce120.png)

Caught:

![image](https://user-images.githubusercontent.com/6309070/58811758-a2605680-85dd-11e9-87c2-a0660f7084e1.png)

Can you try on VS 2019 16.1?

**Comment by cdoool** [comment] 2019-06-03 18:03
Updated Visual Studio to version 16.1.1, still getting this behaviour. Can't even put my finger on why it happens.

![image](https://user-images.githubusercontent.com/37249701/58823549-a2467200-8642-11e9-81fe-67ec44318892.png)

**Comment by cartermp** [comment] 2019-06-03 20:21
@cdoool Your last screenshot shows an expected behavior in VS; any time your throw an exception like that it will show the dialog and allow you to inspect it at debug-time.

In your original report, you implied the exception wasn't being caught. This would mean that the program would exit without printing the empty array. I cannot reproduce that behavior. Is that the case for you?

**Comment by cdoool** [comment] 2019-06-03 20:41
@cartermp That's exactly right, no empty array in the console output, just the unhandled exception dialog. Would an expected behaviour here be the execution of "with" block? Have a look, I just replaced Seq.initInfinite with Seq.unfold and everything now works just as expected. 

![Screenshot_1](https://user-images.githubusercontent.com/37249701/58832768-556d9600-8658-11e9-99bc-d76bc58424ae.png)

**Comment by cartermp** [comment] 2019-06-03 21:17
Can you zip up the project and upload it here? I can see if there's anything funky going on there. But I did just copy-paste your example into a new console app and couldn't reproduce it.

**Comment by penguid** [comment] 2019-06-03 23:57
This issue is not about whether the exception is caught overall, it is about why does Visual Studio debugger consider it a **User-Unhandled** exception and thus break on it?

E.g. if you take OP's code and add a simpler handled exception above it, Visual Studio in debug mode ignores it and only breaks on the original exception, despite both being enclosed in try/with.

```fsharp
[<EntryPoint>]
let main argv =
    try
        failwith "Exception 1" // VS doesn't break here in debug mode
    with
    | ex -> printfn "%s" ex.Message

    let v =
        try
            let read i =
                failwith "Exception 2" // VS breaks here in debug mode
                i
            let values = Seq.initInfinite read |> Seq.takeWhile (fun x -> x < 5) |> Seq.toArray
            values
        with
        | ex ->
            printfn "%s" ex.Message
            Array.empty<int>
    printfn "%A" v
    System.Console.ReadKey() |> ignore
    0
```

**Comment by 0x53A** [comment] 2019-06-04 06:51
That's probably related to "just my code", (which is the first thing I always disable). It treats exceptions different when they pass a boundary from user code (your code) to library code (seq.initInfinite)

**Comment by penguid** [comment] 2019-06-04 18:13
But it doesn't do that with other library functions `List.init` or `Seq.unfold`:

```fsharp
[<EntryPoint>]
let main argv =

  let initFn i = failwith "" ; i // VS debug skips and exception is handled normally
  try
    List.init 99 initFn |> List.takeWhile (fun x -> x < 5) |> List.toArray
  with
  | ex -> printfn "List.init exception handled" ; [||]
  |> ignore

  let unfoldFn i = failwith "" ; Some (i, i+1) // VS debug skips and exception is handled normally
  try
    Seq.unfold unfoldFn 0 |> Seq.takeWhile (fun x -> x < 5) |> Seq.toArray
  with
  | ex -> printfn "Seq.unfold exception handled" ; [||]
  |> ignore

  let initInfiniteFn i = failwith "" ; i // ******** VS debug only breaks here ********
  try
    Seq.initInfinite initInfiniteFn |> Seq.takeWhile (fun x -> x < 5) |> Seq.toArray
  with
  | ex -> printfn "Seq.initInfinite exception handled" ; [||]
  |> ignore
```

**Comment by cdoool** [comment] 2019-06-05 00:14
Can confirm that @0x53A's suggestion works. As soon as I disabled the "Just my code" option, the with block started to work properly. Still, I think something fishy is going on here, because, as @penguid is pointing out, that only happens to Seq.initInfinite.

**Comment by cartermp** [comment] 2019-06-05 00:28
I can't say for sure _why_ that happens, but `initInfinite ` is a much more complicated function than the other examples. Here's where the function is evaluated: https://github.com/dotnet/fsharp/blob/ccb913d3a05863e5b1861d64994ffb97ed498855/src/fsharp/FSharp.Core/seq.fs#L240

Why that makes things messed up when JMC is off is a mystery to me. But this is evaluated with a generated `IEnumerator` calls `Current`, which invokes a callback, which invokes the function in the construction of a `Lazy` value.

**Comment by 0x53A** [comment] 2019-06-05 07:04
I'd guess that _simple_ functions are probably often inlined (either by fsc, or by the JIT), so there are no "foreign" stackframes, so JMC doesn't trigger.

> Why that makes things messed up when JMC is off [...]

This should only happen when JMC is __on__ (which it is by default)?

**Comment by cartermp** [comment] 2019-06-05 12:39
My bad; it was opposite day.

**Comment by cartermp** [comment] 2020-08-31 23:37
Closing as external, resolution is to disable JMC (which seems to be the way to fix an awful lot of problems with debugging in VS generally...)

**Closed by cartermp** 2020-08-31 23:37 UTC
Labels: Area-External, Resolution-External

**Comment by abelbraaksma** [comment] 2020-08-31 23:54
You can also disable breaking on the exception in the Exception window. Since this is not a specific exception, it's by default always selected.

You're encountering behavior that's called "first chance exceptions", which is the moment before any defined handler is executed, but the debugger hooks on that event. That's also why a debugger can catch exceptions that you can't (like SO), or that you didn't, and subsequently breaks for you, before it executes your handler. 

The problem with JMC and F# is that a lot of code ends up in non-user code, which may be the reason that it behaves differently here than it should. And then there's the release vs debug situation.
