### ISSUE TITLE
Support Hot Reload for ASP.NET Core for F#

### ISSUE THREAD

**Issue by javiercn** [dotnet/fsharp#12049] opened 2021-08-27 10:51 UTC
---
**Issue moved from dotnet/aspnetcore#35824**
- Please respond to @serefarikan.

---

_From @serefarikan on Friday, August 27, 2021 10:29:22 AM_

### Is your feature request related to a problem? Please describe.
I'm using F# to develop REST APIS with asp.net core and I have to go through the build cycle to reflect changes to my server side logic, which costs time compared to what's available to other languages and frameworks.

### Describe the solution you'd like
I'd like to have support for Hot Reload that is on its way to be introduced in Asp.NET Core 6.

### Additional context
This feature is already supported for C# but F# support is described as :
_F# is currently not supported in .NET 6 but we are planning to support in a future release based on customer feedback_
https://devblogs.microsoft.com/dotnet/introducing-net-hot-reload

This  the customer feedback.

**Comment by KevinRansom** [comment] 2021-09-22 18:49
Thanks for providing this issue, we already have an issue covering this request,
Closing as a duplicate of: https://github.com/dotnet/fsharp/issues/11636

**Closed by KevinRansom** 2021-09-22 18:49 UTC
