### ISSUE TITLE
F# FS0001: Can't implementing a generic interface define by C# where has special constraints with variance.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12707] opened 2022-02-07 19:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-FS0001:-Cant-implementing-a-generic-/1549582)._

---
[severity:It's more difficult to complete my work]
The issues were filed five days ago at [GitHub](https://github.com/dotnet/fsharp/issues/12206), but received no response. 
My friend suggested that I filed feedback here.

---
(google translate)
I'm writing a [jellyfin](https://github.com/jellyfin/jellyfin) plugin in F#. Translate the sample code from C# to F#. 
But when I implemented `MediaBrowser.Controller.Providers.IRemoteMetadataProvider<'TItemType,'TLookupInfoType>`, a compilation error FS0001 occurred. 
I simplified the code and found that I cannot solve this problem directly.

**Repro steps**
Create a C# class library and compile this:
``` csharp
public class BaseItem : IGetInfo<BaseItemInfo> { }
public class BaseItemInfo { }

public class ItemA : BaseItem, IGetInfo<ItemInfoA> { }
public class ItemInfoA : BaseItemInfo { }

public interface IGetInfo<out T> where T : BaseItemInfo { }
public interface IProvider<T, in U> 
    where T : BaseItem, IGetInfo<U> 
    where U : BaseItemInfo { }
```
**Expected behavior**

If Implementing `IProvider<ItemA, ItemInfoA>` by C#,  the following code will compile succeed.
``` csharp
public class ImplementProvider : IProvider<ItemA, ItemInfoA> { }
```

**Actual behavior**

But when using F#, a compilation error occurred:
``` fsharp
type ImplementProvider() =
    interface IProvider<ItemA, ItemInfoA>
```
```
error FS0001: This expression was expected to have type    'BaseItemInfo'    but here has type    'ItemInfoA' 
error FS0909: All implemented interfaces should be declared on the initial declaration of the type 
```
! [image] (https://user-images.githubusercontent.com/20148769/135830940-2ab97577-9d85-45dc-8e8d-96fd9a218f07.png)
**Known workarounds**

I will try to implement IProvider<ItemA, BaseItemInfo> and explicitly convert the member parameter BaseItemInfo to ItemInfoA, and then test whether it works. It will most likely fail if jellyfin has a code that specifies the use of IProvider<ItemA, ItemInfoA>.

**Related information**

1. I tried define the IProvider<T, U> by F#. A warning FS0064 and error FS0663 occurred
``` fsharp
type IProvider<'T, 'U 
    when 'T:> BaseItem and 'T :> IGetInfo<'U>
    and 'U:> BaseItemInfo> = interface end
```
```
warning FS0064: This construct causes code to be less generic than indicated by the type annotations. The type variable 'U has been constrained to be type 'BaseItemInfo'.
error FS0663: This type parameter has been used in a way that constrains it to always be 'BaseItemInfo'.
```
! [image] (https://user-images.githubusercontent.com/20148769/135834149-f1da14e4-76a2-42bf-84c4-1392d0de5b8d.png)

It may be that the F# compiler adds covariance and contravariance to the 'U at the same time, so a derived class of BaseItemInfo cannot be passed into 'U. 

2. But compilation succeeded after removing `BaseItem`. I don't know the reason.
``` csharp
public class BaseItemInfo { }

public class ItemA : IGetInfo<ItemInfoA> { }
public class ItemInfoA : BaseItemInfo { }

public interface IGetInfo<out T> where T : BaseItemInfo { }
public interface IProvider<T, in U> 
    where T : IGetInfo<U> 
    where U : BaseItemInfo { }
```

* Operating system: Windows 10 Pro 21H1 (19043.1237)
* .NET SDK version: 5.0.401
* Editing Tools: Microsoft Visual Studio Community 2019 Version 16.11.3

---
#### Feedback Bot on 10/11/2021, 01:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Tracy Wang [MSFT] on 1/21/2022, 01:42 AM: 

<p>Thank you for taking the time to log this issue! Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ? If so,could you please provide a sample solution that has this problem so that we can conduct further research?</p>
<p>We look forward to hearing from you!</p>

#### jing8956 on 2/5/2022, 09:59 PM: 

<p>The sample solution code has been pushed to github.</p>
<p><a target='_blank' href="https://github.com/jing8956/dotnet-fsharp-issues12206">https://github.com/jing8956/dotnet-fsharp-issues12206</a></p>

#### Feedback Bot on 2/7/2022, 01:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment] 2022-02-07 20:20
Duplicate of #12206.
We probably need to point user to the issue via the feedback form, keeping this one as an action item.

**Closed** 2022-03-03 22:05 UTC
Labels: Bug
