### ISSUE TITLE
Error opening binary file

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#8889] opened 2020-04-06 19:53 UTC
When using current `master` the following error is shown:
```
<PsiGenAssembly>\Program.fs:0 Error opening binary file
  'C:\Users\Eugene.Auduchinok\RiderProjects\PsiGenAssembly\PsiGenAssembly\PsiGen.exe': A positive number is required.
  Parameter name: capacity

<PsiGenAssembly>\Program.fs:0 Problem reading assembly 'C:\Users\Eugene.Auduchinok\RiderProjects\PsiGenAssembly\PsiGenAssembly\PsiGen.exe':
  The exception has been reported. This internal exception should now be caught at an error recovery point on the stack.
  Original message: Error opening binary file 'C:\Users\Eugene.Auduchinok\RiderProjects\PsiGenAssembly\PsiGenAssembly\PsiGen.exe': A positive number is required.
Parameter name: capacity)
```
<img width="1593" alt="Screenshot 2020-04-02 at 16 02 52" src="https://user-images.githubusercontent.com/3923587/78254205-3b157a80-74fe-11ea-8cb6-e2d8e6908b41.png">

Repro solution:  [PsiGenAssembly.zip](https://github.com/dotnet/fsharp/files/4440525/PsiGenAssembly.zip)

**Comment by cartermp** [comment] 2020-04-07 18:07
The fix for this is not in `master` yet. We need to pick it over: https://github.com/dotnet/fsharp/pull/8852

**Comment by cartermp** [comment] 2020-07-12 04:18
Closing as duplicate of https://github.com/dotnet/fsharp/issues/8851

This should be in master now

**Closed by cartermp** 2020-07-12 04:18 UTC
