### ISSUE TITLE
Nested Record Copy-and-Update missing case: when source is a function output

### ISSUE THREAD

**Issue by MaxWilson** [dotnet/fsharp#16513] opened 2024-01-11 15:50 UTC
Copy-and-update record expression generates spurious compiler error when the source of the copy is a function output.

**Repro steps**

    // example based on https://devblogs.microsoft.com/dotnet/announcing-fsharp-8/
    type SteeringWheel = { Type: string }
    type CarInterior = { Steering: SteeringWheel; Seats: int }
    type Car = { Interior: CarInterior; ExteriorColor: string option }

    let withTheFeature x = { x with Interior.Seats = 5 } // OK
    let repro x = { (id x) with Interior.Seats = 5 } // Error: No assignment given for field 'Steering' of type 'Chargen.Accept.CarInterior'

**Expected behavior**

Should type check without issues in both cases.

**Actual behavior**

**Compiler error:** _No assignment given for field 'Steering' of type 'Chargen.Accept.CarInterior'_

**Known workarounds**

Assign function output to local variable first.

    let workaround x = let car = id x in { car with Interior.Seats = 5 } // OK

**Related information**

VSCode, Ionide v7.16.1

**Comment by kerams** [comment] 2024-01-11 15:56
https://github.com/dotnet/fsharp/issues/16237

**Comment by vzarytovskii** [comment] 2024-01-11 19:58
> 
> EDIT: The fix didn't make into 101 (for reasons unknown to me), but your snippet indeed works on `main`.



Didn't hit the insertion bar unfortunately for servicing release.

**Comment by 0101** [comment] 2024-01-15 18:13
Duplicate of https://github.com/dotnet/fsharp/issues/16237

**Closed by 0101** 2024-01-15 18:13 UTC
Labels: Bug, Needs-Triage
