### ISSUE TITLE
FS0193: ConstraintSolver error

### ISSUE THREAD

**Issue by CharlesTaylor7** [dotnet/fsharp#5580] opened 2018-09-03 21:40 UTC
I'm getting a compiler error message of:
>error FS: internal error: Exception of type 'Microsoft.FSharp.Compiler.ConstraintSolver+LocallyAbortOperationThatFailsToResolveOverload' was thrown.

#### Reproduce steps

[Minimal Example in Sharp Lab](https://sharplab.io/#v2:DYLgZgzgNALiCWwoBMQGoA+B7ADgUwDsACAZQE8IY8BbAWACgGYz8iBhLanYPADyIC8RAK4F4MBkxZ4iABSzAyBTvACGwIgAoAlIMn0iRSqpjwAxkWo0ARngBOWgFS7NEEEWR4z8auqhEcd3lFZWo1YF0ghSUVdUEiMFVEAHdxAAsiACJMhkNjUwsralsHTWctN3ZObj5/QLlo0PDIhpDYjSFElPSsnMZ6aixkYR4iADEsLD1+wx4YIipKBa164Jiw9V0hTQBGADoABiIAWgXdRwD9Wbx5nHi1pvUdXKI55aEDvYBWF5e3uzwEBG8yEi3mtyAA==)

#### Expected behavior

Compiler should report type constraint mismatch for the function `test`.

#### Actual behavior

Compiler exception when solving the constraint. 

#### Known workarounds

Deleting either of the `*` overloads for `Polynomial` causes the compiler to display a sensible error. Replacing the float literals of `1.0` & `0.5` with decimal literals `1.0m` & `0.5m` fixes the compiler errors.

**Comment by cartermp** [comment] 2018-09-03 21:54
Further reduced repro:

```fsharp
type Complex = unit

type Polynomial () =
    static member (*) (s: decimal, p: Polynomial) : Polynomial = failwith ""
    static member (*) (s: Complex, p: Polynomial) : Polynomial = failwith ""

module Foo =
    let test t (p: Polynomial) = (1.0 - t) * p
```

Quick look shows that the error doesn't recover, so that's likely the bug.

**Comment by cartermp** [comment] 2018-09-04 15:59
Leaking of this internal error is a regression.

F# 4.0: https://repl.it/@cartermp/GlisteningBoilingQuagga

**Comment by forki** [comment] 2018-09-04 16:57
Is it solved with @tihan's latest recovery fix?

Phillip Carter <notifications@github.com> schrieb am Di., 4. Sep. 2018,
17:59:

**Comment by TIHan** [comment] 2018-09-04 18:11
@forki it is not resolved with the recovery fix. I just tested it.

**Comment by TIHan** [comment] 2018-09-04 19:43
I found the PR that caused this, and the exact changes: https://github.com/Microsoft/visualfsharp/pull/1650/files#diff-641da7c52ffc888699888ebd03559cb5R1285

I came across this by looking at all the history of changes in ConstraintSolver.fs and came across this one. It ignores unresolved overloads which doesn't seem right.

**Comment by TIHan** [comment] 2018-09-04 20:27
Hmm. This seems more complex than I thought. Apparently that PR was reverted, https://github.com/Microsoft/visualfsharp/pull/4173, but then was re-reverted, https://github.com/Microsoft/visualfsharp/pull/4347 due to this: https://github.com/Microsoft/visualfsharp/issues/4343

**Comment by TIHan** [comment] 2018-09-04 20:34
Quote from @dsyme regarding https://github.com/Microsoft/visualfsharp/pull/1650

> I'm not sure I understand. #1650 has been in for 18 months now and is now the "stable" state. I can see we need to remove the internal error showing above, but we need to do it in a way that doesn't change what does and doesn't compile.

It looks like we were aware of this internal error, but have no found a proper fix to resolve it. Reverting the PR causes other issues, so we have to figure out exactly what is going on to stop the internal error.

**Comment by jindraivanek** [comment] 2018-10-23 17:50
Found another repro for this internal error.

FAKE5 script:
```
#r "paket: nuget Giraffe //"
open System.Threading.Tasks
open FSharp.Control.Tasks.ContextInsensitive

let foo t = task {
    let! t = t
    return t
    }
```

`Error FS0071: Type constraint mismatch when applying the default type 'Task<'a>' for a type inference variable. internal error: Exception of type 'Microsoft.FSharp.Compiler.ConstraintSolver+LocallyAbortOperationThatFailsToResolveOverload' was thrown. Consider adding further type constraints`

Annotating `t` with `t: Task<'a>` fix error.

**Comment by dsyme** [comment] 2018-10-25 15:35
Would be good to have a repro that wasn't a FAKE 5 script i.e. a normal F# project ZIP with exact version of Giraffe

thanks

**Comment by cartermp** [comment] 2020-01-24 08:35
@dsyme this is resolved with #8294?

**Closed** 2020-01-24 08:36 UTC
Labels: Area-Compiler, bug, regression

**Comment by cartermp** [comment] 2020-02-12 17:53
Just confirming that this emits a type constraint mismatch error now instead of the internal error 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/6309070/74362434-8a042680-4d7d-11ea-9a6a-20dbce1b20cb.png">
