### ISSUE TITLE
Compiler tries to compile itself in 2.2.20* NetCore SDK

### ISSUE THREAD

**Issue by Szer** [dotnet/fsharp#6760] opened 2019-05-17 09:12 UTC
For NetCore SDK 2.2.20*:
In case there is explicit `DotnetFscCompilerPath` property `fsc.exe` receives itself as file to compile and fails with error:
`  FSC: error FS0226: The file extension of 'C:\Program Files\dotnet\sdk\2.2.204\FSharp\fsc.exe' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli.`

#### Repro steps

Provide the steps required to reproduce the problem

1. Install NetCore SDK 2.2.20*
2. Create `.fsproj`:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <DotnetFscCompilerPath>C:/Program Files/dotnet/sdk/2.2.204/FSharp/fsc.exe</DotnetFscCompilerPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
```
and `Program.fs`:
```
module Main
[<EntryPoint>]
let main _ = 0
```
2. dotnet build

[fsc_path.zip](https://github.com/dotnet/fsharp/files/3190753/fsc_path.zip)

#### Expected behavior

It should compile successfully with compiler executable which was explicitly set

#### Actual behavior

Fails with error:
`  FSC: error FS0226: The file extension of 'C:\Program Files\dotnet\sdk\2.2.204\FSharp\fsc.exe' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli.`

#### Known workarounds

Rollback to NetCore SDK 2.2.10*

#### Related information 

Provide any related information 

* Operating system: Win 10
* .NET Runtime: 2.2.204

**Comment by ysangkok** [comment] 2019-10-18 19:12
Is this a duplicate of #6326?

**Comment by cartermp** [comment] 2019-10-18 19:54
Yes, @ysangkok thanks, this is a dupe of that.

**Comment by cartermp** [comment] 2019-10-18 19:54
Relevant comment: https://github.com/dotnet/fsharp/issues/6326#issuecomment-478388703

**Closed by cartermp** 2019-10-18 19:54 UTC
