### ISSUE TITLE
Overload resolution fails with C#-style extension methods and properties

### ISSUE THREAD

**Issue by laenas** [dotnet/fsharp#11580] opened 2021-05-18 11:47 UTC
When a type is extended with C#-style extension methods - if those extension methods share a name with a property on the type - we get compiler errors when attempting to use those extension methods.  This behavior is used in some C# libraries to allow for fluent assignment - for example in [Spectre.Console](https://github.com/spectreconsole/spectre.console) - where the UI widgets are extended with fluent methods for assigning to properties of the same name.  Consuming those libraries, as designed, is presently impossible from F# due to this bug.

**Repro steps**

```fs
open System.Runtime.CompilerServices

type Foo() = 
    member val X = () with get,set

[<Extension>]
type FooExt =
    [<Extension>]
    static member X (f: Foo) = ()

let f = Foo()
f.X()
```

**Expected behavior**

Typechecking succeeds, with awareness that while `()` is not a valid application to the intrinsic property `X`, it does suffice for in-scope extension method `X` 

**Actual behavior**

Compiler error - we find the property `X` and since its type cannot have an argument applied, a compiler error is thrown.

**Known workarounds**

The extension method can be used as a normal method: `FooExt.X(f)` in the above example - but this can create non-idiomatic code.

**Related information**

I've done some digging and investigation into this, but am at a point where I'm not sure how I would best proceed with actual resolution:

To some degree, the problem may start in [TcLookupThen](https://github.com/dotnet/fsharp/blob/3cf307601141ec99d0e15a59462bec5e9d069da8/src/fsharp/CheckExpressions.fs#L8189).  At this point, we have the knowledge of the type being operated on via `objExprTy` but we also know what immediately follows this via `delayed`.  However we don't carry that context into `ResolveExprDotLongIdentAndComputeRange`.
That function ends up eventually in [ResolveLongIdentInTypePrim](https://github.com/dotnet/fsharp/blob/3cf307601141ec99d0e15a59462bec5e9d069da8/src/fsharp/NameResolution.fs#L2452) - where we end up crawling the type hierarchy looking for the matching named member.  While this function does attempt to handle overloads, it does so purely alongside property/method lines - if the first thing we find by name is a Property, then we take that and then check the type for property extensions, for example.  So the Property percolates back up, we eventually try to apply to it, and thus the error occurs.

It's unclear - at least to me - what the best strategy for fixing this ends up being.  For example:  While `TryFindIntrinsicNamedItemOfType` is minimally called (just in this chain, and once in `ConstraintSolver`) - modifying it to return *all* similarly named `HierarchyItem`s - there would still be the issue that `ResolveLongIdentInTypePrim` is called from a handful of places, and in most cases - is explicitly expected to only return a single Result.

**Comment by cartermp** [comment] 2021-06-18 15:31
I think this might actually be by design, as per the spec on overload resolution. F# prefers properties over methods, whereas C# prefers methods over properties. Although in this case it's sorta confusing, since it's clear that one of the choices is unambiguous. @dsyme any thoughts?

**Comment by laenas** [comment] 2021-06-18 15:39
> I think this might actually be by design, as per the spec on overload resolution.

I checked this before opening the ticket, and probably should have cited it:

§8.13.1 states (with regards to Property Members)
> However, methods that have the same name can be overloaded when their signatures are different.

(Which is in comparison to an example immediately above it about trying to overload Property members (for example, one static, one instance)

**Comment by dsyme** [comment] 2021-06-21 00:16
> I think this might actually be by design, as per the spec on overload resolution. F# prefers properties over methods, whereas C# prefers methods over properties. Although in this case it's sorta confusing, since it's clear that one of the choices is unambiguous. @dsyme any thoughts?

It unfortunately by design, since anything intrinsic takes priority over anything extrinsic.

I think we could in theory take a change to align to a C#-like rule where, for an actual application of a method to arguments (not a first class use of the method) the extrinsic method would be preferred to an intrinsic property.  (That could only be a breaking change if the intrinsic property was actually of F# function type, which would never be the case for C# members, nor really for F# code either, at least not in combination with an unusable extrinsic method)

**Comment by dsyme** [comment] 2021-06-21 00:17
@laenas Please add a pre-approved language-design suggestion on this.

**Comment by KevinRansom** [comment] 2021-07-07 18:44
design suggestion added, closing.

**Closed by KevinRansom** 2021-07-07 18:44 UTC
