### ISSUE TITLE
Parse error on generic abstract member definition

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#6650] opened 2019-04-29 20:39 UTC
Removing the space before the colon in the following code results in a parse error with no error recovery.
```fsharp
[<AbstractClass>]
type T() =
    abstract Foo<'T> : 'T -> int
```
![abstractGenericMethodSpace](https://user-images.githubusercontent.com/3923587/56925405-f60beb80-6ad7-11e9-8c73-a989ef43a27c.gif)

**Comment by auduchinok** [comment] 2020-08-12 16:13
The same happens in signature files:
```fsharp
```

**Comment by abelbraaksma** [comment] 2020-08-12 16:19
As the message suggests, it's considered an operator. The parser could do some look ahead to permit this kind of construct. I believe there's an RFC for a similar issue with `<^t>`, which also fails.

**Comment by abelbraaksma** [comment] 2020-08-12 16:23
I think it would be good to add this to the rfc here, though it's not exactly the same, it falls in the same area of look ahead for operators: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1083-srtp-type-no-whitespace.md.

**Comment by cartermp** [comment] 2020-08-12 18:17
Ugh, of course it's not just the SRTP issue here too :(

I updated the design: https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1083-srtp-type-no-whitespace.md

Tiny update. I didn't rename the file since that would break links though. We'll keep this issue up though.

**Comment by dsyme** [comment] 2022-03-31 07:54
This is a duplicate of https://github.com/dotnet/fsharp/issues/4607

**Closed by dsyme** 2022-03-31 07:54 UTC
Labels: Feature Request, Area-Compiler-Syntax
