### ISSUE TITLE
Scrolling with trackpad in an F# file causes crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8819] opened 2020-03-27 20:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/942324/scrolling-with-trackpad-in-an-f-file-causes-crash.html)._

---
This is a follow up for the [bug](https://developercommunity.visualstudio.com/content/problem/896570/crash-when-scrolling-f-file-with-touchpad.html) with debug dumps

---
#### Visual Studio Feedback System on 3/9/2020, 00:56 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/27/2020, 11:49 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment] 2020-03-28 00:17
This is most likely a dupe of https://github.com/dotnet/fsharp/issues/6056

I'll close it out as such

**Closed by cartermp** 2020-03-28 00:17 UTC
Labels: Resolution-Duplicate
