### ISSUE TITLE
Missing syntax diagnostics in VS

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#15972] opened 2023-09-13 13:34 UTC
**Repro steps**

Create new Console App project with the following code:
```fsharp
type MyType() =

    member this.Foo(): MyType = {
        Field = 4
    }

    one two three
```
**Expected behavior**

We see errors in Error List in VS when we open the file. 

**Actual behavior**

No errors shown when we open the file. But the errors do appear if the file is closed and project is built.

https://github.com/dotnet/fsharp/assets/217092/a2516453-d8c7-40c8-803b-7cb92a27c01b

**Related information**

Appeared somewhere between 17.8 preview 1 and preview 3

**Comment by 0101** [comment] 2023-09-13 14:28
A current F# extension in VS 17.8 preview 1 works correctly, so it looks like some change in VS or Roslyn caused this issue. @CyrusNajmabadi can you have a look please?

It seems like results from [`IFSharpDocumentDiagnosticAnalyzer.AnalyzeSyntaxAsync`](https://sourceroslyn.io/#Microsoft.CodeAnalysis.ExternalAccess.FSharp/Diagnostics/IFSharpDocumentDiagnosticAnalyzer.cs,4616a6f10cbf75ed,references) are somehow getting lost. The semantic diagnostics work fine.

**Comment by 0101** [comment] 2023-09-19 15:01
@mavasani Did you get a chance to have a look at this?

**Comment by mavasani** [comment] 2023-09-19 15:04
@0101 thanks for the reminder. Let me look tomorrow.

**Comment by mavasani** [comment] 2023-09-20 06:30
@0101 I am unable to repro this on the latest dogfood build

![image](https://github.com/dotnet/fsharp/assets/10605811/4348f2d1-b11f-49d2-bcb2-5e083e426eaf)

**Comment by 0101** [comment] 2023-09-20 09:28
@mavasani that is most likely the workaround https://github.com/dotnet/fsharp/pull/15982

When I disable the workaround I can still reproduce the issue in VS Main `Version 17.8.0 Preview 3.0 [34119.376.main]`

With the workaround, the diagnostics that should be coming from [IFSharpDocumentDiagnosticAnalyzer.AnalyzeSyntaxAsync](https://sourceroslyn.io/#Microsoft.CodeAnalysis.ExternalAccess.FSharp/Diagnostics/IFSharpDocumentDiagnosticAnalyzer.cs,4616a6f10cbf75ed,references)
are also reported from [AnalyzeSemanticsAsync](https://sourceroslyn.io/Microsoft.CodeAnalysis.ExternalAccess.FSharp/R/bbe51a308ab71f17.html).

When it's fixed the syntax diagnostics will mostly likely be doubled in the error list. 

I can make an F# VSIX with the workaround removed if it would help you.

**Comment by mavasani** [comment] 2023-09-20 09:41
Thanks @0101 - I was just skimming over your analyzer code and noticed you have below: https://github.com/dotnet/roslyn/blob/1421a4a8e7c48f4d7fda5e053ab95ffb9f4f35f5/src/Tools/ExternalAccess/FSharp/Internal/Diagnostics/FSharpDocumentDiagnosticAnalyzer.cs#L95-L98

```csharp
        public DiagnosticAnalyzerCategory GetAnalyzerCategory()
        {
            return DiagnosticAnalyzerCategory.SemanticDocumentAnalysis;
        }
```

The above category indicates the analyzer only supports semantic diagnostics, and the fact that it worked before might indicate some underlying bug that got fixed. You can read up the doc comments on each of the flags here: https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Diagnostics/DiagnosticAnalyzerCategory.cs

Are you able to locally make the below Roslyn change + remove the F# workaround and see if things work for you as expected with both these VSIXes installed? If not, I can investigate further.

```csharp
        public DiagnosticAnalyzerCategory GetAnalyzerCategory()
        {
            return DiagnosticAnalyzerCategory.SyntaxTreeWithoutSemanticsAnalysis | DiagnosticAnalyzerCategory.SemanticDocumentAnalysis;
        }
```

**Comment by mavasani** [comment] 2023-09-20 10:36
> I can try. But when debugging it, I saw that [AnalyzeSyntaxAsync](https://sourceroslyn.io/#Microsoft.CodeAnalysis.ExternalAccess.FSharp/Diagnostics/IFSharpDocumentDiagnosticAnalyzer.cs,4616a6f10cbf75ed,references) was still being called, just the results that we provided weren't shown.
> 
> If it was looking at capabilities then I'd expect it not to be called at all.

Indeed, that seems like another bug, filed #16008 to track fixing that on Roslyn side.

**Comment by 0101** [comment] 2023-09-20 10:51
So I made the change in `GetAnalyzerCategory` and it didn't help. I installed:
```
Roslyn.VisualStudio.Setup.Dependencies.vsix
Roslyn.VisualStudio.Setup.vsix
RoslynDeployment.vsix
```

**Comment by mavasani** [comment] 2023-09-20 10:59
> So I made the change in `GetAnalyzerCategory` and it didn't help. I installed:
> 
> ```
> Roslyn.VisualStudio.Setup.Dependencies.vsix
> Roslyn.VisualStudio.Setup.vsix
> RoslynDeployment.vsix
> ```

Alright, let me investigate

**Comment by mavasani** [comment] 2023-09-20 11:58
@0101 I am still unable to reproduce this issue on `Version 17.8.0 Preview 3.0 [34118.359.main]` build. I have tried the following:

1. Tried the scenario without any local changes/patch and things work fine
2. Tried the scenario by commenting out the `AnalyzeSemanticsAsync` call below, which is the single place where this callback is made, and verified things work fine.
3. Once I revert the change in 2 above, I see that no syntax errors are returned by ``AnalyzeSemanticsAsync` call, so most likely I don't have the F# workaround you mentioned above.

I tried the above scenarios with both the below entire solution analysis checkbox being checked and unchecked and see the same behavior:
![image](https://github.com/dotnet/fsharp/assets/10605811/710f1dd2-32da-4582-9d31-291fe8e309ef)

@0101 I am not sure how to proceed here, as everything seems to work fine for me on the above build without the F# workaround

**Comment by 0101** [comment] 2023-09-20 12:20
Ok I'll try to get that exact version and see what I see. Though I doubt it was fixed and then broken again by `34119.376.main`. If it still doesn't work for me than it means it's probably affected by some settings?

**Comment by 0101** [comment] 2023-09-20 12:50
Hmm, when I installed INT preview I got `34119.384.main`. Which includes the workaround and reproduces the issue (with [VSIX without the workaround](https://microsofteur-my.sharepoint.com/:u:/g/personal/petrpokorny_microsoft_com/EYvqOyOIpPxOg7ADJg9EHM4BZbU1eltPjZWlbyyd3aAkFw?e=MqdB2L))

Can you maybe try to update? But still there is probably something external that made it work for you but not for us.

**Comment by mavasani** [comment] 2023-09-21 05:37
@0101 I upgraded to the latest build, no local changes or VSIXes and still can't reproduce the issue. I see duplicate syntax errors:

![image](https://github.com/dotnet/fsharp/assets/10605811/ad095d34-3800-4eeb-9caa-704b9b664e1d)

> still there is probably something external that made it work for you but not for us.

I believe this is the case. I also tried toggling the entire solution analysis checkbox, but that made no difference.

**Comment by mavasani** [comment] 2023-09-22 06:30
Fixed with https://github.com/dotnet/roslyn/pull/70068

**Comment by T-Gro** [comment] 2023-11-02 10:46
Fixed with the roslyn fix above.

**Closed by T-Gro** 2023-11-02 10:46 UTC
Labels: Bug, Impact-High, Area-LangService-Diagnostics, Tracking-External

**Comment by T-Gro** [comment] 2023-11-03 10:52
IMO yes.

**Comment by vzarytovskii** [comment] 2023-11-03 12:07
> Should we revert https://github.com/dotnet/fsharp/pull/15982 now?

Probably. No rush though since p1 is m2 already.

**Comment by brianrourkeboll** [comment] 2024-09-09 16:34
> Should we revert #15982 now?

Does this still need to happen?
