### ISSUE TITLE
In VS 16.9 type checking between files doesn't work until you edit the "later" file

### ISSUE THREAD

**Issue by theprash** [dotnet/fsharp#11434] opened 2021-04-15 11:35 UTC
When you edit a file, the types aren't carried through to later files until you actively edit the later file. This means that the error list isn't updated, and the later file shows the wrong red squiggles and type information.

The exception is when the later file is the very next file in the project. In that case, the errors and types are updated automatically as expected.

This means that when making a change in a project, you need to check the full build output to see which other files are affected, open those files and make any edit, and only then can you see what needs fixing.

**Repro steps**

Provide the steps required to reproduce the problem:

1. Make a three file project where file 3 uses code from file 1.
2. Comment all the code in file 1.

Example project [attached](https://github.com/dotnet/fsharp/files/6317521/vs-fsharp-bug.zip)

**Expected behavior**

New errors should be shown in the error list. The errors should be underlined when viewing file 3.

**Actual behavior**

Nothing.

**Known workarounds**

Edit file 3.

**Related information**

Provide any related information (optional):

* Operating system: Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono): .NET 5
* Visual Studio 16.9.4

**Comment by auduchinok** [comment] 2021-04-19 09:28
This is a duplicate of https://github.com/dotnet/fsharp/issues/11291.

**Closed** 2021-04-19 14:56 UTC
Labels: Resolution-Duplicate
