### ISSUE TITLE
Precision loss in %f formatting 

### ISSUE THREAD

**Issue by goswinr** [dotnet/fsharp#17386] opened 2024-07-05 18:36 UTC
`%.16f` and `.ToString("G17")` both format a float to 16 decimal places.

But `%.16f` seems to lose precision on the last two digits, making round tripping impossible.

Is that intended behavior ?

```fsharp
open System

let f = sprintf "%.16f" (Math.PI) // -> 3.1415926535897900 // last two digits lost
let g = Math.PI.ToString("G17")   // -> 3.1415926535897931

printfn "f: %s" f
printfn "G: %s" g

printfn $"f = PI: {Double.Parse(f) = Math.PI}" // round trip failure
printfn $"G = PI: {Double.Parse(g) = Math.PI}" // round trip success
```

Edit: only affects net48

**Comment by Martin521** [comment] 2024-07-06 07:25
I cannot reproduce this. For me, both f and g have full precision.
(For both .net 6 and 8)

**Comment by goswinr** [comment] 2024-07-06 08:40
@Martin521 indeed, this only applies to net48 Framework

**Comment by Martin521** [comment] 2024-07-06 12:39
`sprintf` uses internally (for `double`) `double.ToString(fmt, CultureInfo.InvariantCulture)`.
The [documentation ](https://learn.microsoft.com/en-us/dotnet/api/system.double.tostring?view=netframework-4.8) of the latter has at the end of the page a paragraph "Notes to Callers", which may explain the issue.
In any case, this seems to be an issue of the framework, not of F#.

**Comment by vzarytovskii** [comment] 2024-07-06 15:50
Thanks for taking time and looking into it, Martin. We indeed shouldn't be doing anything special, so that's probably a bcl issue.

**Comment by goswinr** [comment] 2024-07-08 11:55
Thanks for the link @Martin521, I did not know what `%.16f` uses internally. Indeed, `.ToString("F16")` also looses precision.  It would be nice to get round-trip-able float formatting in F# with something like a `%r` specifier...  But I guess this issue can be closed.

**Comment by T-Gro** [comment] 2024-07-08 13:12
Closing as BCL issue in desktop framework.

**Closed by T-Gro** 2024-07-08 13:12 UTC
Labels: Bug, Needs-Triage
