### ISSUE TITLE
Pattern `DUCase _` matches `DUCase`

### ISSUE THREAD

**Issue by TysonMN** [dotnet/fsharp#10204] opened 2020-09-30 18:57 UTC
The following code compiles, but it expected that it would not compile.

```F#
type MyDU = DUCase
let asdf = function
  | DUCase _ -> ()
```

I thought the last line would have to omit the discard pattern, which would look like `| DUCase -> ()`.

This behavior is the opposite of bug #9520.

I am using
- version 16.7.5 of Visual Studio Enterprise 2019 and
- version 3.1.402 (x64) of the .NET Core SDK.

**Comment by cartermp** [comment] 2020-09-30 19:37
This appears to have been the case for at least F# 4.5, so I don't think it's a bug

**Comment by TysonMN** [comment] 2020-09-30 19:47
Is this possibility mentioned in the [Wildcard Pattern section of the Pattern Matching documentation](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#wildcard-pattern)?  I don't get the impression that it is mentioned there.

**Comment by abelbraaksma** [comment] 2020-09-30 20:21
I raised this back in 2016, @dsyme considered it by design. See https://github.com/dotnet/fsharp/issues/1592

**Comment by cartermp** [comment] 2020-09-30 20:28
Thanks for the clarification @abelbraaksma - I will close as a duplicate of https://github.com/dotnet/fsharp/issues/10204

**Closed by cartermp** 2020-09-30 20:28 UTC
Labels: Resolution-Duplicate

**Comment by abelbraaksma** [comment] 2020-09-30 21:39
I think you meant duplicate of #1592 ;).

**Comment by cartermp** [comment] 2020-09-30 22:17
Indeed! The 'ole copy paste 'a  'roo

**Comment by TysonMN** [comment] 2020-10-01 01:38
Thanks everyone for all the comments and the pointer to the previous issue.  I created https://github.com/dotnet/docs/issues/20858 to suggest that the documentation be changed to mention this feature.

**Comment by abelbraaksma** [comment] 2022-10-09 01:44
May be fixed by: https://github.com/dotnet/fsharp/pull/14055
