### ISSUE TITLE
Members using overloaded operators defined over member's containing type require unsatisfiable constraint

### ISSUE THREAD

**Issue by drvink** [dotnet/fsharp#968] opened 2016-02-15 14:57 UTC
``` fsharp
type hoop< ^a when ^a : (static member (+) : ^a * ^a -> ^a) > = {
  Group1 : ^a;
  Group2 : ^a
} with
  static member inline (+) (x, y) = x.Group1 + y.Group2
end

let z = { Group1 = 1; Group2 = 2 } + { Group1 = 2; Group2 = 3 } // ok

type hoop with
  member inline this.Sum = this.Group1 + this.Group2 // A type parameter is missing a constraint 'when ( ^a or  ^?104290) : (static member ( + ) :  ^a *  ^?104290 ->  ^?104291)'
end
```

**Comment by kbattocchi** [comment] 2016-02-19 22:47
Marking `Sum` as `inline` fixes this problem, although it makes it clear that your definition of `(+)` is more general than you probably intended.  I'm not sure if the inference failure is really a bug or just an extremely hard to understand error message.

**Comment by drvink** [comment] 2016-02-22 06:06
Er, apologies, I pasted the wrong version of the code; it was supposed to have `inline`. The issue is not that it doesn't work without `inline`--that's fine, and not what I meant to point out--but rather the spurious warning that you get from the definition of that member.

**Comment by dsyme** [comment] 2021-11-05 23:45
Treating this as a duplicate of https://github.com/dotnet/fsharp/issues/385

**Closed by dsyme** 2021-11-05 23:45 UTC
Labels: Bug, Area-Compiler, Impact-Low
