### ISSUE TITLE
Bug with type matching of `int8` and `byte`

### ISSUE THREAD

**Issue by gbaydin** [dotnet/fsharp#10202] opened 2020-09-30 18:11 UTC
Hello, this is a bug report uncovered during [DiffSharp](https://github.com/DiffSharp/DiffSharp) development with @dsyme. I faced an issue with creating tensors from byte arrays, where the bytes got erroneously treated as int8, giving incorrect results.

As a reminder:
- byte (System.Byte) encodes values [0, 255]. In F# they look like `1uy`. 
- int8 (System.SByte) encodes values [-128, 127]. In F# they look like `1y`.

**Repro steps**

I isolated the problem to the minimal example represented in the following code:

```fsharp
let a = 158uy
match box a with
| :? int8 as aa -> printfn "int8 %A" aa
| :? byte as aa -> printfn "byte %A" aa
| _ -> printfn "other"
```
Prints: `byte 158uy`. This is correct.

```fsharp
let a = [|158uy; 159uy; 165uy|]
match box a with
| :? (int8[]) as aa -> printfn "int8 %A" aa
| :? (byte[]) as aa -> printfn "byte %A" aa
| _ -> printfn "other"
```
Prints: `int8 [|158uy; 159uy; 165uy|]`. This is not correct.

**Expected behavior**

In the incorrect case, the expected behavior is to match the second case and print `byte [|158uy; 159uy; 165uy|]`.

**Actual behavior**

The incorrect case prints: `int8 [|158uy; 159uy; 165uy|]`.

**Known workarounds**

If one switches the order of `int8[]`, `byte[]`, the `byte[]` case indeed gets matched. But this is not really a solution.
```fsharp
let a = 158uy
match box a with
| :? byte as aa -> printfn "byte %A" aa
| :? int8 as aa -> printfn "int8 %A" aa
| _ -> printfn "other"

let a = [|158uy; 159uy; 165uy|]
match box a with
| :? (byte[]) as aa -> printfn "byte %A" aa
| :? (int8[]) as aa -> printfn "int8 %A" aa
| _ -> printfn "other"
```
Prints:
```
byte 158uy
byte [|158uy; 159uy; 165uy|]
```

**Related information**
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by abelbraaksma** [comment] 2020-09-30 22:35
This issue is wider than just `byte[]` vs `sbyte[]`. It appears to go wrong for `box/unbox` of any array with signed vs unsigned. You can even get an unboxed type `int[]` that contains `uint` internally:

```f#
> let x = box [|1u|];;
val x : obj = [|1u|]

> match x with :? (uint[]) -> true | _ -> false;;
val it : bool = true

> match x with :? (int[]) -> true | _ -> false;;
val it : bool = true

> unbox<uint[]> x;;
val it : uint [] = [|1u|]

> unbox<int[]> x;;
val it : int [] = [|1u|]
```

You tested this on Ubuntu. I can confirm the issue exists in .NET Framework 4.7.x as well. I can also confirm that the issue has been around since at least F# 2.0:

```f#
Microsoft (R) F# 2.0 Interactive build 4.0.40219.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> Binding session to 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.1.0\FSharp.Core.dll'...
1;;
val it : int = 1
> let x = box [|1u|];;
val x : obj = [|1u|]

> match x with :? (uint32[]) -> true | _ -> false;;
val it : bool = true

> match x with :? (int[]) -> true | _ -> false;;
val it : bool = true

> unbox<uint32[]> x;;
val it : uint32 [] = [|1u|]

> unbox<int[]> x;;
val it : int [] = [|1u|]
```

Note that `GetType()` will show the proper type of the boxed value.

**Comment by abelbraaksma** [comment] 2020-09-30 22:51
Hmm, on second thought, this maybe a CLR peculiarity, the same behavior exists in C#:

```c#
> using System;
> var x = new int[] { 42 } as object;

> Console.WriteLine(x.GetType().ToString());
System.Int32[]

> Console.WriteLine(x as int[]);
System.Int32[]

> Console.WriteLine(x as uint[]);
System.Int32[]

> Console.WriteLine(x is int[]);
True

> Console.WriteLine(x is uint[]);
True
```

**Comment by gbaydin** [comment] 2020-10-01 03:25
@abelbraaksma thank you for your observations.

Guided by your investigation, I found the following issues as well:

https://github.com/dotnet/roslyn/issues/20874
https://github.com/dotnet/runtime/issues/8548

So this seems like a dotnet runtime issue and it is by some old design choice and it's unlikely to get fixed.

Quoting from those issues: "I recommend avoiding the use of primitive array types in pattern-matching.", "for a strict type check 'inst.GetType() == typeof(type)' can be used."

I think this behavior is especially bad for F# usage where we heavily rely on pattern matching. It's very unintuitive and bug-prone if we can't rely on types. I'm wondering whether this can still be addressed by F# somehow, as a minimum giving a warning when this type of user code is encountered.

The code that was affected in DiffSharp was [this](https://github.com/DiffSharp/DiffSharp/blob/e6dd80f68b19b3e6ad830192a009af5e25decccc/src/DiffSharp.Core/Util.fs#L280)

Perhaps a solution is to match the type of a single value in each array as, if I understand correctly, this issue is only affecting arrays.

**Comment by abelbraaksma** [comment] 2020-10-01 11:17
@gbaydin, apart from the (rather expensive) `.GetType()`, there's the following workaround which works as long as the array is non-empty (so check for that first):

```f#
> let isSigned (x: obj) =
    match x with
    | :? System.Array as a -> 
        match a.GetValue(0) with
        | :? sbyte | :? int16 | :? int | :? int64 -> true
        | _ -> false
    | _ -> false;;
val isSigned : x:obj -> bool

> isSigned (box [|42uy|]);;
val it : bool = false

> isSigned (box [|42u|]);;
val it : bool = false

> isSigned (box [|42|]);;
val it : bool = true

> isSigned (box [|42y|]);;
val it : bool = true
```

In other words, if your route your matching through `System.Array` you can get the first item of the typed array and investigate that. You could do something similar in your code for DiffSharp. Of empty arrays you'll still need to go through the `GetType()` route afaik.

An alternative, if your domain model allows it, is to wrap the whole array in a DU at creation time, so that type information is preserved. Of course, that won't always be possible.

**Comment by abelbraaksma** [comment] 2020-10-01 11:38
Btw, OT, but related to your code, `tryFlatArrayAndShape` is marked `rec`, but isn't recursive. Also, the code in `dataOfValues` calls `tryFlatArrayAndShape` potentially 8 times. 

You can code this up using `System.Array.Rank` and `System.Array.GetValue`-overloads to find the type of the first item before you flatten the array. Since each array in F# inherits from `System.Array` you can code the array-path specifically. Yeah, it gets a bit messy, but it's better than doing a `GetType()` all the time (I think, if perf is important, you'll have to measure).

**Comment by dsyme** [comment] 2020-10-01 14:27
Yes, the business with array casting is a quirk of .NET unfortunately.  It's called out in the F# spec.

**Comment by dsyme** [comment] 2020-10-01 15:04
I'll close this because it is by-design.  We won't fix this for F# specifically, it's just an unfortunate quirk.

> `val it : int [] = [|1u|]     // how is this even possible??? This should raise.`

The best way to think of this is that arrays of signed/unsigned integer values are interconvertible and can be interpreted "either way", but their runtime type (e.g. `System.UInt32[]`) gives them a preferred interpretation.

When printing them the preferred interpretation is used.

**Closed by dsyme** 2020-10-01 15:04 UTC
