### ISSUE TITLE
[From VSTS] Display None as "None" instead of "null" in Data Tips

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#3716] opened 2017-10-09 19:52 UTC
From here: https://developercommunity.visualstudio.com/content/problem/44030/f-debugging-option-types-returns-null.html

The behavior described is also the same in VS2015 Update 3:

![null-vs2015](https://user-images.githubusercontent.com/6309070/31355797-866c58d8-acf0-11e7-859f-d3c77455cb80.PNG)

So this is not a regression.

**Comment by dsyme** [comment] 2017-10-09 22:05
We could only do this with our own debugger engine which was aware of F# types

**Comment by cartermp** [comment] 2017-10-09 22:08
@gregg-miskelly just to check - is this another case of "F# needs its own EE"?

**Comment by gregg-miskelly** [comment] 2017-10-09 22:10
Correct

**Comment by cartermp** [comment] 2017-10-09 22:27
link #2544

**Comment by matthid** [comment] 2017-10-09 22:39
And https://stackoverflow.com/questions/41337310/f-method-returns-null-instead-of-option

**Comment by samuela** [comment] 2018-10-07 06:53
I just wasted an hour due to this issue.

```
> printfn "%A" None;;
<null>
val it : unit = ()

> printfn "%A" null;;
<null>
val it : unit = ()

>
```

Supremely confusing when you're looking at server logs for things that you think should be Options.

**Comment by cartermp** [comment] 2018-10-07 16:30
@samuela What you describe is not this issue. This issue is about the representation of `None` in debugging tools.

What you're observing is that`None` emits as `null` in IL, which explains why you'd see that as the value in logs. As a remediation, I'd recommend sending all logs through a function that does a check for options, emitting something else for the `None` case. You can check like this:

```fsharp
let inline isOptionType (t:System.Type) =
    t.GetTypeInfo().IsGenericType && t.GetGenericTypeDefinition() = typedefof<option<_>>
```

**Comment by dsyme** [comment] 2021-08-24 00:45
Duplicate of #10168

**Closed by dsyme** 2021-08-24 00:45 UTC
Labels: Area-Debug, Feature Improvement
