### ISSUE TITLE
Unused variable warnings wrong in computation expression

### ISSUE THREAD

**Issue by Smaug123** [dotnet/fsharp#5971] opened 2018-11-30 18:52 UTC
The compiler does a very bad job of identifying unused variables in a computation expression with custom keywords.

#### Repro steps
File `Builder.fs`:
```fsharp
namespace Maybe

type 'a Maybe =
    | Yes of 'a

[<Sealed>]
type MaybeBuilder () =
    member __.Return<'a> (_ : 'a) : 'a Maybe =
        failwith ""

    member __.Bind
        (
            (_ : 'a Maybe),
            (_ : 'a -> 'b Maybe)
        )
        : 'b Maybe
        =
        failwith ""

    [<CustomOperation("filter", MaintainsVariableSpaceUsingBind = true)>]
    member __.Filter
        (
            (_ : 'a Maybe),
            [<ProjectionParameter>] _filter : ('a -> bool)
        )
        : 'a Maybe
        =
        failwith ""

[<AutoOpen>]
module Builders =
    let builder = MaybeBuilder ()

module AnotherThing =
    let filtered = builder {
        let! newInt = Yes 0 // unused?!
        filter (newInt < 3)
        return 3
    }

    let filtered2 = builder {
        let! newInt = Yes 0 // used, hooray
        filter (newInt < 3)
        return newInt
    }

    let filtered3 = builder {
        let! newInt = Yes 0 // unused?!
        let! newInt2 = Yes 0 // unused?!
        filter (newInt2 < 3)
        return newInt
    }

    let filtered3' = builder {
        let! newInt2 = Yes 0 // unused?!
        let! newInt = Yes 0 // unused?!
        filter (newInt2 < 3)
        return newInt
    }

    let filtered4 = builder {
        let! newInt = Yes 0 // unused, hooray
        let! newInt2 = Yes 0 // used, hooray
        filter (newInt2 < 3)
        return newInt2
    }
```
Fsproj file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <OtherFlags>--warnon:1182 --warnaserror-:1182</OtherFlags>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Builder.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="4.5.4" />
  </ItemGroup>
</Project>
```

The compiler incorrectly believes that many of those variables are unused, and emits warnings.

#### Expected behavior

In the above examples, every variable is used (except the ones which I've commented with "unused, hooray").

#### Actual behavior

Many of the variables are marked as unused, and a build warning is raised.

#### Known workarounds

None other than to disable unused-variable warnings.

#### Related information 

* Operating system: observed on Windows in Visual Studio 2017 (15.7.1) and in Rider 2018.2.
* .NET Runtime, CoreCLR or Mono Version: observed on netcoreapp2.0, netstandard2.0, and net461.
* Editing Tools (e.g. Visual Studio Version): VS 2017 (15.7.1) and Rider 2018.2. It's a compiler warning, though, which should be independent of IDE.
* Indications of severity: pretty minor, but this bug is the sole reason my team has not enabled unused-variable warnings.

**Comment by cartermp** [comment] 2018-12-01 00:14
Interestingly, the VS tooling works correctly:
![image](https://user-images.githubusercontent.com/6309070/49321210-ed78a000-f4ba-11e8-8cb5-a095d50b7058.png)

So this is a compiler issue for sure.

**Comment by dsyme** [comment] 2020-08-26 14:53
This is a duplicate of https://github.com/dotnet/fsharp/issues/422

**Closed by dsyme** 2020-08-26 14:53 UTC
Labels: Area-Compiler, bug
