### ISSUE TITLE
F#6 compatibility with Roslyn Source Generators

### ISSUE THREAD

**Issue by nbevans** [dotnet/fsharp#10487] opened 2020-11-17 16:53 UTC
**Is your feature request related to a problem? Please describe.**
.NET 6 will [seemingly](https://twitter.com/davidfowl/status/1328688958730072064) have a story around Roslyn Source Generators being baked right into the dotnet/runtime.

Knowing/predicting that Roslyn Source Generator implementations can (or will) range from being fairly simple to - potentially - very very complex; it seems unworkable to expect "ports" of them to F# to be maintained by the community.

I would consider the "Compiled RegEx Source Generator" on the _fairly simple_ end of the scale. And, probably, ideas like "AOT source generation for Xamarin.iOS" on the _very complex_ end of the scale.

**Describe the solution you'd like**
I believe F# 6 will need some sort of interop/compatibility that allows it to work with Roslyn Source Generators.

I am not an expert on the forces involved, but one idea I had was to delegate to CSC for the Source Generator step of the build, and then merge the IL into the output F# assembly. Though I'm sure this is easier said than done. There is also the "Myriad" project which @7sharp9 highlighted to me - which could form some part of a solution, I don't know?

**Describe alternatives you've considered**
There is the alternative that F# chooses to opt-out of wanting to support (nor, port / emulate) some of these advancements/optimisations which are likely coming in .NET 6.

There is the alternative that one could use a .csproj C# project instead for the particular area of concern where a Roslyn Source Generator provides some functionality that F# doesn't support.

**Additional context**
Because Roslyn Source Generators seem to be a bespoke proprietary feature that was put together without any consideration for other .NET languages - it seems to me (though I may be wrong) one of the hurdles will be getting some sort of retrospectively-fitted abstraction put in place into the `dotnet/runtime` which both Roslyn and other .NET languages can hook into.

**I don't pretend to understand Roslyn Source Generators at a technical level so I may well have made some incorrect assumptions. If so, please add your comments and if necessary I can update the OP.**

**Comment by cartermp** [comment] 2020-11-17 17:04
closing as duplicate of https://github.com/fsharp/fslang-suggestions/issues/864

> Because Roslyn Source Generators seem to be a bespoke proprietary feature that was put together without any consideration for other .NET languages 

They're open source and have always been open source. Generating source code for a target language always requires that language's compiler.

**Closed by cartermp** 2020-11-17 17:04 UTC
Labels: Feature Request
