### ISSUE TITLE
FS0193: when sending file to interactive

### ISSUE THREAD

**Issue by mastoj** [dotnet/fsharp#10075] opened 2020-09-04 22:18 UTC
I have the following code in a file:

```
type Commands =
    | CreateCustomer
    | DeleteCustomer
    | UpdateAddress
    | UpdatePersonalInfo
    | AddAddress
    | SetPrimaryAddress
    | AddConsent
    | AddIdentity
    | MergeCustomer
    | DeleteAddress
    | DeleteIdentity

type Events =
    | CustomerCreated
    | CustomerDeleted
    | AddressUpdated
    | PersonalInfoUpdated
    | AddressAdded
    | PrimaryAddressChanged
    | ConsentAdded
    | IdentityAdded
    | CustomerMerged
    | AddressDeleted
    | IdentityDeleted

type Error =
    | InvalidEmail

type Queries =
    | GetIdentity
    | Search

type QueryResult =
    | GetIdentityResult
    | SearchResult

type CommandHandler = Commands -> Result<Events list, Error list>
type Parser = string -> Result<Commands, Error list>
type Db = Events list -> Result<Events list, Error list>
type ServiceBus = Events list -> Result<Events list, Error list>
type Application = {
    Execute: string -> Result<Events list, Error list>
    Query: string -> Result<QueryResult, Error list>
}

let handler: CommandHandler = function
    | CreateCustomer -> [ CustomerCreated ] |> Ok
    | DeleteCustomer -> [ CustomerDeleted ] |> Ok
    | UpdateAddress -> [ AddressUpdated ] |> Ok
    | UpdatePersonalInfo -> [ PersonalInfoUpdated ] |> Ok
    | AddAddress -> [ AddressAdded ] |> Ok
    | SetPrimaryAddress -> [ PrimaryAddressChanged ] |> Ok
    | AddConsent -> [ ConsentAdded ] |> Ok
    | AddIdentity -> [ IdentityAdded ] |> Ok
    | MergeCustomer -> [ CustomerMerged ] |> Ok
    | DeleteAddress -> [ AddressDeleted ] |> Ok
    | DeleteIdentity -> [ IdentityDeleted ] |> Ok

let db: Db = fun events ->
    printfn "Implement how data should be saved"
    events |> Ok

let serviceBus: ServiceBus = fun events ->
    printfn "Implement logic on how data should be published on servicebus"
    events |> Ok

let parser: Parser = fun s -> CreateCustomer |> Ok

let createApplication (parser: Parser) (handler: CommandHandler) (db: Db) (serviceBus: ServiceBus) : Application =
    let execute s =
        s
        |> parser
        |> Result.bind handler
        |> Result.bind db
        |> Result.bind serviceBus
    let query s = SearchResult |> Ok
    {
        Execute = execute
        Query = query
    }

let application = createApplication parser handler db serviceBus
"create customer"
|> application.Execute
|> printfn "==> Result: %A"
```
When I select all the code in VS Code and send to interactive it fails with

> error FS0193: internal error: Could not load type 'Error' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

If I do send things part by part it works fine, like first all the types and then the rest. 

## Expected behavior

That it works the same way when I send everything and part by part.

* Windows 10
* FSI For .NET Core
* VS Code

**Comment by cartermp** [comment] 2020-09-04 23:02
This is a problem with `dotnet fsi`. If I execute with FSI in Visual Studio, there isn't a problem.

cc @dsyme @KevinRansom

**Comment by mastoj** [comment] 2020-09-05 21:03
Did you reproduce it in VS Code (or with `dotnet fsi` directly) @cartermp?

**Comment by cartermp** [comment] 2020-09-05 22:33
I confirmed this just by using `dotnet fsi` on the command line. That's what Ionide will use too I believe.

**Comment by goswinr** [comment] 2020-09-07 15:08
same with FCS 33.0.1 :
```
Runtime Error: System.TypeLoadException: Could not load type 'Error' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateType()
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.typeCreationHandler@1995.Invoke(Object o, ResolveEventArgs r)
   at System.AppDomain.OnTypeResolveEvent(RuntimeAssembly assembly, String typeName)
   at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateType()
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.traverseTypeRef@1981(Dictionary`2 visited, Dictionary`2 created, emEnv emEnv, ILTypeRef tref)
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.traverseType@1981-2.Invoke(ILTypeRef tref)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 103
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.traverseTypeDef@1972-1.Invoke(ILFieldDef fd)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 103
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.traverseTypeDef@1945(Dictionary`2 visited, Dictionary`2 created, emEnv emEnv, ILTypeRef tref, ILTypeDef tdef)
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.traverseTypeRef@1981(Dictionary`2 visited, Dictionary`2 created, emEnv emEnv, ILTypeRef tref)
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildTypeDefPass4(Dictionary`2 visited, Dictionary`2 created, FSharpList`1 nesting, emEnv emEnv, ILTypeDef tdef)
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildModuleFragment@2064-1.Invoke(ILTypeDef tdef)
   at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 103
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildModuleFragment(cenv cenv, emEnv emEnv, AssemblyBuilder asmB, ModuleBuilder modB, ILModuleDef m)
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitModuleFragment(ILGlobals ilg, emEnv emEnv, AssemblyBuilder asmB, ModuleBuilder modB, ILModuleDef modul, Boolean debugInfo, FSharpFunc`2 resolveAssemblyRef, FSharpFunc`2 tryFindSysILTypeRef)
   at FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.ProcessInputs(CompilationThreadToken ctok, ErrorLogger errorLogger, FsiDynamicCompilerState istate, FSharpList`1 inputs, Boolean showTypes, Boolean isIncrementalFragment, Boolean isInteractiveItExpr, FSharpList`1 prefixPath)
   at FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.EvalParsedDefinitions(CompilationThreadToken ctok, ErrorLogger errorLogger, FsiDynamicCompilerState istate, Boolean showTypes, Boolean isInteractiveItExpr, FSharpList`1 defs)
   at FSharp.Compiler.Interactive.Shell.clo@1786-299.Invoke(FsiDynamicCompilerState istate)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[b](ErrorLogger errorLogger, FSharpFunc`2 f, b istate)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ReraiseIfWatsonable(Exception exn)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, range m)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.StopProcessingRecovery(ErrorLogger x, Exception exn, range m)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[b](ErrorLogger errorLogger, FSharpFunc`2 f, b istate)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.ExecInteraction(CompilationThreadToken ctok, TcConfig tcConfig, FsiDynamicCompilerState istate, ParsedFsiInteraction action, ErrorLogger errorLogger)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.execParsedInteractions(CompilationThreadToken ctok, TcConfig tcConfig, FsiDynamicCompilerState istate, FSharpOption`1 action, ErrorLogger errorLogger, FSharpOption`1 lastResult, CancellationToken cancellationToken)
   at FSharp.Compiler.Interactive.Shell.clo@1964-302.Invoke(CompilationThreadToken ctok, TcConfig tcConfig, FsiDynamicCompilerState istate)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.mainThreadProcessAction[a,b](a ctok, FSharpFunc`2 action, b istate)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ReraiseIfWatsonable(Exception exn)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, range m)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.StopProcessingRecovery(ErrorLogger x, Exception exn, range m)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.mainThreadProcessAction[a,b](a ctok, FSharpFunc`2 action, b istate)
   at FSharp.Compiler.Interactive.Shell.EvalInteraction@2102.Invoke(FsiDynamicCompilerState istate)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[b](ErrorLogger errorLogger, FSharpFunc`2 f, b istate)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ReraiseIfWatsonable(Exception exn)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, range m)
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.StopProcessingRecovery(ErrorLogger x, Exception exn, range m)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[b](ErrorLogger errorLogger, FSharpFunc`2 f, b istate)
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.EvalInteraction(CompilationThreadToken ctok, String sourceText, String scriptFileName, ErrorLogger errorLogger, FSharpOption`1 cancellationToken)
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.EvalInteractionNonThrowing(String code, FSharpOption`1 cancellationToken)
```

**Comment by KevinRansom** [comment] 2020-09-08 20:58
@cartermp , I see the failure in VS which uses the desktop fsi.exe.
Also, if i save the script to disk and run the file using:
fsi script1.fsx it also fails.
````
C:\Temp>fsi Script1.fsx


error FS0193: internal error: Could not load type 'Error' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.


C:\Temp>
````

**Comment by KevinRansom** [comment] 2020-09-08 21:29
It also fails on vs2017. with fsi from F# 4,1
````
Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> 

error FS0193: internal error: Could not load type 'Events' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

> 
````

**Comment by KevinRansom** [comment] 2020-09-08 21:30
I'm reducing the severity to medium, since we have lived with it for such a long time.

**Comment by dsyme** [comment] 2022-03-30 05:42
Fixed by `--multiemit+` which is on y default for .NET Core

**Closed by dsyme** 2022-03-30 05:42 UTC
Labels: Bug, Area-FSI, Impact-Medium
