### ISSUE TITLE
Ignore function cannot be used with IsByRefLike types

### ISSUE THREAD

**Issue by zpodlovics** [dotnet/fsharp#10345] opened 2020-10-27 18:27 UTC
It seems that the core library ignore function cannot be used with IsByRefLike types

**Repro steps**

Provide the steps required to reproduce the problem:

Please consider the following code:

```fsharp
namespace IsByRefLikeIgnore
open System
open System.Runtime.CompilerServices

[<Struct;IsByRefLike>]
type RefValueBuilder =
    val mutable private value1: int32
    val mutable private value2: int32

    member this.GetValue1() = this.value1    
    member this.SetValue1(value) =
        this.value1 <- value
        this

    member this.GetValue2() = this.value2
    member this.SetValue2(value) =
        this.value2 <- value
        this

module RefValueBuilder = begin
    let create() =
        RefValueBuilder()
            .SetValue1(1)
            .SetValue2(2)
    
    let createDiscard() =
        let mutable builder = RefValueBuilder()
        let _ = builder.SetValue1(1)
        let _ = builder.SetValue2(2)
        builder        

    let createIgnore() =
        let mutable builder = RefValueBuilder()
        //[FS0412] A type instantiation involves a byref type. This is not permitted by the rules of Common IL.
        //builder.SetValue1(1) |> ignore
        //builder.SetValue2(2) |> ignore
        builder        
        
end

module Main = begin

    [<EntryPoint>]
    let main argv =
        let  builderCreate = RefValueBuilder.create()                
        printfn "Hello RefValueBuilder.create(%d,%d) from F#!" (builderCreate.GetValue1()) (builderCreate.GetValue2())
        let  builderCreateDiscard = RefValueBuilder.createDiscard()                
        printfn "Hello RefValueBuilder.createDiscard(%d,%d) from F#!" (builderCreateDiscard.GetValue1()) (builderCreateDiscard.GetValue2())
        let  builderCreateIgnore = RefValueBuilder.createIgnore()                
        printfn "Hello RefValueBuilder.createIgnore(%d,%d) from F#!" (builderCreateIgnore.GetValue1()) (builderCreateIgnore.GetValue2())                
        0 // return an integer exit code
end
```

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

[IsByRefLikeIgnore.zip](https://github.com/dotnet/fsharp/files/5447316/IsByRefLikeIgnore.zip)

**Expected behavior**

Ignore can be used with IsByRefLike types.

**Actual behavior**

Ignore cannot be used with IsByRefLike types.

**Known workarounds**

Use discard (```fsharp let _ = ```) istead of ignore.

**Related information**

Provide any related information (optional):

* Operating system:

Ubuntu 20.04

* .NET Runtime kind (.NET Core, .NET Framework, Mono)

```
ii  dotnet-apphost-pack-3.1                                     3.1.9-1                               amd64        Microsoft.NETCore.App.Host 3.1.9
ii  dotnet-host                                                 3.1.9-1                               amd64        Microsoft .NET Core Host - 3.1.9
ii  dotnet-hostfxr-3.1                                          3.1.9-1                               amd64        Microsoft .NET Core Host FX Resolver - 3.1.9 3.1.9
ii  dotnet-runtime-3.1                                          3.1.9-1                               amd64        Microsoft .NET Core Runtime - 3.1.9 Microsoft.NETCore.App 3.1.9
ii  dotnet-runtime-deps-3.1                                     3.1.9-1                               amd64        dotnet-runtime-deps-3.1 3.1.9
ii  dotnet-sdk-3.1                                              3.1.403-1                             amd64        Microsoft .NET Core SDK 3.1.403
ii  dotnet-targeting-pack-3.1                                   3.1.0-1                               amd64        Microsoft.NETCore.App.Ref 3.1.0
```

**Comment by cartermp** [comment] 2020-10-27 18:53
Closing as by design, see https://github.com/fsharp/fslang-suggestions/issues/872 and please update with this as a suggested function

**Closed by cartermp** 2020-10-27 18:53 UTC
