### ISSUE TITLE
F# CodeLens overlays with normal code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#12626] opened 2022-01-19 21:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-CodeLens-overlays-with-normal-code/1531845)._

---
[severity:It's more difficult to complete my work]
With F# CodeLens enabled and set to be "above the line", sometimes the type annotations appear at the same line -- i.e. overlay -- with the normal code.
The custom type name in the overlaying CodeLens annotation is still clickable and can navigate to the type definition.
Please refer to the 71-th line in the attached screenshot for the appearance of this issue.

Before this happened I was trying to delete some nearby lines. 
Not sure what actually triggered this.

---
#### Feedback Bot on 9/16/2021, 11:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/4/2022, 00:01 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by psfinaki** [comment] 2022-10-06 13:10
F# CodeLens "above the line" is broken as of now.

**Comment by psfinaki** [comment] 2022-10-06 13:13
Basically a duplicate of #12625 
Closing, will be addressed there.

**Closed by psfinaki** 2022-10-06 13:13 UTC
Labels: Bug, Impact-Medium, Area-LangService-CodeLens
