### ISSUE TITLE
Internal and private fields aren't resolved

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#5067] opened 2018-06-01 14:42 UTC
It would be nice if compiler resolved inaccessible fields and showed an error about wrong accessibility.
<img width="315" alt="screen shot 2018-06-01 at 17 34 37" src="https://user-images.githubusercontent.com/3923587/40846475-6444787c-65c2-11e8-912d-d04fc3d6f314.png">

Example error message:
<img width="353" alt="screen shot 2018-06-01 at 17 38 31" src="https://user-images.githubusercontent.com/3923587/40846574-acc7dd28-65c2-11e8-9595-bdc00714ffd8.png">

**Comment by dsyme** [comment] 2018-09-21 13:09
I believe reading the internal/private metadata of .NET DLLs could trigger problems where further transitive dependencies are required for the error message to be produced.

I'd imagine the C# compiler doesn't do this for private things, but I haven't checked.

**Comment by smoothdeveloper** [comment] 2018-09-21 14:39
maybe related: #1348

**Comment by zpodlovics** [comment] 2018-09-21 16:40
maybe related: https://github.com/Microsoft/visualfsharp/issues/5503

**Comment by dsyme** [comment] 2022-03-31 04:28
Treating as duplicate of https://github.com/dotnet/fsharp/issues/1348

**Closed by dsyme** 2022-03-31 04:28 UTC
Labels: Area-Compiler, Feature Improvement
