### ISSUE TITLE
FSI using call not callvirt and doesn't check for nulls 

### ISSUE THREAD

**Issue by cartermp** [dotnet/fsharp#5239] opened 2018-06-27 06:23 UTC
Consider the following F# script:

```fsharp
type C() =
    member __.M() = "hello"
let c = Unchecked.defaultof<C>
let s = Unchecked.defaultof<string>

c.M()
```

This will produce the following output:

```fsharp
type C =
  class
    new : unit -> C
    member M : unit -> string
  end
val c : C = null
val s : string = null
val it : string = "hello"
```

Note that `c` is considered `null`, but it still evaluated `c.M()`.

If this is pasted into a console app, a `NullReferenceException` occurs as expected:

<img width="595" alt="screen shot 2018-06-26 at 23 22 30" src="https://user-images.githubusercontent.com/6309070/41956262-d32269b4-7997-11e8-81f1-3d50e5b8914d.png">

If I try to dereference `s` in the F# script, a `NullReferenceException` is also thrown, as expected.

**Comment by matthid** [comment] 2018-07-14 20:29
It seems like it throws in Debug and "works" in Release builds. As soon as I switch to "Release" in Visual Studio the program doesn't throw anymore and returns 0.

**Comment by matthid** [comment] 2018-07-14 20:32
From reading https://stackoverflow.com/questions/10625326/this-null-inside-net-instance-method-why-is-that-possible and https://stackoverflow.com/questions/10169035/why-does-string-equalsobject-obj-check-to-see-if-this-null/10169640#10169640 I'd assume this is a long known "difference" between the C# and F# compiler and the F# compiler will optimize away the `callvirt` to a `call` IL-operation

**Comment by dsyme** [comment] 2022-03-30 05:33
Yes, this is the case:

>  From reading https://stackoverflow.com/questions/10625326/this-null-inside-net-instance-method-why-is-that-possible and https://stackoverflow.com/questions/10169035/why-does-string-equalsobject-obj-check-to-see-if-this-null/10169640#10169640 I'd assume this is a long known "difference" between the C# and F# compiler and the F# compiler will optimize away the callvirt to a call IL-operation

I will close this as by design

**Closed by dsyme** 2022-03-30 05:33 UTC
Labels: Bug, Area-FSI, Impact-Low
