### ISSUE TITLE
Missing References when getting project options from a script with dotcoreapp2.1

### ISSUE THREAD

**Issue by fangyi-zhou** [dotnet/fsharp#6535] opened 2019-04-14 16:07 UTC
`FSharpChecker.GetProjectOptionsFromScript` does not give correct references with dotcoreapp2.1.
#### Repro steps
See https://github.com/fangyi-zhou/missing-system-runtime
#### Expected behavior
No error
#### Actual behavior
`Assembly reference 'mscorlib.dll' was not found or is invalid` when `assumeDotNetFramework = true`
`The type referenced through 'System.Int32' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime'` when `assumeDotNetFramework = false`
#### Related information 
* Operating system
macOS Mojave 10.14.3
* FCS Version
28.0
* .NET Runtime, CoreCLR or Mono Version
```
$ dotnet --version
2.1.500
```

**Comment by fangyi-zhou** [comment] 2019-05-01 23:24
bump bump

**Comment by cartermp** [comment] 2019-05-02 02:42
cc @dsyme

**Comment by fangyi-zhou** [comment] 2019-05-13 14:42
bump bump

**Comment by dsyme** [comment] 2020-08-26 18:50
@fangyi-zhou 

Thank you for the repro for this and our apologies for the long delay in addressing this.

I believe a duplicate of #6161 , and that this has been fixed some time ago.

The one exception is that the application will expect `FSharp.Core.dll` to be in the same location as your executable.  So to get

    dotnet run -- seven.fsx

to run without publishing the app you need to use this in your project file

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

There has also been an API change and I adjusted your code as follows:

```
module MissingSystemRuntime

open FSharp.Compiler.SourceCodeServices

[<EntryPoint>]
let main argv =
    let checker = FSharpChecker.Create(keepAssemblyContents=true)
    let file = argv.[0]
    let options, errors = checker.GetProjectOptionsFromScript(file, FSharp.Compiler.Text.SourceText.ofString file) |> Async.RunSynchronously
    printfn "Options: %A" options
    printfn "Errors: %A" errors
    let results = checker.ParseAndCheckProject(options) |> Async.RunSynchronously
    printfn "%A" results.Errors
    let options, errors = checker.GetProjectOptionsFromScript(file,  FSharp.Compiler.Text.SourceText.ofString file, assumeDotNetFramework = false) |> Async.RunSynchronously
    printfn "Options: %A" options
    printfn "Errors: %A" errors
    let results = checker.ParseAndCheckProject(options) |> Async.RunSynchronously
    printfn "%A" results.Errors
    0 // return an integer exit code
```

**Closed by dsyme** 2020-08-26 18:50 UTC
Labels: Area-FCS, bug
