### ISSUE TITLE
Visual f# tools needs AnyCPU platform in the solution to find references

### ISSUE THREAD

**Issue by AnthonyLloyd** [dotnet/fsharp#3053] opened 2017-05-15 13:36 UTC
I have a solution that targets x86 and x64 platforms but not AnyCPU.

I get the following error across all project references:

Assembly reference 'C:\Users\Ant\src\Asset\External\Asset.Common.dll' was not found or is invalid.

It doesn't seem to be able to find the bin\Debug\x86 directory.

The solution builds correctly though.

#### Repro steps

1. Remove AnyCPU solution platform from an existing solution

2. Restart visual studio

3. Navigate to a fs file which references other project code

#### Expected behavior

Intellisense to work the same as build.

#### Actual behavior

Many errors in the error window and no errors in the output window.

#### Known workarounds

Put AnyCPU back into the solution.

#### Related information 

Not a major issue given the workaround but I thought I'd notify as it may help others who see the same problem.

**Comment by dsyme** [comment] 2017-05-15 20:13
@AnthonyLloyd Any idea if this is a regression?

**Comment by AnthonyLloyd** [comment] 2017-05-15 21:10
@dsyme I upgraded to VS2017 and Visual F# tool nightly build last week of March. I think I've saw it just after then and tweeted asking about it on 10 Apr.

**Comment by saul** [comment] 2017-05-15 21:21
Hmm I've seen this before and it's not a regression - the problem is one of your projects will specify something like:

```
<Platform Condition=" $(Platform) == '' ">AnyCPU</Platform>
```

When that project doesn't have an AnyCPU platform. Fix that.

**Comment by AnthonyLloyd** [comment] 2017-05-15 22:30
@saul I think you may be right. I changed these to x86. Intellisense works if x86 has been built. Problem is If you are on  x64 and x86 hasn't been built it before then the error appears but is looking for the x86 dlls. Should I be doing something different with these Platform lines? Seems Intellisense is looking at incorrect dlls even when there are no errors?

**Comment by dsyme** [comment] 2017-06-20 13:01
Closing as this was a problem with the project file

**Comment by AnthonyLloyd** [comment] 2017-06-20 13:56
@dsyme I think there still may be an issue in that intellisense always works from the default and not the current solution config. I think this leads to odd errors when default not there or out of sync.

**Comment by dsyme** [comment] 2017-06-20 20:32
@AnthonyLloyd Ok, thanks

**Comment by cartermp** [comment] 2020-08-15 17:40
Since this is ultimately a legacy F# project system issue I'll close this out. We don't have any intention of changing the system, and all new projects (including .NET FX) now use the new project system: https://github.com/dotnet/project-system

**Closed by cartermp** 2020-08-15 17:40 UTC
Labels: Area-IDE Legacy Project System, Resolution-Wont Fix, Urgency-Soon, bug
