### ISSUE TITLE
fsc netcore --help shows pdbonly and full. and --debug:__ ignores these options

### ISSUE THREAD

**Issue by enricosada** [dotnet/fsharp#2565] opened 2017-03-09 10:56 UTC
Doing `fsc --debug:full` doesnt work if fsc is built for .net core.
the target framework doesnt matter (`netcoreapp1.1` or `net451` is the same result).

zero pdb, zero warning, zero errors. it's just not created. Maybe a warning/error?

As a note from https://github.com/dotnet/netcorecli-fsc/issues/89 bug report with repro, `csc` netcore support full (/cc @DaveEmmerson)

Repro, using .net core sdk 1.0 rtm because is easier.

```
dotnet new console -lang f#
change fsproj adding `<DebugType>full</DebugType>`
dotnet restore
dotnet build -v n
```

the `-v n` show fsc args :D

Expected:

the full pdb is output dir

Result:

no pdb, no errors, no warning

**Comment by KevinRansom** [comment] 2017-03-09 15:12
Yes, full pdb’s are not built by the netcore compiler.  For F# portable pdbs have all the same information and are teeny-tiny.

Yes C# supports desktop PDBs on coreclr, this is not something we intend to address at this time.

Kevin

**Comment by KevinRansom** [comment] 2017-03-09 15:21
Closing by-design.

**Comment by enricosada** [comment] 2017-03-09 15:33
@KevinRansom that need a warning/error? because atm no pdb is generated and no messages about that, so can be confusing.
happy to add the warning if you think is something who may be useful.

**Comment by KevinRansom** [comment] 2017-03-09 15:43
Oh does the help still allow full and pdb only that is certainly an issue.

**Comment by enricosada** [comment] 2017-03-09 15:46
@KevinRansom 

```
--debug:{full|pdbonly|portable|embedded} Specify debugging type: full, portable, embedded, pdbonly. ('full' is the default if
                                         no debuggging type specified and enables attaching a debugger to a running program,
                                         'portable' is a cross-platform format, 'embedded' is a cross-platform format
                                         embedded into the output file).
```

**Comment by matthid** [comment] 2017-03-09 17:35
I'm not sure if we should break the cli interface. Could we print a warning instead as @enricosada suggested and change the help text? Or is there a good reason to break it?
Or maybe I understood that wrong :)

**Comment by dsyme** [comment] 2017-03-09 17:41
Or we could we print a warning and just generate portable PDBs?

**Comment by enricosada** [comment] 2017-03-09 18:02
as a note, current behaviour:
using a wrong value for `DebugType` property, the `FscTask` will not pass `--debug` to fsc, just `-g`, and no warning/errors.

> we print a warning and just generate portable PDBs

warning and no pdb is better ihmo, at least i see there are no pdb generated. 
The `full` is usually used generate  net45 assemblies/apps (legacy maybe), so using a wrong pdb format is not good (i get the error later at debug time)
As default value embedded is a good alternative, probably better than `portable` for the long run

**Comment by KevinRansom** [comment] 2017-03-09 18:39
Warning works for me ...

**Comment by dsyme** [comment] 2017-03-09 18:55
Certainly it feels like ``-g`` should generate portable

**Comment by cartermp** [comment] 2018-02-18 16:41
This has both `resolution-by-design` and `bug` labels.

Is this by design, or a bug? If it's by design, we should close it.

**Comment by cartermp** [comment] 2018-07-29 17:11
Ping - should this still be `resolution-by-design`?

**Comment by KevinRansom** [comment] 2020-03-25 22:22
--debug:portable on the coreclr compiler generates a portable pdb.

**Closed by KevinRansom** 2020-03-25 22:22 UTC
Labels: Area-Compiler, Resolution-By Design, Urgency-Later, bug
