### ISSUE TITLE
test.sh fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [dotnet/fsharp#11069] opened 2021-02-09 15:23 UTC
build.sh runs fine. However, 'dotnet' or 'fsharpc' isn't found. test.sh fails: 

[jw@cn06 fsharp]$ ./test.sh
FSharp.sln:
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
FSharpEmbedResXSource: Skipping generation: '/data/jw/fsharp/artifacts/obj/FSharp.Core/Proto/netstandard2.0/FSCore.fs' since it is up-to-date.
  FSharp.Core -> /data/jw/fsharp/artifacts/bin/FSharp.Core/Proto/netstandard2.0/FSharp.Core.dll
  fslex -> /data/jw/fsharp/artifacts/bin/fslex/Proto/netcoreapp3.1/fslex.dll
  fsyacc -> /data/jw/fsharp/artifacts/bin/fsyacc/Proto/netcoreapp3.1/fsyacc.dll
  AssemblyCheck -> /data/jw/fsharp/artifacts/bin/AssemblyCheck/Proto/netcoreapp3.1/AssemblyCheck.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.29
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  FSharp.Core -> /data/jw/fsharp/artifacts/bin/FSharp.Core/Proto/netstandard2.0/FSharp.Core.dll
  FSharp.Build -> /data/jw/fsharp/artifacts/bin/FSharp.Build/Proto/netstandard2.0/FSharp.Build.dll
  FSharp.DependencyManager.Nuget -> /data/jw/fsharp/artifacts/bin/FSharp.DependencyManager.Nuget/Proto/netstandard2.0/FSharp.DependencyManager.Nuget.dll
  FSharp.Compiler.Service -> /data/jw/fsharp/artifacts/bin/FSharp.Compiler.Service/Proto/netstandard2.0/FSharp.Compiler.Service.dll
  fsc -> /data/jw/fsharp/artifacts/bin/fsc/Proto/netcoreapp3.1/fsc.dll
  FSharp.Compiler.Interactive.Settings -> /data/jw/fsharp/artifacts/bin/FSharp.Compiler.Interactive.Settings/Proto/netstandard2.0/FSharp.Compiler.Interactive.Settings.dll
  fsi -> /data/jw/fsharp/artifacts/bin/fsi/Proto/netcoreapp3.1/fsi.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:17.64

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.58
Test run for /data/jw/fsharp/artifacts/bin/FSharp.Compiler.ComponentTests/Debug/netcoreapp3.1/FSharp.Compiler.ComponentTests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
---------------------------------------------------------------
Executables

CSC                 =/home/jw/.nuget/packages/microsoft.net.compilers/2.7.0/tools/csc.exe
BUILD_CONFIG        =Debug
csc_flags           =/nologo
FSC                 =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/fsc/Debug/netcoreapp3.1/fsc.dll
fsc_flags           =-r:System.Core.dll --nowarn:20 --define:COMPILED
FSCOREDLLPATH       =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/FSharp.Core/Debug/netstandard2.0/FSharp.Core.dll
FSI                 =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/fsi/Debug/netcoreapp3.1/fsi.dll
FSI_FOR_SCRIPTS     =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/fsi/Debug/netcoreapp3.1/fsi.dll
fsi_flags           =-r:System.Core.dll --nowarn:20 --define:INTERACTIVE --maxerrors:1 --abortonerror
ILDASM              =/home/jw/.nuget/packages/runtime.linux-x64.microsoft.netcore.ildasm/5.0.0-preview.7.20364.11/runtimes/linux-x64/native/ildasm
PEVERIFY            =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/PEVerify/Debug/netcoreapp3.1/PEVerify
---------------------------------------------------------------
The active test run was aborted. Reason: Test host process crashed : Process terminated. Assertion Failed
implicitIncludeDir should be absolute: ''
   at FSharp.Compiler.CompilerConfig.TcConfigBuilder.CreateNew(LegacyReferenceResolver legacyReferenceResolver, String defaultFSharpBinariesDir, ReduceMemoryFlag reduceMemoryUsage, String implicitIncludeDir, Boolean isInteractive, Boolean isInvalidationSupported, CopyFSharpCoreFlag defaultCopyFSharpCore, FSharpFunc`2 tryGetMetadataSnapshot, FSharpOption`1 sdkDirOverride, Range rangeForErrors) in /data/jw/fsharp/src/fsharp/CompilerConfig.fs:line 659
   at <StartupCode$FSharp-Compiler-Service>.$IncrementalBuild.TryCreateIncrementalBuilderForProjectOptions@1299-5.Invoke(Unit unitVar) in /data/jw/fsharp/src/fsharp/service/IncrementalBuild.fs:line 1315
   at Internal.Utilities.Library.Cancellable.delay@766.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 766
   at Internal.Utilities.Library.Cancellable.catch@784.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 786
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.catch@784.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 786
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.catch@784.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 786
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@186-2.Invoke(CompilationThreadToken ctok) in /data/jw/fsharp/src/fsharp/service/Reactor.fs:line 189
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.loop@72-103.Invoke(FSharpOption`1 _arg2) in /data/jw/fsharp/src/fsharp/service/Reactor.fs:line 83
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in /data/jw/fsharp/src/fsharp/FSharp.Core/async.fs:line 404
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.loop@62-101.Invoke(AsyncActivation`1 ctxt) in /data/jw/fsharp/src/fsharp/service/Reactor.fs:line 62
   at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@303-11.Invoke(AsyncActivation`1 ctxt) in /data/jw/fsharp/src/fsharp/FSharp.Core/mailbox.fs:line 303
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in /data/jw/fsharp/src/fsharp/FSharp.Core/async.fs:line 104
   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction) in /data/jw/fsharp/src/fsharp/FSharp.Core/async.fs:line 169
   at <StartupCode$FSharp-Core>.$Async.-ctor@155-1.Invoke(Object o) in /data/jw/fsharp/src/fsharp/FSharp.Core/async.fs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Results File: /data/jw/fsharp/artifacts/TestResults/Debug/FSharp.Compiler.ComponentTests_netcoreapp3.1.xml

Test Run Aborted.
Error running tests (exit code '1').
[jw@cn06 fsharp]$

**Comment by cartermp** [comment] 2021-02-09 16:12
> However, 'dotnet' or 'fsharpc' isn't found.

Hmmm. `fsharpc` wouldn't be found because that's a mono artifact, so I wouldn't expect that to be missing. But you should be able to use `dotnet` from the command line. I assume you already have the .NET 5 SDK installed since you could build, is that correct?

**Comment by LutzWeischerFujitsu** [comment] 2021-02-10 07:13
I didn't do a standard installation. I took the source code to compile (build) it. 'build.sh' runs successfully but calling 'dotnet' fails, likewise 'test.sh' with the above details.

**Comment by cartermp** [comment] 2021-02-10 16:02
What happens if you install .NET 5 for your distro(s)? We require a .NET SDK installation to work in this repo, since it's required for building all application types anyways.

**Comment by KevinRansom** [comment] 2021-02-11 02:12
@LutzWeischerFujitsu , hi, can you please describe the steps needed to reproduce this issue.

**It should be noted that our build relies on the dotnet sdk and nuget, we do not build this repo with mono.**

For example I would say something along the lines of:
````
1. On a clean install of xyz platform (E.g Ubuntu 20.04.lts)
2. Install the 5.03xx  linux x64 dotnet sdk from:  https://github.com/dotnet/installer#installers-and-binaries
2. Clone https://github.com/dotnet/fsharp.git using git
3. from the fsharp directory execute ./build.sh
`````

That way we will be able to try to see the issues you can see and hopefully fix our issue.

Thank you

Kevin

**Comment by LutzWeischerFujitsu** [comment] 2021-02-11 15:33
sudo yum install -y dotnet helped. I can now test successfully for a 'Hello, World'. However: 
[jw@cn06 fsharp]$ ./test.sh
FSharp.sln:
  Determining projects to restore...
  Restored /data/jw/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj (in 2.09 sec).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
FSharpEmbedResXSource: Skipping generation: '/data/jw/fsharp/artifacts/obj/FSharp.Core/Proto/netstandard2.0/FSCore.fs' since it is up-to-date.
  FSharp.Core -> /data/jw/fsharp/artifacts/bin/FSharp.Core/Proto/netstandard2.0/FSharp.Core.dll
  fslex -> /data/jw/fsharp/artifacts/bin/fslex/Proto/netcoreapp3.1/fslex.dll
  fsyacc -> /data/jw/fsharp/artifacts/bin/fsyacc/Proto/netcoreapp3.1/fsyacc.dll
  AssemblyCheck -> /data/jw/fsharp/artifacts/bin/AssemblyCheck/Proto/netcoreapp3.1/AssemblyCheck.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:10.89
  Determining projects to restore...
  Restored /data/jw/fsharp/src/fsharp/FSharp.Build/FSharp.Build.fsproj (in 1.9 sec).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  Restored /data/jw/fsharp/src/fsharp/FSharp.DependencyManager.Nuget/FSharp.DependencyManager.Nuget.fsproj (in 462 ms).
  Restored /data/jw/fsharp/src/fsharp/FSharp.Compiler.Service/FSharp.Compiler.Service.fsproj (in 532 ms).
  Restored /data/jw/fsharp/src/fsharp/fsc/fsc.fsproj (in 546 ms).
  2 of 5 projects are up-to-date for restore.
  Determining projects to restore...
  Restored /data/jw/fsharp/src/fsharp/FSharp.Compiler.Interactive.Settings/FSharp.Compiler.Interactive.Settings.fsproj (in 1 sec).
  Restored /data/jw/fsharp/src/fsharp/fsi/fsi.fsproj (in 1 sec).
  3 of 5 projects are up-to-date for restore.
  FSharp.Core -> /data/jw/fsharp/artifacts/bin/FSharp.Core/Proto/netstandard2.0/FSharp.Core.dll
  FSharp.Build -> /data/jw/fsharp/artifacts/bin/FSharp.Build/Proto/netstandard2.0/FSharp.Build.dll
  FSharp.DependencyManager.Nuget -> /data/jw/fsharp/artifacts/bin/FSharp.DependencyManager.Nuget/Proto/netstandard2.0/FSharp.DependencyManager.Nuget.dll
  FSharp.Compiler.Service -> /data/jw/fsharp/artifacts/bin/FSharp.Compiler.Service/Proto/netstandard2.0/FSharp.Compiler.Service.dll
  fsc -> /data/jw/fsharp/artifacts/bin/fsc/Proto/netcoreapp3.1/fsc.dll
  FSharp.Compiler.Interactive.Settings -> /data/jw/fsharp/artifacts/bin/FSharp.Compiler.Interactive.Settings/Proto/netstandard2.0/FSharp.Compiler.Interactive.Settings.dll
  fsi -> /data/jw/fsharp/artifacts/bin/fsi/Proto/netcoreapp3.1/fsi.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:47.82

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.58
Test run for /data/jw/fsharp/artifacts/bin/FSharp.Compiler.ComponentTests/Debug/netcoreapp3.1/FSharp.Compiler.ComponentTests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
---------------------------------------------------------------
Executables

CSC                 =/home/jw/.nuget/packages/microsoft.net.compilers/2.7.0/tools/csc.exe
BUILD_CONFIG        =Debug
csc_flags           =/nologo
FSC                 =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/fsc/Debug/netcoreapp3.1/fsc.dll
fsc_flags           =-r:System.Core.dll --nowarn:20 --define:COMPILED
FSCOREDLLPATH       =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/FSharp.Core/Debug/netstandard2.0/FSharp.Core.dll
FSI                 =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/fsi/Debug/netcoreapp3.1/fsi.dll
FSI_FOR_SCRIPTS     =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/fsi/Debug/netcoreapp3.1/fsi.dll
fsi_flags           =-r:System.Core.dll --nowarn:20 --define:INTERACTIVE --maxerrors:1 --abortonerror
ILDASM              =/home/jw/.nuget/packages/runtime.linux-x64.microsoft.netcore.ildasm/5.0.0-preview.7.20364.11/runtimes/linux-x64/native/ildasm
PEVERIFY            =/data/jw/fsharp/tests/FSharp.Test.Utilities/../../artifacts/bin/PEVerify/Debug/netcoreapp3.1/PEVerify
---------------------------------------------------------------
The active test run was aborted. Reason: Test host process crashed : Process terminated. Assertion Failed
implicitIncludeDir should be absolute: ''
   at FSharp.Compiler.CompilerConfig.TcConfigBuilder.CreateNew(LegacyReferenceResolver legacyReferenceResolver, String defaultFSharpBinariesDir, ReduceMemoryFlag reduceMemoryUsage, String implicitIncludeDir, Boolean isInteractive, Boolean isInvalidationSupported, CopyFSharpCoreFlag defaultCopyFSharpCore, FSharpFunc`2 tryGetMetadataSnapshot, FSharpOption`1 sdkDirOverride, Range rangeForErrors) in /data/jw/fsharp/src/fsharp/CompilerConfig.fs:line 659
   at <StartupCode$FSharp-Compiler-Service>.$IncrementalBuild.TryCreateIncrementalBuilderForProjectOptions@1299-5.Invoke(Unit unitVar) in /data/jw/fsharp/src/fsharp/service/IncrementalBuild.fs:line 1315
   at Internal.Utilities.Library.Cancellable.delay@766.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 766
   at Internal.Utilities.Library.Cancellable.catch@784.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 786
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.catch@784.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 786
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.catch@784.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 786
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at Internal.Utilities.Library.Cancellable.bind@726.Invoke(CancellationToken ct) in /data/jw/fsharp/src/fsharp/absil/illib.fs:line 727
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@186-2.Invoke(CompilationThreadToken ctok) in /data/jw/fsharp/src/fsharp/service/Reactor.fs:line 189
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.loop@72-103.Invoke(FSharpOption`1 _arg2) in /data/jw/fsharp/src/fsharp/service/Reactor.fs:line 83
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in /data/jw/fsharp/src/fsharp/FSharp.Core/async.fs:line 404
   at <StartupCode$FSharp-Compiler-Service>.$Reactor.loop@62-101.Invoke(AsyncActivation`1 ctxt) in /data/jw/fsharp/src/fsharp/service/Reactor.fs:line 62
   at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@303-11.Invoke(AsyncActivation`1 ctxt) in /data/jw/fsharp/src/fsharp/FSharp.Core/mailbox.fs:line 303
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in /data/jw/fsharp/src/fsharp/FSharp.Core/async.fs:line 104
   at Microsoft.FSharp.Control.TrampolineHolder.ExecuteWithTrampoline(FSharpFunc`2 firstAction) in /data/jw/fsharp/src/fsharp/FSharp.Core/async.fs:line 169
   at <StartupCode$FSharp-Core>.$Async.-ctor@155-1.Invoke(Object o) in /data/jw/fsharp/src/fsharp/FSharp.Core/async.fs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Results File: /data/jw/fsharp/artifacts/TestResults/Debug/FSharp.Compiler.ComponentTests_netcoreapp3.1.xml

Test Run Aborted.
Error running tests (exit code '1').
[jw@cn06 fsharp]$

**Comment by dsyme** [comment] 2021-11-05 16:19
Closing this, I don't think it's in our immediate goals, we can require Ubuntu and the Linux's we directly CI on

**Closed by dsyme** 2021-11-05 16:19 UTC
Labels: Bug, Area-Testing, Contributor Pain, Impact-Low
