### ISSUE TITLE
F# does not recognize C# initonly properties.  --- runtime exception when setting Init Only Property in .NET 5

### ISSUE THREAD

**Issue by jbtule** [dotnet/fsharp#10119] opened 2020-09-14 19:15 UTC
In .net5-RC1, if an F# program that sets a property that is marked as init only in C# 9.0, it compiles okay, but if you try to run that program you get an InvalidProgramException.

The steps required to reproduce the problem:

1. Have a C# library with a class that has an init only property.

```csharp
    public class DontSetMe {
        public string Data {get; init;}
    }
```

2. Have an F# program or library that tries to set that property

```fsharp
    DontSetMe(Data="Badness") |> ignore
```

3. Build and run

Example: FSharp console app called `consumer` and a csharp library called `producer` demonstrate this:
[init-only-props-fsharp-master.zip](https://github.com/dotnet/fsharp/files/5220379/init-only-props-fsharp-master.zip)

**Expected behavior**

I would expect a compiler error––until [init only properties are supported](https://github.com/fsharp/fslang-suggestions/issues/904) in F#. 

**Actual behavior**

*Compiler says OK.*

```bash
dotnet build
Microsoft (R) Build Engine version 16.8.0-preview-20451-02+51a1071f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  producer -> /Users/jayt/Documents/GitHub/init-only-props-fsharp/producer/bin/Debug/net5.0/producer.dll
  consumer -> /Users/jayt/Documents/GitHub/init-only-props-fsharp/consumer/bin/Debug/net5.0/consumer.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

*Runtime says NOOOOOOOOOOOO!*

```bash
dotnet run 
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
```

**Known workarounds**

Don't call such properties.

**Related information**

Provide any related information (optional):

* Operating system
**mac os x 10.15.3 (but probably all)**
* .NET Runtime kind (.NET Core, .NET Framework, Mono)
**.net 5.0 RC1 (5.0.100-rc.1.20452.10)**
* Editing Tools (e.g. Visual Studio Version, Visual Studio)
**n/a**

**Comment by KevinRansom** [comment] 2020-09-14 20:15
We don't yet recognize init when iteroperating with C# libraries.  I am sure that we will implement a feature supporting it.  But for now the work around is to not set public init only properties.

**Comment by jbtule** [comment] 2020-09-14 20:40
Well, I'm just saying, if you were going to treat it like a feature request, rather than a bug, my example's expected behavior should be to actually set the property...I understand it's not going to be supported in .NET 5.0, but there should be a compiler error saying so—rather than "surprise"! Then the workaround for the missing feature of setting an init only property, until a version of F# supported it, would be to use reflection.

**Comment by cartermp** [comment] 2020-09-14 20:44
Will close this out as by design because it is a language feature that needs implementing: https://github.com/fsharp/fslang-suggestions/issues/904

It was explicitly scoped out of the F# 5 release due to the amount of churn going on in the C# side.

We'll likely handle interop of init-only members in the next round of F# language updates.

**Closed by cartermp** 2020-09-14 20:44 UTC
Labels: Feature Request, Resolution-By Design
