### ISSUE TITLE
Loading NuGet packages in dotnet fsi failing in .NET 6.0.100-rc1

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/fsharp#12162] opened 2021-09-15 22:35 UTC
**Repro steps**

On Linux:

```bash
$ wget https://download.visualstudio.microsoft.com/download/pr/4880c5a4-9c22-47a7-b298-651f1294a385/795f7828d8684059705e625b33027f89/dotnet-sdk-6.0.100-rc.1.21458.32-linux-x64.tar.gz # replace link with latest official binaries
$ mkdir dotnet6 && tar xvfz dotnet-sdk-6.0.100-rc.1.21458.32-linux-x64.tar.gz -C dotnet6/
$ dotnet6/dotnet fsi

Microsoft (R) F# Interactive version 12.0.0.0 for F# 6.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "nuget: Newtonsoft.Json" ;;

  #r "nuget: Newtonsoft.Json" ;;
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/eirik/stdin(1,1): error FS3217: /tmp/nuget/457--82636de1-1a6a-4af7-8e32-4119c7d91ab8/Project.fsproj : error NU1102: Unable to find package FSharp.Core with version (>= 6.0.0)
```

I'm assuming it's failing because a v6 FSharp.Core nuget package hasn't been pushed to NuGet yet.

**Related information**

Provide any related information (optional):

* Operating system _Ubuntu 20.04 x64_
* .NET Runtime kind _.NET 6.0.100-rc.1.21458.32_

**Comment by thinkbeforecoding** [comment] 2021-09-17 07:40
This is a duplicate of #12152 , we maybe can merge them.

**Closed** 2021-09-17 09:10 UTC
Labels: Regression, Impact-High, Area-Library
