### ISSUE TITLE
Unable to build F# project by using Visual Studio 2019

### ISSUE THREAD

**Issue by bohdan-krasyuk** [dotnet/fsharp#10515] opened 2020-11-20 10:23 UTC
Unable to build F# project via Visual Studio 2019

## My stuff:
Visual Studio 2019 (16.8.2)

from dotnet --info

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

## Project information:
```
<TargetFramework>netstandard2.0</TargetFramework>
...
FSharp.Core version="5.0.0"
```

## Problem:
When I trying to build a project by using Visual Studio I got an error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6004	The specified task executable location "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\dotnet" is invalid.	MyProjectName	c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\Microsoft.FSharp.Targets	281	
```
### Additional info:
 - build by using CLI works fine (dotnet --version    5.0.100)
 - Microsoft.FSharp.Targets file is default
 - Visual Studio and SDK reinstalled a couple of times already

**Comment by cartermp** [comment] 2020-11-20 17:55
@bohdan-krasyuk I cannot reproduce this with the latest VS 16.8.2. Can you share a repro?

**Comment by bohdan-krasyuk** [comment] 2020-11-20 19:08
@cartermp hey, thanks for the response, there are no steps at all, even when I create a new project, console application, for example, the problem still appears. Maybe I can collect some system info for you because look's like this is an OS related problem. A couple of my colleagues has the same issue, but on my other PC, everything works.

**Comment by mairaw** [comment] 2020-11-20 19:24
@bohdan-krasyuk since this seems related to VS on specific machines, maybe it will be better to use the Report a problem inside VS. That way, it'll send some diagnostic info to the appropriate team.
https://developercommunity.visualstudio.com/content/problem/post.html?space=8

**Comment by bohdan-krasyuk** [comment] 2020-11-20 19:51
@mairaw sure, I will send the report.

**Comment by bohdan-krasyuk** [comment] 2020-11-26 19:34
@mairaw @cartermp hey again, I finally manage to resolve/reproduce the issue. Unfortunately, the problem was appeared because of a workaround for other .NET 5 [issue](https://github.com/dotnet/sdk/issues/14497). I added the user env variable
`setx DOTNET_HOST_PATH "dotnet"`
and after the variable was added I have a wrong F# compiler path:
Instead of `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp`
I have `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\dotnet`
Even when I specify the full path, like this `setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"` path for F# still wrong, but in this case, I have another exception:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"dotnet.exe" exited with code -2147450749.	Aimee.CF.DependencyConnector.LoadTester	c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\Microsoft.FSharp.Targets	281	
```
I hope now you have enough information for reproducing the bug. Because it's incredibly inconvenient to edit an env variable every time when I need to switch between projects.

**Comment by cartermp** [comment] 2020-11-29 20:03
gotcha, this is a duplicate of #10447 then. I don't think we'll really do anything here to change the F# product to work around what is currently a bug though.

As a workaround, you could perhaps add something like this in a `Directory.build.props` file and see if that helps?

```xml
  <PropertyGroup Condition="'$(DisableAutoSetFscCompilerPath)' != 'true' and '$(DOTNET_HOST_PATH)' != ''">
    <FscToolPath Condition="'$(FscToolPath)' == ''">$([System.IO.Path]::GetDirectoryName($(DOTNET_HOST_PATH)))\..\</FscToolPath>
    <FscToolExe Condition="'$(FscToolExe)' == ''">$([System.IO.Path]::GetFileName($(DOTNET_HOST_PATH)))\..\</FscToolExe>
    <DotnetFscCompilerPath Condition="'$(DotnetFscCompilerPath)' == ''">"$(MSBuildThisFileDirectory)fsc.exe"</DotnetFscCompilerPath>

    <FsiToolPath Condition="'$(FsiToolPath)' == ''">$([System.IO.Path]::GetDirectoryName($(DOTNET_HOST_PATH)))\..\</FsiToolPath>
    <FsiToolExe Condition="'$(FsiToolExe)' == ''">$([System.IO.Path]::GetFileName($(DOTNET_HOST_PATH)))\..\</FsiToolExe>
    <DotnetFsiCompilerPath Condition="'$(DotnetFscCompilerPath)' == ''">"$(MSBuildThisFileDirectory)fsi.exe"</DotnetFsiCompilerPath>
  </PropertyGroup>
```

Note that I haven't tried this, but it's a copy-paste of F# targets logic that goes back up a directory to find the path for the compiler and FSI. It does have the potential to be fragile though, since the behavior of `DOTNET_HOST_PATH` could change over time and as bugs get fixed, setting it can no longer be valid. But this may alleviate some of the pain of having to set/unset between codebases.

**Closed by cartermp** 2020-11-29 20:03 UTC
Labels: needs repro

**Comment by bohdan-krasyuk** [comment] 2020-11-29 21:20
@cartermp thanks for the response, then I will wait for the fix,
btw additional build properties don't help me to fix the problem I have exactly the same error.
