### ISSUE TITLE
Find references fails

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9960] opened 2020-08-18 15:08 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/719239/find-references-fails.html)._

---
I know this has been reported, but here is a screenshot where you can clearly see it failing.

---
#### Feedback Bot on 9/2/2019, 02:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/5/2020, 11:09 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment] 2020-08-18 15:11
This should be fixed in https://github.com/dotnet/fsharp/pull/9934

The reported issue came from a 16.2 build. Since there was no code to share and only a screenshot, this is the best we can go with for now. The other issue filed by the same user is confirmed as fixed by https://github.com/dotnet/fsharp/pull/9934

**Closed by cartermp** 2020-08-18 15:11 UTC
