### ISSUE TITLE
Derived class not accepted for a type constraint when it implements `IEquatable<T>`

### ISSUE THREAD

**Issue by albertwoo** [dotnet/fsharp#14020] opened 2022-10-03 23:25 UTC
Please provide a succinct description of the issue.

**Repro steps**

Repo to reproduce: https://github.com/albertwoo/FSharpInheritIssue/blob/c805f56a2fad1e0313a09e85695e88c2bfef77f6/Program.fs#L10

![image](https://user-images.githubusercontent.com/8017681/193703025-00db0542-62ea-46c4-ab1b-0a0592d6ca78.png)

For other types this kind of inheritance is ok, but it looks like the Xaml panel or control have some special thing which cause fsharp compiler cannot infer that.

**Expected behavior**

Should repot no error.

**Actual behavior**

Provide a description of the actual behaviour observed. 

**Known workarounds**

None

**Related information**

Provide any related information (optional):

* Operating system: Window11
* .NET Runtime kind (.NET Core, .NET Framework, Mono): dotnet6
* Editing Tools (e.g. Visual Studio Version, Visual Studio): VS2022

**Comment by 0101** [comment] 2022-10-05 12:55
I believe the reason is because that `Panel` implements `IEquatable<Panel>` and `VirtualizingPanel` implements `IEquatable<VirtulizingPanel>`.

Since `'T` must satisfy `:> Panel` for class `A` the constraint solver figures that `IEquatable<Panel>` should equal `IEquatable<VirtualizingPanel>` and this is where the error message actually comes from. 

So the behavior is correct, because `VirtualizingPanel` does not satisfy this constraint, but the error message is quite confusing because the user doesn't know why the 2 types should be equal. 

We should probably extend the error message with more context that would explain what's going on.

Minimal repro:
```fsharp

open System

type MyClass() =
    member this.x = 1
    interface IEquatable<MyClass> with
        member this.Equals _ = false

type MySubClass() =
    inherit MyClass()
    interface IEquatable<MySubClass> with
        member this.Equals _ = false

type A<'T when 'T :> MyClass>() =
    class end

type B<'T when 'T :> MySubClass>() =
    inherit A<'T>()

```
```
      inherit A<'T>();;
  ------------^^^^^

stdin(19,13): error FS0001: The type 'MyClass' does not match the type 'MySubClass'
```

**Comment by albertwoo** [comment] 2022-10-06 00:04
@0101 I think it is not message confusing. There are two reasons:
1. From the fsharp docs "The provided type must be equal to or derived from the type specified, or, if the type is an interface, the provided type must implement the interface.", So MySubClass is indeed derived from MyClass. So it should satisfy.
2. Same thing works in csharp, and from the sytax shape it make sense.
```csharp
using System;

class MyClass : IEquatable<MyClass>
{
    public int X { get; set; }
    public bool Equals(MyClass? other) => false;
}

class MySubClass : MyClass, IEquatable<MySubClass>
{
    public bool Equals(MySubClass? other) => false;
}

class A<T> where T : MyClass
{
}

class B<T> : A<T> where T : MySubClass
{
}
```

**Comment by 0101** [comment] 2022-10-06 09:32
@albertwoo I guess you are right, it should probably accept any derived class.

**Comment by SteveGilham** [comment] 2022-10-08 11:54
This of course generalises to any such hierarchy based on an instance of the curiously recurring template pattern
```fsharp
type ISprintable<'T> =
    abstract member Print : format:'T -> unit
    
type BaseClass() =
  interface ISprintable<BaseClass> with
    member this.Print t = printfn "%A" t
    
type Derived() =
  inherit BaseClass()
  interface ISprintable<Derived> with
    member this.Print t = printfn "%A" t
    
type A<'T when 'T :> BaseClass>() =
  class
  end
  
type B<'T when 'T :> Derived>() =
  inherit A<'T>()
```
which results in
```
    inherit A<'T>();;
  ----------^^^^^

stdin(18,11): error FS0001: The type 'BaseClass' does not match the type 'Derived'
```
and not just the particular case of `IEquatable<'T>`

**Comment by T-Gro** [comment] 2022-10-10 12:37
Strangely this works when using 2 generic parameters for **B** (provided by the same real type at instantiation), maybe this might give a hint on where the issue is. Can also act as a workaround for the time being ;; @albertwoo and @SteveGilham .

`type ISprintable<'T> =
    abstract member Print : format:'T -> unit
    
type BaseClass() =
  interface ISprintable<BaseClass> with
    member this.Print t = printfn "%A" t
    
type Derived() =
  inherit BaseClass()
  interface ISprintable<Derived> with
    member this.Print t = printfn "%A" t

    
type A<'T when 'T :> BaseClass>() =
  class
  end
  
type B<'T,'U when 'T :> Derived and 'U:> BaseClass>() =
  inherit A<'U>()

let giveMeA = new A<BaseClass>()
let giveMeB = new B<Derived,Derived>()`

**Comment by T-Gro** [comment] 2022-10-10 12:40
Seeing more trough it, this is a duplicate of https://github.com/dotnet/fsharp/issues/12206 .
And is covered by this (not implemented) lang suggestion https://github.com/fsharp/fslang-suggestions/issues/255

**Closed** 2022-10-10 12:40 UTC
Labels: Bug, Area-Compiler-Checking
