### ISSUE TITLE
Visual Studio's "Rename" doesn't work properly for enumeration values

### ISSUE THREAD

**Issue by ArtemyB** [dotnet/fsharp#3205] opened 2017-06-13 12:15 UTC
#### Actual behavior

"Rename" works only for enum value or record field, that was selected (so it finds only 1 reference).

Demo for enumeration:
![Enum demo](http://i.imgur.com/u4THq5c.png)

Demo for record:
![Record demo](http://i.imgur.com/tIOZmGo.png)

#### Expected behavior

Find all references of the enum value/record field (as it does for DU cases, for example).

#### Related information

* Visual Studio 2017 Community, v.15.2
* Visual F# Tools (Nigtly) v.15.4.1.17060901

**Comment by cartermp** [comment] 2018-01-20 22:24
This now works for the record case:

![image](https://user-images.githubusercontent.com/6309070/35188606-6f9de7d6-fded-11e7-9390-7834fa6f888d.png)

Enum case is still the same behavior, but I don't think this is actually an issue with rename itself. The enum cases in the `match` expression are considered unused values and are not matching their definitions as symbols in document highlight. I suspect that the part of rename which looks for all matching symbols is not picking them up because of that.

**Comment by cartermp** [comment] 2020-08-12 23:52
Closing this out as by design. The enum case is because `Case1` and friends aren't actually referring to the enumeration itself. They are variable pattern identifiers. You need to fully quality enum access in F# to refer to the actual enum value.

Note that in F# 5 with `open type` declarations, this will no longer be necessary. Given that this works for the record case, there's no longer a valid repro for this issue.

**Closed by cartermp** 2020-08-12 23:52 UTC
Labels: Area-IDE Language Service, Urgency-Soon, bug
