### ISSUE TITLE
Same tail recursion properly compiled in module function, not recognized in nested function

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#3974] opened 2017-11-19 02:10 UTC
Two identical function bodies compile differently, depending on whether they are placed at module level or as a nested function inside the body of another function.

### Repro steps

This was about the simplest example I could see this behavior (examples are simplified and should not be used as real-world code...):

``` f#
// Example 1: proper tail-recursion
let rec isWs1 (s: string) pos = 
    if s.[pos] > ' ' then false
    elif pos < s.Length - 1 then (pos + 1) |> isWs1 s
    else true

let inline isWhitespace1 (s: string) = isWs1 s 0

// Example 2: same code, no tail-recursion
let inline isWhitespace2 (s: string) = 
    let rec isWs2 (s: string) pos = 
        if s.[pos] > ' ' then false
        elif pos < s.Length - 1 then (pos + 1) |> isWs2 s 
        else true

    isWs2 s 0

// Example 3: removed the piping, proper tail-recursion
let inline isWhitespace3 (s: string) = 
    let rec isWs3 (s: string) pos = 
        if s.[pos] > ' ' then false
        elif pos < s.Length - 1 then isWs3 s (pos + 1)
        else true

    isWs3 s 0
```

### Expected behavior

All examples above should give proper tail recursion.

### Actual behavior

No tail recursion for `isWhitespace2` function. This can be seen in the IL (no `br.s` jumps, but calls to `.Invoke()`), or by simply running it:

```
> for i in 0 .. 100000000 do isWhitespace1 "    \n\r \r\td" |>ignore;;
Real: 00:00:01.375, CPU: 00:00:01.372, GC gen0: 0, gen1: 0, gen2: 0
val it : unit = ()

> for i in 0 .. 100000000 do isWhitespace2 "    \n\r \r\td" |>ignore;;
Real: 00:00:40.801, CPU: 00:00:40.841, GC gen0: 5036, gen1: 5035, gen2: 1
val it : unit = ()

> for i in 0 .. 100000000 do isWhitespace3 "    \n\r \r\td" |>ignore;;
Real: 00:00:01.237, CPU: 00:00:01.232, GC gen0: 0, gen1: 0, gen2: 0
val it : unit = ()
```

### Known workarounds

In this specific case, it can be fixed by removing the piping in `(pos + 1) |> isWs2 s`, but this is highly unpredictable and I only found this out by accident. 

### Related information 

My primary concern is that identical code leads to different compiled IL. I can understand that nested functions sometimes need to be compiled differently (i.e., to parameterize the closure variables), but that is not the case here, and even if, the heuristics for finding tail recursion should be the same, I'd think.

Perhaps even more importantly, this simple example would lead to a StackOverflow example given a properly sized input.

* .NET 4.7, F# 4.1, Visual Studio 2017 RTM 15.4.4 (didn't try on latest builds yet)
* Also tested on .NET 4.6, F# 4.0, both x86 and x64 Release builds (same results)

**Comment by abelbraaksma** [comment] 2017-11-20 13:55
@dsyme: why did you mark this "discussion"? You don't think it's a bug? Can you elaborate?

**Comment by dsyme** [comment] 2017-11-21 17:13
Sorry, I should have replied before labelling

Here's how I see things:

* The F# behaviour for tailcalls (probably best described [here](https://blogs.msdn.microsoft.com/fsharpteam/2011/07/08/tail-calls-in-f/) I think ) doesn't guarantee that ``x |> f y`` results in tailcall to ``f``.  It might happen to, because of various optimizations, but it's not guaranteed.  If you want a guaranteed tailcall, use ``f y x``.  

* For a whole range of reasons, we can't guarantee that the same optimizations apply to both module-defined and expression-defined functions.  And we equally can't guarantee that optimizations might not cause additional tailcalls to happen.

Given this, the discussion is really whether we would like to improve the optimizer to make sure a tailcall is taken in the above situation.  But it's not a bug. 

Equally I understand you experienced a change in behaviour when making a reasonable code transformation which you would expect to preserve operational equivalence, and that you experienced it as a bug....

**Comment by dsyme** [comment] 2022-03-31 07:56
Closing per discsussion above, this one isn't considered a bug

**Closed by dsyme** 2022-03-31 07:56 UTC
Labels: Area-Compiler, Feature Improvement
