### ISSUE TITLE
Module aliases don't get imported?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8848] opened 2020-03-31 18:49 UTC
This does work for type aliases, any reason modules don't work similarly? 

```fs
namespace Foo

module Common = 

    module Vopt = ValueOption

    type S = string

module Bar = 
    open Common
    let y = S.Empty
    let x = Vopt.bind // err can't find Vopt
```

https://sharplab.io/#v2:DYLgZgzgPgdghgWwKYQA5wMZIAQDED2+AsAFCkL4AmArsDgML4IUzYC82pp2P2FNdbADV8qAC7thcYNSQB5cQEt8MLiV7YxAT1Q4AypIhiATopgBzNf1o4AQnGOTuvUUlaNmK5zzoStkvQA6AFEEcS1vbF9sAA9JEXFAgCMzSmwAenTsJGNHDDgYAHIJMFThUTEgA===

**Comment by abelbraaksma** [comment] 2020-04-01 11:13
I've always thought that a module alias is essentially a kind of `open`, much like the up and coming "open static classes feature. As such, it's scoped to the current file or module.

That's why on top of each file in my code I have one or two such statements for (very) common modules. It would certainly be nice to have this be treated similarly as a type alias, but I wonder if that can work without breaking existing practices.

**Comment by cartermp** [comment] 2020-04-01 20:53
As per the spec (second 10.4) this is correct behavior:

> Module abbreviations are implicitly private to the module or namespace declaration in which they appear.

So any of these work:

```fsharp
namespace Foo

module Vopt = ValueOption

module Common = 

    type S = string

module Bar = 
    open Common
    let y = S.Empty
    let x = Vopt.bind // err can't find Vopt
```
or 
```fsharp
namespace Foo

module Common = 

    module Vopt = ValueOption

    type S = string
    let x = Vopt.bind

module Bar = 
    open Common
    let y = S.Empty
```

Given that this is by design I'd expect this to be more of a language suggestion. The spec doesn't say why the behavior is the way it is.

**Comment by NinoFloris** [comment] 2020-04-17 15:59
@cartermp Thanks - I somehow missed your reply - good to know it's expected behavior. I would be more than happy with a way to 'explicitly' mark a module alias as public. I'll add the language suggestion in a bit, afterwards I'll close this issue.

**Comment by cartermp** [comment] 2020-07-12 04:19
Closing in favor of a language suggestion.

This one's fun and unintuitive

**Closed by cartermp** 2020-07-12 04:19 UTC
