### ISSUE TITLE
"error FS3160: Problem reading assembly" when referencing Microsoft.AspNetCore.Http.Abstractions package

### ISSUE THREAD

**Issue by NatElkins** [dotnet/fsharp#6090] opened 2019-01-14 09:37 UTC
FSC has an issue reading an assembly that I believe it shouldn't have a problem with.

#### Repro steps

Provide the steps required to reproduce the problem

1. dotnet new console -n Repro -lang F#
2. cd Repro
3. dotnet add package Microsoft.AspNetCore.Http.Abstractions
4. dotnet run

#### Expected behavior

Should build without issue.

#### Actual behavior

I get this error:

```
FSC : error FS3160: Problem reading assembly '/home/nat/.nuget/packages/microsoft.aspnetcore.http.abstractions/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Abstractions.dll': Index was outside the bounds of the array. [/home/nat/Projects/fsharp-asm-repro/Repro/Repro.fsproj]
```

#### Known workarounds

Current version to cause this issue is 2.2.0.  Pegging to 2.1.1 solves the issue.  See nuget.org page here:

https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/

#### Related information 

This occurs using SDK 2.1.503 and 2.2.102.

This package is a transitive dependency of basically every other AspNetCore package so if others are able to reproduce this is going to cause headaches in a big way.  Not sure whether it's a problem of package or FSC.
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.102/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.105 [/usr/share/dotnet/sdk]
  2.1.503 [/usr/share/dotnet/sdk]
  2.2.102 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by cartermp** [comment] 2019-01-30 15:21
I can't seem to reproduce this:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/6309070/51991281-ad29a400-24a2-11e9-9ad2-fbf490e26ccf.png">

Seems to be fine in VS 2019 as well: 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/6309070/51991192-7fdcf600-24a2-11e9-88b1-56960e89bd49.png">

Using SDK 2.2.100

**Comment by cartermp** [comment] 2019-01-30 15:25
Seems to also work for SDK 2.2.103.

**Comment by NatElkins** [comment] 2019-01-30 15:26
@cartermp Are you on Ubuntu?  I don't get this issue when I'm on macOS.

**Comment by cartermp** [comment] 2019-01-30 15:44
Ah, I haven't tried this on Ubuntu. I'll have to break out a VM!

**Comment by cartermp** [comment] 2019-04-28 20:49
@NatElkins I haven't had a chance to try and reproduce this yet. Have you seen this with later SDKs?

**Comment by NatElkins** [comment] 2019-04-29 15:13
Ah...I'm not sure.  I switched to using macOS, haven't used Ubuntu for a few months now.

**Comment by cartermp** [comment] 2019-05-19 23:44
Using the latest 2.2.x on Ubuntu I can't reproduce. I'll close the issue. Not sure what would have caused it before...

<img width="603" alt="image" src="https://user-images.githubusercontent.com/6309070/57989820-4df19e80-7a55-11e9-8655-4d8f5e94912a.png">

**Closed by cartermp** 2019-05-19 23:44 UTC
Labels: needs repro

**Comment by NatElkins** [comment] 2019-05-20 13:17
@cartermp Just to confirm, when doing the repro, did you peg to version 2.2.0 (which is not the latest version)?

**Comment by NatElkins** [comment] 2019-05-20 13:18
I'll try and repro this today again on a Ubuntu machine.

**Comment by cartermp** [comment] 2019-05-20 15:02
This is with version 2.2.0 of the package. It's the latest version now.
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/6309070/58031604-98b2fb00-7ad5-11e9-8ead-b2b5991b2e04.png">
