### ISSUE TITLE
Confusing error message with custom comparison on structs

### ISSUE THREAD

**Issue by mrakgr** [dotnet/fsharp#3429] opened 2017-08-12 13:11 UTC
```
[<Struct;CustomComparison>]
type Node<'a>(expr:'a, symbol:int) = 
    member x.Expression = expr
    member x.Symbol = symbol
    override x.ToString() = sprintf "%A" expr
    override x.GetHashCode() = symbol
    override x.Equals(y) = 
        match y with 
        | :? Node<'a> as y -> symbol = y.Symbol
        | _ -> failwith "Invalid equality for Node."

    interface IComparable with
        member x.CompareTo(y) = 
            match y with
            | :? Node<'a> as y -> compare symbol y.Symbol
            | _ -> failwith "Invalid comparison for Node."
```
The type error in the above fragment reports `Script1.fsx(4,6): error FS0377: This type uses an invalid mix of the attributes 'NoEquality', 'ReferenceEquality', 'StructuralEquality', 'NoComparison' and 'StructuralComparison'` which confused me for a bit since I am using none of the aforementioned attributes.  After poking around for a bit, I added the `CustomEquality` attribute and it compiled. That having said, it was suggested to me that I report this so here it is.

**Comment by dsyme** [comment] 2017-08-14 13:55
Looks like a duplicate of https://github.com/Microsoft/visualfsharp/issues/960 more or less. We should just add CustomComparison and CustomEquality to the list?

**Closed** 2024-01-04 20:06 UTC
Labels: Feature Improvement, Theme-Simple-F#
