### ISSUE TITLE
fsi still uses Thread.Abort to abort an operation

### ISSUE THREAD

**Issue by hez2010** [dotnet/fsharp#10044] opened 2020-08-31 15:43 UTC
Please provide a succinct description of the issue.

**Repro steps**

Provide the steps required to reproduce the problem:

1. dotnet fsi
2. `let rec fib n = if n <= 1 then 1 else fib (n - 1) + fib (n - 2);;`
3. `fib 50;;`
4. press ctrl+c to abort the operaiton

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

**Expected behavior**

The operation should be aborted normally

**Actual behavior**

```
Unhandled exception. System.PlatformNotSupportedException: Thread abort is not supported on this platform.
   at System.Threading.Thread.Abort()
   at FSharp.Compiler.Interactive.Shell.killerThread@1719.Invoke() in F:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 1727
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
And fsi crashed.

**Related information**

Provide any related information (optional):

```
.NET Core SDK (global.json を反映):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.20201
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by cartermp** [comment] 2020-08-31 16:33
Closing as duplicate of #9397

**Closed by cartermp** 2020-08-31 16:33 UTC
