### ISSUE TITLE
AsyncBuilder raises exception when it tries to add same exception in `associationTable`

### ISSUE THREAD

**Issue by vasily-kirichenko** [dotnet/fsharp#3757] opened 2017-10-15 17:50 UTC
Debugging this code:
```fsharp
    let findReferencedSymbolsAsync(document: Document, ...) : Async<unit> =
        asyncMaybe {
            try
                let! sourceText = document.GetTextAsync(context.CancellationToken) ...
         .......
            with e ->
                let _e = e
                raise e
        } |> Async.Ignore
```
I saw this exception:

![image](https://user-images.githubusercontent.com/873919/31587404-0911c8a6-b1ea-11e7-9597-998247122a21.png)

**Comment by matthid** [comment] 2017-10-15 17:54
Well, there is a `try _ with _ -> ()` around so it should actually still work? (but yeah it should be fixed).

**Comment by vasily-kirichenko** [comment] 2017-10-15 17:57
I've no idea what the code does. However, having a `try..with _ -> ()` block is very suspicious anyway.

**Comment by dsyme** [comment] 2021-08-24 00:44
Closing out this old issue - the Add is protected byt the try/with, a code smell but not a bug

**Closed by dsyme** 2021-08-24 00:44 UTC
Labels: Area-Library, Feature Improvement
