### ISSUE TITLE
Nullness issue - NotNullIfNotNullAttribute not respected

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#18019] opened 2024-11-17 22:26 UTC
### Issue description

This code produces a nullness warning:

```fsharp
let htmlEncode (str: string) : string =
    System.Web.HttpUtility.HtmlEncode str
```

> Warning FS3261 : Nullness warning: The types 'string' and 'string | null' do not have compatible nullability.

`HttpUtility.HtmlEncode` is annotated with `[<return:NotNullIfNotNullAttribute ("s")>]`:

![Image](https://github.com/user-attachments/assets/2572efb6-4809-48f0-b082-725a05c19236)

### Choose one or more from the following categories of impact

- [x] Unexpected nullness warning (false positive in nullness checking, code uses --checknulls and langversion:preview).
- [ ] Missing nullness warning in a case which can produce nulls (false negative, code uses --checknulls and langversion:preview).
- [ ] Breaking change related to older `null` constructs in code not using the checknulls switch.
- [ ] Breaking change related to generic code and explicit type constraints (`null`, `not null`).
- [ ] Type inference issue (i.e. code worked without type annotations before, and applying the --checknulls enforces type annotations).
- [x] C#/F# interop issue related to nullness metadata.
- [ ] Other (none of the categories above apply).

### Operating System

Windows (Default)

### What .NET runtime/SDK kind are you seeing the issue on

.NET SDK (.NET Core, .NET 5+)

### .NET Runtime/SDK version

.NET SDK 9.0.100

**Comment by vzarytovskii** [comment] 2024-11-18 07:23
That's not a bug, a known limitation, this will require a full blown flow/scope analysis mechanism in the compiler akin to what Roslyn currently has.

**Comment by T-Gro** [comment] 2024-11-18 09:38
Like Vlad wrote, this is not a bug, it is a Roslyn capability which was not replicated for F#.
The tooling has been updated to show this, since the attribute do form a contract communicated from library authors to consumers.

This attribute is "easier" because it does not affect branching constructs.
I could imagine a lot simplified flow analysis (compared to e.g. NotNullWhen(true)) for APIs having exactly 1 input, 1 output and using NotNullIfNotNullAttribute - F# could pretend the API is almost like an generic T, with two possible instantiations either T=string or T=string|null. But it is still something which would need a separate language suggestion and specification indicating on how it should behave in the presence of type inference (e.g. prefer non nullable if not indicated otherwise?).

In the meantime, I think all of these APIs allow a hopefully small workaround:
```fsharp
let htmlEncode (s:string) = System.Web.HttpUtility.HtmlEncode s |> Unchecked.nonNull
```

**Comment by Martin521** [comment] 2024-11-18 10:25
> `let htmlEncode (s:string) = System.Web.HttpUtility.HtmlEncode s |> Unchecked.nonNull`

or `let htmlEncode (s:string) = System.Web.HttpUtility.HtmlEncode s |> string` ?

**Comment by T-Gro** [comment] 2024-11-18 11:06
> > `let htmlEncode (s:string) = System.Web.HttpUtility.HtmlEncode s |> Unchecked.nonNull`
> 
> or `let htmlEncode (s:string) = System.Web.HttpUtility.HtmlEncode s |> string` ?

Indeed, even better - this will prevent crashes and also allow nullable string on the input, if needed.

**Comment by T-Gro** [comment] 2024-11-25 17:18
Flow analysis is not part of F# NRTs , it is a Roslyn-only feature for C# as of now.
I will close the issue with it.

Adding flow analysis would be a separate (large) change for the compiler - not saying it will never happen, but is not like other bugs.

**Closed by T-Gro** 2024-11-25 17:18 UTC
Labels: Feature Improvement, Needs-Triage, Area-Nullness
