### ISSUE TITLE
(=) uses non-generic equality on custom types

### ISSUE THREAD

**Issue by charlesroddie** [dotnet/fsharp#9398] opened 2020-06-04 21:56 UTC
```fsharp
type T() =
    interface System.IEquatable<T> with member x.Equals _ = true
    override x.Equals _ = failwith "non-generic equality"
    override x.GetHashCode() = 0
T() = T() // System.Exception: non-generic equality
```
The current .Net advice is: [If you implement IEquatable<T>, you should also override ... Equals(Object)](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=netcore-3.1).

The reason for this advice is: [Non-Strongly typed collections and Frameworks don’t use IEquatable](https://blog.paranoidcoding.com/2009/01/15/if-you-implement-iequatable-t-you-still-must-override-object-s-equals-and-gethashcode.html).

However now  [DE0006: Non-generic collections shouldn't be used](https://github.com/dotnet/platform-compat/blob/master/docs/DE0006.md).

So the expectation is that if you don't use .Net collections that predate generics, which you shouldn't do, then non-generic equality will not be used in preference to generic equality.

**Comment by abelbraaksma** [comment] 2020-06-04 22:40
I think an attempt to fix this was here, but fell short of completion as of yet: https://github.com/dotnet/fsharp/pull/6175. In the last comments, the problem is explained, though I don't fully understand it.

Also, this thread is related: https://github.com/dotnet/fsharp/issues/9348.

**Comment by TIHan** [comment] 2020-06-05 00:09
Related: https://github.com/dotnet/fsharp/issues/526

**Comment by manofstick** [comment] 2020-06-09 03:33
@charlesroddie 

This is kinda fixed by [this PR](https://github.com/dotnet/fsharp/pull/9404), although it mightn't work 100% how you want it!

In the above example, you would have to add a `[<Sealed>]` attribute, because the comparer otherwise doesn't know if a derived class would implement `IStructuralEquatable`, and hence it falls back to the current way f# does it.

**Comment by abelbraaksma** [comment] 2020-06-10 11:28
@manofstick, so this fix works correctly for records age unions, they are sealed, and for value types, they cannot be overridden.

That raises the question that, by the time you fall through, you're either having a non sealed type that doesn't implement `IEquatable`, or you have a type that implements it. Wouldn't a type test by that time solve the issue? Boxing then doesn't matter anymore, because you're going to call a virtual method anyway, or is it not possible to implement such path deterministically?

**Comment by dsyme** [comment] 2020-08-24 19:10
This is by design, the F# spec makes it clear that in the worst case `Equals` gets used for the implementation of `a = b`

**Closed by dsyme** 2020-08-24 19:10 UTC

**Comment by charlesroddie** [comment] 2020-09-02 15:30
> in the worst case Equals gets used for the implementation of a = b

Why would this be the worst case? The type implements `System.IEquatable<T>` so there isn't a need for the worst-case Object.Equals is there?

**Comment by charlesroddie** [comment] 2022-03-31 10:15
The corresponding language suggestion is https://github.com/fsharp/fslang-suggestions/issues/816
