### ISSUE TITLE
VS handling of overloaded operators is inconsistent

### ISSUE THREAD

**Issue by jimfoye** [dotnet/fsharp#10272] opened 2020-10-18 18:21 UTC
Take a look at this screenshot of some custom operators. Note that the first two are only partially colorized as a custom operator, but the third one is completely. 

![image](https://user-images.githubusercontent.com/4249676/96376364-2c15b300-1144-11eb-9791-5b4bc915eae9.png)

In other files, if I use the third operator, it is colorized correctly, and I can hover over it and see the /// comment, and I can navigate to its definition with F12. But not for the first two. 

In this screenshot, you can see a use of the first operator - note the color. As noted above, expected behavior (e.g. F12) is missing.

![image](https://user-images.githubusercontent.com/4249676/96376381-42bc0a00-1144-11eb-8474-c844a247e124.png)

But, all three custom operators work as expected (in appearance and behavior) in Rider (Windows and Linux).

**Comment by cartermp** [comment] 2020-10-18 18:37
This looks like the same root cause as https://github.com/dotnet/fsharp/issues/3462, where the operator starting with `>` isn't really recognized properly by the IDE. I'll close this in favor of that and make a note in the issue that this is an additional outcome.

**Closed by cartermp** 2020-10-18 18:37 UTC

**Comment by jimfoye** [comment] 2020-10-18 18:39
@cartermp Yep, thanks.
