### ISSUE TITLE
Infers incorrect record type even though it seems to be fully specified

### ISSUE THREAD

**Issue by cmeeren** [dotnet/fsharp#8110] opened 2020-01-07 11:46 UTC
Consider the following code:

```f#
type Person = { Name: string }
type PersonSearchFilter = { Name: string option }

type ApiAttribute<'entity>() =

  member val Getter: (unit -> 'entity -> string) option = None with get, set

  member this.WithGetter(f: unit -> 'entity -> string) =
    this.Getter <- Some f

  member this.WithGetter(f: 'entity -> string) =
    this.Getter <- Some (fun () a -> f a)


type ApiAttributeCreator<'entity>() =

  member _.Create() =
    ApiAttribute<'entity>()

type ApiResource<'entity>() =
  
  static member Attribute = ApiAttributeCreator<'entity> ()


type ApiPerson() =
  inherit ApiResource<Person>()

  static member name =
    ApiPerson.Attribute
      .Create()
      .WithGetter(fun ctx p -> p.Name)

  static member name2 =
    ApiPerson.Attribute
      .Create()
      .WithGetter(fun p -> p.Name)
```

It fails to compile at the bottom because it infers the type of `p` to be `PersonSearchFilter`, and not `Person`.

![image](https://user-images.githubusercontent.com/7766733/71893119-fff7eb00-314a-11ea-9bb4-939e9a9d59ce.png)

This error should not be there. As far as I can see, the way the code is structured, the type is fully specified to be `Person`: `ApiPerson.Attribute` is an instance of `ApiAttributeCreator<Person>()`. Its `Create` method then returns `ApiAttribute<Person>()`, whose `WithGetter` then accepts a `Person -> string` argument.

The overloads are an important part of the problem. If one of the `WithGetter` functions are named differently, the code compiles. (In other words, either of the overloads works fine on its own.)

**Comment by charlesroddie** [comment] 2020-01-08 19:53
> As far as I can see, the way the code is structured, the type is fully specified to be Person

It would be great to have a way to switch off all unreliable inference from the F# type-checker. Including inferring `fun x -> x+x` to be `int->int` and guesses about records based on some of the property names.

Here there is a guess that something is a `PersonSearchFilter` which is incorrect. This guess could be muted by first using a correct inference that the only `Person -> string option` and `unit -> Person -> string option` are the possible candidates, and the most likely response to this issue will probably be to do that.

However if we want type inference that we can rely on and reason about, it's better to remove unreliable guesses everywhere, not only in cases where they are provably wrong.

If that is done then this code would still fail to compile, but just with a different error. The candiates are `Person->string option` and `unit -> Person -> string` and, with inference running from left to right, it has no way to tell whether `p` is a `unit` that is later being misused or a `Person`.

**Comment by cmeeren** [comment] 2020-01-09 13:23
> The candiates are `Person->string option` and `unit -> Person -> string`

I don't understand. Do you mean `Person->string` and `unit -> Person -> string`?

**Comment by smoothdeveloper** [comment] 2020-01-09 14:03
@charlesroddie the code in the issue reproduces without record as well, so it is not related on two records having same field names.

Your suggestion about turning off some of the type inference heuristics is interesting nonetheless, it may be worth to file it, with the detail of which heuristics should be disabled.

Here is some reduced reproduce code with the same issue as in original post:

```fsharp
type Person(name: string) =
  member x.Name = name

type ApiAttribute<'entity>() =
  static member WithGetter(f: unit -> 'entity -> string) = ()
  static member WithGetter(f: 'entity -> string) = ()

let test () =
  let appAttr1 = ApiAttribute<Person>.WithGetter(fun () p -> p.Name)
  let appAttr2 = ApiAttribute<Person>.WithGetter(fun p -> p.Name) // this one fails to resolve
  ()
``` 

It is likely to be method overloads taking `FSharpFunc` that causes the issue.

Changing the signatures to 
```fsharp
type ApiAttribute<'entity>() =
  static member WithGetter(f: Func<unit,'entity ,string>) = ()
  static member WithGetter(f: Func<'entity,string>) = ()
```

and the compiler is able to pick the correct overload without changing the remaining code.

**Comment by smoothdeveloper** [comment] 2020-01-09 18:38
@cmeeren, I think this is normal.

I'm not able to figure out what are the parts of the spec in § 14.4 Method Application Resolution explicitly rejects this, but I kind of understand why F# can't pick the overload, it is possible for the lambda to return another function that would match a subsequent overload, even though in this case, `unit` can't have a property called `Name` being a function that would match another overload, there is a point where looking ahead into the lambda has to stop and having annotations is probably better.

If this is intended as I kind of understand now, maybe:
* the spec should precise such restriction on overloaded methods taking single argument of first class functions
* the design guidelines should discourage overloaded methods taking a single first class function as parameter

As is, I'm personally fine with the compiler asking for type annotation in this case, unless there is a clear algorithm that would allow the inference to work, it could say try to resolve on lambda argument count and disfavor or plainly disallow lambda returning a lambda that would match any overload if there is no type annotation, but I don't think that complexity affords much.

Hope this is making some sense.

A potential workaround is to define delegates with the different arity / argument types, I think this would work if you want to retain the same feel of the API as you intended.

**Comment by cartermp** [comment] 2020-01-09 18:57
Overloading based on lambdas is very very limited in F#. This isn't a case of a buggy type inference heuristic as @charlesroddie suggests; it's actually an extremely difficult problem space that leads to needing to solve the 3SAT problem. C# avoids to explosion in compile times by simply picking something and moving on, which results in a very touchy part of a compiler that is prone to breaking. So while I'm sure a patch of sorts could get added here to "make it work" it won't solve the general problem space.

> However if we want type inference that we can rely on and reason about, it's better to remove unreliable guesses everywhere, not only in cases where they are provably wrong.

This doesn't really make much sense to do. Firstly, this would break untold amounts of F# code since what you're referring to as unreliable guesses aren't unreliable guesses but simply decisions made by the compiler that are reproducible. Finding a way to turn off type inference for these kinds of cases is probably equivalent to "just making it work" in all cases.

**Comment by jmarolf** [comment] 2020-01-09 19:11
> C# avoids to explosion in compile times by simply picking something and moving on

Slight correct, C# actually solves 3SAT for overload resolution it just doesn't synthesize conversions from one delegate type to another. I think F#'s approach here is fine. The insane complexity of overload resolution in C# is something the team is constantly paying for.

**Comment by cartermp** [comment] 2020-07-12 18:48
Closing this as by design  - I do not anticipate overloading based on lambdas to ever be in F#. In this case a type annotation will be required.

**Closed by cartermp** 2020-07-12 18:48 UTC
Labels: Resolution-By Design
