### ISSUE TITLE
Task ate my data! Unexpected results at runtime. No errors in core stack.

### ISSUE THREAD

**Issue by simontreanor** [dotnet/fsharp#13404] opened 2022-06-28 17:57 UTC
**Description of the issue**

Converting an existing async function to the new F# 6 task CE throws up some unexpected and undesirable behaviour:
- Runtime failure, not compiler failure
- No errors thrown in core stack at all, just lost data

**Steps required to reproduce the problem:**

The attached ZIP file contains two .NET Interactive Notebooks, test_async.dib, which is the original function using async, and test_task.dib, which uses the new task CE. Running them yields the results described. The data array gets swallowed up.

[test.dib.zip](https://github.com/dotnet/fsharp/files/9003534/test.dib.zip)

Other notes:
- Weird error if you remove unused fromAccount variable declaration:
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed

**Expected result**

`True, [ ( 2022-06-28 18:06:32Z, 3, 4, 5, { Some(6): Value: 6 }, { Some(1): Value: 1 }, True, ( { Some(7): Value: 7 }, True, 2022-06-28 18:06:32Z ) ), ( 2022-06-28 18:06:32Z, 3, 4, 5, { Some(6): Value: 6 }, { Some(1): Value: 1 }, True, ( { Some(7): Value: 7 }, True, 2022-06-28 18:06:32Z ) ), ( 2022-06-28 18:06:32Z, 3, 4, 5, { Some(6): Value: 6 }, { Some(1): Value: 1 }, True, ( { Some(7): Value: 7 }, True, 2022-06-28 18:06:32Z ) ) ], 3`

**Actual result**

`True, null, 3` 

**Known workarounds**

1. Change task to async -> Works, but reverts to slower workflow. The code has no real async operations.
2. Move mapPrioritiesTransfers tasks inside match conditions -> Works, but high overhead to convert code
3. remove minOrder and set isPrio to true -> Works, but altered behaviour

There is no clear understanding of when we need a workaround for what, leading to a lack of ability to trust the new task-construct, so it seems rather fragile.

**Related information**

* Win 11
* .NET SDK 6
* F# 6.0
* VS2022 and VSCode

**Comment by Thorium** [comment] 2022-06-28 21:25
If I create a new console app and add paste the code there (with `open System` and `printfn "%A" test.Result`) the observations:
- Happens on Release mode only, not on Debug. Happens systematically, not random.
- Seems to happen on both .NET6 (Core) and .Net Framework 4.7.2

Could it be that if you have multiple taskbuilders, or the task continuation changes the execution thread, somehow something here is not thread-safe or overwrites the state of another task? 

tasks.fs type TaskBuilder, `RunDynamic(code: TaskCode<'T, 'T>)` what is this `sm.ResumptionDynamicInfo.ResumptionData <- null` ?

**Comment by dsyme** [comment] 2022-06-29 13:04
@Thorium reports that he's using latest SDK which I assume means `6.0.301` or later

I can confirm that a workaround is to move synchronous code using `Array.map` out of the `task { ... }`.  You can also workaround by using this at the top of your file:

```
module Array =
    [<MethodImpl(MethodImplOptions.NoInlining)>]
    let map f xs = FSharp.Collections.Array.map f xs
```

Though you may want to use this code instead, so you can scan for `Array.map` and force the use of `Array.mapFixed`:
```fsharp
module Array =
    [<MethodImpl(MethodImplOptions.NoInlining)>]
    let mapFixed f xs = FSharp.Collections.Array.map f xs

    [<Obsolete("Do not use Array.map in this project because of https://github.com/dotnet/fsharp/issues/13404", true)>]
    let map f xs = FSharp.Collections.Array.map f xs
```

**Comment by isaacabraham** [comment] 2022-06-29 13:22
So is this actually a bug  or just that it's using an early version of F#6 which had that issue with Array.map (which was my first thought when seeing this) - has it been reproed in e.g. FSI directly or VS/VSCode etc.?

**Comment by dsyme** [comment] 2022-06-29 13:35
@isaacabraham This certainly looks like another variation of the bug of #12359, unfixed as yet. Also https://github.com/dotnet/fsharp/pull/12337 may be relevant. 

The circumstances appear to be:
* A single task has multiple `Array.map` or other functions that are inlined to imperative loops
* These loops manipulate a struct type like Guid
* You get the warning `warning FS3511: This state machine is not statically compilable. A resumable code invocation at '(50,12--50,16)' could not be reduced. An alternative dynamic implementation will be used, which may be slower. Consider adjusting your code to ensure this state machine is statically compilable, or else suppress this warning.`

The underlying problem is that Array.map is inlined to an imperative `while` loop. This appears to be interacting with logic for zero-initialization of locals of struct type like `Guid`. From playing around it seems the problem only occurs when there are multiple inlined loops working on type `Guid` - indeed even more specific than that. It's quite tricky to get a really small repro though we will work on it.

**Comment by dsyme** [comment] 2022-06-29 13:39
BTW I haven't yet found a repro that doesn't involve ` FS3511` being generated. Please let me know if you do.

**Comment by Thorium** [comment] 2022-06-29 17:06
> > I'm on the latest version of everything.
> > […](#)
> 
> If it's a notebook, the kernel _can_ be using an old `FSharp.Compiler.Service` package.
> 

notebook is just a detail to reproduce the issue, this happens also new non-notebook.

**Comment by dsyme** [comment] 2022-06-29 17:24
Smallish repro that gives a `peverify` failure: https://gist.github.com/dsyme/9523e4738707311dd5bc4b3933689f32.  I have a fix for this.

**Comment by Thorium** [comment] 2022-07-04 11:00
That's excellent, thanks.
I hope the state machine will get fixed at some point too.
Getting "warning FS3511: This state machine is not statically compilable." has a feeling that I have to please the compiler, not like the typical FSharp where the compiler is there to help me.

**Comment by dsyme** [comment] 2022-08-16 11:05
The lack of static complation of some tasks is being tracked here: https://github.com/dotnet/fsharp/issues/12839

**Closed by dsyme** 2022-08-16 11:05 UTC
Labels: Bug, Area-Compiler-StateMachines
