### ISSUE TITLE
F# gives important structs explicit size causing coreclr to pessimize codegen for them

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/fsharp#15174] opened 2023-05-02 17:34 UTC
`Microsoft.FSharp.Core.FSharpValueOption<T>` and `Microsoft.FSharp.Core.FSharpResult<T, TError>` are both marked in metadata as having an explicit size of 1. This causes the JIT to believe that the padding in these types has to be considered significant which leads to significant codegen pessimizations for many cases.

Would it be possible for the F# compiler to stop marking these structs as having explicit size?

**Comment by vzarytovskii** [comment] 2023-05-03 10:09
> `Microsoft.FSharp.Core.FSharpValueOption<T>` and `Microsoft.FSharp.Core.FSharpResult<T, TError>` are both marked in metadata as having an explicit size of 1. This causes the JIT to believe that the padding in these types has to be considered significant which leads to significant codegen pessimizations for many cases.
> 
> Would it be possible for the F# compiler to stop marking these structs as having explicit size?

HM, that looks wrong, let me check why do we set the explicit size in the first place

**Comment by vzarytovskii** [comment] 2023-05-03 10:21
Hm, it seems we make the decision here:
https://github.com/dotnet/fsharp/blob/124ca6bd0257ac8c594abe0390befd0d039d7f13/src/Compiler/CodeGen/IlxGen.fs#L11190-L11201

**Comment by En3Tho** [comment] 2023-05-03 10:57
Or the condition is incomplete

**Comment by vzarytovskii** [comment] 2023-05-03 11:58
> Or the condition is incomplete

It's likely wrong, it's pretty much a duplicate of the isstruct check above

**Closed** 2023-05-04 13:32 UTC
Labels: Needs-Triage
