### ISSUE TITLE
ReadOnlySpan extensions don't show up in completion in some positions

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet/fsharp#10524] opened 2020-11-22 13:52 UTC
**Repro steps**

1. Create new .NET 5 F# project
2. Write the following code:
   ```fsharp
   open System

   let compare a b =
       ReadOnlySpan(a).Seque
   ```
3. Press the completion button (`Ctrl+Space`) at the end of `Seque`

**Expected behavior**

Method `SequenceEqual` should be suggested (since it is exported from `System.MemoryExtensions`.

**Actual behavior**

No suggestions:
![image](https://user-images.githubusercontent.com/92793/99905535-f1cfa080-2d03-11eb-9a0d-ccd4f0d9d4b4.png)

If I write the method name manually, the code may be successfully compiled; e.g. this:
```fsharp
open System

let compare a b =
    ReadOnlySpan(a).SequenceEqual(b)
```

So, there're no `open`s required; it's just missing from the completion when it should be available.

**Related information**

* OS: Windows 10
* .NET Runtime: .NET 5
* Editing Tools: Visual Studio 2019 16.8.1; Rider 2020.3 Nightly (both share the same behavior)

This probably has something to do with #5858: `ReadOnlySpan` is already known to cause completion problems.

**Comment by cartermp** [comment] 2020-11-22 23:26
Yeah, this is likely the same root cause as #5858. I'll keep this open since it surfaces as a seemingly different issue though.

**Comment by KevinRansom** [comment] 2021-07-21 18:26
Obsolete filtering might need updating to exclude spans.

**Comment by dsyme** [comment] 2022-04-04 15:28
Closing as a duplicate of https://github.com/dotnet/fsharp/issues/5858

**Closed by dsyme** 2022-04-04 15:28 UTC
Labels: Bug, Area-Compiler, Impact-Low
