### ISSUE TITLE
Symbols: local functions don't provide parameter names and declaring type info

### ISSUE THREAD

**Issue by auduchinok** [dotnet/fsharp#13381] opened 2022-06-24 17:38 UTC
Consider 3 function declarations:

```fsharp
let a x = ()

type T() =
    let b x = ()

do
    let c x = ()
    ()
```

`a` provides info about its parameters:

<img width="365" alt="Screenshot 2022-06-24 at 19 24 58" src="https://user-images.githubusercontent.com/3923587/175611675-3c71146c-f3f4-4da3-aac2-c2c18d099f94.png">

`b` and `c` don't:

<img width="386" alt="Screenshot 2022-06-24 at 19 26 14" src="https://user-images.githubusercontent.com/3923587/175611871-198c2bec-c236-45d6-8961-d51004368f86.png">

Without this info it's problematic to provide rich tooling experience, as the features like Parameter Info popup need the parameter names. In addition to that, `b` doesn't provide its declaring entity.

The apparent difference between `a` and `b` or `c` is that the latter don't return any data from their `TypedTree.ValRef.ValReprInfo` properties. The data seems to be kept somewhere, as (at least) `b` has its parameter name [compiled](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfAsAKGAUwC4AICGOAHjgLw4AUAlGjalgJ4AOGOAKlaWjtzprgEZFSFaqjQwA9lx58cAYyFkq07gqpA===).

@dsyme Do you have an idea of how the missing data could be added?

**Comment by auduchinok** [comment] 2022-06-24 17:40
It looks like #13061 is caused by the same problem, though this issue is about the missing parameter data, and the other one  sounds like it's about the presentation improvement (since parameter can indeed not have a name, and backticks aren't good there).

**Comment by kerams** [comment] 2022-06-24 17:54
A dupe of https://github.com/dotnet/fsharp/issues/7080.

**Comment by psfinaki** [comment] 2022-06-27 16:23
@auduchinok @kerams thanks for your investigations! Will take this as well.

**Closed** 2022-06-27 16:25 UTC
Labels: Bug, Regression
