### ISSUE TITLE
Upgraded VS to 17.5.3 issue disappeared but then suddenly popped up again

### ISSUE THREAD

**Issue by halcwb** [dotnet/fsharp#14974] opened 2023-03-24 19:34 UTC
Please provide a succinct description of the issue.

I upgraded VS to version 17.5.3 and issue #14948 seemed to be resolved. But then suddenly popped up again. Now I can't get rid of this annoying error messsage appearing all over the fsi output.

Provide the steps required to reproduce the problem:

1. Open up an fsx file
2. Write some code
3. Load this in the fsi

**Expected behavior**

Running the code and showing the results

**Actual behavior**

Issue #14948 appears again.

**Known workarounds**

????

**Related information**

Microsoft Visual Studio Community 2022
Version 17.5.3
VisualStudio.17.Release/17.5.3+33516.290
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

ASP.NET and Web Tools   17.5.318.41597
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.318.41597
Azure App Service Tools v3.0.0

C# Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

ILSpy.AddIn   1.0
Integration of the ILSpy Decompiler into Visual Studio.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by vzarytovskii** [comment] 2023-03-27 10:55
Duplicate of #14948

**Closed by vzarytovskii** 2023-03-27 10:55 UTC
Labels: Bug, Needs-Triage
