### ISSUE TITLE
Microsoft.Windows.SDK.Contracts reference fails due to file path error

### ISSUE THREAD

**Issue by reinux** [dotnet/fsharp#7727] opened 2019-10-14 09:37 UTC
Microsoft.Windows.SDK.Contracts, which in turn references a bunch of .winmd files, fails to reference those .winmd files correctly. If I'm understanding the error messages correctly, it seems to be trying to be feeding a full path when it's expecting just a filename.

The files in question do exist where it's referencing.

**Repro steps**

1. Create a new .NET Core 3 Windows project
2. Add a reference to Microsoft.Windows.SDK.Contracts
3. Attempt to build

Repro: [BluetoothTest2.zip](https://github.com/dotnet/fsharp/files/3723795/BluetoothTest2.zip)

**Expected behavior**

It compiles

**Actual behavior**

A bunch of errors like this one:

`1>FSC : error FS0078: Unable to find the file 'C:\Users\rei\.nuget\packages\microsoft.windows.sdk.contracts\10.0.18362.2005\ref\netstandard2.0\Windows.WinMD' in any of C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0\ref\netcoreapp3.0 C:\Users\rei\source\repos\BluetoothTest2\BluetoothTest2 C:\Users\rei\.nuget\packages\fsharp.core\4.7.0\lib\netstandard2.0`

* Operating system: Windows 10 1903
* .NET Runtime kind .NET Core 3
* Editing Tools Visual Studio 2019

**Comment by cartermp** [comment] 2019-10-14 18:41
Confirmed failed with the latest Windows 10 SDK.

**Comment by reinux** [comment] 2019-10-14 23:03
I wonder if there are any workarounds for this?

**Comment by BillHally** [comment] 2019-11-25 22:52
I've looked into this a bit, and there's 2 key factors:

1. When the F# compiler is passed the `--simpleresolution` flag it causes the path errors
2. Even if compiled successfully (by not passing the `--simpleresolution` flag), running code which depends on a `.winmd` file fails at runtime because the assembly references do not have their [ContentType](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname.contenttype?view=netcore-3.0) set to [WindowsRuntime](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblycontenttype?view=netcore-3.0).

I've created the repository [Microsoft.Windows.SDK.Contracts.Issue](https://github.com/BillHally/Microsoft.Windows.SDK.Contracts.Issue) which demonstrates that resolving these issues (with some hacky workarounds) results in a working application:

1. Fiddles with `msbuild` so that when the F# compiler is invoked `--simpleresolution` isn't passed
2. Uses a little console app which uses `Mono.Cecil` to set the referenced `.winmd` assembly reference `AssemblyName.ContentType` values to `WindowsRuntime`

There's a `Powershell` script you can run which builds the console app, runs it to show it fail at runtime, fixes it, then runs it again to show it working.

Note that it only builds when built from the command line with `msbuild` - neither building in Visual Studio or on the command line using `dotnet build` work.

**Comment by reinux** [comment] 2019-11-25 23:52
@BillHally Interesting... I think I can use this for now.

Thanks for finding a workaround!

**Comment by Enigmatrix** [comment] 2020-05-16 03:18
Hi, is there any way to build via just `dotnet build` with this issue currently (the workaround is a bit ... icky)?

**Comment by cartermp** [comment] 2020-05-22 18:36
Hey folks, with the recently-published new SDK package things like this should be available in F# now: https://www.nuget.org/packages/Microsoft.Windows.SDK.NET

There's a small demo project showing some of this here: https://github.com/AngelMunoz/WinRTFs/tree/master/Core

**Comment by BillHally** [comment] 2020-05-22 21:35
Thanks @cartermp - I've just confirmed that fixes the issue I demonstrated in the repository above.

**Comment by Enigmatrix** [comment] 2020-05-23 03:39
same from here, thanks!

**Comment by cartermp** [comment] 2020-05-23 17:51
Thanks for confirming. I'll resolve this as external, but please do ping back if you see an issue. Some of the folks working on the team would like to hear if anything goes wrong, and I can direct them here if that is the case.

**Closed** 2020-05-23 17:52 UTC
Labels: Area-Compiler, Resolution-External, bug
