### ISSUE TITLE
FSC locks when compiling project after upgrading VS to 17.4.x

### ISSUE THREAD

**Issue by ReedCopsey** [dotnet/fsharp#14336] opened 2022-11-16 19:59 UTC
Please provide a succinct description of the issue.

When upgrading to 17.4.1, VS causes one of our F# projects to lock up indefinitely when trying to compile.

Provide the steps required to reproduce the problem:

1. Upgrade VS to 17.4.1 from 17.3.x
2. Compile

**Expected behavior**

This compiles normally in previous releases, including VS 2019.

**Actual behavior**

Compilation hangs during the compile of one specific F# project within the sln.

**Known workarounds**

None

**Related information**

Part of large (non public) solution, with quite a few dependencies. Using .net 4.7.2 as the target.

**Comment by vzarytovskii** [comment] 2022-11-16 20:02
From discussions on slack: it seems FSC task just hangs after starting. On both CLI build as well as VS build.

**Comment by dsyme** [comment] 2022-11-17 21:04
Do we have a repro for this? Or a stack?

**Comment by ReedCopsey** [comment] 2022-11-17 21:09
We've been working on this in slack. Did provide a dump of FSC while hung.

**Comment by vzarytovskii** [comment] 2022-11-17 21:35
> Do we have a repro for this? Or a stack? 

No repro yet. Got a dump of FSC.exe, but can't publish it here, since not public.

**Comment by vzarytovskii** [comment] 2022-11-30 18:24
So, according to the dump, it locks in `ilread.fs`:
https://github.com/dotnet/fsharp/blob/186d3f6ce267c27f8acaa2c8f3df1472bf2a88bf/src/Compiler/AbstractIL/ilread.fs#L1374-L1375

Might be related to https://github.com/dotnet/fsharp/pull/13821?

@auduchinok does this ring a bell by any chance?

I was not, however, reproduce it myself. Will look at internal stack later today or tomorrow.

**Comment by vzarytovskii** [comment] 2022-11-30 18:25
**Update:**
Here's the full stack:
```
>	FSharp.Compiler.Service.dll!FSharp.Compiler.AbstractIL.ILBinaryReader.seekReadHasCustomAttributeIdx(FSharp.Compiler.AbstractIL.ILBinaryReader.ILMetadataReader ctxt, FSharp.Compiler.IO.ReadOnlyByteMemory mdv, ref int addr) Line 1375	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.AbstractIL.ILBinaryReader.seekReadCustomAttributeRow(FSharp.Compiler.AbstractIL.ILBinaryReader.ILMetadataReader ctxt, FSharp.Compiler.IO.ReadOnlyByteMemory mdv, int idx, ref FSharp.Compiler.AbstractIL.ILBinaryReader.CustomAttributeRow attrRow) Line 1499	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.AbstractIL.ILBinaryReader.seekReadIndexedRowsRange<FSharp.Compiler.AbstractIL.ILBinaryReader.CustomAttributeRow, FSharp.Compiler.AbstractIL.ILBinaryReader.TaggedIndex<FSharp.Compiler.AbstractIL.BinaryConstants.HasCustomAttributeTag>, FSharp.Compiler.AbstractIL.IL.ILAttribute>(int numRows, bool binaryChop, FSharp.Compiler.AbstractIL.ILBinaryReader.ISeekReadIndexedRowReader<FSharp.Compiler.AbstractIL.ILBinaryReader.CustomAttributeRow, FSharp.Compiler.AbstractIL.ILBinaryReader.TaggedIndex<FSharp.Compiler.AbstractIL.BinaryConstants.HasCustomAttributeTag>, FSharp.Compiler.AbstractIL.IL.ILAttribute> reader) Line 1304	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.AbstractIL.ILBinaryReader.seekReadIndexedRowsByInterface<FSharp.Compiler.AbstractIL.ILBinaryReader.CustomAttributeRow, FSharp.Compiler.AbstractIL.ILBinaryReader.TaggedIndex<FSharp.Compiler.AbstractIL.BinaryConstants.HasCustomAttributeTag>, FSharp.Compiler.AbstractIL.IL.ILAttribute>(int numRows, bool binaryChop, FSharp.Compiler.AbstractIL.ILBinaryReader.ISeekReadIndexedRowReader<FSharp.Compiler.AbstractIL.ILBinaryReader.CustomAttributeRow, FSharp.Compiler.AbstractIL.ILBinaryReader.TaggedIndex<FSharp.Compiler.AbstractIL.BinaryConstants.HasCustomAttributeTag>, FSharp.Compiler.AbstractIL.IL.ILAttribute> reader) Line 1312	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.AbstractIL.IL.ILAttributesStored.GetCustomAttrs(int metadataIndex) Line 1231	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.CompilerImports.GetCustomAttributesOfILModule(FSharp.Compiler.AbstractIL.IL.ILModuleDef ilModule) Line 828	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.CompilerImports.RawFSharpAssemblyDataBackedByFileOnDisk.FSharp.Compiler.CompilerConfig.IRawFSharpAssemblyData.get_HasAnyFSharpSignatureDataAttribute() Line 927	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.CompilerImports.TryRegisterAndPrepareToImportReferencedDll@2142-2.Invoke(FSharp.Compiler.CompilerConfig.ProjectAssemblyDataResult contentsOpt) Line 2180	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.BuildGraph.Bind@61-1<System.__Canon, System.__Canon>.Invoke(System.__Canon x) Line 63	F#
 	FSharp.Core.dll!Microsoft.FSharp.Control.FSharpAsync.StartImmediateAsTask<FSharp.Compiler.CompilerImports.TcImports>(Microsoft.FSharp.Control.FSharpAsync<FSharp.Compiler.CompilerImports.TcImports> computation, Microsoft.FSharp.Core.FSharpOption<System.Threading.CancellationToken> cancellationToken) Line 1788	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.BuildGraph.NodeCode.RunImmediate<FSharp.Compiler.CompilerImports.TcImports>(FSharp.Compiler.BuildGraph.NodeCode<FSharp.Compiler.CompilerImports.TcImports> computation, System.Threading.CancellationToken ct) Line 129	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.Driver.main1(Internal.Utilities.Library.CompilationThreadToken ctok, string[] argv, FSharp.Compiler.CodeAnalysis.LegacyReferenceResolver legacyReferenceResolver, bool bannerAlreadyPrinted, FSharp.Compiler.AbstractIL.ILBinaryReader.ReduceMemoryFlag reduceMemoryUsage, FSharp.Compiler.CompilerConfig.CopyFSharpCoreFlag defaultCopyFSharpCore, FSharp.Compiler.DiagnosticsLogger.Exiter exiter, FSharp.Compiler.Driver.IDiagnosticsLoggerProvider diagnosticsLoggerProvider, Internal.Utilities.Library.Extras.DisposablesTracker disposables) Line 646	F#
 	FSharp.Compiler.Service.dll!FSharp.Compiler.Driver.CompileFromCommandLineArguments(Internal.Utilities.Library.CompilationThreadToken ctok, string[] argv, FSharp.Compiler.CodeAnalysis.LegacyReferenceResolver legacyReferenceResolver, bool bannerAlreadyPrinted, FSharp.Compiler.AbstractIL.ILBinaryReader.ReduceMemoryFlag reduceMemoryUsage, FSharp.Compiler.CompilerConfig.CopyFSharpCoreFlag defaultCopyFSharpCore, FSharp.Compiler.DiagnosticsLogger.Exiter exiter, FSharp.Compiler.Driver.IDiagnosticsLoggerProvider loggerProvider, Microsoft.FSharp.Core.FSharpOption<Microsoft.FSharp.Core.FSharpFunc<FSharp.Compiler.CompilerImports.TcImports, Microsoft.FSharp.Core.Unit>> tcImportsCapture, Microsoft.FSharp.Core.FSharpOption<Microsoft.FSharp.Core.FSharpFunc<System.Tuple<FSharp.Compiler.CompilerConfig.TcConfig, FSharp.Compiler.TcGlobals.TcGlobals, string, FSharp.Compiler.AbstractIL.IL.ILModuleDef>, Microsoft.FSharp.Core.Unit>> dynamicAssemblyCreator) Line 1189	F#
 	fscAnyCpu.exe!FSharp.Compiler.CommandLineMain.main(string[] argv) Line 97	F#

```

**Comment by auduchinok** [comment] 2022-12-01 10:04
> @auduchinok does this ring a bell by any chance?

Not really, sadly. My PR was about a related thing indeed, but I don't see how it could make things lock here

**Comment by vzarytovskii** [comment] 2022-12-12 23:31
> So, according to the dump, it locks in `ilread.fs`:
> https://github.com/dotnet/fsharp/blob/186d3f6ce267c27f8acaa2c8f3df1472bf2a88bf/src/Compiler/AbstractIL/ilread.fs#L1374-L1375
> 
> Might be related to https://github.com/dotnet/fsharp/pull/13821?
> 
> @auduchinok does this ring a bell by any chance?
> 
> I was not able, however, reproduce it myself. Will look at internal stack later today or tomorrow.

Okay, with help of @ReedCopsey, we were able to test the compile with that change reverted, and it does fix it.
I will prepare the revert for 17.5 and will investigate why it could've been failing.

Cc @auduchinok

**Comment by auduchinok** [comment] 2022-12-13 15:43
@vzarytovskii That's unfortunate, I'm really sorry for that.

Would it be possible to find out on what assembly it locks and look into it further? I'd be happy to look into it with you if you wish.

**Comment by vzarytovskii** [comment] 2022-12-13 15:57
> @vzarytovskii That's unfortunate, I'm really sorry for that.
> 
> Would it be possible to find out on what assembly it locks and look into it further? I'd be happy to look into it with you if you wish.

No worries, I will try to figure out what handles it holds from the dump and will ask folks for the assembly

**Comment by vzarytovskii** [comment] 2023-01-05 14:28
The revert was inserted into 17.5, I am going to close it, as it should be fixed when the new VS is released.

**Closed** 2023-01-05 14:30 UTC
Labels: Bug, Impact-High
