### ISSUE TITLE
After trying to run a modified compiler:  Could not load file or assembly 'fsiAnyCpu' in FSI window

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9630] opened 2020-07-06 13:48 UTC
Dumping this here as contributors like myself may run into this: FSI doesn't work when you change the compiler.

**Repro steps**

Change something in the compiler (in my case, I changed something in the lexer) and Ctrl-F5 with `VisualFSharpFull` as start-up project. This creates a new VS 2019 instance that loads the locally changed F# binaries.

However, in FSI this gives:

```f#
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'fsiAnyCpu, Version=10.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.AppDomain.ExecuteAssemblyByName(AssemblyName assemblyName, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(AssemblyName assemblyName, String[] args)
   at Sample.FSharp.Compiler.Interactive.Main.MainMain(String[] argv)
```

**Expected behavior**

Not sure, as this error is not entirely unexpected, but perhaps we could add a line in the CONTRIBUTORS.md to explain how to test, if the "run everything in a new VS" doesn't work. Or maybe this error is only specific to FSI, and we should mention that it cannot be tested that way.

**Actual behavior**

The error as above

**Known workarounds**

I'm working on finding a workaround. Probably something simple.

**Comment by abelbraaksma** [comment] 2020-07-06 14:02
Workaround: select `fsiAnyCpu` as startup. Well, that was easy ;).

**Comment by kevmal** [comment] 2020-12-29 16:54
Turning off "Shadow copy assemblies" seems to be another workaround. The `ExecuteAssemblyByName` call is this one

https://github.com/dotnet/fsharp/blob/668642b5b73b5d860260cc1f09c9a043d6971a2c/src/fsharp/fsi/fsimain.fs#L331-L342

**Comment by KevinRansom** [comment] 2023-06-09 23:52
Closing this:  it is by design.

If you want to start a Visual Studio Instance and debug self-built fsi or fsc then

- Set VisualFSharpDebug as the startup project.  use Ctrl+F5 to start a new VS.
The VisualFSharpFull vsix contains Ide assemblies only and is primarily used to deliver into VisualStudio.

The DevGuide instructions are here:  https://github.com/dotnet/fsharp/blob/main/DEVGUIDE.md#developing-the-f-tools-for-visual-studio

![image](https://github.com/dotnet/fsharp/assets/5175830/6d0e765d-005c-4357-9738-d22998e23819)

**Closed by KevinRansom** 2023-06-09 23:52 UTC
Labels: Contributor Pain, Impact-Low
