### ISSUE TITLE
"Open declaration can be removed" - but actually it cannot

### ISSUE THREAD

**Issue by forki** [dotnet/fsharp#3347] opened 2017-07-18 07:48 UTC
#### Repro steps

1. clone https://github.com/fsprojects/Canopy.Mobile
2. run paket restore
3. open sln in VS2017
4. open Canopy.Mobile.fs

![image](https://user-images.githubusercontent.com/57396/28306055-26d09c42-6b9e-11e7-8246-9cac92838d3d.png)

If you accept then you get compile errors

#### Expected behavior

Don't show the suggestion

/cc @vasily-kirichenko

**Comment by vasily-kirichenko** [comment] 2017-07-18 08:01
Why it cannot be removed?

**Comment by forki** [comment] 2017-07-18 08:03
because then compile errors happen

**Comment by forki** [comment] 2017-07-18 08:03
it's a false postive

**Comment by matthid** [comment] 2017-07-18 08:08
@forki I guess @vasily-kirichenko is asking for the compiler error or the statement which needs the `open` ;)

**Comment by forki** [comment] 2017-07-18 08:10
typical name resolutions issues.

![image](https://user-images.githubusercontent.com/57396/28306864-48fa0b02-6ba1-11e7-805f-bccf75bb8bd8.png)

**Comment by vasily-kirichenko** [comment] 2017-07-18 08:22
No, I'm asking for the source code of a symbol that makes the open statement needed.

**Comment by vasily-kirichenko** [comment] 2017-07-18 08:23
(I guess it's the exception definition)

**Comment by forki** [comment] 2017-07-18 08:23
see screenshot

**Comment by forki** [comment] 2017-07-18 08:24
/// Contains canopy specific exception
        module canopy.mobile.Exceptions

        open System

        type CanopyException(message) = inherit Exception(message)
        type CanopyElementNotFoundException(message) = inherit CanopyException(message)

^^ is the other file

**Comment by vasily-kirichenko** [comment] 2017-07-18 08:31
Thanks.

**Comment by vasily-kirichenko** [comment] 2017-07-18 08:34
Ah, relative opens. They are not supported. Use full ns/module names.

**Comment by forki** [comment] 2017-07-18 08:42
What do you mean they are not supported? That's proper F# - the tooling should adjust and not my code, right? If there is no way to make it work with relative opens then it should be disabled for relative opens, right?

Also not that òpen Wait` is not greyed out

**Comment by vasily-kirichenko** [comment] 2017-07-18 09:06
Right :) The problem is that opens are not symbols, they are text from untyped AST. However, if it works properly for `Wait`, it maybe the case that exceptions are not processed.

**Comment by vasily-kirichenko** [comment] 2017-07-18 09:09
Sorry, Ctrl+F5 crashes VS immediately on my machine :))

**Comment by dsyme** [comment] 2017-07-19 23:21
> What do you mean they are not supported? That's proper F# - the tooling should adjust and not my code, right? If there is no way to make it work with relative opens then it should be disabled for relative opens, right?

Perhaps a code fix to turn relative opens into fully-qualified opens.

**Comment by BentTranberg** [comment] 2017-07-23 18:56
I believe this is an exact duplicate of the older #3306.

**Comment by cartermp** [comment] 2017-10-07 03:18
This issue seems to be mitigated.  You can still get a lightbulb which will remove it, but `Exceptions` is not greyed out anymore on 15.5.3.

**Comment by bender2k14** [comment] 2019-06-11 15:40
What is a "relative open"?

**Comment by bender2k14** [comment] 2020-08-06 12:23
Issue #7111 was just marked as a duplicate of this one.  That issue includes a very minimal working example.

The consensus here seems to be that the present issue is related to the concept of a "relative open", which is contrasted with a "fully-qualified open".  I have only ever heard these terms in this issue.

Is there documentation that explains what these terms mean?  If not, can someone explain what these terms mean in this issue?

Because of my lack of knowledge (both generally of F# and specifically about the answer to those two questions) and the not-so-minimal working example provided in the present issue, I am unable to verify for myself that issue #7111 is a duplicate of this one.

**Comment by abelbraaksma** [comment] 2020-08-06 13:33
@bender2k14, a relative open is when you don't fully specify the whole namespace, or the namespace before the module. A fully qualified open is when, in contrast, you do specify the FQN (fully qualified name) in the open statement.

```
open System // fqn
open IO   // relative, will raise FS0783, which shows these terms
```

**Comment by cartermp** [comment] 2020-08-06 14:47
Slight correction, the analyzer itself lives here: https://github.com/dotnet/fsharp/blob/master/src/fsharp/service/ServiceAnalysis.fs#L12

As mentioned earlier in this issue there is a problem related to the data that is being operated on here. It can likely be fiddled with a bit.

**Comment by bender2k14** [comment] 2020-08-06 17:05
Thanks @abelbraaksma.  That is very helpful.

> I think it would be good to collect a couple of simple repros so that working on the issue in a PR becomes easier.

Are there any existing unit tests for this unused open analyzer?  If so, I might be able to add tests for the cases that have been reported in this and the linked issues.

**Comment by abelbraaksma** [comment] 2020-08-06 17:24
I assume there are, but where exactly I don't know. I haven't played with this part of the tooling yet.

**Comment by cartermp** [comment] 2020-08-07 04:28
In this case there are some fairly comprehensive tests here: https://github.com/dotnet/fsharp/blob/master/vsintegration/tests/UnitTests/UnusedOpensTests.fs

**Comment by bender2k14** [comment] 2020-08-12 00:47
> I think it would be good to collect a couple of simple repros so that working on the issue in a PR becomes easier. The code that does this currently is in `UnusedOpensDiagnosticAnalyzer.fs`.

I tried and failed to reproduce the bugs reported in this issue and the two linked issues.  Here is the environment I used.
Operating system: Windows 10
.NET Runtime kind: .NET Core 3.1
Editing Tools: Visual Studio Enterprise 2019 version 16.6.5

1. I followed the steps in the first comment (https://github.com/dotnet/fsharp/issues/3347#issue-243628567) of this issue.  No open was reported as unused...not even `open Exception`.
2. Linked issue #3306: Not surprising that I couldn't reproduce because it was already claimed to be fixed in https://github.com/dotnet/fsharp/issues/3306#issuecomment-334906650.
3. Linked issue #7111: This was the issue I created that was marked as a duplicate of this one.

Seems like all these bugs are fixed.  I recommend closing this issue.

> In this case there are some fairly comprehensive tests here: https://github.com/dotnet/fsharp/blob/master/vsintegration/tests/UnitTests/UnusedOpensTests.fs

Thanks @cartermp.  I was so excited to contribute something to F# that I confirmed that the 67 unused open tests pass on my machine before confirming that I had a MWE to make into a test.   I see there are more open issues in this repo, so I will investigate them now.

**Comment by cartermp** [comment] 2020-08-12 00:57
Thanks @bender2k14 - I also failed to reproduce the issue in the latest internal preview build of the F# tools. It _could_ be that something changed since this report was initially filed that influences the lack of repro, but looking at the history of the codebase it doesn't appear to be the case. I'll close this one out.

**Closed by cartermp** 2020-08-12 00:57 UTC
Labels: Area-IDE Language Service, Urgency-Soon, bug
