### ISSUE TITLE
Locals windows empty

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#8820] opened 2020-03-27 20:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/625085/locals-windows-empty.html)._

---
With a .Net Core 2.1 F# solution the local window is empty when a breakpoint is hit. 

Stepping to the next line populates the window and all local variables are shown.

---
#### Visual Studio Feedback System on 6/27/2019, 01:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/7/2019, 06:34 PM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .

---
### Original Solutions
(no solutions)

**Comment by cartermp** [comment] 2020-03-28 00:19
This is most likely a duplicate of https://github.com/dotnet/fsharp/issues/7456

Not the same repro, but it's pretty much the same behavior.

**Closed by cartermp** 2020-03-28 00:19 UTC
Labels: Resolution-Duplicate
