### ISSUE TITLE
Internal Error destNullableTy

### ISSUE THREAD

**Issue by tick-rick** [dotnet/fsharp#8646] opened 2020-03-02 04:55 UTC
Issue moved from https://github.com/ionide/ionide-vscode-fsharp/issues/1315
A bug appears (entire file red squiggles, see screenshot) when using OpenApiClientProvider. On hovering the error is `internal error: destNullableTy: not a Nullable type (Failure) F# Compiler(73)`. This does not occur when running dotnet build/run, so it appears that it may be ionide or FSAC related.

**To Reproduce**
Steps to reproduce the behaviour:
1. dotnet new console -lang F# && dotnet add package SwaggerProvider
2. Save this to folder as json [schema.txt](https://github.com/ionide/ionide-vscode-fsharp/files/4265308/schema.txt)
3. Use the following repro code:
```
open SwaggerProvider
type Api = OpenApiClientProvider<"schema.json">
let h = Api.Heartbeat([||], None)
```
4. dotnet build and reload vscode

**Expected behaviour**
There should be no errors.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/50384876/75512179-af16bb80-5a44-11ea-93b3-6d862b2b5378.png)

**Environment (please complete the following information):**
 - OS:  Debian
 - Ionide version: 4.6.2
 - VSCode version: 1.42.1
 - dotnet SDK version: 3.1.102

**Additional context**

**Comment by cartermp** [comment] 2020-03-02 19:26
Thanks, yes this is a bad bug. It paints the whole editor red, which some of these internal errors can do.

cc @TIHan @jonsequitur

**Comment by cartermp** [comment] 2020-03-02 21:35
This is seen in the desktop compiler as well, but not the CoreCLR one. So there's definitely a compiler bug here.

**Comment by cartermp** [comment] 2020-03-02 21:45
I can actually get this to crash VS (internal dogfood) every time just by typing this out:

```fsharp
open SwaggerProvider
type Api = OpenApiClientProvider<"schema.json">
let h = Api.Heartbeat([||])
```

We should get to the bottom of that, otherwise this will be a serious regression.

**Comment by forki** [comment] 2020-03-02 22:30
Regression? Is there a version that did work?

**Comment by tick-rick** [comment] 2020-03-02 22:32
Hello, I had this working in 3.1.101

**Comment by forki** [comment] 2020-03-02 22:39
Urgs. I hopes it's not because of my optimizations.

**Comment by tick-rick** [comment] 2020-03-02 22:50
I was trying to rollback to 3.1.101 to confirm, however its not so trivial to get fsautocomplete\ionide to point to old sdk (seems to ignore global.json)

**Comment by baronfel** [comment] 2020-03-02 23:05
> however its not so trivial to get fsautocomplete\ionide to point to old sdk (seems to ignore global.json)

What do you mean here? There's no way in Ionide to typecheck with an older SDK, because we use the FSharp.Compiler.Service for this and it's not tied to any particular SDK. We  _do_ use the latest SDK you have installed for typechecking F# Scripts, but that's just to find versions of FSharp.Core and the BCL libraries to reference, never for files in projects.

**Comment by tick-rick** [comment] 2020-03-02 23:16
Ah, thanks for the clarification. I have failed getting an older SDK installed and working without the above error, but others may have more luck. I most certainly had type provider working on .netcore, but maybe something else changed.

**Comment by TIHan** [comment] 2020-03-03 00:17
@forki I think you are fine.

My guess it could be related to the optionals interop, but I need to confirm.

**Comment by tick-rick** [comment] 2020-03-03 00:32
@TIHan not sure if this helps but when I remove the uuid type from schema, the error goes away. I believe uuid is generated as `Guid option`, so the options interop thing makes sense

**Comment by TIHan** [comment] 2020-03-03 01:02
@tick-rick , yes. It has to do with using F#'s Option type in C#/IL declared methods that are optional. :)

Example:
```csharp
using Microsoft.FSharp.Core;

namespace CSharpTest
{
    public static class Test
    {
        public static void M(FSharpOption<int> x = null) { }
    }
}
```

```fsharp
open System
open CSharpTest

let optionValue = Some 1

Test.M(x = 1)
```

This will result in the same error.

I will have a fix soon.

**Comment by tick-rick** [comment] 2020-03-03 01:35
For anyone looking for a workaround for ionide, it seems if you right click extension -> Install another version -> install 4.6.0, it will avoid the bug from nuking entire project

**Comment by baronfel** [comment] 2020-03-03 01:40
@tick-rick that makes sense, when you rolled back Ionide in that way you reverted to an older version of the compiler services bundled with it.

I'm treating this bug as pretty high priority, so as soon as the F# team is happy with a fix, I'll work with @Krzysztof-Cieslak to get an updated Ionide for you and others impacted.

**Comment by TIHan** [comment] 2020-03-03 02:07
This is a little tricky and may take a bit to get a fix.

**Comment by cartermp** [comment] 2020-03-03 22:56
Fixed in #8655

**Closed by cartermp** 2020-03-03 22:56 UTC
Labels: Area-Compiler, bug, regression

**Comment by kerams** [comment] 2020-03-19 09:52
I take it the fix did not make it to .NET 5 SDK. Seeing the same thing in Visual Studio now.

**Comment by cartermp** [comment] 2020-03-19 15:03
That's correct. It should be in the next preview.
