### ISSUE TITLE
Unclear error, FS3204: If a union type has more than one case and is a struct, then all fields within the union type must be given unique names

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#3648] opened 2017-09-25 23:52 UTC
> FS3204: If a union type has more than one case and is a struct, then all fields within the union type must be given unique names

That error is thrown for a construct like this:

```
[<Struct>]
type A = B of int | C of int
```

Could we update that error to say what is actually wrong or somehow make it clearer? I have no idea what is wrong with the code above, as the two cases have unique names `B` and `C`.

**Comment by thinkbeforecoding** [comment] 2017-09-26 07:26
B and C are the cases, the fields are int and ... int... but you can give them names:
```
[<Struct>]
type A = B of b: int | C of c: int
```
So it should solve your problem, but it's true that the error message could be clearer.

**Comment by thinkbeforecoding** [comment] 2017-09-26 07:30
I see with a `sizeof<A>` that there is no field compaction in this case, event if both `b` and `c`  fields are int, the size is 12 = 3 * `sizeof<int>`: one int for the case, one int for `b` and one for `c`.
In .net, reference fields cannot be merged with other fields, but value fields can.

**Comment by thinkbeforecoding** [comment] 2017-09-26 07:32
What would be a better error message to suggest the solution ?

**Comment by abelbraaksma** [comment] 2017-09-26 19:53
@thinkbeforecoding, thanks for taking the time to look into this and explaining it. The current error is puzzling (and to be honest, I don't understand why `Struct` requires field names, I thought these were nothing more than decoration and shouldn't change the semantics).

Note that the documentation is confusing, as [it says this](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/discriminated-unions):

> As of F# 3.1, you can give an individual field a name, but the name is optional, even if other fields in the same case are named.

But given that this error is legitimate (I mean, I'm sure there's some plausible reason for it), I'd suggest something like the following:

## Situation one, no field names at all or missing field names

> FS3204: Missing field names for cases 'Foo', 'Bar' in struct union type; union types that are a struct and that have more than one case must contain unique field names for each case that wraps a type, as with [<Struct>]type A = B of fieldx: int | C of fieldy: double | D.

## Situation two or more non-unique field names

> FS3204: Field names 'field1', 'field2' or not unique in struct union. Union types that are a struct and that have more than one must contain unique field names for each case that wraps a type, as with [<Struct>]type A = B of fieldx: int | C of fieldy: double | D.

## Situation three, non-unique names and missing names

Both errors are thrown.

If it is not possible to differentiate between these cases, or if it is not possible to enumerate the field names that are non-unique, we could consider a different message. But I think what helps in either case is simply adding an example (some other errors do that too). And by adding "that wraps a type" (or equivalent) we emphasize what we mean with "field names" (which may not be clear on the onset).

**Comment by thinkbeforecoding** [comment] 2017-09-26 20:07
>  I thought these were nothing more than decoration and shouldn't change the semantics

Actually when doing reflection on CLR types generated by a union without field names, the type has properties named Item1, Item2 ...
When you give names to Union type fields, they're named accordingly...
I think this is why... 
when using reference Unions, each subclass can have the same properties Item1.. but with as struct, there is a single type in the end, and it cannot have several different properties Item1...

**Comment by abelbraaksma** [comment] 2017-09-26 22:35
@thinkbeforecoding, I'm not sure I follow your reasoning. Because with that idea, you wouldn't be allowed to have the names `Item1` and `Item2`. I'd assume they must be unique to the type, and `Item1` and `Item2` are also unique to the type.

Just saying that, when declared as a `struct`, it _should_ be possible to autogen these fieldnames. But I'm drifting away from my original issue. It is what it is and I'm glad the feature is there (though haven't used it much, I must add). But I do think we should do something about the error.

**Comment by kspeakman** [comment] 2019-03-12 18:08
I ran into this today and had to search for the error code. In normal (non-struct) usage of DUs, a dev gets accustomed to the field name on the union type not mattering. And in fact, I don't even think of it as a field. (That's really an underlying implementation detail.) So upon reading the message, I thought "My union cases all have unique names?!".

Anyway, I would suggest the error message mention that the case values have to be named with unique names rather than "fields". A longer term goal would be for the dev to not have to worry about naming values at all.

**Comment by forki** [comment] 2019-03-12 18:39
Do you have a small sample code that shows the issue?

Kasey Speakman <notifications@github.com> schrieb am Di., 12. März 2019,
19:08:

**Comment by kspeakman** [comment] 2019-03-12 19:31
The OP has a simple repro: 

```fsharp
[<Struct>]
type A = B of int | C of int
// produces error FS3204
```

If you are wanting context as to why, I'm using it for parsing. I am using simple DUs and then using struct attribute to avoid heap allocations. For example:

```fsharp
[<Struct>]
type StringPhase =
    | InString
    | InEscape
    | InByte1
    | InByte2 of a:int
    | InByte3 of b:int
    | InByte4 of c:int
// forced to arbitrarily label a, b, c here
// they could all reuse the same underlying field
```

Then here is the bit that uses the cases with data. These are just the branches that parse the unicode escaped characters within a string.

```fsharp
let rec loop phase sb state =
    let append c = StringBuilder.appendChar c sb
    let nState = State.consume 1 state
    // <snip>
    match phase, c with
    ...
    | InString, '\\' ->
        loop InEscape sb nState
    | InEscape, 'u' ->
        loop InByte1 sb nState
    | InByte1, x when isHex x ->
        // hexToInt 'f' = 0000 0000 0000 1111
        // <<< 12       = 1111 0000 0000 0000
        let code = hexToInt c <<< 12
        loop (InByte2 code) sb nState
    | InByte2 code, x when isHex x ->
        let nCode = hexToInt c <<< 8 + code
        loop (InByte3 nCode) sb nState
    | InByte3 code, x when isHex x ->
        let nCode = hexToInt c <<< 4 + code
        loop (InByte4 nCode) sb nState
    | InByte4 code, x when isHex x ->
        let ord = hexToInt c + code
        let ch = System.Convert.ToChar(ord)
        loop InString (append ch) nState
    | (InByte1 | InByte2 _ | InByte3 _ | InByte4 _), _ ->
        Error InvalidUnicodeSequence
```

**Comment by abelbraaksma** [comment] 2019-03-13 01:07
@forki, have a look at my original report above, it's a very simple sample. Basically, any struct union without explicit labels (which are optional according to the docs), throws this confusing error. 

It seems reasonable that labels ought to be optional, but that's a feature suggestion. Given that they aren't optional for struct unions (apparently, or I've totally missed the mark), the error should say so. It currently doesn't and confuses programmers new to the 'required optional labels' of struct unions.

A more elaborate example and discussion on the perceived uselessness of this requirement was given by @kspeakman above, which I think makes a case for lifting this error entirely.

**Comment by jimfoye** [comment] 2022-09-14 02:46
Hello from the future (5 years). Bumped into this today and the message was so puzzling, but fortunately this GitHub issue is the top search result on Google.

**Comment by voronoipotato** [comment] 2022-10-04 23:09
We just hit this in a demo for our F# meetup today :) .

**Comment by T-Gro** [comment] 2022-10-05 08:16
IMO the best return of investment would be to change the name-generation strategy in case of structs - BUT, that would break backwards compatibility if those fields are used outside of F#. Not good.

I am thinking about having different messages depending on using / not using named fields.

My current understanding is that if a person is already using named fields, the message is not bad (?).
But in case of using autogenerated field names only, the message does not help at all (backed by the common understanding of field naming being optional in DUs).

Proposal:

FS3204: "If a union type has more than one case and is a struct, then all fields within the union type must be given unique **field** names, *and not rely on auto-generated field names.
Instead of '[<Struct>] type A = B of int | C of int' (no field names given), write '[<Struct>] type A = B of b: int | C of c: int' (unique field names 'b' and 'c' assigned).*"

**Comment by edgarfgp** [comment] 2022-10-05 08:42
@T-Gro Once you understand the error it make sense , but at fist glance is confusing :) 

Some related issues and suggestions: 

-  https://github.com/dotnet/fsharp/issues/9368,
-  https://github.com/fsharp/fslang-suggestions/issues/699 
- https://github.com/dotnet/fsharp/issues/5215.
- https://github.com/dotnet/fsharp/pull/11718
- https://github.com/dotnet/fsharp/issues/5236
- https://github.com/dotnet/fsharp/issues/13897

**Comment by T-Gro** [comment] 2022-10-05 08:45
Exactly, should be optimized for a person who did not see it before, and maybe even for a person who might not know that fields in DUs can have optinal names.

What do you think of the message proposal? Or is there a better one?

**Comment by edgarfgp** [comment] 2022-10-05 09:00
I think your message proposal is more clear :) .  I think we should use the DU field range to report error to make it more clear where the issue is , No the type one that is more ambiguous ?

**Comment by T-Gro** [comment] 2022-10-05 09:02
True and a good idea. Issue is in the fields, not in the DU type

**Comment by edgarfgp** [comment] 2022-10-05 09:10
Hopefully https://github.com/fsharp/fslang-suggestions/issues/699 gets implemented one day . to remove this limitation :)

**Comment by charlesroddie** [comment] 2022-10-13 20:24
### If the word "field" is problematic, then change it or add docs to it

One possible difficulty is the use of the word "field". It may not be clear that the named arguments are "fields".
This isn't a lack of clarity as this is what the documentation says they are. For example documentation on names of DU arguments calls them fields: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/discriminated-unions#remarks

It might however be too much an implementation detail to expose to users. In that case the correct fix would be to choose a replacement name for "field" in DU arguments and to use it consistently in error messages and other documentation.

It might instead be that field is too obscure, in which case a message might link to documentation about fields in DU cases.

### If the word "field" is OK, then there is no issue to fix in this thread

If the world field is OK, then there is no problem here and no need to adjust the error message based on this thread.

```
Situation one, no field names at all or missing field names
Situation two or more non-unique field names
Situation three, non-unique names and missing names
```

This adds unnecessary complexity. Not only are there three errors now to manage, but each error is more complex to understand than the original. "Must have unique field names" clearly implies that there must be field names, and that these field names must be unique.

**Closed** 2022-10-18 09:41 UTC
Labels: Feature Improvement, Area-Diagnostics

**Comment by abelbraaksma** [comment] 2022-10-21 22:38
I agree, it’s a tricky message to improve. But it also hints at an implementation detail (like you mentioned) that’s totally superfluous. Just as with normal DUs, the compiler can freely come up with field names. That won’t be a breaking change, as currently, that’s not possible to do.

I thought there was already an issue or proposal for this, but I couldn’t readily find it. Also, typing this on mobile, so browsing is a bit limiting. Either way, the best fix for this confusing error is not having this error at all.

**Comment by abelbraaksma** [comment] 2022-10-21 22:41
Oh wait, nvm, this has meanwhile been fixed. Awesome 👏 @edgarfgp and @T-Gro. For posterity, if I read it correctly, the new message is a vast improvement:

> If a multicase union type is a struct, then all union cases must have unique names. For example: 'type A = B of b: int | C of c: int'.

**Comment by voronoipotato** [comment] 2022-10-25 12:50
Honestly I expected it to have come up with field names based on the case name by default unless explicitly overridden with different field names, but with the new error message it is at least intuitive to resolve.

**Comment by Xyncgas** [comment] 2024-01-20 08:41
```B of b :b | C of c :c``` is better
