### ISSUE TITLE
Evaluating a task that is still executing locks FSI

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/fsharp#5885] opened 2018-11-11 13:16 UTC
Using FSI 10.2.3 and F#4.5, executing the following trivial code as a block locks FSI indefinitely every time:

```fsharp
let wc = new System.Net.WebClient()
let x = wc.DownloadStringTaskAsync(System.Uri "https://compositional-it.com")
x.Result
```

However, if you manually wait a few seconds until the download string task has completed and *then* call `x.Result`, FSI doesn't lock.

I seem to recall chatting with @dsyme about this (or even raising an issue about it) many moons ago and the general consensus being it was "by design".

With `Task<'T>` becoming more pervasive in the F# world, especially with things like TaskBuilder and the potential for Task becoming a first class citizen of FSharp.Core, I think that this issue should be revisited; the issue manifests itself only in FSI, not in a proper app AFAIK, and doesn't even block the IDE (I've tried Ionide and VS) - it's only in the actual REPL that things get stuck.

**Comment by matthid** [comment] 2018-11-11 13:37
I think the problem is that fsi is basically a UI-Thread/Event-loop (to support winform and stuff ootb). 
If you run the above code in a UI thread the thread will "block" and wait for the result to be available.
At the same time I'd assume the finished download-task tries to finalize itself on the Thread it started in (the UI thread).

Can someone confirm this assumption (so we have an analysis for discussion)?

I'm not sure you can "fix" this in the FSI code. Potentially related https://github.com/Microsoft/visualfsharp/issues/4354 and https://github.com/fsharp/fsharp/issues/115 (which is imho very similar pitfall to this but has been fixed)

**Comment by cartermp** [comment] 2018-11-11 15:58
I don't think this is by design since it locks up indefinitely. I would expect it to block on any further input until the string is downloaded. I get the feeling this is as old as the FSI window in VS.

**Comment by isaacabraham** [comment] 2018-11-11 16:31
The temporary blocking wouldn't be a problem - I should have made clear that it locks indefinitely, which is the bug In referring to. @matthid doing the same with Async.RunSynchronously works as expected (even if the async is actually just an AwaitTask).

**Comment by dsyme** [comment] 2018-11-16 14:37
This comment is relevant: https://github.com/Microsoft/visualfsharp/issues/4354#issuecomment-365681192

IIRC it is indeed hard to fix this - either we run the `task.Result` code on the GUI thread (risking blocking) or change to a background thread (making FSI scripting for GUI/WinFormsWPF/... purposes much, much harder).

**Comment by isaacabraham** [comment] 2018-12-20 10:59
Note the workaround identified [here](https://github.com/Microsoft/visualfsharp/issues/4354#issuecomment-365681192) does not *appear* to work (using the Cosmos DB SDK in FSI).

**Comment by dsyme** [comment] 2020-08-26 14:48
THis works in `dotnet fsi` without any specific event loop installed:

```
let wc = new System.Net.WebClient()
let x = wc.DownloadStringTaskAsync(System.Uri "https://www.compositional-it.com/wp-content/cache/all/index.html")
x.Result
```

It also works on .NET Framework with `fsi --gui-`

For .NET Framework F# Interactive with the GUI I believe we can't really do anything - we are both starting the task and evaluating the blocking `x.Result` on the GUI thread and the resumption on the GUI thread can't complete.  It's really annoying but there's nothing we can do about it.

I'll close this as by design.  The issue will resurface if we support single-threaded GUI execution in `dotnet fsi`

**Closed by dsyme** 2020-08-26 14:48 UTC
Labels: Area-IDE FSI, bug
