### ISSUE TITLE
Operators can't be discovered through Intellisense

### ISSUE THREAD

**Issue by mexx** [dotnet/fsharp#876] opened 2016-01-15 09:50 UTC
In contrast to other values in scope, operators are not shown in Intellisence.

I know that custom operators should be used sparingly, but if a library provides a set of them, the only way to find which operators are present is to study the documentation or source code of the library.

**Comment by dsyme** [comment] 2016-01-19 15:38
IIRC this was originally by design.  However they should I suppose be listed as 

    Module.``( + )`` etc.  

I don't know if listing operator members defined on types is a great idea - seeing 

    VectorType.``(+)``

or

    VectorType.op_Addition

doesn't fill me with joy

**Comment by cloudRoutine** [comment] 2016-01-19 17:36
If the approach of surrounding operators with double backticks were employed, would that be the canonical representation of operators in intellisense as opposed to the way they can currently be called for from unopened modules and the types within them?

```fsharp
module ExOp =
    let (<@>) a b = Checked.(+) a b

    type ExType() =
        static member (<@>) (a,b) = Checked.(+) a b
        
module Use =

    let res1 = ExOp.(<@>) 22 22
    let res2 = ExOp.ExType.(<@>) (22,22)
```

**Comment by mexx** [comment] 2016-01-19 20:22
> doesn't fill me with joy

As it stand here, it's pretty subjective. Could you explain, why there is no joy? What are the reasons to hide the operators defined on types?

About the canonical name, my suggestion is to use the name of the operator that was used to define it. The author of the library mostly refers to the operator in the documentation by the name she given while defining it, so to remove friction and obtain consistency let's use the original.
Note: I'm unsure whether the original name is preserved for addition etc.

**Comment by cloudRoutine** [comment] 2016-01-19 23:11
@mexx regarding naming that's aready the case
> Other combinations of operator characters that are not listed here can be used as operators and have names that are made up by concatenating names for the individual characters from the following table. For example, +! becomes op_PlusBang.
 
[Overloaded Operator names](https://msdn.microsoft.com/en-us/library/dd233204.aspx#Anchor_3)

**Comment by dsyme** [comment] 2016-01-20 05:35
@cloudRoutine - yes, you're right, no backticks

@mexx - yes, you're right, there is a degree of subjectivity in this. 

We would be showing the operator for discoverability purposes, but would be offering a somewhat undesirable autocomplete - we don't actually want people to scatter Foo.(@) calls over their code, which is what they would inevitably do more of if offered the autocompletes. We'd be offering a legitimate but non-idiomatic autocomplete as the only assist for the language feature.  

 It's possible listing operators in the QuickInfo hint for a module may be better (we don't currently show any content in QI for modules)

**Comment by mexx** [comment] 2016-01-20 06:09
IMHO Autocomplete is for discovery not to guide the user how to write idiomatic code, that what a linter is for. Btw. sometimes it's practical to use `Foo.(@)`.
Further when writing `value |`, why shouldn't the Autocomplete offer a list of all in scope operators starting with `|`?
Note: I know that the Autocomplete in C# doesn't show the operators either, but first there are no custom operators definable and second we can do better than C#.

IMHO QuickInfo hint is not the right place, its size is limited. What if a module defines many operators, like FSharp.Core?

**Comment by dsyme** [comment] 2016-01-21 00:37
Well, I'm wrong - types currently do provide ``op_XYZ`` completions, e.g.

    System.TimeSpan.op_Addition
    System.Uri.op_Equality

shown at the bottom of the list.

Given this, it does seem consistent to offer either the same for modules, or change both to use the symbolic names where they exist.

@mexx Would you like to try a PR for this?  It looks like the relative filtering code is here:

``
                    // Filter out operators (and list)
                    let items = 
                        // Check whether this item looks like an operator.
                        let isOpItem(nm,item) = 
                            match item with 
                            | [Item.Value _]
                            | [Item.MethodGroup(_,[_])] -> 
                                (IsOpName nm) && nm.[0]='(' && nm.[nm.Length-1]=')'
                            | [Item.UnionCase _] -> IsOpName nm
                            | _ -> false              

                        let isFSharpList nm = (nm = "[]") // list shows up as a Type and a UnionCase, only such entity with a symbolic name, but want to filter out of intellisense

                        items |> List.filter (fun (nm,items) -> not (isOpItem(nm,items)) && not(isFSharpList nm)) 
``

You might need to add a call to ``DecompileOpName``.

**Comment by cloudRoutine** [comment] 2016-01-21 06:36
I wonder if something similar to the approach we use for Unicode glyphs in Ionide might be useful.  

![](http://i.imgur.com/x14msiR.png)

Each glyph has a named assigned to it which is used to filter the auto completion and the partially typed name is replaced with the glyph upon completion. 
Perhaps operators could be listed similarly with a name defined in an attribute not unlike `[<CompiledName("FuncName")>]`. In most libraries I've encountered the functionality of operators are most often implemented in a named function. This would allow the operator and named function to show up next to each other in the auto completion list.

I'm not sure how Xamarin or the other editors list items for auto complete, but in Ionide we don't use the Visual Studio ordering. Instead we order using case insensitive levenshtein distance.

**Comment by cartermp** [comment] 2020-09-03 03:15
I think this should largely be by design because custom operators are so rare compared to the basic arithmetic operators like `+`, and any overloaded arithmetic operator for custom types. Getting a completion trigger every time you type `+` would be pretty annoying.

One alternative would be to trigger completion on the 2nd character in an identifier only if the first character was an operator character and the second one is too. The downside is that you already need a way to know which first character to type, so it doesn't solve the problem of knowing which operators are available to you.

**Comment by cartermp** [comment] 2021-03-16 06:19
Gonna by-design this. We don't really ever want to trigger completion on operators. Custom operators should naturally be discoverable as a part of a DSL as well.

**Closed by cartermp** 2021-03-16 06:19 UTC
Labels: Area-IDE Language Service, Feature Improvement, Resolution-By Design
