### ISSUE TITLE
Find references files three times too many when dual targeting

### ISSUE THREAD

**Issue by bender2k14** [dotnet/fsharp#9750] opened 2020-07-22 18:17 UTC
Please provide a succinct description of the issue.

When dual targeting, the "find references" feature should return four hits (1 definition + 1 usage) x (2 targets) but the usage contribution from usage references are three times too large.

Provide the steps required to reproduce the problem:

1. Unzip [this repo](https://github.com/dotnet/fsharp/files/4961654/MWE.zip)
2. Open in Visual Studio
3. Right-click on `bar`
4. Select "Find All References"

Here is the code that in that repo.

Project file:
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;net461</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>
</Project>
```

F# code file:
```F#
module Foo
  let bar = ()
  let baz = bar
```

**Expected behavior**

There are four search results:
1. line 2 where `bar` is defined for `net461`
2. line 2 where `bar` is defined for `netcoreapp3.1`
3. line 3 where `bar` is used for `net461`
4. line 4 where `bar` is used for `netcoreapp3.1`

**Actual behavior**

There are 10 search results because there are six duplicate references for uses of `bar`.

![2020-07-22_12-53-54_191_devenv](https://user-images.githubusercontent.com/34664007/88212720-4f9c9080-cc1d-11ea-87d9-f346b76bc3ff.png)

**Known workarounds**

This doesn't happen when only single targeting, so that is sort of a workaround.

**Related information**

Provide any related information:

* Operating system: WIndows 10 Enterprise Version 10.0.18362 Build 18362
* .NET Runtime kind: NA (since bug is a tooling issue at compile time)
* Editing Tools: Visual Studio Enterprise 2019 Version 16.6.5

**Comment by cartermp** [comment] 2020-07-23 04:39
This is also the same root cause as https://github.com/dotnet/fsharp/issues/9275

**Comment by cartermp** [comment] 2020-08-13 21:59
As of https://github.com/dotnet/fsharp/pull/9934 it no longer produces duplicates, but the definition is _not_ included in the results. This is because it's not a usage of the type, but a declaration.

![image](https://user-images.githubusercontent.com/6309070/90191348-8fb2e700-dd75-11ea-86d1-edc851367d8d.png)

I think we could consider that by design?

**Comment by bender2k14** [comment] 2020-08-13 22:07
I would be satisfied with the search results being all references but the definition.  From any reference, I can easily get to the definition.

The case that including definitions would help is if it is possible to split a definition into multiple pieces like is possible in C# with partial classes.

Is there anything like that in F#?

**Comment by cartermp** [comment] 2020-08-13 22:12
Sort of, but not in the same way as C#. You can create F# interface files to lock down the public API surface area. This then requires that the implementation file implements that API.

File.fsi

```fsharp
module File

val myID: 'T -> 'T
```

File.fs

```fsharp
module File

let myID x = x
```

Results from Find References picks up both:

![image](https://user-images.githubusercontent.com/6309070/90192152-35b32100-dd77-11ea-865e-59cc6cb2d60c.png)

Interestingly, the `myID` declaration in the FSI file is not a use, but a definition. In that case I think we should just show it all.

@TIHan any thoughts?

**Comment by cartermp** [comment] 2020-08-14 03:50
Base problem resolved by https://github.com/dotnet/fsharp/pull/9934

Display issue I mentioned is tracked here: https://github.com/dotnet/fsharp/issues/9924

**Closed by cartermp** 2020-08-14 03:50 UTC
Labels: Area-FCS, bug
