### ISSUE TITLE
Discarded use is only allowed in CEs

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/fsharp#8570] opened 2020-02-13 21:50 UTC
Discarded use is only allowed in CEs

```fs
open System.IO

let x = 
    // error FS0852: 'use' bindings must be of the form 'use <var> = <expr>'
    use _ = new MemoryStream()
    async {
       // fine
       use _ = new MemoryStream()
       return ()
    }
```

[Sharplab for your convenience](https://sharplab.io/#v2:DYLgZgzgPg9gDgUwHYAIDKBPCAXBBbAOgEkB5AWAChLgFsUAPFAXhUpXZQFcIEUB9ZiiQIA7igCy+GACcMabNIQBDPAAoAlGw5KIGJAGMUAby0d23XgJbCxkvDLkLlazRTMdF2TtNQbTKAF8gA==)

**Comment by FunctionalFirst** [comment] 2020-02-13 23:15
The answer to this [related SO question](https://stackoverflow.com/questions/8438923/wildcard-use-binding-works-in-sequence-expression-but-not-otherwise) is helpful.

**Comment by cartermp** [comment] 2020-08-31 22:52
will close as dupe of https://github.com/fsharp/fslang-suggestions/issues/881 for bookkeeping purposes. I don't think we'd disallow this code since it would be a breaking change, so the only recourse is to do nothing or make it work outside the CE

**Closed by cartermp** 2020-08-31 22:52 UTC
