### ISSUE TITLE
Go To Definition - f12 fails, tooltip works

### ISSUE THREAD

**Issue by isaacabraham** [dotnet/fsharp#5521] opened 2018-08-16 11:29 UTC
If you F12 on a symbol in another file, it can't navigate to the item. However, if you click the type in the tooltip that follows, it works.

**Comment by realvictorprm** [comment] 2018-08-16 13:56
I already experienced that in a Fable project with 15.7 .

In 15.8 it still doesn't work there but it works for me on a backend project so looks like it's bound to specific circumstances?

**Comment by cartermp** [comment] 2018-08-16 16:06
@isaacabraham can you provide some more details or upload a repro solution?

Using 15.8, .NET Core project:

![gtd1](https://user-images.githubusercontent.com/6309070/44220378-4d794f80-a133-11e8-9f56-19ac37f0ace7.gif)

fsx-to-fs in a .NET Framework project:

![gtd2](https://user-images.githubusercontent.com/6309070/44220510-a0eb9d80-a133-11e8-95d6-737b3d8af66b.gif)

**Comment by cartermp** [comment] 2018-08-17 16:05
@isaacabraham Do you have a repro? I used this throughout the VF# codebase yesterday and could not get GTD to fail.

**Comment by isaacabraham** [comment] 2018-08-22 09:13
I've managed to get a repro in an existing project. The only thing I can see that *might* be the cause is that the symbol I'm trying to go to definition on lives in a *linked* `.fs` file in the project, rather than a normal project file.

**Comment by 0x53A** [comment] 2018-08-22 10:43
I've seen the same in safe bookstore - f12 mostly doesn't work, the clickable tooltips do

**Comment by cartermp** [comment] 2018-08-22 15:12
@isaacabraham in the second GIF, I'm doing the same as this:

> I can also reproduce on a script where I'm loading in an .fs file and trying to go to definition of a symbol defined in that.

But it succeeds. Do you have a repro?

I'll take a look at the fable bookstore, which uses linked files.

**Comment by vasily-kirichenko** [comment] 2018-08-22 15:15
It's always caused by wrong slashes (`/` in FCS vs `\` in Roslyn, etc.) in `range` or non normalised paths there.

**Comment by isaacabraham** [comment] 2018-08-22 15:20
@cartermp this is then something either environmental - my install of 15.8.1 is somehow borked, or something specific with the project. But I can't see anything there else unusual - it's a netcore2.0 console app.

There's definitely something different in the behaviour of Go To Definition when hitting F12 compared to clicking the hyperlink in the tooltip, because the latter works whilst F12 doesn't.

**Comment by vasily-kirichenko** [comment] 2018-08-22 15:22
@isaacabraham The implementation of go to def and links on the tooltip are completely different (and surprisingly complicated).

**Comment by cartermp** [comment] 2018-08-22 15:32
@isaacabraham I just tried with a .NET Core 2.1 console app with a script that navigates to a symbol in a source file for that project: works with f12, ctrl+click, and tooltip go to definition.

**Comment by forki** [comment] 2018-08-22 15:34
So zip with repro it is. Like always...

**Comment by cartermp** [comment] 2018-08-22 16:00
Okay, so the issue is when you attempt to go to definition from one linked file to another. Example:

`Home.fs` --> `viewLink` symbol

Tooltip shows and you can go to definition, but cannot use f12 or ctrl+click (which share the same implementation).

If files are "normal", or you're going to definition within a linked file, or going to definition between linked/non-linked files, everything seems to work.

I also noticed that finding symbols for Find Refs or Rename is inconsistent in this project. For example:

`Wishlist/Msg`:

![image](https://user-images.githubusercontent.com/6309070/44475095-071b6900-a5e9-11e8-837e-c25618deb5a1.png)

Not a linked file, and the references live in the same file.

`Database/DatabaseType`:

![image](https://user-images.githubusercontent.com/6309070/44475149-2f0acc80-a5e9-11e8-91cb-44805acf31b3.png)

Not a linked file, and all references live in the same file.

**Comment by cartermp** [comment] 2018-08-22 16:01
@isaacabraham can you update the title to accurate reflect that this is between linked files?

**Comment by isaacabraham** [comment] 2018-08-23 07:07
@cartermp I said that the project *contained* a link file. I don't believe that all of the issues I'm seeing are *only* related to symbols that live in that linked file. I'll double check this later today.

**Comment by cartermp** [comment] 2018-08-23 15:30
My observations are on playing around with the Bookstore app myself. If you can upload a repro that isn't Go to Definition from a linked file to a linked file, I'd appreciate that.

**Comment by isaacabraham** [comment] 2018-11-29 09:32
@cartermp I think the latest version of master in the Azure Storage TP has this issue now (at least, I'm seeing it there).

**Comment by cartermp** [comment] 2018-11-29 16:02
Do you have a specific repro there? What I noticed in SAFE was specifically when moving from linked file -> linked file. Is that the same in the Azure Storage TP codebase?

**Comment by isaacabraham** [comment] 2018-12-28 11:36
@cartermp I don't believe that there are any linked files in there. It seems to happen when going to definition of a symbol in another file e.g. In `AzureTypeProvider.fs`, line 69 - try to F12 on `Table.StaticSchema.createSchema`.

**Comment by isaacabraham** [comment] 2019-06-18 15:46
I can confirm that this problem still exists in the latest master of the Azure Storage TP.

**Comment by cartermp** [comment] 2019-08-09 17:40
Noting this in two additional areas:

* Tachyus' solution after a chat with them
* Our own codebase, when going from FSharp.Editor --> FSharp.Compiler.Private

**Comment by zanaptak** [comment] 2019-08-09 19:29
In the Azure TP it's the forward slashes #4016

**Comment by cartermp** [comment] 2019-08-09 22:23
Fixed by #7376

**Closed by cartermp** 2019-08-09 22:23 UTC
Labels: Area-IDE Language Service, Urgency-Now, bug
