### ISSUE TITLE
Missing debug breakpoints in a .NET Core 3.1 project

### ISSUE THREAD

**Issue by esplace** [dotnet/fsharp#10838] opened 2021-01-05 16:16 UTC
In a specific [project](https://github.com/SaturnFramework/Saturn.Sample), it is possible to place a breakpoint in the editor that will not trigger during the debugging.

**Repro steps**

1. Clone https://github.com/SaturnFramework/Saturn.Sample
2. Set breakpoint at lines 20 in `src/SaturnSample/Router.fs`
3. Start Debugging

**Expected behavior**

Breakpoint on line 20 is triggered during the debugging when appropriate.

**Actual behavior**

Breakpoint on line 20 is not available during the debugging (i.e. disappears in the editor when the user starts debugging). Seems like .pdb does not contain the information about this line.

**Known workarounds**

-

**Related information**

Provide any related information (optional):

Breakpoints on lines 21 and 22 work as expected. The issue might be related to [this one](https://github.com/dotnet/fsharp/issues/7643).

* Operating system: OS X, Linux, Windows
* .NET Runtime kind: .NET Core 3.1
* Editing Tools: Visual Studio 2019, Visual Studio Code, Rider

**Comment by cartermp** [comment] 2021-01-05 18:02
Will tenatively assume this is not the same as https://github.com/dotnet/fsharp/issues/7643 but it is likely highly related, since if you can set the breakpoint there _should_ be a breakpoint and it should be resolved (i.e., solid red in the editor and no warning/error message on it). If it's resolved but doesn't trigger, then it's likely the same issue

**Comment by cartermp** [comment] 2021-03-11 01:29
This can't be reproduced since the project isn't buildable / is archived. I will close this out, but if you have another repro to share please ping back and I'll re-open.

**Closed by cartermp** 2021-03-11 01:29 UTC
Labels: Area-Compiler, Area-IDE Debug
