### ISSUE TITLE
F# fails to load DLL in solution which mixes net8.0 and net8.0-windows

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#16868] opened 2024-03-13 11:16 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-fails-to-load-DLL-in-solution-which-m/10610684)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.9.0]
In an F# solution which mixes net8.0 and net8.0-windows (or net6.0 and net6.0-windows), Visual Studio can get into a state where intellisense is broken by failing to find DLLs from a project reference.

---
#### Toby Shaw on 3/7/2024, 00:42 PM: 

(private comment, text removed)
#### Feedback Bot on 3/8/2024, 02:31 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vzarytovskii** [comment] 2024-03-13 11:16
Feedback item: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1991243

**Comment by KevinRansom** [comment] 2024-04-04 20:45
I am unable to reproduce this:
The repro solution is working fine for me:
![image](https://github.com/dotnet/fsharp/assets/5175830/3be82070-2183-4104-85d2-e9c6745ef5cc)

Perhaps whatever caused the build issue has been addressed in a more recent build of Visual Studio and the SDK.

**Closed** 2024-04-05 16:52 UTC
Labels: Impact-High, Triage-Investigate
