### ISSUE TITLE
error FS1113 accessing constructor parameter with SRTP

### ISSUE THREAD

**Issue by ingted** [dotnet/fsharp#15135] opened 2023-04-24 05:17 UTC
**Repro steps**

```
type MyType<'T when ^T: (member o: int)> (t:^T) =
    member inline this.T = t
```

**Expected behavior**

Successfully executed.

**Actual behavior**

```
error FS1113: The value 'T' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
```

**Known workarounds**

None

**Related information**

* Operating system: win 2019
* .NET Runtime: .NET 7
* fsi: 12.5.0.0 for F# 7.0
* Editing Tools: Visual Studio

**Comment by ingted** [comment] 2023-04-24 05:27
![image](https://user-images.githubusercontent.com/4289161/233907226-e6a7b2ab-2ca5-4579-8f29-ef33de57faca.png)
It was executable in F# 5.0

**Comment by ingted** [comment] 2023-04-24 05:28
![image](https://user-images.githubusercontent.com/4289161/233907371-b33880ab-6f59-41ba-98cc-5c0d8872733c.png)
But not executable in F# 7.0

**Comment by 0101** [comment] 2023-04-24 16:48
A workaround for this may be to add a `member val` for the parameter from the constructor.

But we should definitely fix it.

**Comment by ingted** [comment] 2024-01-29 23:38
Still not works in .NET 8. (FSharp.Core 8.0.100)

**Comment by vzarytovskii** [comment] 2024-01-30 12:21
> Is there any branch having this fixed? Or any progress?

Nobody worked on it to my knowledge

**Comment by ingted** [comment] 2024-02-17 11:51
@vzarytovskii If you could give me some hints, e.g. which part one could look into it, I would like to study it and try to fix it? (I mean it needs guidance for one who tries to change code of the compiler (stuff?!) the first time...)

**Comment by vzarytovskii** [comment] 2024-02-17 12:15
> @vzarytovskii If you could give me some hints, e.g. which part one could look into it, I would like to study it and try to fix it? (I mean it needs guidance for one who tries to change code of the compiler (stuff?!) the first time...)

That's not an easy part of compiler, how I would approach it is see if it changes with different language versions but same sdk (langversion flag, compile same project with different versions), if it is, I would debug in the place it throws an error and see what's different.

If it still doesn't work with different language versions, it's harder, will have to find what revision of sdk it was working in, check it out and again repeat - see what's different. Maybe even bisect it and see where it started breaking.

**Comment by Martin521** [comment] 2024-02-18 15:44
I checked this with .net 5.0.408 and DO see the FS1113 reported by `fsc`. So it probably was there forever.
For `fsi`, it is reported only since .net 6. I don't know why it is not reported by `fsi` in .net 5. I assume some optimizations (and related checks) did not happen for fsi but only for fsc.

Furthermore, I suspect that the code (simplified example: `type MyType<'T> (t:'T) = member inline this.T = t`) is indeed invalid, only the error message is misleading. The right one might be the infamous FS0669 ("escape its scope"). Can some expert confirm this? It is happening [here](https://github.com/dotnet/fsharp/blob/44af7c8141b70e33685fcf58d44145a9d93eb7d7/src/Compiler/Optimize/Optimizer.fs#L1345).

**Comment by ingted** [comment] 2024-02-18 15:52
Why it is indeed invalid?... Logically it seems good to use.

**Comment by Martin521** [comment] 2024-02-18 17:34
I think my guess above about the correct error message was wrong.
Because you get the error also in non-generic code like this `type MyType<'T> (t:'T) = member inline this.T = t`.
I rather think now that for inline code all referenced values (like `t`) must have at least the accessibility of the function/member (`T` in this case). This makes sense because inlining means expanding the function/method at the call site. That would generate invalid IL as `t` is not accessible at the call site.

**Comment by Martin521** [comment] 2024-02-19 08:32
The above, though, leads to a workaround for your problem:
```
type HasO =
    abstract member o : int
type MyType<'T when 'T :> HasO> (t: 'T) =
    member this.T = t
```

**Comment by Martin521** [comment] 2024-02-19 09:19
I think we have established that the FS1113 error (re accessibility) in the original post is correct.
The other one that we have discussed above ("type could not be generalized") is a duplicate of #3302.

**Comment by ingted** [comment] 2024-02-19 10:04
Oops... Seems like not applied to my scenario....

In .net 5, it is really powerful...
![Screenshot_2024-02-19-17-58-36-77_2665fb67b16260a8d818298cef8dc107](https://github.com/dotnet/fsharp/assets/4289161/0d89f15f-6415-4110-b65b-aa33f3c9475c)

But not in .net 8... (It's hard to make all types implemented a specific interface...)
![Screenshot_2024-02-19-17-56-08-28_2665fb67b16260a8d818298cef8dc107](https://github.com/dotnet/fsharp/assets/4289161/3741b6b9-a424-4ecf-a2ab-17d3a4c35c0b)

**Comment by ingted** [comment] 2024-02-19 14:00
```
//working
type MyType6< ^T 
            when ^T: (member o :  int)
            > () = 
    static member inline get (t:^T) = t.o
    
    
//not working
type MyType6_2< ^T 
            when ^T: (member o :  int)
            > () = 
    static member val T = 123 
    static member inline get (t:^T) = t.o
```

![image](https://github.com/dotnet/fsharp/assets/4289161/8ac6a9cf-3a14-41ef-9047-c2eab20e162c)

**Comment by ingted** [comment] 2024-02-19 14:38
```
//not working in .net 8
type MyType7< ^T 
            when ^T: (member o : int)
            > (t:^T) = 
    member inline this.get () = t.o

//working in .net 5
type MyType7_2< ^T 
            when ^T: (member public o : int)
            > (t:^T) = 
    member inline public this.get () = (^T :(member public o :  int)(t))
```

According to this, I would vote that FS1113 error message is valid as well...

**Comment by Martin521** [comment] 2024-02-21 08:38
After some further digging into my earlier question

> But I really don't know why your non-inlined example `type MyType<'T when 'T: (member o: int)> (t:'T) = member this.T = t` is shown as invalid, while `type MyType2<'T when 'T: comparison> (t:'T) = member this.T = t` compiles.

I found the underlying reason. The CLR that handles generics recognizes a number of [constraints](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters), including type/interface constraints, but not explicit member constraints. The latter is a pure [F# thing](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/constraints). This means (now I am speculating) the compiler has to express it in IL by an interface constraint, and that can be done only if `MyType` is a "head type", i.e. statically known at compile time. These complications are also the reason why the F# Language Reference says that explicit member constraints are "not intended for common use".

So, I think we have answered all questions now.
- The `error FS1113` in `type MyType3<'T when 'T: (member o: int)> (t:'T) = member inline this.T: 'T = t` is correct.
- That this error was not reported by fsi in .net 5 was just a bug that has been fixed for .net 6
- The `error FS0670` in `type MyType4<'T when 'T: (member o: int)> (t:'T) = member this.T = t` is also correct.
- This error message should be improved, but we have an issue already for this (#3302)
- The fact that a comparison contraint works in the non-inlined case, but a member constraint does not work, is explained above.

So I guess this issue can be closed?

**Comment by ingted** [comment] 2024-02-21 08:48
Wow!! Sounds reasonable, let me close it! I learned a lot!!

**Closed** 2024-02-21 08:49 UTC
Labels: Bug, Regression, Impact-Medium

**Comment by ingted** [comment] 2025-05-01 12:21
A much quicker workaround:

```
type O<'T when 'T:(member i:int)>(t:'T) as this =
    [<DefaultValue>]
    val mutable internalState : 'T
    do
        this.internalState <- t

type O<'T when 'T:(member i:int)> with
    member inline this.i2 = this.internalState.i
```

No inherit required!!
