### ISSUE TITLE
New .NET Core 3.0 projects default to FSharp.Core 4.5.2

### ISSUE THREAD

**Issue by aspnetde** [dotnet/fsharp#7845] opened 2019-11-12 19:43 UTC
When creating a new (console) application which targets .NET Core 3.0, it references `FSharp.Core` 4.5.2 implicitly. It does not matter if it is created with Rider or Visual Studio for Mac.

When referencing another package which requires `FSharp.Core` >= 4.7.0, like `Fake.Tools.Git`, this results in

```
xyz.fsproj: [NU1605] Detected package downgrade: FSharp.Core from 4.7.0 to 4.5.2. Reference the package directly from the project to select a different version. 
xyz -> Fake.Tools.Git 5.18.3 -> FSharp.Core (>= 4.7.0) 
xyz -> FSharp.Core (>= 4.5.2)
```

Referencing `FSharp.Core` 4.7.0 explicitly like

```
<PackageReference Include="FSharp.Core" Version="4.7.0" />
```

does not help. But

```
<PackageReference Update="FSharp.Core" Version="4.7.0" />
```
works as a workaround.

**Sample project**

[fs47v2.zip](https://github.com/dotnet/fsharp/files/3837905/fs47v2.zip)

**My machine**

- macOS 10.15.1
- Rider 2019.2.3
- VS4Mac 8.3.8

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1322584/68704717-0a539980-058d-11ea-8e3a-7c92aa4089d3.png">

**Comment by cartermp** [comment] 2019-11-13 23:28
The uploaded project is invalid. When I remove the explicit FSharp.Core package reference, it builds with no errors or warnings.

This doesn't reproduce with the .NET CLI for me either

```
dotnet new console -lang F# -o test
cd test
dotnet add package Fake.Tools.Git
dotnet build
```

No warnings, no errors, using .NET Core 3.0 with the 3.0.100 SDK. I don't use VSMac or Rider, perhaps there's something wrong with how they're creating projects?

**Comment by auduchinok** [comment] 2019-11-13 23:41
@cartermp In Rider we use templates coming from `dotnet` and it should produce the same result you'd get in the terminal.
There're also bundled templates for legacy projects but it's not what was used here.

**Comment by cartermp** [comment] 2019-11-13 23:48
@auduchinok thanks, makes sense.

Also worth noting that even with the incorrect `<PackageReference Include="FSharp.Core" Version="4.7.0"/>` syntax everything still compiles without error or warning for me. This is coincidental though because there isn't any lower version getting pulled in.

@aspnetde My best guess is that you have something on your machine (a targets file perhaps?) that is pinning FSharp.Core to 4.5.2 and this reference is conflicting with your project.

**Comment by aspnetde** [comment] 2019-11-14 06:34
I also tried:

```bash
dotnet new console -lang F# -o test
cd test
dotnet add package Fake.Tools.Git
dotnet build
```

The result is identical to what I got with Rider and VS4Mac:

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/1322584/68832200-a0ccab80-06b0-11ea-8016-e96cb93250d3.png">

> My best guess is that you have something on your machine (a targets file perhaps?) that is pinning FSharp.Core to 4.5.2 and this reference is conflicting with your project.

I am not aware of something like that. And as said on the Twitter thread recently, I set up this machine only two weeks ago – without copying anything over from elsewhere. So if I have some kind of global misconfiguration here, that would probably be caused by one of the (pretty standard) tools I've installed so far. Which is, in terms of F#, nothing more than the usual suspects: Rider, VS4Mac, VSCode, Ionide.

Do you have an idea where to look for such a file?

(It's not like the world is going to end for me as I now know how to work around it. I am rather confused that this happens in the first place, as it really kind of ruins the developer experience [for others]).

**Comment by auduchinok** [comment] 2019-11-14 08:58
@aspnetde there's an action called "Rebuild project with diagnostics" in the context menu for a project in Solution explorer which opens a log file after doing the build. Could you share the said log please?

**Comment by abelbraaksma** [comment] 2019-11-14 12:01
Can you also perhaps double check that the project file is equal to the one from @cartermp? I'd be surprised there's a difference, but just to be sure...

**Comment by auduchinok** [comment] 2019-11-14 12:53
@abelbraaksma There may be some hard to spot differences in generated files in obj folder even with the same project files to boot.

**Comment by aspnetde** [comment] 2019-11-14 21:36
@auduchinok 

> there's an action called "Rebuild project with diagnostics" in the context menu for a project in Solution explorer which opens a log file after doing the build. Could you share the said log please?

Here you go: [JetBrainsLog.ReSharperBuild_2019_11_14_21_32_22_7148.log](https://github.com/dotnet/fsharp/files/3848712/JetBrainsLog.ReSharperBuild_2019_11_14_21_32_22_7148.log)

@abelbraaksma The project file is identical.

**Comment by cartermp** [comment] 2019-11-14 21:48
I think this is actually Mono's fsc getting called:

```
Task "Fsc"
  /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/fsharp/fsc.exe -o:obj/Debug/netcoreapp3.0/test.dll
  -g
  --debug:portable
  --noframework
  --define:TRACE
  --define:DEBUG
  --define:NETCOREAPP
  --define:NETCOREAPP3_0
  --optimize-
  --tailcalls-
  -r:/Users/thomas/.nuget/packages/fake.core.context/5.18.3/lib/netstandard2.0/Fake.Core.Context.dll
  -r:/Users/thomas/.nuget/packages/fake.core.environment/5.18.3/lib/netstandard2.0/Fake.Core.Environment.dll
  -r:/Users/thomas/.nuget/packages/fake.core.fakevar/5.18.3/lib/netstandard2.0/Fake.Core.FakeVar.dll
  -r:/Users/thomas/.nuget/packages/fake.core.process/5.18.3/lib/netstandard2.0/Fake.Core.Process.dll
  -r:/Users/thomas/.nuget/packages/fake.core.semver/5.18.3/lib/netstandard2.0/Fake.Core.SemVer.dll
  -r:/Users/thomas/.nuget/packages/fake.core.string/5.18.3/lib/netstandard2.0/Fake.Core.String.dll
  -r:/Users/thomas/.nuget/packages/fake.core.trace/5.18.3/lib/netstandard2.0/Fake.Core.Trace.dll
  -r:/Users/thomas/.nuget/packages/fake.io.filesystem/5.18.3/lib/netstandard2.0/Fake.IO.FileSystem.dll
  -r:/Users/thomas/.nuget/packages/fake.tools.git/5.18.3/lib/netstandard2.0/Fake.Tools.Git.dll
  -r:/Users/thomas/.nuget/packages/fsharp.core/4.5.2/lib/netstandard1.6/FSharp.Core.dll
```

And Mono F# is F# 4.5, with FSharp.Core 4.5.2. Why this would happen with `dotnet build` is utterly bizarre though.

**Comment by naughtyGitCat** [comment] 2019-11-21 01:47
Then, Is there any solution to this warning? I run into this during install giraffe package

**Comment by cartermp** [comment] 2019-11-21 01:58
@naughtyGitCat use this:

`<PackageReference Update="FSharp.Core" Version="4.7.0" />`

**Comment by naughtyGitCat** [comment] 2019-11-21 02:14
> @naughtyGitCat use this:
> 
> `<PackageReference Update="FSharp.Core" Version="4.7.0" />`

thanks, It takes effects, Seems the vs4mac run into this warning but runs in the console does not

**Comment by cartermp** [comment] 2020-08-29 21:38
Closing this out as per the analysis that due to some environmental issue, Mono's Fsc task was getting called instead of the Fsc task in the .NET SDK. It does not reproduce with the latest .NET SDK or preview for me.

**Closed by cartermp** 2020-08-29 21:38 UTC
Labels: needs repro
