### ISSUE TITLE
Avoid boxing on equality and comparison

### ISSUE THREAD

**Issue by 0101** [dotnet/fsharp#16497] opened 2024-01-04 18:01 UTC
https://github.com/fsharp/fslang-suggestions/issues/1280

**Comment by vzarytovskii** [comment] 2024-01-04 23:45
It's a duplicate of https://github.com/dotnet/fsharp/issues/526 technically, but I can't bring it back to project since it was bulk closed and archived.

**Comment by vzarytovskii** [comment] 2024-01-04 23:48
This also needs an approval by @dsyme. Specifically - an opt-out behaviour for new default operators (and somehow make it work for fslib as well).

**Comment by psfinaki** [comment] 2024-01-09 11:04
Restored 526 from the archive so closing this one as a duplicate.

**Closed by psfinaki** 2024-01-09 11:04 UTC
Labels: Theme-Performance
