### ISSUE TITLE
MailboxProcessor.Receive () doesn't handle CancellationToken properly

### ISSUE THREAD

**Issue by mishun** [dotnet/fsharp#3337] opened 2017-07-14 21:34 UTC
In this example:
```F#
open System
open System.Threading

[<EntryPoint>]
let main argv = 
    let cts = new CancellationTokenSource ()

    let mb =
        MailboxProcessor.Start (
            fun inbox -> async {
                use disp =
                    { new IDisposable with
                        member this.Dispose () =
                            printfn "Disposed"
                    }

                while true do
                    let! (msg : int) = inbox.Receive ()
                    printfn "Received %i" msg
            }, cancellationToken = cts.Token)

    mb.Post 1
    Thread.Sleep 1000
    cts.Cancel ()
    Thread.Sleep 4000
    0
```
expected output is:
```
Received 1
Disposed
```
but for some reason Dispose is not getting called. If line:
```F#
let! (msg : int) = inbox.Receive ()
```
is changed for something like:
```F#
let! (msg : int) = inbox.Receive 1000000
```
everything works as it should. Looks like at least TryReceive has the same problem.
Tested under Visual Studio Community 2017.

**Comment by forki** [comment] 2017-07-24 12:48
I added this as a test in https://github.com/Microsoft/visualfsharp/pull/3369

**Comment by forki** [comment] 2017-07-24 12:52
added a potential fix

**Comment by stmax82** [comment] 2018-03-06 16:41
Does the fix also work when you replace cts.Cancel() with (mb :> IDisposable).Dispose()?

**Comment by cartermp** [comment] 2021-03-10 22:16
I will close this because it works as intended and was fixed a while ago, just not closed.

@stmax82 yes, this also works at least in a script that I did an ad-hoc test for.

**Closed by cartermp** 2021-03-10 22:16 UTC
Labels: Area-Library, Severity-Medium, bug
