### ISSUE TITLE
Different analysis of a method call depending on parentheses

### ISSUE THREAD

**Issue by DedSec256** [dotnet/fsharp#14194] opened 2022-10-28 15:16 UTC
```F#
open System

let f x  = (DateTime.UtcNow.ToBinary) x
let f x = DateTime.UtcNow.ToBinary x
```

![image](https://user-images.githubusercontent.com/26364714/198668030-6e182f53-4527-497c-91e8-addede1f9c6f.png)

**Expected behavior**

Behavior is consistent between both cases. (Correct type inference and no errors in the second case?)

**Comment by LyndonGingerich** [comment] 2022-11-15 22:01
I think my issue at https://github.com/fsharp/fslang-suggestions/issues/1208 is probably a duplicate of yours, though I approached the question rather differently, so I'm closing it.

My findings:
- You can't directly pass a single bound parameter of type `unit` into a member.
- You can pipe such a value into a member. This is an alternate workaround to parenthesizing the member.

A [helpful comment](https://github.com/fsharp/fslang-suggestions/issues/1208#issuecomment-1315892484) from @kerams:
> There's a dissonance between what `x.Method ()` means in F#, and functional programming in general, conceptually (passing in one argument of type unit, which is why I prefer to add that extra space), and how it is represented in .NET (calling a method with no arguments). My guess is that the compiler looks for methods with 0 parameters when the `()` constant is passed in. In your case the constant is hidden and method resolution looks for a method with 1 parameter.

**Comment by vzarytovskii** [comment] 2023-01-23 19:48
This probably should go via suggestions and @dsyme's review.

**Closed** 2023-03-10 14:50 UTC
Labels: Bug, Impact-Low, Area-Compiler-Checking
