### ISSUE TITLE
Active Patterns with generic parameters trigger FS1189

### ISSUE THREAD

**Issue by baronfel** [dotnet/fsharp#8221] opened 2020-01-15 15:35 UTC
Defining an active pattern that returns a generic type where that type must be explicitly declared instead of inferred during function usage (to prevent unification to `obj`) seems to be impossible to do without triggering FS1189, the warning about spaces between generic parameters and types that they belong to.

**Repro steps**

This sample code is an active pattern that maps a string representation of a single-case DU to the matching DU value.  As part of this, the object result of `FSharpValue.MakeUnion` must be cast to the destination DU type `'t`, meaning `'t` must be declared as a type parameter of the AP case.  However, it is impossible to attach `'t` in any position other than after the closing banana-clip, which results in the warning being thrown:

```fsharp
type DU = A | B | C

open FSharp.Reflection

let (|UnionCaseName|_|)<'t> = // FS1189 triggered on this line
  let caseToValueMap =
    if FSharpType.IsUnion typeof<'t>
    then
      FSharpType.GetUnionCases typeof<'t>
      |> Array.map (fun case -> case.Name, FSharpValue.MakeUnion(case, [||]) :?> 't)
      |> Map.ofArray
    else Map.empty

  fun s ->  Map.tryFind s caseToValueMap
```

**Expected behavior**

I should be able to define AP cases that use generic types without warnings.

**Actual behavior**

FS1189 is triggered at the site of type parameter declaration.

**Known workarounds**

* Use nowarn, which either renders the entire file unchecked in this respect, or the whole project, depending on which scope the nowarn is applied.
* use a different factoring of the code, which doesn't _quite_ work because matching now requires a spurious unit value in the match:

```fsharp
type DU = A | B |C

open FSharp.Reflection

let unioncasename<'t> () =
  let caseToValueMap =
    if FSharpType.IsUnion typeof<'t>
    then
      FSharpType.GetUnionCases typeof<'t>
      |> Array.map (fun case -> case.Name, FSharpValue.MakeUnion(case, [||]) :?> 't)
      |> Map.ofArray
    else Map.empty
  fun s ->  Map.tryFind s caseToValueMap

let inline (|UnionCaseName|_|) () = unioncasename<_> ()

match "A" with
| UnionCaseName () (a: DU) -> a
```

**Related information**

Provide any related information (optional):

* Operating system: MacOS Mojave
* .NET Runtime kind: .Net Core 3.1
* Editing Tools: Ionide (FSC 33.0.1)

**Comment by cartermp** [comment] 2020-01-15 17:22
Yeah this definitely seems like a bug. There shouldn't be any such warning there.

**Comment by abelbraaksma** [comment] 2020-01-16 01:59
This is the same issue as what I reported a few months ago, but that went unnoticed so far ;), see: #7797

In that issue, I encountered it with SRTP, but it's likely the cause is the same.

**Comment by cartermp** [comment] 2020-06-20 00:59
Thanks @abelbraaksma, closing this as duplicate of #7797

**Closed by cartermp** 2020-06-20 00:59 UTC
Labels: Resolution-Duplicate
