### ISSUE TITLE
A bug for Anonymous Records

### ISSUE THREAD

**Issue by GratianPlume** [dotnet/fsharp#10583] opened 2020-12-02 04:30 UTC
1. 
```
let gm = {| Ah = 10; Ah = "" |}
```
It can be compiled, didn't throw an error. but throw errors when to `printf`

2. 
```
   let gm = {| Ah = 10; |}

   let aa = {| gm with Ah = "a" |}
```
It can be compiled again, this is it's result: `val it : {| Ah: string |} = { Ah = "a" }`

for the second, I don't sure it a feature or a bug?

**Comment by cartermp** [comment] 2020-12-02 19:50
The second behavior is by design. There is an exact match for the label name and so it updates it, rather than adding a new label with the existing name but a different type.

I think the first case is also a bug. This isn't something that you can replicate in a normal record definition.

![image](https://user-images.githubusercontent.com/6309070/100923718-75238b80-3494-11eb-9e48-4ddb373338cd.png)

So it shouldn't be allowable in an anonymous record, either. If for some reason we decide it's allowable, then pretty-printing has a bug that should get resolved.

**Comment by dsyme** [comment] 2022-04-04 15:32
Duplicate of https://github.com/dotnet/fsharp/issues/11743

**Closed by dsyme** 2022-04-04 15:32 UTC
Labels: Bug, Area-Compiler, Impact-Low
