### ISSUE TITLE
Core Task Builder is suprisingly cancelled only in Release mode

### ISSUE THREAD

**Issue by Lanayx** [dotnet/fsharp#12487] opened 2021-12-03 22:01 UTC
Please provide a succinct description of the issue.

When using a cancellation token inside task builder (token not related to the builder itself), the task gets cancelled when cancellation token gets cancelled (although logically it shouldn't)

Provide the steps required to reproduce the problem:

1. Clone [TaskCancellationIssue branch](https://github.com/fsharplang-ru/pulsar-client-dotnet/tree/TaskCancellationIssue)
2. `cd tests\compose\standalone`
3. `docker-compose up`
4. Wait until cluster starts
5. `cd tests\IntegrationTests`
6.  `dotnet run`
7. Verify that 1 test is passed successfully
8. `dotnet run -c Release`
9. Verify that 1 test is hanging with the last message "mailbox has stopped normally"

[The code that works with cancellation token](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/TaskCancellationIssue/src/Pulsar.Client/Internal/ConsumerImpl.fs#L878-L898)
[The code that creates cancellation token](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/TaskCancellationIssue/tests/IntegrationTests/Cancellation.fs#L26-L40)

Some explanation:
The message "mailbox has stopped normally" comes from [this line](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/TaskCancellationIssue/src/Pulsar.Client/Internal/ConsumerImpl.fs#L1276), there we have t.IsFaulted = false, t.IsCancelled = true, which means that the whole task loop was cancelled after token cancellation happened.

**Expected behavior**

Expected behavior - external task shouldn't depend on random accessToken object, just as it doesn't in Debug mode

**Actual behavior**

In Release mode it depends (based on repro)

**Known workarounds**

1) Use TaskBuilder.fs instead of core task builder
2) First - extract the code that works with cancellation token in function, second - change tuple to record (or box cancellation token) [link to the commit fixing the issue](https://github.com/fsharplang-ru/pulsar-client-dotnet/commit/dba66c6f037d714af632c5cbbd1a28ea877d2c8d), both steps are required for the workaround

**Related information**

F# 6.0, .NET 6.0
Linked issue https://github.com/fsharplang-ru/pulsar-client-dotnet/issues/200

**Comment by dsyme** [comment] 2021-12-06 16:42
I think we'd need a much smaller repro for this - while I agree in principle there shouldn't be an apparent debug/release dependency here, it's very unclear from the code whether the debug/release change is due to timing or some other issue related to task compilation.  I mean it _might_ be the case but the repro is just too large to make sensible progress on in tracking down what's happening.

**Comment by Lanayx** [comment] 2021-12-06 17:47
@dsyme Unfortunately I was unable to create a simple repro, while at the provided repository it's reproduced steadily.

**Comment by dsyme** [comment] 2021-12-06 17:53
I see.  I don't think we can reasonably trim the repro down then, if it's not possible for you to do it - the code and dependencies is too large and unknown to us, and it's really hard to assess if there is even really a bug.  

If you get a chance to iterate on it please reopen with a smaller repo.

**Comment by gsomix** [comment] 2021-12-06 18:14
@dsyme I'll take a look.

**Comment by Lanayx** [comment] 2021-12-06 18:19
@dsyme We've just found out that task cancellation happens [on this line](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/TaskCancellationIssue/src/Pulsar.Client/Internal/ConsumerImpl.fs#L752) and what is charming is that if we change 
`mb.Reader.ReadAsync()` to `mb.Reader.ReadAsync(CancellationToken.None)` it works normally in Release mode as well

**Comment by dsyme** [comment] 2021-12-06 18:38
> @dsyme We've just found out that task cancellation happens on this line and what is charming is that if we change
mb.Reader.ReadAsync() to mb.Reader.ReadAsync(CancellationToken.None) it works normally in Release mode as well

Hmmm... it's hard for me to understand why cancellation would (or wouldn't) happen there, or why it would be related to task compilation and codegen. That call feels like it should be non-cancellable in both cases you've shown.

**Comment by gsomix** [comment] 2021-12-06 19:25
@dsyme @Lanayx 

OK, I've reduced example a bit. ;)

```fsharp
open System
open System.Threading
open System.Threading.Tasks
open System.Threading.Channels

type Message = Token of CancellationToken

type Issue12487() =
    let mb = Channel.CreateUnbounded<Message>()

    let startLoop(): Task =
        task {
            while true do
                let! Token (token) = mb.Reader.ReadAsync()
                Console.WriteLine("Token received")

                // The line below is important for repro.
                Console.WriteLine("token.CanBeCanceled {0}, token.IsCancellationRequested {1}", token.CanBeCanceled, token.IsCancellationRequested)
        }

    do startLoop().ContinueWith(fun t -> Console.WriteLine("Task.IsCanceled {0}", t.IsCanceled)) |> ignore

    member _.PostToken(token: CancellationToken) =
        mb.Writer.TryWrite(Token(token)) |> ignore

[<EntryPoint>]
let main args =
    async {
        let tmp = Issue12487()
        use cts = new CancellationTokenSource()
        cts.CancelAfter(100)
        tmp.PostToken(cts.Token)

        do! Async.Sleep(1000)
        return 0
    } |> Async.RunSynchronously
```

```
> dotnet --version
6.0.100

> dotnet run -c Debug
Token received
token.CanBeCanceled True, token.IsCancellationRequested False

> dotnet run -c Release
Token received
token.CanBeCanceled True, token.IsCancellationRequested False
Task.IsCanceled True
```

**Comment by Lanayx** [comment] 2021-12-08 09:42
@dsyme is the reduced repro good enough to regard it as a bug?

**Comment by dsyme** [comment] 2021-12-08 16:34
@Lanayx It's enough to take a close look. I haven't run the repro yet.

So the expected bheaviour is that Debug case? That is, the loop never terminated and `Task.IsCanceled False` is never printed?

In that case I agree the release case should not terminate/cancel as well.  I'm very curious as to why the loop terminates, perhaps it's following an exception path.

**Comment by gsomix** [comment] 2021-12-08 16:46
@dsyme

> So the expected behaviour is that Debug case? That is, the async loop never terminated and the task never completes and Task.IsCanceled False is never printed?

Yes.

> I'm very curious as to why the loop terminates, perhaps it's following an exception path.

It seems external cancellation token somehow interferes with default token of  [`ReadAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channelreader-1.readasync) method. Please note, removing line with accessing external token properties fixes problem, also as providing explicit token to ReadAsync call.

**Comment by dsyme** [comment] 2021-12-08 17:14
OK I see, there is a default argument to ReadAsync.  

It turns out this is fixed in "main", it's a duplicate of https://github.com/dotnet/fsharp/issues/12333.  I verified by using `fsi`, e.g.

17.0:
```
> dotnet fsi  --optimize --tailcalls --debug b.fs
Token received
token.CanBeCanceled True, token.IsCancellationRequested False
Task.IsCanceled True
```
and main:

```
> artifacts\bin\fsi\Debug\net5.0\fsi.exe --optimize --tailcalls --debug b.fs
Token received
token.CanBeCanceled True, token.IsCancellationRequested False
```

**Comment by dsyme** [comment] 2021-12-08 17:15
The workaround of giving an explicit `CancellationToken.None` to `ReadAsync` is adequate in this case, though obviously it's very hard to spot that

**Comment by dsyme** [comment] 2021-12-08 17:16
I'll close this since I've verified that it's fixed in `main`

**Closed by dsyme** 2021-12-08 17:16 UTC
Labels: Needs-Repro

**Comment by gsomix** [comment] 2021-12-08 17:22
@dsyme Thanks! Good to know it's same problem.
