### ISSUE TITLE
Indention eliminated  when copy and paste in F# code

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/fsharp#9875] opened 2020-08-05 00:37 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1132577/indention-eliminated-when-copy-and-paste.html)._

---
<p>[severity:I’m frustrated, but able to complete my work]<br>
In F# code, copying lines that have some indents and pasting them result in the lines with no indents.</p>

---
#### Feedback Bot on 8/2/2020, 09:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by abelbraaksma** [comment] 2020-08-07 21:53
You have to disable "reformat on paste" in <kbd>Options > Text Editor > F# > Formatting</kbd>, that feature is totally broken (or at least, I haven't seen it working on my machine). It should probably be disabled by default and get the "Experimental" flag.

![2fb62122-77da-446c-9aea-710ac5bf1ce9](https://user-images.githubusercontent.com/16015770/89691329-fdd85380-d908-11ea-83e8-cbbeb6a4a48b.gif)

**Comment by abelbraaksma** [comment] 2020-08-07 21:59
There's however a way of using this feature properly, which means you have to have your cursor in the right position. See this: https://github.com/dotnet/fsharp/issues/6281#issuecomment-468294388, and this

**Comment by cartermp** [comment] 2020-08-10 22:48
I think this could be improved, but ultimately it's still just pasting lipstick on the pig that is our lack of proper code formatting tools in VS for F#. We don't integrate with fantomas, which could offer up that support. It's something we should really revisit.

**Comment by dsyme** [comment] 2020-09-01 16:13
I do think this needs fixing, I notice it all the time.

**Comment by dsyme** [comment] 2021-11-05 23:15
Duplicate of https://github.com/dotnet/fsharp/issues/12158

**Closed by dsyme** 2021-11-05 23:15 UTC
Labels: Bug, Impact-Medium, Area-IDE Language Service
