### ISSUE TITLE
An inref<_> returned by a property or method is weirdly behaving in C#

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/fsharp#9997] opened 2020-08-24 22:30 UTC
### Problem

F# code that defines a method or property with a readonly return byref using an `inref` is not usable from C#.

### Details

Consider the following snippet:

``` fsharp
type C() =
    let x = 59
    member _.X: inref<_> = &x
```

The emitted code is missing an attribute

     .custom instance void System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor() = ( 01 00 00 00 ) 

Sample solution

[ClassLibrary4 (2).zip](https://github.com/dotnet/fsharp/files/5124444/ClassLibrary4.2.zip)

It is compiled to this C# code:

``` csharp
[Serializable]
[CompilationMapping(SourceConstructFlags.ObjectType)]
public class C
{
    internal int x;

    public ref int X
    {
        get
        {
            return ref x;
        }
    }

    public C()
    {
        x = 0;
    }
}
```

`X` is seen as a read-write byref by C#, not as a `readonly ref`. This subtle bug could bite the unsupecting C# consumer of a public library. 

A C# code file referencing the first F# snippet and containing these statements:

``` csharp
using System;
static class Program {
    public static vod Main() {
        var c = new C();
        Console.WriteLine(c.X);
    }
}
```

The C# program does not compile! It displays `Error CS0570 : 'C.X.get' is not supported by the language`.

### Workaround

The workaround is to add the `IsReadOnly` attribute manually:

```
open System.Runtime.CompilerServices

type C() =
    let x = 59
    
    
    member _.X(): [<IsReadOnly>] inref<_> = &x
```

**Comment by dsyme** [comment] 2020-08-25 13:17
Could you add the compilation of the equivalent C#?

**Comment by dsyme** [comment] 2020-08-25 13:21
Oh - you mean the initialization of `x` is wrong?

**Comment by NinoFloris** [comment] 2020-08-25 13:26
@dsyme there is no way to express ref returning properties in C# which is why I expect this is an issue. 

I do see some value in ref properties (they just work like ref returning methods), this may be chalked up to a design difference between C# and F#?

**Comment by dsyme** [comment] 2020-08-25 13:31
C# source:
```csharp

using System;

namespace ClassLibrary1
{
    public class C
    {
        internal int x;

        public ref int X
        {
            get
            {
                return ref x;
            }
        }

        public C()
        {
            x = 0;
        }
    }
}

```

C# generated code:

```
.method public hidebysig specialname instance int32& 
        get_X() cil managed
{
  // Code size       12 (0xc)
  .maxstack  1
  .locals init (int32& V_0)
  IL_0000:  nop
  IL_0001:  ldarg.0
  IL_0002:  ldflda     int32 ClassLibrary1.C::x
  IL_0007:  stloc.0
  IL_0008:  br.s       IL_000a
  IL_000a:  ldloc.0
  IL_000b:  ret
} // end of method C::get_X


.property instance int32& X()
{
  .get instance int32& ClassLibrary1.C::get_X()
} // end of property C::X
```

F# source:
```fsharp
namespace ClassLibrary4

type C() =
    let x = 59
    member _.X: inref<_> = &x
```

F# generated code:
```
.method public hidebysig specialname instance int32& modreq([netstandard]System.Runtime.InteropServices.InAttribute) 
        get_X() cil managed
{
  // Code size       7 (0x7)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  ldflda     int32 ClassLibrary4.C::x
  IL_0006:  ret
} // end of method C::get_X


.property instance int32& X()
{
  .get instance int32& modreq([netstandard]System.Runtime.InteropServices.InAttribute) ClassLibrary4.C::get_X()
} // end of property C::X
```

**Comment by dsyme** [comment] 2020-08-25 13:33
So the problem appears to be that F# is generating `modreq([netstandard]System.Runtime.InteropServices.InAttribute)` in return position.

**Comment by dsyme** [comment] 2020-08-25 13:40
Sample solution here:

[ClassLibrary4.zip](https://github.com/dotnet/fsharp/files/5124036/ClassLibrary4.zip)

**Comment by teo-tsirpanis** [comment] 2020-08-25 13:40
Forgot to mention: in the C# code, `X` should have been a `readonly ref`.

**Comment by dsyme** [comment] 2020-08-25 13:41
@teo-tsirpanis From what I see the C# code doesn't need readonly to repro the bug - is there any specific reason why you're saying it should be there?

**Comment by teo-tsirpanis** [comment] 2020-08-25 13:45
Yes. The property's type is an inref, AKA a read-only reference.

**Comment by dsyme** [comment] 2020-08-25 14:56
> Yes. The property's type is an inref, AKA a read-only reference.

I see, the problem is that the F# code is missing
```
  .param [0]
  .custom instance void System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor() = ( 01 00 00 00 ) 
```

This should indeed be emitted

**Comment by dsyme** [comment] 2020-08-25 15:00
OK, the workaround is to add that attribute manually:
```
namespace ClassLibrary4

open System.Runtime.CompilerServices

type C() =
    let x = 59
    
    
    member _.X(): [<IsReadOnlyAttribute>] inref<_> = &x
```

However I agree it should not be needed.

**Comment by teo-tsirpanis** [comment] 2020-08-25 17:04
Even with the `IsReadOnlyAttribute` we can't do things like this in C#:

``` csharp
var c = new C();
ref readonly var x = ref c.X();
```

**Comment by dsyme** [comment] 2020-08-26 11:02
@teo-tsirpanis This compiled for me with that attribute added:
Source zip: [ClassLibrary4.zip](https://github.com/dotnet/fsharp/files/5129369/ClassLibrary4.zip)

```csharp
using System;
static class Program
{
    public static void Main()
    {
        var c1 = new ClassLibrary1.C();
        var c4 = new ClassLibrary4.C();
        Console.WriteLine(c1.X());
        Console.WriteLine(c4.X());
        ref readonly var x1 = ref c1.X();
        ref readonly var x4 = ref c4.X();
    }
}
```

**Comment by teo-tsirpanis** [comment] 2020-08-27 14:55
The properties are still not considered read-only.

``` fsharp
namespace ClassLibrary4

open System.Runtime.CompilerServices

type C() =
    let x = 59

    member _.X(): [<IsReadOnly>] inref<_> = &x
    member _.XProp: [<IsReadOnly>] inref<_> = &x
```

``` csharp
using System;
static class Program
{
    public static void Main()
    {
        var c4 = new ClassLibrary4.C();
        Console.WriteLine(c4.X()); // Prints 59
        Console.WriteLine(c4.XProp); // Prints 59
        ref readonly var x4 = ref c4.X();
        ref var x4Prop = ref c4.XProp;
        x4Prop = 0; // Shouldn't be allowed!
        Console.WriteLine(c4.X()); // Prints 0
        Console.WriteLine(c4.XProp); // Prints 0
    }
}
```

**Comment by TIHan** [comment] 2020-08-27 22:26
@teo-tsirpanis I've noticed this too, even after I started emitting the attribute automatically. C# still does not see it as `readonly` even with the attribute. Investigating the C# compiler.

**Comment by TIHan** [comment] 2020-08-28 01:24
Looks like we need to put the 'IsReadOnly' attribute and a modreq(InAttribute) on the IL 'property' itself.

**Comment by TIHan** [comment] 2020-08-28 04:36
I've managed to add those attributes on the property itself, it seems to have resolved the issue.

**Comment by cartermp** [comment] 2020-09-09 17:19
Resolved by https://github.com/dotnet/fsharp/pull/10022

**Closed by cartermp** 2020-09-09 17:19 UTC
Labels: Area-Compiler, Severity-Medium, bug
