### ISSUE TITLE
Do not support for datetime string interpolation

### ISSUE THREAD

**Issue by naughtyGitCat** [dotnet/fsharp#11163] opened 2021-03-01 10:10 UTC
Please provide a succinct description of the issue.

**Repro steps**
```f#
open System
let x = $"{DateTime.Now:yyyy-MM-dd HH:mm:ss}"
```
**Expected behavior**

generate datetime string

**Actual behavior**
```
Unexpected symbol '-' in binding. Expected interpolated string (final part), interpolated string (part) or other token.F# Compiler(1)

error FS0010: 意外的 符号“-” 在绑定中。应为 内插字符串(最终部分)、内插字符串(部分) 或其他标记。 
```

* Operating system 
> MacOS 11.2.1
* .NET Runtime kind 
> NetCore 5.0

* Editing Tools (e.g. Visual Studio Version, Visual Studio)
> VSCode

**Comment by naughtyGitCat** [comment] 2021-03-01 10:11
this is work normally in c#

**Comment by cartermp** [comment] 2021-03-01 16:34
Closing as a duplicate of https://github.com/dotnet/fsharp/issues/10449

**Closed by cartermp** 2021-03-01 16:34 UTC
