### ISSUE TITLE
Unexpected behaviour of static abstract members in F#7

### ISSUE THREAD

**Issue by August-Alm** [dotnet/fsharp#14859] opened 2023-03-07 09:05 UTC
The compiler fails to detect an implemented static member that is the implementation of a static abstract member of an implemented interface, in an unexpected fashion.

__Repro steps__

The following code shows the behavior.

```F#
  type App<'F, 'a> = App of obj

  type IFunctor<'F when 'F :> IFunctor<'F>> =
    static abstract fmap<'a, 'b> : ('a -> 'b) -> App<'F, 'a> -> App<'F, 'b>

  type FList =
    static member wrap (xs : list<'a>) : App<FList, 'a> = App xs
    static member unwrap (App xs : App<FList, 'a>) : list<'a> = xs :?> _

    interface IFunctor<FList> with
      static member fmap<'a, 'b> (f : 'a -> 'b) (v : App<FList, 'a>) : App<FList, 'b> =
        FList.wrap (List.map f (FList.unwrap v))

  // This fails compilation with
  // "error FS0039: The type 'FList' does not define the field, constructor or member 'fmap'."
  let mapper1 f = FList.fmap f

  // This works just fine.
  let private fm<'F when 'F :> IFunctor<'F>> f = 'F.fmap f
  let mapper2 f = fm<FList> f
```

__Expected behavior__

I would expect reference to `FList.fmap` in `mapper1` to work. And, if it doesn't work, then at least I'd expect `fm<FList> f` in `mapper2` to fail as well.

__Actual behavior__

`mapper1` fails compilation with  "error FS0039: The type 'FList' does not define the field, constructor or member 'fmap'." but `mapper2` compiles (and runs).

__Known workarounds__

None.

__Related information__

F#7/net7.0 build.

**Comment by vzarytovskii** [comment] 2023-03-07 09:49
This was a conscious choice, to behave same as instance, when we were implementing static abstracts, specific implementation should be on the type, and interface implementation should be calling it.

Same as non-static members.

**Comment by vzarytovskii** [comment] 2023-03-07 09:56
This was a conscious choice, to behave same as instance, when we were implementing static abstracts, specific implementation should be on the type, and interface implementation should be calling it.

Same as non-static members.

See this test as an example: https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/Interop/StaticsInInterfaces.fs#L179

**Comment by vzarytovskii** [comment] 2023-03-07 10:01
This was a conscious choice, to behave same as instance, when we were implementing static abstracts, specific implementation should be on the type, and interface implementation should be calling it.

Same as non-static members.

See this test as an example: https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/Interop/StaticsInInterfaces.fs#L179

**Update:** to expand a bit - F# doesn't generate an implicit interface methods on type as C# does, hence this behaviour.

**Comment by August-Alm** [comment] 2023-03-07 10:17
Thought I should try the same thing in C#. The exact same behavior repeats there so maybe it it is not a bug? Does not make it any less confusing and unexpected though. See the below code.

```C#
public sealed class App<F, A>
{
    private readonly object Item;
    
    public object Value => Item;

    public App(object x)
    {
        Item = x;
    }
}

public interface IFunctor<F> where F : IFunctor<F>
{
    static abstract App<F, B> Fmap<A, B> (Func<A, B> f, App<F, A> v);
}

public class ListF : IFunctor<ListF>
{
    public static App<ListF, A> Wrap<A>(List<A> xs)
    {
        return new App<ListF, A>(xs);
    }

    public static List<A> Unwrap<A>(App<ListF, A> v)
    {
        return v.Value as List<A>;
    }

    static App<ListF, B> IFunctor<ListF>.Fmap<A, B>(Func<A, B> f, App<ListF, A> v)
    {
        List<A> xs = Unwrap<A>(v);
        var ys = new List<B>(xs.Count);
        foreach (var x in xs) ys.Add(f(x));
        return Wrap<B>(ys);
    }
}

public static class Program
{
    static App<F, B> FMapper<F, A, B>(Func<A, B> f, App<F, A> v) where F : IFunctor<F>
    {
        return F.Fmap<A, B>(f, v);
    }

    static void Main ()
    {
        var xs = new List<string>(new string[] {"a", "b", "c"});
        var v = ListF.Wrap<string>(xs);
        Func<string, string> f = s => s.ToUpper();
        // This works!
        var w = FMapper<ListF, string, string>(f, v);
        // This does not! Fails compilation with
        // "error CS0117: 'ListF' does not contain a definition for 'Fmap'"
        //var w = ListF.Fmap<string, string>(f, v);
        var ys = ListF.Unwrap<string>(w);
        foreach (var y in ys) Console.WriteLine("{0}", y);
    }
}
```

**Comment by August-Alm** [comment] 2023-03-07 10:27
> This was a conscious choice, to behave same as instance, when we were implementing static abstracts, specific implementation should be on the type, and interface implementation should be calling it.
> 
> Same as non-static members.
> 
> See this test as an example: https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Compiler.ComponentTests/Interop/StaticsInInterfaces.fs#L179
> 
> **Update:** to expand a bit - F# doesn't generate an implicit interface methods on type as C# does, hence this behaviour.

Thank you for your answer. Could you elaborate? To me it seems entirely backwards -- static should not behave the same as instance members (that is what makes them static! no?) -- but I'm probably misunderstanding your point.

I also do not understand your comment on F# vs C#. See my comment with a translation to C#, which has the same behavior.

**Comment by En3Tho** [comment] 2023-03-07 10:48
@August-Alm In F# every interface implementation is explicit unlike C# where it's implicit by default but you can opt-in to explicit interface implementation. Both with instance members and now with statics too.

What you did in C# was basically a translation from F#. You explicitly implemented an interface and chose not to add that method to a type itself honoring the same behaviour.

But at the same time in C# you could just move Fmap method to type's body instead and get interface implementation automatically. F# doesn't let you do this. Meaning you have to declare method in type's body and then call that method in interface implementation.

**Comment by August-Alm** [comment] 2023-03-07 11:07
> @August-Alm In F# every interface implementation is explicit unlike C# where it's implicit by default but you can opt-in to explicit interface implementation. Both with instance members and now with statics too.
> 
> What you did in C# was basically a translation from F#. You explicitly implemented an interface and chose not to add that method to a type itself honoring the same behaviour.
> 
> But at the same time in C# you could just move Fmap method to type's body instead and get interface implementation automatically. F# doesn't let you do this. Meaning you have to declare method in type's body and then call that method in interface implementation.

Thank you! Now I understand! =D I still think the design isn't very ergonomic but the workarounds are fairly easy. Let me record them here for completeness, posterity, and the benefit of readers who share my initial confusion:

If in C#, always let the compiler infer interface implementations of interfaces with static abstract members:
```C#
   // Do this! Never explicit `IFunctor<F>.Fmap<A,B>`.
    public static App<ListF, B> Fmap<A, B>(Func<A, B> f, App<ListF, A> v)
    {
        List<A> xs = Unwrap<A>(v);
        var ys = new List<B>(xs.Count);
        foreach (var x in xs) ys.Add(f(x));
        return Wrap<B>(ys);
    }
```
If in F#, always implement static abstract members twice: once for the type and once for the interface.
```F#
    static member fmap<'a, 'b> (f : 'a -> 'b) (v : App<ListF, 'a>) : App<ListF, 'b> =
      ListF.wrap (List.map f (ListF.unwrap v))
    
    interface Functor<ListF> with
      static member fmap<'a, 'b> (f : 'a -> 'b) (v : App<ListF, 'a>) : App<ListF, 'b> =
        ListF.fmap<'a, 'b> f v
```
Were the reasons for these choices, as they pertain to interfaces with static abstract members, discussed in some public thread?

**Comment by August-Alm** [comment] 2023-03-07 16:03
@En3Tho Thank you for reply!
I think I get the picture. What irks me about the F# design choice is not that I have to be explicit about the interface implementation. The questionable design, in my view, is that `ListF.fmap f` does not work if only the interface is implemented. I would understand such a behavior for an instance member, because then you can actually explicitly cast the instance to the interface, i.e., do `(myObj :> IMyInterface).Method ()`. In the present situation, with a static method, there is no `myObj` to cast, so there is no explicit way of saying "consider ListF as an IFunctor<ListF> here". Instead, you're forced to do the arguably very non-explicit workaround `let fm<'F when 'F :> IFunctor<'F>> f = 'F.fmap f in fm<ListF> f`.

**Comment by vzarytovskii** [comment] 2023-03-08 18:19
I am going to close this as by design, please refer to RFC: https://github.com/fsharp/fslang-design/blob/main/FSharp-7.0/FS-1124-interfaces-with-static-abstract-members.md#alternatives, and specifically the conlusion for the implementation - https://github.com/fsharp/fslang-design/blob/main/FSharp-7.0/FS-1124-interfaces-with-static-abstract-members.md#conclusion

If you'd like, you can create a language suggestion for implementing a specific syntax (`(MyRepeatSequence :> IGenNext<MyRepeatSequence>).Next(str)`), as described in https://github.com/fsharp/fslang-design/blob/main/FSharp-7.0/FS-1124-interfaces-with-static-abstract-members.md#option-d---give-some-kind-of-explicit-call-syntax

**Closed** 2023-03-08 18:26 UTC
Labels: Bug, Needs-Triage
